### ISSUE TITLE
When a multiplayer game is started when you're not ready your cursor will disappear

### ISSUE THREAD

**Issue by IceDynamix** [Quaver/Quaver#1066]
**Describe the bug**
As mentioned in the title

**To Reproduce**
1. Enter a multiplayer room
2. Have someone else start the game while you're not ready
3. Observe no cursor

**Expected behavior**
Cursor

**Comment by Swan** [comment]
If the game starts, wouldn't the expected behavior be to get rid of the cursor? Why would it still need to be shown if there's no UI to interact with anymore?

**Comment by IceDynamix** [comment]
Because you're not in the game. It was started while you weren't ready, so you remain in the lobby screen.
