### ISSUE TITLE
Random Freezes (Any song, only on quaver, tested other games)

### ISSUE THREAD

**Issue by AndreyPGH** [Quaver/Quaver#1092]
Hello, I really have no idea on how to go more in-depth with this, the game just freezes randomly during any song, but not always. The game keeps "running" so notes are missed mid freeze.
The video doesn't record audio for some reason, but the glitch happens exactly as shown in the video as shadowplay actually captures it.

https://youtu.be/dkMVIs3sqDs (github doesn't support mp4)

**Comment by xrbiay** [comment]
Hello! This is a still an issue as of April 30th 2021.

OS: Ubuntu 20.04 LTS
Kernel: 5.8.0-50-generic
Version: Quaver v0.28.0

I would like to elaborate - but as AndreyPGH said, there is nothing to add. I experience the exact same issue as him - where it freezes, but the game keeps "going". So the notes are still "moving", but when it unfreezes it snaps back to it. The video he provided is a perfect representation of what I'm expiriencing.

I've tried FPS limits, Unlocked, V-Sync, Wayland V-Sync, but none seem to yield a fix.

This is only an issue with Quaver, I've played countless games on this exact configuration and this is the first time this has happened. Even osu! mania under WINE doesn't have this issue.

@Swan please consider re-opening this issue as it's a sizeable issue.

I would like to help troubleshoot this bug, but I'm not sure where to begin. Is there any way of opening Quaver w/ a terminal - so I can see what is being logged? Thank you, I hope this issue gets fixed.

**Comment by Spaghet4Life** [comment]
Having this same issue, but after freezing the game sometimes crashes, sometimes it unfreezes after a couple seconds. I have 2 monitors if that matters.

OS: Windows 10
Latest Quaver version
GPU: Radeon RX 580
CPU: AMD Ryzen 5 2600

**Comment by JoltStorm** [comment]
I'm having the same issue... It doesn't crash, but It's basically a second long freeze but while it's frozen the game is still technically running, which causes me to miss. Here are my specs:

OS: Windows 10
Latest Quaver version
GPU: Nvidia RTX 3070
CPU: 11th gen Intel i7
and 16 GB of RAM, if that matters.

**Comment by syrinka** [comment]
Having the same issue, random song random time and suddenly freeze

**Comment by 5GBurrito** [comment]
Same issue, system specs below:

```
OS: Manjaro Linux x86_64 
CPU: Intel i3-3227U (4) @ 1.900GHz 
GPU: Intel 3rd Gen Core processor Grap 
Memory: 7741MiB 
```

**Comment by clearlyace** [comment]
can confirm that going into your task manager and putting quaver in compatibility mode fixes the issue. not only did this fix the issue for me, it also fixed it for my friend who was having the same issue. working for 2024 :3

**Comment by shfigit** [comment]
> can confirm that going into your task manager and putting quaver in compatibility mode fixes the issue. not only did this fix the issue for me, it also fixed it for my friend who was having the same issue. working for 2024 :3

how do you do this??
