### ISSUE TITLE
Ability to see highest difficulty spike and (single lane and overall) KPS of a song

### ISSUE THREAD

**Issue by SparkySpartan** [Quaver/Quaver#1095]
Lots of speed training activities involves playing maps that may be out of the comfort zone of players, and it's no fun when you die to a 5 point difficulty spike or a super fast jumptrill, especially when you have already played 2/3rds of said map.

A simple way to resolve this would be to display what the most difficult X seconds of a song are by itself without the rest of the map, and to display the highest NPS of the song with it. With this, players will be able to spend less time playing maps that won't be possible with their skillset and more time playing maps that truly test their limits.

I'm not sure how difficult this would be to implement, but it would be a cool QOL feature for all tiers of players.

Example of purpose - Difficulty of the full 6 minutes of MyZterioN-'s "Megalovania (Camellia Remix)" vs. the difficulty of the final minute.
![20190930122316_1](https://user-images.githubusercontent.com/52823561/65845318-1b4da000-e37d-11e9-80d7-71c6225c6629.jpg)

**Comment by Janko5** [comment]
>Example of purpose - Difficulty of the full 6 minutes of MyZterioN-'s "Megalovania (Camellia Remix)" vs. the difficulty of the final minute.

You can do it yourself using the editor

**Comment by SparkySpartan** [comment]
> You can do it yourself using the editor
Saying you can do this by using the editor is like saying you can play rates of any song you like in osu!mania. Technically, it's not that hard to do, but it's time consuming to do over and over again.
This is why I referred to this suggestion as "quality of life."
