### ISSUE TITLE
[redesign] scroll bar goes above the top of its visible range

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#1108]
![image](https://user-images.githubusercontent.com/1794388/66160320-9095cb00-e632-11e9-82ad-c357f7e3c7c4.png)
![image](https://user-images.githubusercontent.com/1794388/66160329-94c1e880-e632-11e9-882f-0788f8bc2aab.png)

**Comment by Swan** [comment]
#3286
