### ISSUE TITLE
[redesign] mod description tooltip isn't shown when hovering over buttons

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#1110]
Like on/off or the rate left/right arrows

**Comment by Swan** [comment]
This is done intentionally

**Comment by YaLTeR** [comment]
Looks kinda weird that the tooltip disappears there imo

**Comment by Swan** [comment]
The buttons are too small that the tooltip would overlap and hide a good portion of them.  If it's truly important, the only way around it is if the tooltip is raised higher whenever hovering over those buttons, but it might look a bit weird. In that case I can reopen
