### ISSUE TITLE
Mod descriptions are inconsistent

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#1113]
Some of them are "Do something" ("Change the rate"), some of them are "Does something" ("Flips the map")

**Comment by Swan** [comment]
The only ones that are in the "Do something" format are the speed and judgement window mods which prompts the user that they're the one responsible for setting/customizing the value. The other on/off mods describe what it does, I think it's valid imo

**Comment by YaLTeR** [comment]
> they're the one responsible for setting/customizing the value

The exact same could be said about other mods though ("they are the one responsible for enabling the mirror mod")
