### ISSUE TITLE
[Feature request] More keyboard shortcut on Select screen

### ISSUE THREAD

**Issue by MineMy** [Quaver/Quaver#1138]
`Home` - Go to first song.
`End` - Go to last song.
`Page Up` - Scroll up song page.
`Page Down` - Scroll down song page.

`Ctrl` + `4` - Toggle are 4k songs invisible.
`Ctrl` + `7` - Toggle are 7k songs invisible.
`Ctrl` + `A` - Toggle autoplay mode.
`Ctrl` + `Arrow Up` - Increase playback speed.
`Ctrl` + `Arrow Down` - Decrease playback speed.
`Ctrl` + `F3` - Increase scroll speed.
`Ctrl` + `F4` - Decrease playback speed.

**Comment by Swan** [comment]
Most of these are already implemented in the current game and/or `ui-redesign` branch.

`CTRL` + `+` - Increases the playback rate
`CTRL` + `-` - Decreases the playback rate
`CTRL` + `0` - Toggles between pitched and non-pitched audio
`Page Up` - Scrolls upwards
`Page Down` - Scroll downwards
`CTRL` + `F3` - Decreases the scroll speed for the selected map's game mode
`CTRL` + `F4` - Increases the scroll speed for the selected map's game mode

**Comment by YaLTeR** [comment]
Are <kbd>Ctrl</kbd>+<kbd>4</kbd> and <kbd>Ctrl</kbd>+<kbd>7</kbd> really needed considering you can just search for `k=4` or `k=7`?
