### ISSUE TITLE
Fullscreen is glitched

### ISSUE THREAD

**Issue by nobbele** [Quaver/Quaver#1152]
**Describe the bug**
Game looks very glitched when going into fullscreen mode

**Screenshots**
<img src="https://i.imgur.com/Jsh4NWQ.jpg"/>

**Desktop**
 - OS: Pop!_OS

**Comment by YaLTeR** [comment]
Please provide other system details like GPU, etc. Also Pop!_OS version.

**Comment by nobbele** [comment]
$ uname -a
Linux pop-os 5.0.0-21-generic #22+system76-Ubuntu SMP Tue Jul 16 19:57:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ sudo lshw -C display              
       description: VGA compatible controller
       product: Juniper XT [Radeon HD 5770]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:05:00.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=radeon latency=0
       resources: irq:30 memory:e0000000-efffffff memory:f7fc0000-f7fdffff ioport:e000(size=256) memory:c0000-dffff

**Comment by nobbele** [comment]
It was Gnome 3's fault I think, works in MATE
