### ISSUE TITLE
[redesign] Add pause functionality to song select screen

### ISSUE THREAD

**Issue by robby250** [Quaver/Quaver#1172]
Can look something like this:
![Untitled](https://user-images.githubusercontent.com/51453670/67271933-3450f900-f4c4-11e9-83b5-fd4a88be2f61.png)
Next button could jump to a random map. Previous button can be a history for the previously selected maps. When sitting on one map in song select it can keep looping that song like it currently does, with the option to pause it.

Alternatively, just a pause/resume button.

**Comment by Janko5** [comment]
this is place for profile.  
![screen](http://puu.sh/EvuD3/8faa555520.png)
if I had to place the jukebox somewhere, I would put it in the same place as in the main menu. But to be honest I don't know if this is needed in song select

**Comment by robby250** [comment]
At the very least a pause button to stop the music, but the jukebox functionality I mentioned would be different from the one in main menu so it would be useful as well. It takes up very little space I'm sure it can be added somewhere.

**Comment by Janko5** [comment]
the pause button itself will look at least strange. A full jukebox makes more sense
