### ISSUE TITLE
Inconsistent SV behavior with osu!mania

### ISSUE THREAD

**Issue by Illuminati-CRAZ** [Quaver/Quaver#1189]
https://osu.ppy.sh/beatmapsets/961786#mania/2013923
Quaver causes parts of this map to "blink(?)" during SV sections.
I think the 0.01x SV cap in osu may be a cause for some of this, but the blinking doesn't seem to make sense.

https://osu.ppy.sh/beatmapsets/714467#mania/1509933
Quaver can't read this file properly. Might be because of this map having two timing points at the same time at many points in the map.

**Comment by YaLTeR** [comment]
> https://osu.ppy.sh/beatmapsets/961786#mania/2013923
Quaver causes parts of this map to "blink(?)" during SV sections.
I think the 0.01x SV cap in osu may be a cause for some of this, but the blinking doesn't seem to make sense.

lol wtf. It works correctly in another qua-playing engine, so it's unrelated to both osu->qua and 1 ms rounding, so it's something in Quaver's SV handling.

> https://osu.ppy.sh/beatmapsets/714467#mania/1509933
Quaver can't read this file properly. Might be because of this map having two timing points at the same time at many points in the map.

Aren't there LNs with end before start there? Certainly looks like it. Those are marked invalid in Quaver intentionally.

**Comment by Illuminati-CRAZ** [comment]
Right, totally forgot about the invalid LNs.

**Comment by Illuminati-CRAZ** [comment]
First link is dead, but I think referred to a map of the song titled "Shiawase ni Nareru Kakushi Command ga Arurashii", by Kamikaze(?). I think the map is used in the Quaver.API tests?

The map has BPM affects SV enabled, with timing points of BPM infinity being used to teleport.
The strange "blinking" behavior can be replicated by using Infinity SVs to teleport.

The state the map is in after teleporting once with an infinity sv is similar to what happens when an sv with a large multiplier (like 10k) is left active for too long. It seems the farther away from position 0 the gameplay is, the less precise the position of everything else is, kinda reminiscent of the Minecraft Farlands.

**Comment by YaLTeR** [comment]
> First link is dead, but I think referred to a map of the song titled "Shiawase ni Nareru Kakushi Command ga Arurashii", by Kamikaze(?). I think the map is used in the Quaver.API tests?

Yeah, that's the map, and it is in the API tests indeed. The .qua from the tests is also the one that the aforementioned "another qua-playing engine" can play fine (just like it looks in osu!).

> The map has BPM affects SV enabled, with timing points of BPM infinity being used to teleport.
> The strange "blinking" behavior can be replicated by using Infinity SVs to teleport.
> 
> The state the map is in after teleporting once with an infinity sv is similar to what happens when an sv with a large multiplier (like 10k) is left active for too long. It seems the farther away from position 0 the gameplay is, the less precise the position of everything else is, kinda reminiscent of the Minecraft Farlands.

Ah, perhaps. The other engine has a maximum SV multiplier, so infinity is fixed that way, I don't remember about Quaver.

**Comment by Illuminati-CRAZ** [comment]
The strange blinking behavior is caused by integer underflow (overflow?). The distance between velocity position markers is calculated to be Single.PositiveInfinity, whick after casting to a long becomes Int64.MinValue.

Assuming an initial position of 0, adding MinValue to it causes it to become MinValue, and adding MinValue to it again causes it to return to 0.

(Apparently Single.NegativeInfinity also casts to Int64.MinValue)

https://dotnetfiddle.net/Keh30C

**Comment by Illuminati-CRAZ** [comment]
I should also link the relevant code huh https://github.com/Quaver/Quaver/blob/b1369ddc62a5c62b5da7806021da20c081732f3f/Quaver.Shared/Screens/Gameplay/Rulesets/Keys/HitObjects/HitObjectManagerKeys.cs#L741-L759
