### ISSUE TITLE
Apply global/local offset differently with rates

### ISSUE THREAD

**Issue by Adrriii** [Quaver/Quaver#1204]
I propose that local and global offset be handled differently while using rates (if it's not already the case).

The reason for this is :
- Global offset is used to compensate for hardware or perception reasons, and to be in sync with audio feedback while playing
- Local offset is used to compensate for an individual map's error in offset setting

Local offset should be 'applied' before the rate, by moving the original notes
Global offset should be used to apply a delta to user input, independently of rate

**Comment by YaLTeR** [comment]
lol https://github.com/Quaver/Quaver/pull/952/commits/9f94e470b0c97577006d326daa018c885c10bb4a
