### ISSUE TITLE
Notes aren't hittable until they appear on screen

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#1222]
This is an issue if the judgement windows are so large that some judgements are not attainable while the notes are on screen. This is a bad thing because (at the very least) scroll speed shouldn't affect the judgements, and if people are using this to make something like "marv or miss", a proper way of doing that should be added instead.

**Comment by Swan** [comment]
This is not the case and can be tested by setting the marv window to the max amount.

**Comment by YaLTeR** [comment]
Did you try with a high scroll speed? There's a hardcoded time cap when the notes are loaded into the pooling iirc.

**Comment by Swan** [comment]
They still seem to be hittable with 100 scroll speed

**Comment by Swan** [comment]
https://streamable.com/hmv9b6
