### ISSUE TITLE
Session and global key counter

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#1223]
**Is your feature request related to a problem? Please describe.**
Many people use key counter programs to show on stream and for fun. Building one into Quaver shouldn't be too difficult and will improve ease of use and remove false positives (only count keys when hit during gameplay).

**Describe the solution you'd like**
A key counter, displayed during gameplay and perhaps somewhere accessible via menus, probably skinnable. Ability to toggle between this session's counts and global counts (preserved in quaver.db).

I've never used one myself so feedback from people who do use one is needed.

**Comment by robby250** [comment]
I like the idea, perhaps also a "total keys" statistic on the website that the quaver.db global counter syncs with (in case of database corruption/reset) and it's a good metric of how much you've played, ranked/unranked/unsubmitted and all.
