### ISSUE TITLE
Scores with NF can still get the F grade

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#1230]
When your HP goes too low. Also if you finish with the F grade it'll show the F in the leaderboard, even though it's NF.

Not sure if this should be just removed though because it's kinda useful to see if you have actually failed even while playing with NF.

**Comment by Swan** [comment]
Gonna close as this is pretty useful. The actual grade can be determined by the accuracy

**Comment by YaLTeR** [comment]
No, it's actually broken rn. I'm not sure when exactly it switches to F but it's not when your HP reaches 0, and also it switches back from F whenever you cross an accuracy boundary (so when you go from 89 to 90 for example). Also getting F in the leaderboard is not linked to getting an F during the play or finishing with an F grade.

**Comment by Swan** [comment]
Will keep this open then

**Comment by Swan** [comment]
Should be fixed now after this commit
https://github.com/Quaver/Quaver.API/commit/9dc4ef9a312f27e4a32f6dbeb661bb2d0224d555
