### ISSUE TITLE
[Audio Player] Blacklist song from music player

### ISSUE THREAD

**Issue by Adrriii** [Quaver/Quaver#1242]
Small idea for the music player : being able to blacklist a song from being randomly played in it.

There could be a small button near the controls and pressing it would skip & blacklist the song. You would be able to remove it from blacklisted from either song select interaction (easiest?) or a blacklist control panel (maybe too high effort)

Other improvement: be able to create a whitelist? Looks less useful to me, but if that looks better/ a good addition, why not !

**Comment by Swan** [comment]
You can create a playlist or use the search function
