### ISSUE TITLE
Multiple deadlocks during song select

### ISSUE THREAD

**Issue by Swan** [Quaver/Quaver#1269]
After a bit of investigating, I found two places during song select where the deadlocks occur.

**1. Creating DrawableLogs on separate threads (Debug Builds)** 

**How To Reproduce:** Harder to reproduce, but spam switching maps for a bit should trigger it.

`DrawableLog` was a class in [Wobble](https://github.com/Quaver/Wobble/blob/master/Wobble/Logging/DrawableLog.cs) from long ago that displayed logs on-screen. From the snapshot, it seems like it's hanging when trying to create the text's texture (it uses the old `SpriteText`).

In any case, the class could either be removed entirely or updated to use `SpriteTextPlus` if we find there's still use in having it.

![image](https://user-images.githubusercontent.com/20389565/69001867-64699d00-08b4-11ea-8406-63888f6bc792.png)

**2. Locking `AvailableMapsets` on the main thread**

**How To Reproduce:** This can be reproduced quite easily by switching the grouping from playlists back to none.

In `FilterPanelMapsAvailableUpdateText`, within the method to update the amount of found results, there's a scheduled update lock around `AvailableMapsets`. 

Removing the lock here should be enough, as it's not needed.

![image](https://user-images.githubusercontent.com/20389565/69002095-8c0e3480-08b7-11ea-8f0d-5b10d7b819f6.png)

**Comment by YaLTeR** [comment]
> From the snapshot, it seems like it's hanging when trying to create the text's texture (it uses the old `SpriteText`).

Do you have an idea why that would deadlock?
