### ISSUE TITLE
Mistakenly read song tittle when there's colon

### ISSUE THREAD

**Issue by aphelionosu** [Quaver/Quaver#1277]
This bug happens when I tried to load "archive::zip" and "Re:End of a Dream" from osu! The title ended up written as "zip" for "archive::zip" and "End of a Dream" for "Re:End of a Dream".

screenshots are below
[https://photos.app.goo.gl/gEYDAAkxkhwK111RA](url) [https://photos.app.goo.gl/koxqQEUZZsHTByuM7](url)

**Comment by Illuminati-CRAZ** [comment]
Appears to have been fixed three years ago
