### ISSUE TITLE
[Multiplayer] Add to playlist

### ISSUE THREAD

**Issue by robby250** [Quaver/Quaver#1380]
Option to add a map picked in multiplayer to playlist without entering song select. Perhaps using right click on the map banner?

**Comment by QiuFeng54321** [comment]
This can also be a preferable change to multiplayer gameplay experience. Currently, only the host is able to add the current map to a playlist, and only via map selecting screen. For normal players, they can only achieve so by leaving the room to singleplayer map-selection screen.

This feature can be changed in the following ways:
+ Change the current behavior when clicking on the map:
  + When the map is not downloaded, only left click is allowed to download the map
  + When the player has the map, left click (or right click) opens up the sub-actions as allowed in singleplayer:
    + Online Listing
    + Add to Playlist
    + Remove scores
  + When autohost is on, the following behavior can be changed (optionally tho, it arguable that this is not a good idea):
    + When the game ends, the server waits for a few moment (20-30s maybe) before changing the map, so players are given time to see the results and perform the actions described above.
