### ISSUE TITLE
[redesign] Quit popup has wrong options

### ISSUE THREAD

**Issue by JaanJah** [Quaver/Quaver#1390]
**Describe the bug**
When clicking Quit Game on redesign UI, the 2 options are `Create` and `Cancel`, but should probably be `Quit` and `Cancel`

**Screenshots**
https://i.imgur.com/u3x8dFe.png

**Additional context**

**Comment by Janko5** [comment]
buttons work but graphics are wrong. This is known and occurs in several places

**Comment by JaanJah** [comment]
Alright, perhaps we should list everywhere where these are wrong, so we can fix all of em at once.

**Comment by Sublimity** [comment]
The [https://github.com/Quaver/Quaver/blob/ui-redesign/Quaver.Shared/Graphics/Dialogs/ConfirmCancelDialog.cs](ConfirmCancelDialog) class is used for all of these, the graphic only needs to be changed once in this location for them all to update, with that being said though, I think the best route would be to spring away from using dedicated graphics for the buttons, and instead using the pill button graphics for the button background, and instead rendering text on top.

**Comment by Janko5** [comment]
yeah probably but from I remember rendering text in quaver looks extremely poor

**Comment by Sublimity** [comment]
![image](https://user-images.githubusercontent.com/6015313/71641746-a53e3980-2cdb-11ea-9093-2948a566823a.png)

The confirmation text in this dialog renders, and looks completely suitable. I think it would be fine.

**Comment by Janko5** [comment]
I will add a Swan's quote from #dev-design: the text doesn’t look good on light backgrounds and you can see black shadows around the letters
