### ISSUE TITLE
Unusually high GPU usage

### ISSUE THREAD

**Issue by nobbele** [Quaver/Quaver#1409]
Describe the bug:
When I am playing for long sessions(especially like long 5 minutes maps) my GPU overheats to the point where the whole PC kills itself. It does not happen in other games so I think it's a problem with Quaver.

To Reproduce:
1. Get an old PC with a bad GPU
2. Play for a long time
3. Maybe works?

Expected behavior:
The GPU has normal temperature

Information:
Radeon HD 5770

Additional Context:
A guy I know also experiences unusual heating(although not overheating as mine) on Quaver while osu!, even centipede, has no issues at all. He has a GTX 1050 Ti so it's not a problem on having a bad GPU

**Comment by robby250** [comment]
Have you tried using an FPS cap ?

**Comment by YaLTeR** [comment]
> GPU overheats to the point where the whole PC kills itself

That, uhh, sounds like a driver or BIOS settings issue. No application should be able to do that.

**Comment by nobbele** [comment]
> Have you tried using an FPS cap ?

Happens with limited, vsync fucks up gameplay.

> That, uhh, sounds like a driver or BIOS settings issue. No application should be able to do that.

No idea what to even look for to fix it

**Comment by robby250** [comment]
Your gpu is probably so weak that the 'limited' default cap is higher than what your gpu can output so it's still running at 100%. You can try lowering the 'limited' fps cap from the config file to a frame rate lower than what your gpu can output.
This is a PC thermal management issue unfortunately, you can try cleaning your gpu if its dusty, it's not supposed to overheat.

**Comment by nobbele** [comment]
Yeah well still games like Minecraft are way more intense while they run at much higher frame rates without any overheating issues

**Comment by robby250** [comment]
Minecraft is a single threaded cpu bound game, so it's likely bottlenecked by the cpu and the gpu isn't running at max power there. So no overheating.

**Comment by robby250** [comment]
The "much higher frame rates" is a valid argument though and the game could be optimized to run better. But overheating is solely on you, your GPU shouldn't overheat even in a stress test never mind a game.

**Comment by nobbele** [comment]
Changed title to be more accurate I guess

**Comment by robby250** [comment]
If the framerate is uncapped or not high enough to reach the cap, the game is supposed to spit out as many frames as the pc can handle. This means that either the cpu or gpu is going to run at 100% power, depending on which one is bottlenecking. This is normal, and tbh it's better when a game bottlenecks the gpu rather than the cpu, since that is usually a sign of good workload distribution. But it depends on the game of course.
