### ISSUE TITLE
Scroll Speed type selection in options

### ISSUE THREAD

**Issue by Janko5** [Quaver/Quaver#1412]
It could use a choice of options, what kind of scroll we want to use. For example

Scroll type:
- quaver 
- osu!
- stepmania
(can be more if they exists)

after choosing the option we will be able to adjust needed scroll using F3/F4

**Comment by Swan** [comment]
Not sure if there's a public algorithm as to how scroll speed is calculated in osu, so im not entirely sure how possible that is. Lazer seems to work differently than the stable client as well
