### ISSUE TITLE
Add file dialog to select the osu!.db file in the settings menu

### ISSUE THREAD

**Issue by IceDynamix** [Quaver/Quaver#1413]
**Is your feature request related to a problem? Please describe.**
When new users try to connect their database to Quaver, they have to manually edit the Quaver config files.

**Describe the solution you'd like**
A label with the current path and a button which opens a file dialog to select a new path.

**Comment by Sublimity** [comment]
Swan has stated before he would like for external sources to not be specifically included within the game, this includes any branding or recognization of "osu!". While the options to import your osu!.db file, and osz files into Quaver exist, this does not mean they are endorsed by peppy and the osu! team, so avoiding any branding helps with legality as Quaver is a separate entity.

**Comment by Swan** [comment]
Already mentioned this before, but I'll write it here as well - we can add the ability to drag the db file into the window and that should make the process easier

**Comment by Sublimity** [comment]
That would be a good solution
