### ISSUE TITLE
Select map with arrow left/right when scrolling with page up/down

### ISSUE THREAD

**Issue by ElectroYan** [Quaver/Quaver#1428]
**Is your feature request related to a problem? Please describe.**
When quickly scrolling through your maps with page up/down you can't select a currently visible song (like the one the middle) without using your mouse. When pressing any arrow key is just jumps back to the previous position and enter starts the map.

**Describe the solution you'd like**
If pressing left or right arrow it selects the map in the middle of the screen in case you've scrollen with page up/down.

**Comment by ElectroYan** [comment]
Should mention this is for the redesign, forgot it in the title.

**Comment by robby250** [comment]
I think left/right should select the center map whenever it is not selected, so you could scroll with the mouse and use left-right to pick the center map as well. Not just with page up/down. If center map is already selected, then left/right can go up/down like usual.
