### ISSUE TITLE
[redesign] Shortcut to jump to next diff of mapset.

### ISSUE THREAD

**Issue by ElectroYan** [Quaver/Quaver#1431]
**Is your feature request related to a problem? Please describe.**
When sorting by a criterion which splits mapsets into single difficulties, like when sorting by "Difficulty", "Online Grade", or "Long Note %", in order to get to the next difficulty of a mapset you have to sort by e.g. "Title", select the wanted difficulty and sort it by your previous choice again.

**Describe the solution you'd like**
Some key combination, maybe involving ctrl+page up/down or some arrow keys which directly jumps to the next difficulty.

**Comment by Janko5** [comment]
You can use up/down arrows

**Comment by IceDynamix** [comment]
> When sorting by a criterion which splits mapsets into single difficulties, like when sorting by "Difficulty", "Online Grade", or "Long Note %"
