### ISSUE TITLE
[redesign] Negative time on leaderboard

### ISSUE THREAD

**Issue by ElectroYan** [Quaver/Quaver#1438]
**Describe the bug**
There was a negative time shown on the leaderboard (which even counted up (towards 0)) as to be seen on the screenshot.

**To Reproduce**
I have no idea.

**Screenshots**
https://i.imgur.com/jhqFd8y.png

**Additional context**
If relevant, map is imorted and the screenshot is of the global leaderboard.

**Comment by YaLTeR** [comment]
Known, probably caused by lack of time synchronization between clients & the server, probably not worth the effort to fix (unclear how).

**Comment by ElectroYan** [comment]
Shall I close this issue then?

**Comment by YaLTeR** [comment]
Dno let's wait for @Swan

**Comment by IceDynamix** [comment]
a temporary solution would be replacing any negative value "now", since the exact number of seconds is not that important in my opinion.

**Comment by YaLTeR** [comment]
Great idea actually
