### ISSUE TITLE
[Custom Judgements] Toggle setting "Use custom judgements only for in-game judgements display"

### ISSUE THREAD

**Issue by Adrriii** [Quaver/Quaver#1471]
The idea is to add a on/off setting that would have these effects : 

- In-game, Displayed accuracy would be the Ranked Accuracy
- In-game, Displayed grade would be the grade according to Ranked Accuracy

- In-game, the Judgments would be according to Custom Judgements
- In-game, the HitError bar/Accuracy meter would be according to Custom Judgements

- In results screen, everything would stay as is right now
- The score would be saved using the Ranked Accuracy (in local) instead of custom judgements

-------

If you want to take this the other way, it would do as described : The only incidence of Custom Judgements would be when displaying in-game judgements and acc meter, then the result screen's judgements and error graph would also use the custom judgements.

I know that sounds really specific, but that's something that i was able to configure in etterna and i found it really good so maybe other people would like that as an intended feature :) 

Since it doesn't sound too hard, if you have too many other things to do i could try and make it, just tell me if you're up for this and don't have time !

**Comment by Swan** [comment]
Probably not. This just adds unnecessary complexity.
