### ISSUE TITLE
Quaver changes OS resolution

### ISSUE THREAD

**Issue by JaanJah** [Quaver/Quaver#1501]
**Describe the bug**
When trying to change screen resolution in Quaver, then it changes screen resolution for Quaver, but also for the OS, after changing OS resolution back to 1920x1080, then you can see that Quaver is correct resolution

**To Reproduce**
1. Launch Quaver
2. Go to settings and change resolution to lower (1920x1080 -> 1280x720) for example
3. Check OS resolution (Is set to 1280x720)

**Expected behavior**
Resolution is only set for Quaver and not for entire OS

**Screenshots**
Video evidence: https://www.youtube.com/watch?v=I5mgiNxfaAs

**Desktop (please complete the following information):**
 - OS: Pop!_OS (Ubuntu) 19.10

**Comment by YaLTeR** [comment]
I have reproduced this on GNOME 3.36 Xorg on Fedora 32. It can also lock the session if you attempt to change to a weird resolution, now with the arbitrary scaling support.
