### ISSUE TITLE
Add main menu background art

### ISSUE THREAD

**Issue by thenerdie** [Quaver/Quaver#1604]
![image](https://user-images.githubusercontent.com/47013933/75122241-b5362200-5669-11ea-8594-bc655eedc308.png)

Up above is the default bgs for the initial array of buttons. New images should be added instead of the placeholders.

**Comment by Fretzi** [comment]
The reason we haven't added any images yet is because we don't have any so far.
They will be created and added shortly before the game will be available on Steam, but right now there are more important things to do.

**Comment by thenerdie** [comment]
Fair enough, but should I feel free to open a pull request when I have the images?
