### ISSUE TITLE
Manually changing the name of audio file doesn't work as intended

### ISSUE THREAD

**Issue by PianoLuigi** [Quaver/Quaver#1607]
To reproduce:
1. Have a map with mp3 audio file
2. Manually change the name of that mp3, change the audio file used from the qua file (while Quaver is closed) and save.
3. After opening Quaver again, the audio file is not detected.

If you change to the canary client at this point, the new audio works as intended.

I also noticed that after all this, you can change the mp3 file name back, and it works again, THOUGH the qua file still has the updated audio file showing (meaning you  can have "audio.mp3" in the folder and "audio2.mp3" showing in the qua file, while it still works).

**Comment by Swan** [comment]
Should work now after refreshing your songs
https://github.com/Quaver/Quaver/pull/1803
