### ISSUE TITLE
Song Select: select map instantly after clicking instead of waiting for release

### ISSUE THREAD

**Issue by staravia** [Quaver/Quaver#1623]
It's more responsive if we don't wait for the mouse button to be released (after pressing it) to select maps in the song selection screen

Also note that in the videos I am spam-clicking
Before: https://streamable.com/kjw75
After: https://streamable.com/9ufsu

**Comment by robby250** [comment]
but what if you just want to click on one map and end up scrolling down because it clicks 5 times while you're clicking down because not everyone releases instantly (I dont know how long it waits before it 'clicks' again while holding down though)

**Comment by robby250** [comment]
also I think click and drag support similar to osu for scrolling would be better

**Comment by staravia** [comment]
> but what if you just want to click on one map and end up scrolling down because it clicks 5 times while you're clicking down because not everyone releases instantly (I dont know how long it waits before it 'clicks' again while holding down though)

What do you mean by clicking 5 times? It will select only one map after you click (not hold). Right now it selects the map after you've released which is not responsive if the container is scrolling

**Comment by robby250** [comment]
oh, I thought you were holding down click in the 'After' video and it was scrolling down because of that

**Comment by staravia** [comment]
> also I think click and drag support similar to osu for scrolling would be better

You can hold down the middle mouse button for that, but
 it should be binded to the right mouse button

**Comment by robby250** [comment]
>You can hold down the middle mouse button for that, but
it should be binded to the right mouse button

thats for absolute scrolling, not regular scrolling

**Comment by robby250** [comment]
Yeah I just realized that you were mashing click in both videos and in the second its more responsive, this is a good improvement I just didn't understand it properly the first time, my bad

**Comment by staravia** [comment]
> Yeah I just realized that you were mashing click in both videos and in the second its more responsive, this is a good improvement I just didn't understand it properly the first time, my bad

Thanks for brining it up. I reworded the title and description a bit, hopefully it makes more sense :joy:

**Comment by Swan** [comment]
Doing this won’t allow us to implement “touchscreen” scrolling where you’d be able to drag to scroll the container. This also isn’t how buttons usually work and disallows the user to change their mind after initially holding the button.
