### ISSUE TITLE
[Linux] Mouse gets stuck while in fullscreen when alt-tabbing

### ISSUE THREAD

**Issue by Kangaroux** [Quaver/Quaver#1661]
**Describe the bug**
With my game in fullscreen mode, trying to alt-tab to another program **on the same monitor** causes my mouse to get stuck. My mouse looks like it kind of moves but it immediately snaps back into place.

This issue only appears to happen if I'm coming from Quaver. For example, if I alt-tab to something on my secondary monitor, it releases the mouse fine, and I'm able to interact with everything on all of my monitors. Once I click back into Quaver I have to repeat this process of going Quaver -> Secondary -> Primary.

**To Reproduce**
1. Open any window (browser, file explorer, etc.) 
2. Launch the game in fullscreen
3. Try and alt-tab to the first window you opened
4. Note that the mouse gets stuck until you alt-tab back to Quaver

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Version 02.12.2020

**Comment by YaLTeR** [comment]
X11? GNOME? "Ubuntu" or "Ubuntu on Wayland"?

**Comment by Kangaroux** [comment]
It's a brand new install of Ubuntu with no modifications. Should be X11 and gnome

**Comment by YaLTeR** [comment]
Not sure if it's the same issue, but I can reproduce it on GNOME 3.36 Xorg on Fedora 32 if I open the editor, then press the Super key to bring out the overview, and scroll to another workspace. Scrolling into the Quaver workspace makes the cursor behave normally. Alt-tabbing from Quaver also keeps the cursor behavior normal.
