### ISSUE TITLE
[Linux] - Segmentation fault when launching - seemingly SteamAPI related

### ISSUE THREAD

**Issue by monotron** [Quaver/Quaver#1668]
**Describe the bug**
When launching from the command line in Linux, the game segfaults when attempting to fetch the player's Steam avatar in the newest version of Quaver. Some cursory debugging on my end shows this is occurring in the native Steam libraries.

**To Reproduce**
- Clone the repository with all submodules
- Build with `dotnet build`
- Use the generated `quaver.sh` to launch the game with Steam open

**Expected behavior**
The game should launch

**Screenshots**
![Screenshot from 2020-03-09 02-37-30](https://user-images.githubusercontent.com/25872549/76178512-7ba7ff80-61af-11ea-8a1a-730b1845680d.png)

**Desktop (please complete the following information):**
 - OS: Reproduced on Ubuntu 18.04 and Pop!_OS 19.10

**Additional context**
Using dotnet core 2.1 directly from Microsoft, debugging done with Rider and lldb+SOS, newest version of Steam, system up to date

**Comment by monotron** [comment]
Interestingly, the game seems to launch fine if I symlink the libbass shared libraries into `/usr/lib`, like so, and try launching the game without setting `LD_LIBRARY_PATH` (either manually or by using quaver.sh):

```bash
ln -s $(pwd)/Quaver/bin/Debug/netcoreapp2.1/x64/libbass*.so /usr/lib
dotnet run --project Quaver
```

This doesn't feel like the right solution though and something interesting is seemingly going on with shared library resolution

**Comment by YaLTeR** [comment]
This is really weird. There was at least one other person before who solved their crash by copying bass to /usr/lib but that's definitely not what you want to do.

Could you try latest ui-redesign and launch via the Steam runtime as described here? https://github.com/YaLTeR/Quaver.Wiki/blob/master/FAQ/en.md#linux-offline-or-local-build

**Comment by monotron** [comment]
I can attempt this when I get home tonight - will report back.

**Comment by monotron** [comment]
@YaLTeR Runs fine when started through Steam runtime (the command on my system was `~/.steam/bin32/steam-runtime/run.sh Quaver/bin/Debug/netcoreapp2.1/quaver.sh`). Feel free to close this issue if you think it's relevant to do so

**Comment by YaLTeR** [comment]
Yeah, once we get rid of a particular library it should run fine without having to use the runtime.

**Comment by cloudrac3r** [comment]
I can reproduce everything above: Ubuntu 19.10, [dotnet 2.1 from microsoft](https://docs.microsoft.com/en-nz/dotnet/core/install/linux-package-manager-ubuntu-1910), ui-redesign branch, and segmentation fault with similar logs. Launches using Steam runtime workaround. I don't know if this information is useful to anyone, but there you go :D
