### ISSUE TITLE
Pausing bug

### ISSUE THREAD

**Issue by llAnasll** [Quaver/Quaver#1675]
When you are pausing and trying to resume the play you can not press the notes that are near to the receptors, it's literally impossible press that notes, every time I try to pause and resume this issue happen.

![bug](https://user-images.githubusercontent.com/46055365/76319702-df314a80-62df-11ea-809a-b8ec6248a4ae.jpg)

**Comment by Swan** [comment]
This isn't a bug. It's intentional that you're only able to press the keys while the song is playing.
