### ISSUE TITLE
Don't rely on bass audio library times when drawing frames

### ISSUE THREAD

**Issue by robby250** [Quaver/Quaver#1684]
With bass: 
![76436712-39560c80-63c1-11ea-8136-ebf07b26bbe5](https://user-images.githubusercontent.com/51453670/76442255-5393e880-63c9-11ea-9164-e09f703771e1.jpg)

Without bass:
![20200311_184832](https://user-images.githubusercontent.com/51453670/76442166-33642980-63c9-11ea-9297-f2f36fc402d4.jpg)

Consistent frame distance, much smoother motion overall.

**Comment by YaLTeR** [comment]
Obligatory note that audio and frame clocks are different so if audio timing isn't taken into account at all everything will go off-sync.
