### ISSUE TITLE
Add the ability to head to a map's mapset from ingame 

### ISSUE THREAD

**Issue by adagakii** [Quaver/Quaver#1692]
**Is your feature request related to a problem? Please describe.**
It takes a lot of time always having to open Quaver's Website first and to search a specific mapset.
If we'd be able to do all this from ingame it'd be a lot easier and faster.

**Describe the solution you'd like**
A "head to mapset" button (or something similar in context) next to the ranked sign should be added.

**Describe alternatives you've considered**
Alternatively Quaver could start displaying more data about a map ingame (tags, source, submit date and etc). But being able to just have a button for this all seems a lot easier and it would take a lot less space.

**Additional context**
In general I think this is a feature many would appreciate. Especially mappers. Being able to just quickly find a lot of metadata instantly is very helpful.

**Comment by Fretzi** [comment]
The new UI already allows you to do that.
Right click a map in the song select and hit "Online Listing"
