### ISSUE TITLE
Some maps have a brief stutter on the first beat

### ISSUE THREAD

**Issue by Kangaroux** [Quaver/Quaver#1703]
**Describe the bug**
Not sure what causes this but just before the first beat of some maps the scrolling freezes for a very short period of time and usually will cause you to get a great judgment instead of a marvelous.

An example of this is Fascination Maxx [7k Light]

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Version 3.14.2020

**Comment by Kangaroux** [comment]
I am fairly certain I experienced this when I was on windows as well so it's not an OS specific problem

**Comment by thenerdie** [comment]
This happens on osu! too. I think it has to do with RAM being used to start the song.
