### ISSUE TITLE
[redesign/editor] Change snap/playback speed by clicking value in details window

### ISSUE THREAD

**Issue by Janko5** [Quaver/Quaver#1705]
Instinctively, I tried to change the snap/playback speed by clicking the value in the details window, so adding this option (or replacing the existing one) would be useful in my opinion http://puu.sh/FkQfY/d8c1571d14.png

**Comment by Swan** [comment]
Needs a proper design to let users know they're clickable if this is being added

**Comment by Swan** [comment]
There are already three ways to change these values including hotkeys
