### ISSUE TITLE
Always play the combo break sound for the first CB

### ISSUE THREAD

**Issue by Kangaroux** [Quaver/Quaver#1728]
This would mean playing the sound if you get a CB in the first 20 (?) notes. This lets the player know they can't get an FC. This would be nice for songs that have intros which are easy to mindblock.

**Comment by Kangaroux** [comment]
I should note that I disabled the combo text so I rely heavily on that sound to know when I miss an FC

**Comment by thenerdie** [comment]
I can see if I can add this.

**Comment by thenerdie** [comment]
I added this functionality just now.

**Comment by thenerdie** [comment]
@Kangaroux

**Comment by thenerdie** [comment]
ok well because im mentally impaired idke if this functionality made it into the release.. guess its time to reimplement

**Comment by thenerdie** [comment]
ok i did it agaiiin
