### ISSUE TITLE
Add option to always start Quaver on the primary display

### ISSUE THREAD

**Issue by Kangaroux** [Quaver/Quaver#1750]
The game appears to start on whatever display your cursor is on. It's a bit annoying to start the game, mouse over to my secondary display, have quaver start there in fullscreen, and then have to alt-f4 and relaunch. I don't imagine anyone is playing on their secondary display.

**Comment by YaLTeR** [comment]
Window positioning should be the responsibility of your window manager. On Wayland for instance there's straight up no API to access the global window position, let alone set it.
