### ISSUE TITLE
Highlight the song being played when you launch the game

### ISSUE THREAD

**Issue by Kangaroux** [Quaver/Quaver#1751]
When you launch the game and it picks a random song to start playing it would be nice if it highlighted that song in the song list like how it does in osu. It feels a bit inconsistent and in the rare occasion where it selects a song you wouldn't mind playing it would make it easy to know which one it selected.

**Comment by Swan** [comment]
It should already select the current song that's being played on the jukebox . If this isn't the case, would you mind showing a video? Closing until then.

**Comment by Kangaroux** [comment]
@Swan If you have the mode set to 4k/7k and it picks a song that isn't the selected keymode you won't see it.
