### ISSUE TITLE
Editor: Start 2 or 3 Seconds Earlier When Playtesting

### ISSUE THREAD

**Issue by staravia** [Quaver/Quaver#1760]
It's physically impossible to test songs that start close to 0:00:00, and it's just overall more UX friendly

**Comment by YaLTeR** [comment]
I use playtesting for practising maps and this would be confusing and inconvenient.

**Comment by YaLTeR** [comment]
Maybe just do that for playtest-from-the-start?

**Comment by robby250** [comment]
Just give like 0.3 seconds of blank space before the notes start when playtesting from any point so you actually have time to react, and you don't lose that much time either.

**Comment by staravia** [comment]
> I use playtesting for practising maps and this would be confusing and inconvenient.
Just looked at osu. There's a ~2 second delay when you start close to the beginning when you start at the beginning. When you start somewhere in the middle, there's no delay.

**Comment by staravia** [comment]
The delay at the beginning is mandatory, but I think even a 0.3s delay would be good to have

**Comment by robby250** [comment]
If you start the playtest right on the beat snap of a note (or very close to it) its impossible to react, so an added 0.3s of space when starting like that would allow you to prepare. If you start earlier from the upcoming note then theres no need to add extra time.
