### ISSUE TITLE
Editor: Layers UI should follow conventions from other programs

### ISSUE THREAD

**Issue by staravia** [Quaver/Quaver#1763]
We should follow the convention from other software that use this sort of system.

Do not have the on/off button for every layer, and a seperate button that will toggle visiblity. It would be more intuitive to just hide individual layers by pressing the on/off button.

![Capture](https://user-images.githubusercontent.com/20867601/77241199-0f180200-6bac-11ea-9838-ad6e834ff71b.PNG)

Similar feature request: https://github.com/Quaver/Quaver/issues/1762

**Comment by Swan** [comment]
The editor uses different textures within the user’s skin when viewing layers. These objects are typically white, so they can be tinted to the appropriate layer color. If the user wants to view the layers of the map, they need to turn the setting on.

The global on/off button will toggle between these layer object textures and the normal skin’s textures. If you’re in the layer view, you can then toggle their visibilities individually using the checkbox.

Closing as already implemented.

**Comment by staravia** [comment]
> 
> 
> The editor uses different textures within the user’s skin when viewing layers. These objects are typically white, so they can be tinted to the appropriate layer color. If the user wants to view the layers of the map, they need to turn the setting on.
> 
> The global on/off button will toggle between these layer object textures and the normal skin’s textures. If you’re in the layer view, you can then toggle their visibilities individually using the checkbox.
> 
> Closing as already implemented.

I know it was implemented like this, but wouldn't it make more sense to be able to fully hide a layer by pressing a button that toggles it?

**Comment by staravia** [comment]
So even if you have non-white hitobjects in the game, pressing the on/off will hide the layer fully. You can still toggle the note colors with the eye button

**Comment by Swan** [comment]
Sure. The old editor did do this in fact, and I wouldn't mind carrying over the same functionality to the new one. In any case, this should be in a separate issue.
