### ISSUE TITLE
Mouse-overing leaderboard time should display exact timestamp

### ISSUE THREAD

**Issue by robby250** [Quaver/Quaver#1765]
![5nCNAo2](https://user-images.githubusercontent.com/51453670/77245457-660eed00-6c27-11ea-89d2-def6874cb2eb.png)
The red highlighted zone should show a tooltip with the exact time when hovering over it:
![Untitled](https://user-images.githubusercontent.com/51453670/77245464-7030eb80-6c27-11ea-9b89-867e22fad488.png)

**Comment by thenerdie** [comment]
hmm
