### ISSUE TITLE
Green Number support

### ISSUE THREAD

**Issue by Crimson-foxGITHUB** [Quaver/Quaver#1837]
It's hard to figure out what kind of scroll speed you want to use whenever each game uses different metrics for scroll speed X or Y, especially if you want *accuracy* between games in your note scrolling speed. 

However, there is one metric that's shared across all of them that can be measured: the duration the notes are on-screen from the first moment they're visible to the time they hit the receptors. 

This is a value that in IIDX and BMS terminology is known as **green number.**

Would it be possible to implement this metric into the game so that people can figure out what scroll speed they should be using?

**Comment by thenerdie** [comment]
Also referred to as prebuffer time, this would be very useful. osu!lazer makes use of this now (who would have thought). I'll see what I can do.
