### ISSUE TITLE
Go to objects doesn't go to objects on Enter

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#1877]
It should work on Enter after filling in the input field, not just pressing the Go button.

**Comment by Swan** [comment]
Can't reproduce on latest ui-redesign. Enter should work

**Comment by YaLTeR** [comment]
Doesn't work on Wayland specifically I think, need to check again. also copy-paste doesn't work on linux there

**Comment by YaLTeR** [comment]
So for some reason Enter in go to objects works for me only if I mash it 3-4 times quickly. If I press it with long intervals (even long-press) then it doesn't work.

**Comment by YaLTeR** [comment]
Could the issue be that IsKeyPressed is called during Draw and not during Update (assuming ImGUI things get executed during Draw)?
