### ISSUE TITLE
Difficulties with a high character count hide the rate

### ISSUE THREAD

**Issue by SparkySpartan** [Quaver/Quaver#1879]
Problem:
When a map's difficulty has above a certain amount of characters, instead of showing "[Difficulty Name] + (Rate)" within the info section of the song, it only shows "[Long Difficulty Name..." regardless of the rate.

Reproduction:
- Either go to a song with a long difficulty name, (ex: Evening's "Why do you hate me?") or make your own
- Change the rate of the song in any direction

Expected:
The difficulty should be displayed as "[Long Difficulty Name...] + (Rate)" instead.

Displayed: "Why do you hate me?" on 1.2x
![image](https://user-images.githubusercontent.com/52823561/79423923-c6186980-8002-11ea-8f60-2fc29ba2c977.png)

**Comment by robby250** [comment]
duplicate https://github.com/Quaver/Quaver/issues/1598
