### ISSUE TITLE
Advanced settings 

### ISSUE THREAD

**Issue by Hikudo** [Quaver/Quaver#1897]
Hey, I would like something that permit us to move the game window at the left or the right, and btw, an option that permit to edit the window size could be awesome
![image](https://user-images.githubusercontent.com/38385795/79917566-ff9a0c00-842a-11ea-9828-7fb22d036ffc.png)

**Comment by IceDynamix** [comment]
There are skin.ini settings for what you're asking for. If by "game window" you mean the active playfield, then are [skin.ini](https://quavergame.com/wiki/Skins/Skin.ini) settings for what you're asking (`ColumnAlignment` and `ColumnSize`). If by game window you mean the actual Quaver window, then there is a setting in the quaver.cfg file for the sizes. The new UI has options to freely scale the Quaver window size to whatever you want.

_Note: What you refer to as the "game window" is usually referred to as the "playfield" or "stage", a window in the traditional sense is the entire application itself._
