### ISSUE TITLE
Editor: Minimap Support

### ISSUE THREAD

**Issue by staravia** [Quaver/Quaver#1905]
This will show a high-level preview of the map, and it will allow us to navigate to a certain time in the song without finicking too much. It can be put in place of the difficulty graph.

Similar to this and the thing in Arrow Vortex
![](https://i.stack.imgur.com/xJfTk.jpg)

**Comment by Janko5** [comment]
this will look something like this but probably a bit bigger
https://cdn.discordapp.com/attachments/570610404527570945/646430318039007263/unknown.png

https://cdn.discordapp.com/attachments/570610404527570945/646824475161002009/unknown.png

I mentioned adding something like that while designing, but I forgot what the verdict was
