### ISSUE TITLE
Loading an animated hit lighting causes the game to become unresponsive

### ISSUE THREAD

**Issue by ethanwritescode** [Quaver/Quaver#1949]
**Describe the bug**
When any animated hit lighting file is specified in the 4k/Lighting or 7k/Lighting folder correctly, the game does not boot correctly. Its process exists in the task manager having a very high GPU usage (~50%) and logs do not update.

**To Reproduce**
1. Create a file in 4k/Lighting and call it hitlighting@275x275.png with any image.
2. Start Quaver/reload the skin. 
*If reloading, the window becomes unresponsive.

**Expected behavior**
The game should boot/the skin should reload.

**Screenshots**
see below

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Version 4.15.2020

**Additional context**
None.
![explorer_SHfmGnSuWs](https://user-images.githubusercontent.com/14879958/81489254-2f695200-9228-11ea-8d29-ecf60a6d147f.png)
![Taskmgr_0fnEEm2wPH](https://user-images.githubusercontent.com/14879958/81489255-32fcd900-9228-11ea-987e-f53dd5aa2091.png)

**Comment by Swan** [comment]
You're trying to load 75,000 images here. If you want to animate this, you have to provide a spritesheet named `hitlighting@{rows}x{columns}.png`
