### ISSUE TITLE
Default skin issues

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#1959]
With the recent update the column width of the default skin is now good, yay! However, I still have a few issues with it.

1. The health bar is blurry which can probably be fixed by using a higher reso image:
    
    ![изображение](https://user-images.githubusercontent.com/1794388/81559973-2481ff00-9399-11ea-886f-43d4f5ce248c.png)

    Also the kerning on the "Health" seems off, for instance the space between "a" and "l" is too large.

1. The judgements are impossible to tell apart when playing. There's way too little color on them (as in, the area that changes color is too small), when you're playing you absolutely cannot tell what judgements you get.

1. The note height is still too small for my tastes. I think it's even more of a problem for 60 Hz screen users, you really want to increase that height for the notes to not become complete blur.

cc @Janko5

**Comment by Janko5** [comment]
these are temporary skins. I did these skins a year ago. Correct new skins matching the design have not yet been created. They are only in the project phase in figma
