### ISSUE TITLE
Deviance graph shows negative ms above the center and positive below

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#1962]
Since it currently shows early hits below the center, negative ms should also be below the center.

**Comment by IceDynamix** [comment]
just say "deviance graph numbers and average mean have the wrong sign"

**Comment by YaLTeR** [comment]
Important note: even though the mean has the wrong sign, the offset adjustment it suggests is correct (when you hit early the local offset should decrease)
