### ISSUE TITLE
Order by date added

### ISSUE THREAD

**Issue by AiAe** [Quaver/Quaver#199]

**Comment by JaanJah** [comment]
I tried adding this, but ran into some problems. Need help. Here is my commit though: https://github.com/JaanJah/Quaver/commit/64a954306be11ebfe68508f3da8ad9e5e7afd0c0 (Problems: Doesn't order them by date added for some reason and the button is a bit buggy). Someone more experienced please look into my code and help me fix it, so I can learn what I did wrong and learn from my mistakes.

**Comment by Swan** [comment]
@JaanJah Open a pull request with your branch, so I can properly review it/steer you in the right direction.

**Comment by JaanJah** [comment]
@Swan did pullrequest with that branch https://github.com/Quaver/Quaver/pull/279
