### ISSUE TITLE
Song selection grade doesn't update when leaderboard set to "Rate"

### ISSUE THREAD

**Issue by Adrriii** [Quaver/Quaver#2026]
If it works with Global, Mods, Country, Rate and Friends, it should work on Rate at least in this case :
- Currently no grade displayed
- Score is found on Rate leaderboard
-> Should change the grade to what's found on the rate

If a grade is already displayed, idk we could chose between : 
1- Keep the highest QR grade
2- Keep the highest grade
3- Keep the highest rate grade
(maybe let the user choose, but looks like too specific of an option)

**Comment by Swan** [comment]
Online grade is only for your absolute personal best score
