### ISSUE TITLE
[Results] Include country flag next to country rank

### ISSUE THREAD

**Issue by robby250** [Quaver/Quaver#2030]
![image](https://user-images.githubusercontent.com/51453670/82728429-c2aa8900-9cf8-11ea-9084-a6199a18b058.png)
Or perhaps somewhere else in the results screen as there's no indication of which country it is whatsoever
(Ignoring the fact that you don't know whether it's about 4k or 7k as well as that was written in a different issue)

**Comment by Janko5** [comment]
Country flag next to the nick in the top panel should be enough. The flag directly in the result screen will be out of place (it would require an icon for each title and this is unnecessary)

**Comment by robby250** [comment]
Sure that's fine.
