### ISSUE TITLE
Starting the game with Vsync on sets vsync to 60hz on 144hz/240hz monitors

### ISSUE THREAD

**Issue by robby250** [Quaver/Quaver#2048]
If Vsync has been turned on from a previous session, closing and reopening the game causes vsync to use 60hz instead of the monitor's higher refresh rate. Spamming F7 until you cycle back to Vsync fixes the issue.

**Comment by YaLTeR** [comment]
gonna link this one since related https://github.com/Quaver/Quaver/issues/720#issuecomment-536165516
