### ISSUE TITLE
Song select breaks sometimes when toggling windowed/fullscreen

### ISSUE THREAD

**Issue by robby250** [Quaver/Quaver#2083]
It doesn't seem to happen in a consistent fashion, but to trigger it:
1. Press alt+enter to make the game windowed
2. Move the windowed game to another monitor
3. Press alt+enter to make it fullscreen on that monitor

Do this a few times and the song select will break (only while fullscreen, windowed still works), resulting in this:
https://steamusercontent-a.akamaihd.net/ugc/1031834104884805066/C6ABE5FF7E653C3A0E5525FE10049B164EE00AE9/

Animations don't happen anymore, the left panel doesn't change, etc.

**Comment by Fretzi** [comment]
Managed to trigger this without switching resolutions/fullscreen, and the logs spit out an error too, so I'll post my logs that contain the error for this issue
[runtime.log](https://github.com/Quaver/Quaver/files/4842100/runtime.log)
