### ISSUE TITLE
Add a way to view keymode on the results screen

### ISSUE THREAD

**Issue by KitsuneDeity** [Quaver/Quaver#2085]
Could be something like this, where the key amount icon on the same row as the mod icons:

![](https://cdn.discordapp.com/attachments/398037301696921600/717311661970554930/612020_12-55-5-714.jpg)

Or maybe it can be inside the brackets of the difficulty rating, for example:
[Retribution 1.75x] (50.23 | 7K)
or
[Another 0.95x] (25.40 | 7+1K)

**Comment by LevFlavien** [comment]
I second this
