### ISSUE TITLE
STRG + click on slider settings

### ISSUE THREAD

**Issue by NekoSlando** [Quaver/Quaver#2096]
I would like to see a optional "STRG + Click" function on the settings with slider. It means if you click on a setting with a movable slider with the STRG button pressed that it opens a input fiel do type in the exact number, it would make it easier to set a specific scroll speed value.

**Comment by robby250** [comment]
or perhaps just a regular editable input field where the number is
![Fq2m9LK](https://user-images.githubusercontent.com/51453670/83680984-685bd300-a5ea-11ea-9e17-262c4eefda55.png)
