### ISSUE TITLE
Calibrate map local offset in multiplayer room

### ISSUE THREAD

**Issue by Adrriii** [Quaver/Quaver#2113]
As a audio player, the worst thing in life is starting a multiplayer game and noticing a map is offsync (which happens a lot, especially when playing for accuracy).
In osu, you can only keep playing and hope to still have some decent ratio but you know it's over from the start.

In quaver, we can do better and very simply !
First, add a way to change the map local offset from the lobby.
Second, add a keybind that you can tap along with the beat playing in the room, and according to the current bpm point in the song that is playing it will tell you how offsync you are !

**Comment by YaLTeR** [comment]
What I usually do is seek around in F3 to find a chordjack-y spot ideally, then playtest for a few beats, which gives me an approximate idea for the offset. The problem is not every map has a convenient chordjack-y spot.

**Comment by Adrriii** [comment]
> What I usually do is seek around in F3 to find a chordjack-y spot ideally, then playtest for a few beats, which gives me an approximate idea for the offset. The problem is not every map has a convenient chordjack-y spot.

The issue here is that you're unable to apply any offset even if you're able to somehow know the offset (whether someone gives it to you, or you are able to find it in F3)

So the first point definitely holds up, it's a bit like scroll speed, you can change it either in gameplay or in the lobby, but not the offset. Just this bit could improve a lot.
The second point is a bit over the top and frankly not really necessary
