### ISSUE TITLE
Scoreboard qr and acc formatting is inconsistent at the start

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#2121]
![image](https://user-images.githubusercontent.com/1794388/84421071-b2b10580-ac23-11ea-9584-12bc641dc1a3.png)

00.00 for you, 0.00 for everyone else

**Comment by Fretzi** [comment]
It remains for every score below 10qr, see #1637

**Comment by YaLTeR** [comment]
Oh, that's what that's about
