### ISSUE TITLE
Add an option to duck game volume when game window is inactive

### ISSUE THREAD

**Issue by emberdex** [Quaver/Quaver#2143]
**Is your feature request related to a problem? Please describe.**
When tabbing out of the game, often it's because I want to listen to something (watch back a recording of my gameplay for example). It's tedious to reset my volume every time I do this.

**Describe the solution you'd like**
There should be a toggle in the audio settings, which, when enabled, the game should automatically reduce the volume to a percentage of its current setting when the window loses focus, then return it to its original setting when the game window regains focus.

**Describe alternatives you've considered**
N/A

**Comment by monotron** [comment]
I'm happy to put the dev work into this if there's enough support for it.

**Comment by robby250** [comment]
until then, you can use ctrl+p to pause the music before alt tabbing

**Comment by monotron** [comment]
good call - I still think this would be a useful feature though. Other games have implemented this.

**Comment by robby250** [comment]
i think just slapping an "Unfocused Window" volume slider under audio settings would be good enough

**Comment by monotron** [comment]
That would work too, and I guess adds the ability to customise how low you want the volume to go when you tab out

**Comment by robby250** [comment]
Oh and it should work as a percentage of the Master slider instead of taking over the volume completely. So if the unfocused slider is at 100% and the master is at 50% and you alt tab, the volume will be at 100% of 50%, which is 50%. That way you can't accidentally set your inactive window volume higher than the original volume lol
