### ISSUE TITLE
Separate offsets (audio and visual) for each gamemode

### ISSUE THREAD

**Issue by chitudorin** [Quaver/Quaver#2176]
**Is your feature request related to a problem? Please describe.**
Yes, I am using different visual offsets for 4k and 7k and changing them everytime I switch from a 4K map to a 7K map is a struggle.

**Describe the solution you'd like**
Separate settings for offsets.

**Comment by YaLTeR** [comment]
Uh, you should definitely not be using a separate _audio_ offset between modes. That's not how it works. Visual I can see.

**Comment by Swan** [comment]
Not really sure if there's a point in visual per mode as well since you can just change the hit position.
