### ISSUE TITLE
Issues with LNs at replay: misscounts do not match

### ISSUE THREAD

**Issue by Adfond** [Quaver/Quaver#2186]
The misscounts between a normal play and a replay has problems due to severe ColumnLock generated by missed LNs during replay. The replay in some maps usually dies when the LNs are generated at high bpm.

1. Play a LN map with at least 15% of LNs
2. Check the replay, take a screenshot of the score if needed
3. Don´t move anything during the replay.
4. Compare between the replay score and your screenshot

In a normal scenario, the misscounts will do not match by 2 to 5 LNs missed, in a map with like 60% LN or FLN the replay can send your replay to the doom (dead).

If you check the graph, you won´t see any difference because the extra misses occurs in a ColumnLock between a real miss and a LN above that miss.
REPLAY
![6272020 5-35-18-345](https://user-images.githubusercontent.com/58799659/85920419-a347d400-b841-11ea-874e-f7d8aef5b7ba.jpg)
ORIGINAL
![6272020 5-35-23-570](https://user-images.githubusercontent.com/58799659/85920421-a5119780-b841-11ea-8af7-e8856d7152ff.jpg)

Extra misses in the middle of the map.
REPLAY
![6272020 5-29-54-419](https://user-images.githubusercontent.com/58799659/85920468-0b96b580-b842-11ea-95c7-98f82e046aad.jpg)
ORIGINAL
![6272020 5-30-7-32](https://user-images.githubusercontent.com/58799659/85920470-0c2f4c00-b842-11ea-87d0-68805056bd48.jpg)

Videos
https://www.youtube.com/watch?v=uquBbTfDZwo Dead replay.
https://youtu.be/-J1lgmPrMtg?t=21 In this second you can see a real miss and a ColumnLock above that in third column.

 - Windows 7
 - Version v.6.21.2020

This won´t happen with Rice Charts (or 0% LNs) and the replay speed won´t affect the result at all, it will keep doing the same reaction.

*Resources*
Sunshine: https://osu.ppy.sh/beatmapsets/715728#mania/1589603
Replay: https://u.pcloud.link/publink/show?code=XZNkhIkZX1ThYtAFkxkytcacWU2x94WK10TV

Fireflies: https://u.pcloud.link/publink/show?code=XZ7XhIkZMKkbPzlYURFmiWXmBzjixbARIHV7
Replay: https://u.pcloud.link/publink/show?code=XZhXhIkZiRGy8kqSEYzUXeJ11He8cYAEUQRy

**Comment by aphelionosu** [comment]
I also want to add that misscount will increase when there's more fps drop

When there's fps drop as i recording:
![Screenshot (93)](https://user-images.githubusercontent.com/41836319/87763290-c103ca00-c83e-11ea-8afe-73aad7511b42.png)
Original:
![7172020 15-0-27-715](https://user-images.githubusercontent.com/41836319/87763514-1a6bf900-c83f-11ea-82f2-17fb110f79af.jpg)
