### ISSUE TITLE
Quaver doesn't launch. OpenGL-related issue but computer supports OpenGL 2.1

### ISSUE THREAD

**Issue by AquaVirus** [Quaver/Quaver#2190]
**Describe the bug**
The game has never been able to launch on my computer, which meets the minimum requirements.

**To Reproduce**
1. Try to run Quaver from the Steam library.

**Expected behavior**
The game should launch.

**Screenshots**
Proof that my computer meets the minimum graphics requirements (No, I can't update my graphic drivers, that's the most recent version): 
![Capture](https://user-images.githubusercontent.com/13694686/85934512-bbf3d080-b8b9-11ea-9caa-3dfe1314182e.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I've checked if the game just keeps running in the background. It doesn't.
Running versions compiled/built by other people doesn't help, so it's not anything to do with Steam.
Possibly related issue: https://github.com/Quaver/Quaver/issues/294
[runtime.log](https://github.com/Quaver/Quaver/files/4841457/runtime.log)

**Comment by 1234gggsie667** [comment]
Same issue, same error, same OpenGL version and driver version.

**Comment by enoslayd** [comment]
same

**Comment by MrTroble** [comment]
Could any of you provide additional system info in form of a system information file for your error? @AquaVirus @enoslayd @1gg2 
You can acquire it from your System Information Windows App as follows
![First](https://user-images.githubusercontent.com/13779831/95009593-8b8fa100-0623-11eb-9207-bd415d4e6696.png)
![Second](https://user-images.githubusercontent.com/13779831/95009592-8af70a80-0623-11eb-8ff7-55880266a39d.png)

**Comment by enoslayd** [comment]
ok (ill edit this later after it finished exporting)


ps. also, i cant update to newest driver since i already have the latest ones

**Comment by MrTroble** [comment]
Thank you for the additional infos @enoslayd

**Comment by MrTroble** [comment]
@enoslayd A DxDiag would be helpful tho

**Comment by enoslayd** [comment]
[DxDiag.txt](https://github.com/Quaver/Quaver/files/5322899/DxDiag.txt)

**Comment by MrTroble** [comment]
So what I found so far: 

`Microsoft.Xna.Framework.Graphics.MonoGameGLException: GL.GetError() returned 1280`
The returned error seams to be a INVALID_ENUM error, which indicates an unsupported enum given into a call of the BlendState `PlatformApplyState` function.

(As defined in glcorearb.h `#define GL_INVALID_ENUM                   0x0500`)

I have searched through the functions that could cause such error which are:

* `GL.Enable(cap)` ✔️ Hardcoded
* `GL.Disable(cap)` ✔️ Hardcoded
* `GL.BlendEquationSeparatei` ✔️ Protected by `GetBlendEquationMode()`
* `GL.BlendFuncSeparatei` ✔️ Protected by `GetBlendFactorSrc()` and `GetBlendFactorDest()`
* `GL.BlendEquationSeparate` ✔️ Protected by `GetBlendEquationMode()`
* `GL.BlendFuncSeparate` ✔️ Protected by `GetBlendFactorSrc()` and `GetBlendFactorDest()`
* `GL.ColorMask` ✔️ Does not throw INVALID_ENUM

Hence there is no problem with the Monogame Framework or it has been fixed.

**Comment by MrTroble** [comment]
@enoslayd
So from what I can see this is a driver issue. As the driver is a system driver other causes of this issue could be:

1. BIOS settings such as Power Saving settings or other DMA restriction settings.
2. Windows Insider build has corrupted driver settings/drivers.
3. Windows itself is partly corrupted.
4. Maybe your hardware is just to old to support the given blend functions or equations

So the questions would be. Since when did the issue start? Are there any other minor issues with your windows installation?
Does this issue persist? Who else has this issue? With exactly the same runtime log? Do you have a different runtime log @enoslayd like the one given by @AquaVirus ?

**Comment by enoslayd** [comment]
ummm, im on 2004 when it happened and i became insider just last month and it still happen
bios settings, nope, it doesnt have any bios settings related to that since this is an older laptop and has very little bios settings
windows itself is corrupted, no it isnt
Maybe your hardware is just to old to support the given blend functions or equations, maybe cause its open gl 2.1 only. in osu lazer, this kinda happens though it starts, i can play, but it lags so much especially in osu catch with hit lighting on

about the runtime.log, seems we have the same contents but ill still upload them just in case
[runtime.log](https://github.com/Quaver/Quaver/files/5322971/runtime.log)

**Comment by enoslayd** [comment]
maybe ill try on other os (windows 7 since this is the os that really come with the laptop) but it might take a while

**Comment by enoslayd** [comment]
So..... It works in manjaro

**Comment by MrTroble** [comment]
Thanks for the info. This means tho that there is an issue with the windows driver which is unfortunate.

**Comment by MrTroble** [comment]
![Screenshot 2020-10-04 191449](https://user-images.githubusercontent.com/13779831/95022183-e81bac00-0675-11eb-9927-5349704a366a.jpg)
It seams like your Intel Driver isn't started correctly. Could you try to starte it manually?

**Comment by MrTroble** [comment]
Sorry for the German Interface
Gestarted=started
Nein=No
@enoslayd

**Comment by enoslayd** [comment]
so.... i dont have igfx service
![image](https://user-images.githubusercontent.com/41866328/95057490-d810d480-0728-11eb-8be7-ec7977bea334.png)

**Comment by enoslayd** [comment]
so goint to the event viewer theres some errors

[WER.cf2fbf13-c64a-42d7-954d-e59f420f04d5.tmp.zip](https://github.com/Quaver/Quaver/files/5326255/WER.cf2fbf13-c64a-42d7-954d-e59f420f04d5.tmp.zip)
[errors.evtx.zip](https://github.com/Quaver/Quaver/files/5326256/errors.evtx.zip)

**Comment by MrTroble** [comment]
Could you try to start the game with it being confirmed that the driver is running?

**Comment by MrTroble** [comment]
Also could you give me more information on the graphical device used? Especially the OGL extensions and so forth. Therefore could you send me your OpenGL Hardware Capability Viewer report with https://opengl.gpuinfo.org/download.php
(with the Save XML feature)?

**Comment by enoslayd** [comment]
> Could you try to start the game with it being confirmed that the driver is running?

After i sent the services screenshot, i tried it to run again but didn't, resulting in the next comment after (event viewer)


Regarding the open gl extensions ill do it a little bit later

**Comment by enoslayd** [comment]
[lovesickgirls.xml.zip](https://github.com/Quaver/Quaver/files/5327435/lovesickgirls.xml.zip)

**Comment by MrTroble** [comment]
For some weird reasons are the used blend function extension defined:
```xml
        <extension>GL_EXT_blend_minmax</extension>
        <extension>GL_EXT_blend_subtract</extension>
        <extension>GL_EXT_blend_color</extension>
```

**Comment by enoslayd** [comment]
Is there anything i should do?

**Comment by MrTroble** [comment]
I need some time to try around and figure out why at least on of these extensions fail. And how the driver could be saved from throwing away those enums.

I will write back in a while if I find something.

**Comment by Xyphoes** [comment]
Same specs and same problem here

**Comment by enoslayd** [comment]
update:
![image](https://user-images.githubusercontent.com/41866328/126447978-0e7a0dff-afc4-45d6-a7b6-ea4f381ea4e4.png)
its running now (albeit i already updated to windows 11 insider build)
still same specs
