### ISSUE TITLE
[Song select] Show detailed score stats on mouse hover

### ISSUE THREAD

**Issue by Jolomann** [Quaver/Quaver#2196]
Right now there is no tool-tip for mouse hover, but it would be nice to have one that displays additional stats that are useful for score comparison

Let's first establish what's currently visible on the leaderboard
- Ranking number
- Grade
- Avatar
- Country
- Name
- Time since score (simplified)
- Mods
- Combo
- Rating
- Percent

The previous list works fine for a general overview and looks quite good. It would be a shame to ruin that. Though I still find myself going into the score screen for individual scores to compare judge counts. For additional stats on song select I think the following would be useful to have in the hover tool-tip
- Judge counts
- Maybe ratio and/or standard deviation
- Full date

Rough sketch (please don't use this exact look or wording, it's just to get the idea across)
![no tool-tip](https://bries.s-ul.eu/0tbNxXI6.png)
![tool-tip](https://bries.s-ul.eu/buDIMdSl.png)

**Comment by Swan** [comment]
[A video example of your request](https://streamable.com/7dnnvv)

Not sure if I'd like it to always appear on hover since it obstructs the view a ton. I would rather opt for another hoverable icon like the unbeatable one:

![img](https://i.imgur.com/CUMjVvO.png)

**Comment by Jolomann** [comment]
Yeah I see what you mean, it covers up a lot of info. It would be less obnoxious if it was anchored to the top left instead of the bottom right, but even then it could still be in the way. That said, if a user is hovering over a score I'd imagine they wanted to take a closer look at that score (for more stats), or scroll in the panel. This kind of popup isn't intrusive in osu, but then again their leaderboard has less info on the panels.

As for the icon I don't know if it's a good idea to create icons that will show on every single panel. Would you be opposed to showing the popup only when hovering accuracy? That would fit with what it shows minus the full date. I don't think the full date is all that necessary so it can be omitted imo

**Comment by robby250** [comment]
Full date can be shown over the timestamp icon, I've already had an issue for this

**Comment by robby250** [comment]
Also there's no need for the :1 part in Ratio

**Comment by Jolomann** [comment]
Ah I didn't realise the date had a popup. In that case, it would make sense to go with the latter solution (yeet the time from the panel and show it on accuracy hover)

**Comment by robby250** [comment]
Date doesn't have a popup yet, i was just talking about this: https://github.com/Quaver/Quaver/issues/1765
Show the date when hovering over the time, and the other info over the accuracy. Though that may be too many small things that you can hover? idk?

**Comment by Jolomann** [comment]
Oh I see. Currently there are already popups for several things so it would be in line with how the rest of the panel works. I first included date because the popup would show when hovering anywhere on the panel, showing general info. I'm not so sure about including date if you have to hover *accuracy* to see it. At least I wouldn't think to hover accuracy to check for the full date

**Comment by YaLTeR** [comment]
Note to Swan: please consider that some icon indicating that other judgement windows were used would be a very welcome addition to the score. Maybe that could display additional info, together with the custom judgements?
