### ISSUE TITLE
LN end sprite is draw under receptors

### ISSUE THREAD

**Issue by llAnasll** [Quaver/Quaver#2205]
https://gyazo.com/bce843390ad0c7ca3b9095639765bb29 
As you can see in this video the long note end can surpass the receptors, that feels really weird and can make confusion about when you should drop the LN.

**Comment by Swan** [comment]
It would help if you could link the skin you're using.

**Comment by YaLTeR** [comment]
You can observe this on default arrows if you set the scroll speed really low and play some LN map while holding the LNs for too long.

**Comment by llAnasll** [comment]
As yalter says that happen in default skins too, also this issue happen to all my arrow/circles skins with LN end sprite, here some examples:

Default Circles:
![6292020 22-57-22-480](https://user-images.githubusercontent.com/46055365/86055356-e8475280-ba5b-11ea-98b3-09bdadddaa25.jpg)

HexOS (swan edit):
![6292020 23-5-37-151](https://user-images.githubusercontent.com/46055365/86056079-22fdba80-ba5d-11ea-818c-5254a1d8d366.jpg)

Moongatepersona:
![6292020 23-8-43-22](https://user-images.githubusercontent.com/46055365/86056313-90a9e680-ba5d-11ea-8979-f5cd71bf9464.jpg)

**Comment by CrzJugLadder** [comment]
I have this same issue and it is very annoying because when the LN sprite is drawn bellow my receptors that makes me think I did not hit the LN at all so playing LN maps is nearly impossible for me until this is fixed
