### ISSUE TITLE
Non-PB scores should submit to mod leaderboards

### ISSUE THREAD

**Issue by loafusofbread** [Quaver/Quaver#2208]
Had trouble with a good title. What I mean is that currently, plays will not submit if they are not your highest-rated score, meaning that mod leaderboards only show PB scores, which I think kind of defeats the purpose. It would be better if scores wither lower ratings than the player's highest-rated score on that map were also visible on mod leaderboards.
Example:
I set a 97.62% score on A E I U E O Ao! x1.1 which is given a performance rating of 40.39. Despite it being my highest-rated score for that mod combination, because my personal best score is a 42.15 on x1.0, it does not show up on the global mod leaderboards. The goal is for both scores to be accounted for, and show up on their respective leaderboards. 

This would make mod leaderboards much more meaningful, and I believe that this proposal is how they were intended to function. Sorry for the long-winded-ness, it's late and I'm repeating myself to make sure I'm understood.

**Comment by YaLTeR** [comment]
I think they do submit to the rate leaderboards so maybe it's something with the mod leaderboard display?

**Comment by Swan** [comment]
The Rate leaderboard section should do exactly what's described. It shows your score per rate. However I'll keep this open if/whenever we add more ranked mods other than mirror.
