### ISSUE TITLE
Stats for Map Llngth and BPM in the map downloading screen are affected by current rate mods

### ISSUE THREAD

**Issue by loafusofbread** [Quaver/Quaver#2209]
When viewing a map in the map downloading screen the incorrect BPM and map length will be shown if the player had a a rate mod applied in the song select screen. The map's actual BPM and length should be displayed similar to the map's difficulty rating, and not be affected by what rate mod the player had selected in the previous screen.

**Comment by Fretzi** [comment]
Duplicate of #1560

**Comment by loafusofbread** [comment]
Woops!
