### ISSUE TITLE
Editor Gameplay Preview Notes Disappear

### ISSUE THREAD

**Issue by Reyder95** [Quaver/Quaver#2211]
Sometimes when moving around the timeline quickly the gameplay preview has a chance to just prevent notes from being visible. This is usually fixed by moving around the timeline more.

**Comment by Swan** [comment]
This happen with autoplay off? Or both on and off?

**Comment by Reyder95** [comment]
I've only tested with autoplay on. I cant confirm if it's both off and on.

**Comment by Jolomann** [comment]
Toggling autoplay made no difference when this happened on my end. I could see judgments and hitlighting appear but no notes
