### ISSUE TITLE
Properly convert mania SV

### ISSUE THREAD

**Issue by Adrriii** [Quaver/Quaver#2220]
When converting from mania, the SVs are capped between 0.1 and 10 multiplier. 
Thats not the case in quaver, so it should properly convert them so that we get the same map after the conversion !

**Comment by YaLTeR** [comment]
Does it break maps that were released after the osu!mania uncap update or smth

**Comment by Adrriii** [comment]
It should update maps that are imported from osu!, but of course those that are already imported to quaver can't be changed. But it's better to make this asap

**Comment by YaLTeR** [comment]
So does it break maps that were released after the osu!mania uncap update or smth

**Comment by Adrriii** [comment]
I don't understand why it would break maps ? Was there an uncap update yet ?

**Comment by YaLTeR** [comment]
What I mean is, with the current implementation I'm yet to see a single map that converts incorrectly. So I'm asking if your issue is that some newer maps aren't converted correctly?

**Comment by Adrriii** [comment]
All maps with a SV that is lower than 0.1x or greater than 10x are affected

**Comment by YaLTeR** [comment]
Could you link an example map?

**Comment by IceDynamix** [comment]
osu! clamps all SV values between 0.01x and 10x during gameplay (used to be 0.1x until the lower bound was extended), while still preserving the original value in the .osu file. Quaver takes that original value, while ignoring the fact that osu! handles it differently during gameplay.

Example: A saved value of 0.005x in the .osu file would render as 0.01x in osu! gameplay but convert and render as 0.005x in Quaver gameplay.

No example map is needed, as you can check it for yourself. Compare the note distance of 0.01x and 0.001x in osu! gameplay.

The solution would be to iterate over all SV values and clamp them between 0.01x and 10x. BPM scaling can be disregarded, as the value is clamped independently from the BPM scaling.

**Comment by YaLTeR** [comment]
> osu! clamps all SV values between 0.01x and 10x during gameplay (used to be 0.1x until the lower bound was extended)

So.. did osu! just break all older maps that relied on 0.1x in that update or what?

> No example map is needed, as you can check it for yourself.

Well of course I can check it for myself. That involves actually going through the trouble of creating a map and adding svs to it which I'd rather avoid if there was an existing map showing this issue.

**Comment by Adrriii** [comment]
See the end here : 
https://osu.ppy.sh/beatmapsets/1062462#mania/2224947
https://quavergame.com/mapset/map/11655

**Comment by Adrriii** [comment]
Another map with issues, but very different : 
https://osu.ppy.sh/beatmapsets/1182702#mania/2465807

**Comment by Eve-ning** [comment]
Might be looking for this line, the converter `clamps` it to `0.1f`
https://github.com/Quaver/Quaver.API/blob/a1801cf2b946a006635630a40cc6adde89684414/Quaver.API/Maps/Parsers/OsuBeatmap.cs#L543

**Comment by YaLTeR** [comment]
From what I understood from this thread, that clamp should be changed only for newer osu!mania maps somehow.

**Comment by Eve-ning** [comment]
peppy didn't version it actually, there's no easy way to detect it, releasing the clamp to `0.01` is potentially going to break some maps, but not to a large degree.

**Comment by YaLTeR** [comment]
So these maps that would break also broke after that osu! update?

**Comment by Eve-ning** [comment]
yea, they all just broke lol
