### ISSUE TITLE
Give map preview a SV/Timing Point density graph

### ISSUE THREAD

**Issue by Illuminati-CRAZ** [Quaver/Quaver#2225]
I've been playing some SV maps, and I thought it would be cool to be able to see where SVs are present within a map using the map preview. This could be used to be able to find the more SV intense sections of maps, and would also show where SVs are used to normalize scroll speed in multi-bpm maps.

If implemented, I was thinking this could be placed right next to the diff graph, which could get a bit crowded, or it could togglable and replace the diff graph with something like alt+F3

**Comment by YaLTeR** [comment]
> and would also show where SVs are used to normalize scroll speed in multi-bpm maps.

actually no, it would show SVs after conversion to the BPM-does-not-affect-SV form

> it could togglable and replace the diff graph with something like alt+F3

I don't like this, I think it could be made visible all the time

**Comment by robby250** [comment]
Yeah it could be made on top of the normal graph or next to it

**Comment by Kanarisky** [comment]
This could also be incorporated into the editor's density graph, as it's hard to keep track of all your SVs throughout a map. It would also aid in navigating between sections of a map, as there's no bookmarking/labelling feature (to my knowledge)
