### ISSUE TITLE
Ctrl+left/right arrow to move the text cursor in song select search

### ISSUE THREAD

**Issue by robby250** [Quaver/Quaver#2226]
Could also apply to the download screen one and wherever else applicable.

Also ctrl+shift+left/right arrows to skip words instead of letters?

**Comment by YaLTeR** [comment]
So this is a little complicated as we don't have a concept of a cursor in our text fields yet.

Apart from this, I will prefer ctrl-left/right to go by words as that's the standard key combo for going by words everywhere. Maybe we can use the regular left/right for the character-wise motion?

**Comment by Sadkawt** [comment]
This would be nice for editing the name of playlists as well. Editing names without being able to move letters is kind of a hassle :/
