### ISSUE TITLE
Etterna db check ignores songs when "AdditionalSongFolders=" is used in Etterna

### ISSUE THREAD

**Issue by Jolomann** [Quaver/Quaver#2230]
**Describe the bug**
Etterna has a line in preferences.ini called `AdditionalSongFolders=` that's primarily used for multiple installs so you don't need multiple song folders.

When this is used, Quaver will check all Etterna paths as the path specified in `quaver.cfg` *with* `/AdditionalSongs/` at the end, resulting in a mangled path

Example:
`[5:05:23] - RUNTIME - WARNING: Skipping load on file: /AdditionalSongs/Otaku's Dream 5th Anime Mix/[aloola] Ai no Hoshi [Ah! My Goddess - Tatakau Tsubasa Opening]/Ai no Hoshi.sm because the file could not be found at: C:\Games\Stepmania - Etterna point 69 point 1//AdditionalSongs/Otaku's Dream 5th Anime Mix/[aloola] Ai no Hoshi [Ah! My Goddess - Tatakau Tsubasa Opening]/Ai no Hoshi.sm`

Since I have set the additionalsongs path to `AdditionalSongFolders=C:\Games\Etterna571\Songs`, the correct path would be `C:\Games\Etterna571\Songs\Otaku's Dream 5th Anime Mix\[aloola] Ai no Hoshi [Ah! My Goddess - Tatakau Tsubasa Opening]\Ai no Hoshi.sm`

**To Reproduce**
1. Use `AdditionalSongFolders=` in `preferences.ini` (Etterna)
2. Use `EtternaDbPath =` in `quaver.cfg`
3. Check runtime logs to see mangled paths

**Expected behavior**
Quaver should use the song folder path from `AdditionalSongFolders=` located in `preferences.ini` when used, instead of combining it with the path where the `cache.db` file is located

**Version:**
 - Quaver v0.18.0

**Comment by pyroy** [comment]
I'm quite new to C# and GitHub, but I thought I'd try and fix this issue as I really want my song folder to be in Quaver. Hope this helps :)

**Comment by Jolomann** [comment]
Ah I see what you did, reading the path from preferences should work, well done. I hope this makes it in

I don't think many people do this, but you can have multiple paths set in preferences separated by commas like this
`AdditionalSongFolders=C:\Games\Songs1,C:\Games\Songs2`

I'm kind of code illiterate so I can't tell whether you accounted for that or not. If not, I'd suggest to do so just in case

**Comment by pyroy** [comment]
Oh, you're right. I should have accounted for that, my bad. Made a quick fix. should work now :)
