### ISSUE TITLE
Ratio doesn't display properly if one of the values is 0

### ISSUE THREAD

**Issue by Fretzi** [Quaver/Quaver#2232]
Example scores:

60 Marv, 0 Perf - Ratio 0:0        definitely not correct, should be 60(.0):0
0 Marv, 60 Perf - Ratio 0.0:1     rounding overall makes this weird, and makes it appear as 0.0:1. 0:60 will cause inconsistency.
0 Marv,  0 Perf  - Ratio 0:0        ye this works

**Comment by IceDynamix** [comment]
60:0 should be canceled to 1:0 or just show as infinite. 0:1 should cancel to 0.
