### ISSUE TITLE
Make an option to disable the ability to change volume with keyboard while playing

### ISSUE THREAD

**Issue by ghost** [Quaver/Quaver#2243]
**Is your feature request related to a problem? Please describe.**
I would say yes, as someone whose layout is [X C V Space Right Down Left] (i have a azerty layout), i sometime hit the alt key, and combined with the arrow, it change the volume multiple time, which is annoying, and also the fast pop up of the volume change can be distracting.

**Describe the solution you'd like**
Add an option to disable the change of volume with key when playing and/or add an option to change the key that change the volume (instead of the arrow).

**Describe alternatives you've considered**
Alternatively i could change my key layout (or stop hitting the alt key randomly), but i shouldn't feel forced to change my layout because the game lack the ability to disable volume change with keyboard.

**Comment by YaLTeR** [comment]
Maybe we should just do that by default?
