### ISSUE TITLE
Changing Sound Effect volume no longer makes it relative to Master

### ISSUE THREAD

**Issue by Emik03** [Quaver/Quaver#2247]
**Describe the bug**
Whenever you adjust the sound effect volume, it ignores whatever Master is set to.

**To Reproduce**
The most noticable way to reproduce this bug is:
1. Set Master to 0% (scroll wheel & options tab both work fine)
2. Set Effect to 100%
Sound effects are still played (like menus) despite Master being 0%.

![quaverBug](https://user-images.githubusercontent.com/14614115/86912844-fc571800-c11d-11ea-94f5-d10a0a326083.gif)

Tested on Windows 10, latest build (at the time of posting this)

**Comment by dionzz99** [comment]
oh oops
i was going to post a similar core problem. but with different kind of approach

https://github.com/Quaver/Quaver/issues/2878

**Comment by Emik03** [comment]
This bug still happens, I am able to reproduce it exactly as I stated in the initial post, albeit on Linux. (Pop!_OS 22.04 LTS x86_64)
