### ISSUE TITLE
Indexed hitsounds from osu!mania are converted to default ones

### ISSUE THREAD

**Issue by Wieku** [Quaver/Quaver#2252]
**Describe the bug**
Indexed hitsounds from osu!mania maps are converted to default hitsounds. Tried changing `.ogg` samples to `.wav` in `.osz` file with no success.

**To Reproduce**
Import osu!mania map with indexed hitsounds

**Expected behavior**
https://streamable.com/fwvo0f

**Video**
https://streamable.com/mos71w

**Version:**
https://github.com/Quaver/Quaver/commit/92ef2002e82a301d333a164b1f5ddd61f80e1fb8

**Comment by YaLTeR** [comment]
Custom hitsound sample sets aren't implemented yet (and we haven't yet decided if/how we want them to work in the 
.qua format).

**Comment by Wieku** [comment]
I'm working on converting them to keysounds since Quaver supports multiple on the same note
