### ISSUE TITLE
RFC: replace No Fail with opt-in Fail

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#2254]
Remove the No Fail mod; instead, when the HP reaches zero behave like a fail in multiplayer: the player will be notified of their failure (e.g. by playfield dimming) and can continue playing, but their score will be failed (and not submit). Introduce a Fail mod (modulo bikeshedding) that will result in current no mod behavior on failure.

### Why does this matter?
Sometimes you check the map preview and see that you might be on the edge of passing it. You have to choose between guaranteeing the enjoyment of the whole map while losing your score (it's not submitted regardless of pass with No Fail) and not losing the score but potentially failing. Making Fail optional removes the need for this choice: you play through the whole map, and if you pass your score submits, but if you don't pass you can still play to the end.

### Why does this make sense?
We have a precedent for "fail"-type mods in osu! (Sudden Death and Perfect). We have a precedent for optional Fail (multiplayer).

In fact, playing on a very easy judgement is pretty much equivalent to an optional Fail, but comes with an inconvenience of wrong judgements being displayed. Realizing this last point is what prompted me to consider this issue again.

If it's important that newer players don't mistakingly assume they can't fail and be confused, the Fail mod could be enabled by default.

**Comment by loafusofbread** [comment]
I think this is the ideal for how HP failing should work in a competitive VSRG. 100% support for this.

**Comment by Lightseypoo** [comment]
I see no good reason not to implement this, fantastic idea.

**Comment by Illuminati-CRAZ** [comment]
Only potential problem I can see with this is that we need to make sure the name of the mod doesn't make it look like someone failed

**Comment by PianoLuigi** [comment]
Support this idea 100%

**Comment by untitld** [comment]
i support this as long as the game fails you out of maps by default so as to not confuse newer players

**Comment by s8411127** [comment]
good idea!

**Comment by Reyder95** [comment]
support!

**Comment by ElectroYan** [comment]
Yes please
