### ISSUE TITLE
Numbers can't be typed in the username through the in-game login

### ISSUE THREAD

**Issue by Minion24** [Quaver/Quaver#2260]
for some reason you can't type numbers in your username when you log in through the in-game system, making usernames that contain numbers (like mine) impossible to choose

**Comment by Duder963** [comment]
Same here, but I had no prior account, so now the username tied to my Steam account is just Duder, not Duder963

**Comment by AiAe** [comment]
For now, you can request name change by emailing support@quavergame.com , and in the future, name changing will be available for donators only.

Till the problem is solved.
