### ISSUE TITLE
Unknown Server Error

### ISSUE THREAD

**Issue by erics-willi** [Quaver/Quaver#2262]
**Describe the bug**
When I first launched the game and created a username, I received an error about not being able to connect to the server, now every time I try to connect, I keep getting the Failed To Login: Unknown Server Error

**To Reproduce**
1. Click log in
2. See error

**Expected behavior**
Expect to login

[**Screenshots**]
[https://postimg.cc/CBxGPmSj](url)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Error won't go away when restarting game.

**Comment by YaLTeR** [comment]
![image](https://user-images.githubusercontent.com/1794388/87181078-5e647880-c2ea-11ea-8614-b08f67a16bbb.png)
