### ISSUE TITLE
Skin Editor ?

### ISSUE THREAD

**Issue by Edouardo26** [Quaver/Quaver#2266]
Hello, if a skin editor (even very simple it's okay)can be added it would be really useful for me (I really don't understand anything to all these **_wow skin.iniiiii_**) as much as for other people who... Like me don't understand anything... . Maybe make an in-game skin editor where you can for exemple ajust directly the size and emplacement of images or make an element transparent. Thanks. (Sorry if I don't have a god-like english)

**Comment by YaLTeR** [comment]
Duplicate of #344
