### ISSUE TITLE
Quaver crashes when tabbing out in full screen/horrible FPS in windowed

### ISSUE THREAD

**Issue by uwu-osu** [Quaver/Quaver#2267]
When on full screen in Quaver, if I tabbed out and went to another application, and try to tab back into Quaver, it crashes.

This happens Everytime in full screen, but when on windowed, it doesn’t. Which also brings another issue

The performance is 3 times worse on windowed rather than full screen.

I hope these issues can be fixed ^^

**Comment by OtterGauze** [comment]
Could you mention any platform specifics, for example what platform are you playing on? (Windows, macOS, Linux) And if you're on Linux, what compositor are you using?

**Comment by uwu-osu** [comment]
My apologies, I’m on Windows 10

**Comment by lilxleb** [comment]
For me, everything works fine. Might be a system/spec specific thing.

**Comment by Swan** [comment]
Please provide your `runtime.log` file located in the `Logs` folder and open the issue back up.
