### ISSUE TITLE
Audio offset wizard cannot suggest offset

### ISSUE THREAD

**Issue by tilda** [Quaver/Quaver#2275]
**Describe the bug**
Whenever I try to fix my busted offset it seems that the wizard errors out for some reason and does not change my offset.

**To Reproduce**
1. Go to Options -> Audio -> Calibrate Offset
2. Play through the map
3. See error

**Expected behavior**
No error and a fixed offset

**Screenshots**
[Video of what happens](https://tda.s-ul.eu/KRMbUPuf) (yes, I know my offset is busted)

**Desktop (please complete the following information):**
Windows 10 20H2, Quaver v0.19.1

**Additional context**
I'm a bit dumb in terms of audio stuff, but if it makes any difference all my audio goes through a USB sound card. If any other info is needed, please tell me.

**Comment by Swan** [comment]
Can you send your `runtime.log` file located in the `Logs` folder?

**Comment by tilda** [comment]
https://paste.ee/p/hJIwl

**Comment by tilda** [comment]
Updated this morning and it seems to be fixed so I'm closing this issue :)

**Comment by YaLTeR** [comment]
It will only set the offset if your hit deviation is not too large.
