### ISSUE TITLE
Game crashes after early access warning

### ISSUE THREAD

**Issue by cyclowns** [Quaver/Quaver#2278]
**Describe the bug**
I'm able to get past the 'Warning: This is an early access' alert as well as accept the ToC and privacy policy, but after the game gets to the main menu it crashes without fail

**To Reproduce**
1. Open up Quaver from Steam
2. Press enter to skip the early access alert
3. Game crashes

**Expected behavior**
For the game to get to the main menu without crashing

**Screenshots**
![image](https://user-images.githubusercontent.com/19853115/87217532-113ed180-c2ff-11ea-9cee-eaa08f39b28e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Unsure why this matters but Firefox
 - Version: v0.19.1

**Additional context**
Wasn't offline on steam, if that matters

**Comment by IceDynamix** [comment]
Can you post your logs? They can be found in your Quaver folder under ./Logs

**Comment by cyclowns** [comment]
https://pastebin.com/N6iKAFV5

**Comment by snowbdd9f1** [comment]
Same issue. 
Log: https://pastebin.com/ALNGsPGL

**Comment by cyclowns** [comment]
that's quite a silly reason for a game to crash but that fixed it for me as well
