### ISSUE TITLE
Allow changing of username

### ISSUE THREAD

**Issue by Duder963** [Quaver/Quaver#2281]
**Is your feature request related to a problem? Please describe.**
I fell victim to #2260 and now my username doesn't have the correct username.

**Describe the solution you'd like**
Some way of changing the username of a profile

**Describe alternatives you've considered**
Also a way to delete a profile, for whatever reason one would want their profile to be deleted

**Additional context**
I noticed no options in the Profile section on the website

**Comment by AiAe** [comment]
For now, you can request name change by emailing support@quavergame.com , and in the future, name changing will be available for donators only.
