### ISSUE TITLE
Can't change speed of a song

### ISSUE THREAD

**Issue by oyiuu** [Quaver/Quaver#2283]
When I try to change the playback rate of a song in the modifiers section, nothing happens. (Restarting the game/pc does not help)

![image](https://user-images.githubusercontent.com/46087741/87221798-205d6800-c36f-11ea-843c-049becb0cc3e.png)

OS: Windows10
-Quaver v.0.19.1

**Comment by Swan** [comment]
This is probably due to your cursor being a circle and the skin not acknowledging that.

Put `CenterCursor = True` under the `[General]` section
