### ISSUE TITLE
Game doesn't launch

### ISSUE THREAD

**Issue by zbyamada** [Quaver/Quaver#2286]
**Describe the bug**
When I start the game, it does not open even waiting for a long time.
It even appears in the task manager and in the rich presence of the discord, but it does not open at all
If I try to close it through the steam library nothing happens, and if I try to close it through the task manager, it stops running and the presence of the discord also disappears, but in steam it still appears that I am running the game.
https://prnt.sc/tfwv86 (discord presence)
https://prnt.sc/tfwvdu (steam library)
https://prnt.sc/tfwvoi (task manager)

**To Reproduce**
1. Go to 'Quaver' on steam library
2. Click on 'Play'

**Expected behavior**
The game should open seconds after clicking play

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Comment by Swan** [comment]
Please reopen the issue providing your `runtime.log` file located in the `Logs` folder.

**Comment by zbyamada** [comment]
> Please reopen the issue providing your `runtime.log` file located in the `Logs` folder.

Done
