### ISSUE TITLE
Game doesn't get past initial warning screen.

### ISSUE THREAD

**Issue by odce1206** [Quaver/Quaver#2287]
When I open the game, I see the warning screen asking me to press enter. I tried pressing enter but it doesn't get past that point. Steam overlay is also not working for some reason. I suspected it could be the game not recognizing my computer keyboard but I was able to alt-tab without issues.

OS: Windows 10. 

Here's the runtime log:

https://pastebin.com/AAUvFKRe

**Comment by Swan** [comment]
Duplicate of #2248
