### ISSUE TITLE
Cursor disapear in editor when I click on test play and theres's no hit object.

### ISSUE THREAD

**Issue by Edouardo26** [Quaver/Quaver#2290]
In the map editor when I click on test play if there's no hit object it make disapear my cursor, but I'm still able to use my mouse, I just don't see my cursor and it's really annoying because I need to either click another time on test play with hit object at a point or either quit the editor and reopen the editor to see my cursor again.

**Comment by Swan** [comment]
Duplicate of https://github.com/Quaver/Quaver/issues/1908
