### ISSUE TITLE
Can't use scandinavian keys like ["Æ", "Ø", "Å"]

### ISSUE THREAD

**Issue by HenrikDK2** [Quaver/Quaver#2295]
**Describe the bug**
I have a Danish keyboard, and i'm unable to use Æ, Ø and Å on my keboard. I use these keys for 7k on other mania games, this does limit my playspace, and is a hinderence on my comfort. 

**To Reproduce**
1. Go to 'Input Settings'
2. Click on '7K Gameplay Layout'
3. Try Æ, Ø and Å.

**Comment by ItzFireable** [comment]
Nordic keyboard, partially the same issue. Thry show up as none, but the keys still work.

Any support for layouts that are non US?

**Comment by HenrikDK2** [comment]
That's the problem, it doesn't show up as none for me.

**Comment by ItzFireable** [comment]
For me, I can choose multiple nones, äöå all work for me.

**Comment by lilxleb** [comment]
known issue, should be closed.

**Comment by HenrikDK2** [comment]
I recorded a video to show the issue [Video](https://www.youtube.com/watch?v=5jjCTV_0VfQ)
