### ISSUE TITLE
Top lane cover doesn't work as intended

### ISSUE THREAD

**Issue by chitudorin** [Quaver/Quaver#2303]
The top lane cover at 75% does cover the top, but starts at a weird position.

https://i.imgur.com/CiPFZDt.jpg

**Comment by staravia** [comment]
Can you post your skin onto here so that we can take a look

**Comment by fakebrin** [comment]
> Can you post your skin onto here so that we can take a look

I'm using [this](https://steamcommunity.com/sharedfiles/filedetails/?id=2161951743&searchtext=) skin.

**Comment by Takane42** [comment]
![image](https://user-images.githubusercontent.com/29156066/88744221-e95dc380-d170-11ea-897d-59eaf2802c3d.png)
same For The bottom lane cover
