### ISSUE TITLE
Song UI Fully Customizable.

### ISSUE THREAD

**Issue by esqzerolol** [Quaver/Quaver#2314]
**Is your feature request related to a problem? Please describe.**
When I'm playing songs and i want to see how long the song will still go on i always lose a combo because the timer sing is too far away (I have a ultrawide monitor)

**Describe the solution you'd like**
Maybe giving the option to move all the things in the interface (points, life bar, combo, time left...) will make the game a little bit better QoL wise

**Describe alternatives you've considered**
For me the best is a in-game editor with each UI element.

**Additional context**
Maybe there is already a way to do this with skin editing, but i think for a Normie like me (basic knowledge in Computers) is kinda hard changing things in the files

**Comment by YaLTeR** [comment]
A better solution is to automatically display the meters no further than some distance from the playfield. You know how in some newer FPS games the HUD always stays close the the center on ultrawide.
