### ISSUE TITLE
Make Scrollbar Clickable/Draggable

### ISSUE THREAD

**Issue by synetic707** [Quaver/Quaver#2315]
Currently It is not possible to click and drag on the scrollbar in the song selection screen on the right side. For people with over thousand maps, it's a hassle scrolling with the mouse wheel to get to the more difficult songs, when sorting by difficulty

**Comment by ItzFireable** [comment]
Use middle click to scroll :)

**Comment by Swan** [comment]
Duplicate of https://github.com/Quaver/Quaver/issues/2102
