### ISSUE TITLE
Workflow improvements for SVs in Editor

### ISSUE THREAD

**Issue by Kanarisky** [Quaver/Quaver#2319]
**Is your feature request related to a problem? Please describe.**
While Quaver's editor is fantastic, there are some possible workflow improvements to be made for SVs.
<br />

**1. SVs should be visible in the density graph, or next to it.** 
It would be easier to manage your SVs scattered throughout the map. Something like this, either on the side of—or within—the density graph:
![image](https://user-images.githubusercontent.com/68185248/87245142-60fbd500-c486-11ea-91fe-c56989b654e6.png)
<br />

**2. A hotkey for creating a new SV point.** 
Preferably rebindable. This is *ctrl + shift + P* in Osu. With this you can place many points sequentially, then *ctrl + click* every 2nd or 3rd one in the SV window to apply pattern SV in bulk. Currently, adding SVs is very slow.
<br />

**3. Mouse wheel / arrow key control of the notefield while mouse is within the non-list section of the SV window.** 
Again, to make it quicker to add SVs. Currently you must have the mouse off the SV window, scroll to the next tick, mouse over *Add* and click it, then mouse off the SV window and scroll another tick, etc. 

The above also applies to left and right arrow keys; it's based on your mouse position. In fact, if you're in the middle of typing in the "Multiplier" entry field with your mouse off the SV window and you press left or right arrow keys, it will both shift the typing position, and move forward/backward a tick in the notefield. I believe this is a bug.

With your mouse within the green rectangle below you should still have scroll wheel functionality, but you currently don't:
![image](https://user-images.githubusercontent.com/68185248/87245304-b5ec1b00-c487-11ea-86c5-ff2f28aeee9e.png)
<br />

**4. Automatically select the string in "Multiplier" entry field upon creation of an SV point.** 
Makes it quicker to create SVs, rather than having to click onto the field for every single new SV.
![image](https://user-images.githubusercontent.com/68185248/87245407-50e4f500-c488-11ea-9bdf-8616ee084f32.png)
<br />

**5. Allow navigation of SV points in the list with up/down arrow keys while the SV window is in focus.**
(Not necessarily while your mouse is hovering the SV window)
<br />

**6. While an SV point is selected in the list, pressing *Enter* should select the string in "Multiplier" entry field.** 
Makes editing points quicker, and doable completely with keyboard rather than swapping from keyboard to mouse repeatedly.
<br />

**7. Single left/right click on the "Multiplier" viewing field *next to* an SV point in the list should select the string in "Multiplier" entry field.** 
Easier editing of existing points.
![image](https://user-images.githubusercontent.com/68185248/87245829-1aa97480-c48c-11ea-8251-5d7095de5015.png)
<br />

**8. Allow dragging the bottom edge of the SV window to be able expand to a longer list of SV points.** 
Only seeing 8 points at once is really quite limiting.
![image](https://user-images.githubusercontent.com/68185248/87246009-9952e180-c48d-11ea-85d5-270460e234ed.png)
<br />

**9. Selection of a range of SV points with *shift + left click*.** 
Currently only *ctrl + left click* is possible, which makes deleting or moving whole sections a timesink.
![image](https://user-images.githubusercontent.com/68185248/87246057-fbabe200-c48d-11ea-9256-bff95d227411.png)
<br />

**10. A UI button to copy selected SV points to the current position in the map *OR* to a user-entered position**. 
Duplicating sections of SV is a huge timesink for SV mappers. Every time a mapper wants to do this, they need to copy the points, calculate the difference in time between the two sections, enter that into the "Move Times By" box then paste the points back into their original positions.

With this proposed feature you would either enter the desired position for the first selected SV point to be moved/copied to, or you would move to your desired position in the map and press the "current position" button to move/copy the selected SVs, starting at that location. The other selected SV points would remain relative to the given position of the first selected SV point. 

**This would be fantastic quality of life feature, so please consider!!**
![image](https://user-images.githubusercontent.com/68185248/87246491-28152d80-c491-11ea-9d45-4864767f693a.png)

**11. Allow middle click to control scrollbar in the SV list, similar to how it's done in song select.**
<br />

**12. Add a UI button to jump the SV list to the most recent SV at the current position within the map.** 
Would be very useful when jumping between sections, helping the mapper avoid having to manually scroll the SV list to wherever in the map they are each time.
<br />

**13. Allow clicking on the green SV lines on the right of the notefield to scroll to + select that SV point in the SV list, and also select the string in "Multiplier" entry field for editing.** 
It's easy to get lost in an ocean of SV points. This alleviates that and also provides quicker editing and jumping between sections.
![image](https://user-images.githubusercontent.com/68185248/87247238-ed61c400-c495-11ea-8fd3-edbae5add2d7.png)
<br />

**14. "Sync SV List and Notefield scrolling" toggle option.** 
What this setting would do is scroll the SV list in sync with the notefield. It's similar to what request number 12 in this list suggested, but as if the button is being held all the time. This means that while the map is playing in Editor, on every new SV point reached, the SV list would scroll down by 1. Helpful for following what's going on with your SV values while watching the effects!

While the map is not playing and the user is scrolling or scrubbing through the map, the SV list would also follow when appropriate (i.e. when new SVs are reached -- obviously no scrolling should happen when there haven't been any SV changes).

**This would be the ultimate solution to the pain that is managing the SV list**, though having it as a toggle is important for when the mapper wants to edit many SVs at once, or check what SVs are at other parts of the map without going there. 
It could even be as simple as a lock button in the top-right of the SV Window that you would click to toggle the "locking" of the SV list with the notefield.
<br />

**15. Possible future endeavour for ultimate comfort: SV grouping/layering.**
This could work similarly to grouping objects in Microsoft Office products, or how layering of notes works in the current Quaver editor. Ideally, one could darken or completely hide certain "groups" or "layers" of SV points that are linked together as one unit. When editing a single SV point in a group, the multiplier change could apply to the entire group.

You could also look at it as layers, and put SVs for different sounds of the music into different layers so you can keep track of which SV effect is emphasizing which part of the music.

I understand that this one in particular would require a new UI and is likely a whole lot of programming work. Might be a pipe dream.
  
  <br />
  
  
**I hope at least some of these can be incorporated easily. The more of these changes that are made, the less hassle mappers will have to go through to produce those mind-boggling effects we all love. I honestly can't wait for these; it'll make mapping SVs so much more fun!**

**Comment by IceDynamix** [comment]
here are my thoughts on the proposals from the view of a plugin maker (since the sv editor is basically just an included plugin written in lua). some of the comments reference [iceSV](github.com/IceDynamix/iceSV), which is my own plugin for SV editing and pattern generation. please consider using it for copying ranges of sv points for the time being.

1. not doable with plugin work

2. not doable with plugin work

3. should be solvable by having a specific script variable change when the mouse is above the list

4. not sure if possible, although you can make it that the automatically selects the entire string when clicking on the field

5. in conflict with 3, since both rely on the same variable being active at different times

6. see 4

7. probably very weird to solve so i won't give any input on that yet

8. should be easily doable

9. is not possible out of the box, you'll have to code the keybinds yourself (or use icesv, it only includes copying ranges for now but value editing will come at a later date)

10. see icesv

11. might be doable with janky mousepos calculations although i'd have to play around with it

12. very easy

13. not doable with plugins

14. possible, but might cause framedrops depending on how it's implemented

15. requires a rework of the qua file, so maybe in a year or so
