### ISSUE TITLE
When exiting chat, sometimes mouse doesn't work

### ISSUE THREAD

**Issue by Reyder95** [Quaver/Quaver#232]
Unsure exactly how to reproduce this as it only happened once, but when I was in song results screen after playing a song, I went to type some stuff in chat, and when backing out I couldn't use my mouse to control anything. However, my keyboard was perfectly functional.

**Comment by JaanJah** [comment]
I think this is similar to this issue I managed to record: https://streamable.com/2o577

Not sure how I did it, but couldn't use mouse to drag/click on anything, only scrolling would work. Keyboard also worked.
