### ISSUE TITLE
Steam achievement bug

### ISSUE THREAD

**Issue by TheJeme** [Quaver/Quaver#2324]
Achievement not unlocking in Steam while I got it in Quaver website.

I have tried to pass multiple levels even after that bug, but I still don't get that achievement. I would appreciate that it would be fixed.

**Screenshots**
https://i.imgur.com/IcWCUPh.jpg
https://i.imgur.com/p3CMHzO.jpg

**Comment by ElectroYan** [comment]
Same happened to me with the 5k combo achievement. Got the 7.5k and 10k on both steam and quaver but the 5k one only on quaver.
