### ISSUE TITLE
Timing Signatures

### ISSUE THREAD

**Issue by WinterIsPretty** [Quaver/Quaver#2341]
**Is your feature request related to a problem? Please describe.**
I can't even add waltz timing points makes it a bit harder for mapping

**Describe the solution you'd like**
the ability to type in the timing signature you need so you can also add exotic ones like 9/8 or 2/4

**Describe alternatives you've considered**
there are none

**Additional context**
none

**Comment by YaLTeR** [comment]
Duplicate of #602
