### ISSUE TITLE
Make LN sprite more black when you drop it (Should be more black by default)

### ISSUE THREAD

**Issue by llAnasll** [Quaver/Quaver#2342]
It's hard to see the difference between which LN is dropped and which isnt.

![7132020 4-55-36-969](https://user-images.githubusercontent.com/46055365/87266398-7a704180-c4c5-11ea-961a-c1943d0abe64.jpg)

**Comment by Kanarisky** [comment]
This is part of your skin's skin.ini. It's the DeadNoteColor entry. If you set it to a darker grey it will tint that colour onto every dead note.

https://old.quavergame.com/wiki/Skins/Skin.ini

**Comment by llAnasll** [comment]
This is the new default skin, i think should be more difference between which LN is dropped
