### ISSUE TITLE
Input Delay Offset Wizard/Helpers

### ISSUE THREAD

**Issue by prank855** [Quaver/Quaver#2344]
I've been trying to play for the past couple hours, fiddling with audio offset etc, yet my mean offset is always too early (around 40-30ms early for me). i hit perfectly fine in osu!mania, and have ported the essentials of my skin to the game. Its just frustrating to me since I should be getting good accuracy on these songs other wise haha.

**Describe the solution you'd like**
-Much like audio/video delay, add slider for delay to input

**Describe alternatives you've considered**
-maybe even add a feature where the first x amount of notes of song can automatically determine your input offset

**Example:**
![7122020 20-38-17-209](https://user-images.githubusercontent.com/5534076/87268599-a2d54d00-c47f-11ea-9568-9646b1babc42.jpg)

Edit: It might be that when I change the audio offset my hitsound sfx gets delayed as well, which if it is, it probably shouldn't, or atleast have a toggle of whether or not it should.

**Comment by YaLTeR** [comment]
What you want should be the visual offset. Set the audio offset by playing through the offset calibrator blindly (only listening), then adjust the visual offset to compensate for the visual reading.

**Comment by Prankster855** [comment]
> 
> 
> What you want should be the visual offset. Set the audio offset by playing through the offset calibrator blindly (only listening), then adjust the visual offset to compensate for the visual reading.

This seems to be it, I have no idea why. Trying to wrap my head around it but it doesn't make much sense, yet it worked. 

_I set mine to -42ms, which seems high, running an Predator XB271HU @165hz GSYNC 162fps locked RTSS and VSYNC-ON in Nvidia Control Panel_

Maybe it is possible to add a **second** offset wizard/calibration for visual delay?

**Comment by YaLTeR** [comment]
I would add one if I had a sound idea of how it should work, but I don't yet.

**Comment by robby250** [comment]
same offset wizard but without sound and without seeing the judgements/hiterror bar?

**Comment by robby250** [comment]
also the audio offset one should be changed so that it's easier to tap to the beat while blindfolded (and also mention that you should tap to the audio without looking at the notes)

**Comment by staravia** [comment]
created a new feature request here https://github.com/Quaver/Quaver/issues/2361

**Comment by staravia** [comment]
oops, i've misread the conversation. i'll keep the new feature request open and rename this to be more clear
