### ISSUE TITLE
[FEATURE] ESC/Retry on failed map

### ISSUE THREAD

**Issue by Mempler** [Quaver/Quaver#2349]
**Is your feature request related to a problem? Please describe.**
if you fail a map, you can't exit the map without seeing the whole dying animation

**Describe the solution you'd like**
If you fail a map, you should be able to press ESC and cancel the dying animation and swap back to the song selection scene.
Same should be done for the quick restart key!

NOTE: Quick exit doesn't work either! i tried.

**Comment by Swan** [comment]
Duplicate of #1065
