### ISSUE TITLE
Sort the player list

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#2351]
Right now it's unclear what order the players are listed in (random?). Would be nice to sort them in some order.

Global rank is natural, but we don't have one. Maybe toggle between 4K and 7K global rank sorting? This way it's easy to see when top players play and e.g. spectate them.

Maybe alphabetically? Doesn't really make a ton of sense.

**Comment by robby250** [comment]
yes 4k/7k rank sort toggle pls and also show the rank next to each name

**Comment by YaLTeR** [comment]
An idea for without toggle is to sort by min(4k rank, 7k rank)
