### ISSUE TITLE
Don't lock out the country/friend leaderboards under donator please

### ISSUE THREAD

**Issue by robby250** [Quaver/Quaver#2352]
I'm going to buy donator anyway and there are enough really cool features for donator as it is, please allow everyone to access country/friend leaderboards.

**Comment by Adrriii** [comment]
I guess this could apply to other "not costly stuff" like reading unranked leaderboards, scores are submitted anyway after a donator unlocked the leaderboard for the map. In this example it could also cause confusion since the user doesn't know if his score is in the leaderboard.
