### ISSUE TITLE
stage-right-border.png overlaps the song selection menu.

### ISSUE THREAD

**Issue by chirijikaiser** [Quaver/Quaver#2356]
**Describe the bug**
When I clicked the **[View Map]** with my skin, the character included in the element file overlaps the song selection menu.

**To Reproduce**
1. Create the element stage-right-border that includes an image of character in the right position. (The size of the element I used is 1000x1537)
2. Add it to the Stage folder of either 4k folder or 7k folder
3. After adding the element file, reload the skin in Quaver client.
4. Click the **[View Map]**.

**Expected behavior**
Any image of the character included in the element will overlap the song selection menu.

**Screenshots**
![7132020 23-4-24-706](https://user-images.githubusercontent.com/55966752/87322824-8230f400-c560-11ea-91c5-7e002a9b8f82.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: v0.19.3

**Comment by chirijikaiser** [comment]
I have a suggestion regarding this bug.

To fix this, just remove the stage borders in the map preview. Use the default instead.

**Comment by Swan** [comment]
Will add a better way doing this type of thing without modifying the border
