### ISSUE TITLE
Issue with re-uploading deleted mapsets

### ISSUE THREAD

**Issue by RagnarokVII** [Quaver/Quaver#2362]
**Describe the bug**
Once a mapset is uploaded and then deleted from the website, it is no longer possible to upload it again without changing the mapset ID and map ID. The page displays a mapset not found error.

**To Reproduce**
1. Upload a mapset from Quaver client;
2. Delete the mapset from the website;
3. Attempt uploading the mapset again from the Quaver client;
4. Attempt going on the mapset page again on the website;
5. "Mapset not found" error is displayed;
6. No longer possible to upload the mapset in question.

**Expected behavior**
Mapset being displayed on the website/ability to reupload mapset properly.

**Screenshots**
No screenshot, here is a link to a previous mapset where the issue was encountered. (Mapset was uploaded again as a different ID later)
https://quavergame.com/mapset/map/14520

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]: v.0.19.2

**Additional context**
None.

**Comment by Swan** [comment]
This is intended behavior.
