### ISSUE TITLE
Fullscreen is broken with Windows 10 scaling enabled

### ISSUE THREAD

**Issue by JustMoneko** [Quaver/Quaver#2364]
Setting the game to a fullscreen mode with Windows' 10 scaling enabled (125%) causes the game to overscan, unless the compatibility setting is changed for the program.

Screenshots:
![Base Profile Screenshot 2020 07 14 - 00 10 08 79](https://user-images.githubusercontent.com/63615036/87358952-287ff800-c567-11ea-8c53-fdeab38a0744.png)
![Base Profile Screenshot 2020 07 14 - 00 10 15 22](https://user-images.githubusercontent.com/63615036/87358953-2ae25200-c567-11ea-9348-045f16223cb1.png)

 OS: Windows 10

**Comment by NotGate** [comment]
I also had this issue. I could almost never tab back into the game. I had to close and reopen it over and over until I could randomly get access back to the options menu to turn fullscreen off. It wasn't until I found this issue that I turn scaling off and now everything works perfectly.
