### ISSUE TITLE
Borderless fullscreen not working well when XFCE compositor is running

### ISSUE THREAD

**Issue by KrosisBH** [Quaver/Quaver#2368]
**Is your feature request related to a problem? Please describe.**
I run Manjaro Linux on xfce desktop environment with a double monitor setup. One monitor is 165hz and the other is 60hz. However, even running on my 165hz monitor, it still registers as 60hz. I know this because turning on vsync caps the fps at 60, and the game plays the exact same way. I don't know if it's a problem with my system, or just a quirk of how Linux or xfce works, but it seems like running Native Linux games requires a exclusive full screen to get stuff running at 165hz instead of 60hz. Etterna has such a option and it really made a difference.

I get 900fps average, but it still feels choppy. In my OS atleast, exclusive means it complete takes over and you can't alt+tab or press the Super key to get the applications menu. The way you get out is to close the game. It appears that full screen here is borderless windowed full screen because I can alt+tab out. 

**Describe the solution you'd like**
Add an option in the video settings for an exclusive full screen mode. 

**Describe alternatives you've considered**
Running in windowed mode, lowering resolution. Turning on "Prefer Wayland" Using Wayland Vsync in the fps limiter. All have the same behavior.

**Comment by YaLTeR** [comment]
I had to turn off modeset fullscreen on Linux because it caused lock-ups when used with a weird resolution. I suppose we could check the current screen resolution and switch to modeset fullscreen only for that resolution.

That said, as far as I know in theory there should be no difference between this "exclusive" fullscreen and fullscreen borderless windowed on Linux if the mode is the same. I'm not sure why it makes a difference on some compositors. I'll need to look into it more to understand how it works.

Maybe XFCE has a "make this window fullscreen" key combo that you can press that will fix this?

**Comment by KrosisBH** [comment]
Oh my god. I totally forgot about my compositor. I had the same trouble getting osu! to work on Wine for the same reason. I like the compositor. (Who doesn't love transparent terminals) Even made a custom hotkey to swap it on and off. Lutris has a mode to disable the compositor when running the game, so I stopped.  I'll just need to tick it on and run the game from Lutris from now on.

**Comment by YaLTeR** [comment]
So there's no issue without compositor?

**Comment by KrosisBH** [comment]
Yup. Used my hotkey and it worked as expected. For any xfce users, you can toggle the Compositor with the command `xfconf-query -c xfwm4 -p /general/use_compositing -t bool --toggle`. I just bounded that to an unused binding. Only annoying thing my tilda terminal on my other monitor disables transparent so I can't run any fun bash script while playing. That's nothing huge though. Should probably close this then.

**Comment by YaLTeR** [comment]
I would want it to work out of the box even with compositor running though.

**Comment by YaLTeR** [comment]
Could you please try the [0.18.0 offline build](https://github.com/Quaver/Quaver/releases/tag/0.18.0) *with compositor enabled*? That one had exclusive fullscreen.

**Comment by KrosisBH** [comment]
It crashed on me when trying to change the settings, but I was able to make it full screen in the quaver.cfg. It has the same issue. 60hz with compositor on.

**Comment by YaLTeR** [comment]
Well, then I'm not sure there's anything easy I can do.
