### ISSUE TITLE
Music lags sometimes

### ISSUE THREAD

**Issue by rumpff** [Quaver/Quaver#2369]
**Describe the bug**
Sometimes while playing the music stops but the notes keep moving, then after 1 to 5 seconds the music continues and the notes jump back

**Screenshots**
A video if it happening (in this example the lag time isn't big, but usually it happens for 3 or more seconds)
https://streamable.com/g6tm2j
(if down) https://drive.google.com/file/d/1SC_OkhRQUWO38Q0jgBm5t5_cHf-fJyj_/view?usp=sharing

**Comment by Swan** [comment]
Try updating your drivers and reopen if this is still an issue.

**Comment by rumpff** [comment]
Updated windows to current version, updated nvidia drivers, however the issue still persists
