### ISSUE TITLE
Sound-combo-alert playing in song select

### ISSUE THREAD

**Issue by V3rald** [Quaver/Quaver#2370]
I don't know how i managed to do this but when selecting a certain song, it plays my sound-combo-alert sfx.
(in the video, that "nyaa" is my combo alert)
https://www.youtube.com/watch?v=6pkCb4LCvQ8
heres map: https://quavergame.com/mapset/map/630

Edit: it does this even after quaver restart so it has to do with this specific map i guess
Edit2: i checked it with like 200 another map, only that one does the sound

**Comment by V3rald** [comment]
Just wanted to update that i found another map: https://quavergame.com/mapset/map/1137
might help to find what's common if its still unknown

**Comment by V3rald** [comment]
was this fixed then?

**Comment by WarpABoi** [comment]
No, Swan closed all issues to clean things up. ([Full Message](https://discord.com/channels/354206121386573824/630734138923810827/1138476874360705114))

You can open this issue again if you still experience the problem.

**Comment by V3rald** [comment]
I have no way to reopen this issue. I checked and this issue still remains so if someone could open it, that would be nice
