### ISSUE TITLE
"Detect Game" Not Working Correctly

### ISSUE THREAD

**Issue by Reyder95** [Quaver/Quaver#2371]
**Note: This issue occured to someone in the discord, just putting forth the problem.**

**Description**
When detecting games, maps show up with no background and when trying to play them, it gives the error "is your .qua file valid?"

It's useful to note normal importing works, so it seems to be specifically a "detect game" issue. Or maybe an osu!db issue?

**Comment by Reyder95** [comment]
We figured it was an osu!db issue rather than a quaver bug

**Comment by IceDynamix** [comment]
The issues lies in the osu! songs directory not being at the default location, which is why it was able to read the osu!.db (title, artist, mapper) but could not find the actual map data and background.
