### ISSUE TITLE
A setting to change how the pause menu (In-Game) is opened

### ISSUE THREAD

**Issue by SeikoTheWeeb** [Quaver/Quaver#2374]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

- [Almost every time, I am trying to pause the game, i die because of the time required to hold the ESC-button.]

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

- [A setting for a prefered option on how you want to open your pause menu.
For example an option to open the pause menu by pressing the ESC-button twice instead of holding it.
Or pressing 2 buttons simultaneously.]

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

- [Remove holding the ESC-button entirely and just make it a normal button press in order to pause?]

**Additional context**
_Add any other context or screenshots about the feature request here._

- []

If anything might be unclear, just ask me on Quaver... "Seiko" my name :)
Ill be sticking around at about ~4p.m. to ~8p.m. UTC+2 ( can vary depending on the weekday )

**Comment by robby250** [comment]
![image](https://user-images.githubusercontent.com/51453670/87466942-d222c000-c61f-11ea-81da-66f656b4e9f6.png)

**Comment by SeikoTheWeeb** [comment]
Well uh... Hmm... I am kinda confused xd
I was asking a dev on quaver... and he probably didnt understood what i was asking him then...
But thanks :) that will be way more convenient. And I got a Bug to report too... just happened right now
