### ISSUE TITLE
GPU Rendering Abnormally High

### ISSUE THREAD

**Issue by CrisperSpeedruns** [Quaver/Quaver#2382]
**Describe the bug**
To be honest i'm not sure if this is a bug exactly, but I noticed that my GPU 3D rendering was sitting between 75%-80% while just sitting on the results screen. Considering there's almost nothing being rendered there it seemed pretty strange. I can kind of understand the song select being slightly higher than average since it has to load the song previews, but it seems this game is taking more GPU rendering power than is necessary, which i find odd. Compared to games like Osu, Quaver is taking more than 2-3 times the GPU processing power (Osu sitting at around 25% during a song, while Quaver is sometimes over 80%). I have noticed that the steam overlay also adds on to this and brings GPU rendering over 90% a lot of the time, I understand if not much can be done about the steam overlay portion of things.

I have an Nvidia GeForce GTX 1060 6GB

**To Reproduce**
1. Open the game
2. Look at GPU 3D renderiing in task manager
3. Open steam overlay in-game and check gpu processing power again

**Expected behavior**
I'd expect the processing power to be comparable to games such as Osu

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Latest windows 10 and chrome version

**Comment by Swan** [comment]
Use the frame limiter. Your GPU will try to render as many frames as possible if you have it on unlimited.
