### ISSUE TITLE
BPM changes with Note Snap Color dont work as expected

### ISSUE THREAD

**Issue by Storn42** [Quaver/Quaver#2383]
Occasionally in charts there will be bpm changes that dont fall on a 1/1. Sometimes its due to the performers in the song not being able to hold a steady bpm, or a gradual speed up / slow down in bpm. If I had a 1/4 stream that increased bpm every note, The expected outcome is for the notes to go red, yellow, blue, yellow. Instead this happens: 
![note snap and bpm changes](https://user-images.githubusercontent.com/68167130/87499923-54fc4880-c629-11ea-821d-757de0b14952.png)

Any file made with the intent to use BPM changes to color notes (Referred to as color theory) look nothing as intended. 

![color correction](https://user-images.githubusercontent.com/68167130/87501318-c7225c80-c62c-11ea-867c-950c8a0dbb94.png)

This seems to be cause by 2 issues 
1) if a bpm change and snap fall at the same time the color is based on the snap the bpm change falls on. There seem to be a few scenarios where the note color is actually red, usually when importing sm files. It is unclear if the new bpm sometimes takes the color snap or if the note is 1ms late, pushing it into the new bpm. 

2) All bpm changes force the note snap back to 1/1. A 1/4 stream that slows down (and correctly snaps the notes to red) will look like a 1/1 stream, implying that the bpm just sped up 4x. when the song is slowing down. 

I see two solutions to these problems. 

1) force notes that fall on bpm changes to use the snap of the new bpm and make it possible to have BPM changes that don't reset the snap to 1/1 .sm files imported should be forced to use those kinds of bpm changes since that is what they are stepped with and it will make them look more accurate to how they look in stepmania/etterna

2) Make it possible to force a note to change color. This will allow charters to manually fix note color issues and make it easier to use Color Theory.

**Comment by Illuminati-CRAZ** [comment]
Just as a note, we've been using this [plugin](https://github.com/Illuminati-CRAZ/BeatSnapColorOverride) to do some timing point jank to override note colors.
