### ISSUE TITLE
Keyboard Nordic-layout support isnt avaivable.

### ISSUE THREAD

**Issue by OreoQuaver** [Quaver/Quaver#2386]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by OreoQuaver** [comment]
I cant set keybind to letter "Ö" to play 7k as i prefer to. 
QWERTY support to the game. "Ö, Ä" letters doesnt work on  this game.
https://www.twam.info/wp-content/uploads/2009/09/german.png

**Comment by lilxleb** [comment]
known bug.
