### ISSUE TITLE
Option to turn off the score displays

### ISSUE THREAD

**Issue by Razorflamekun** [Quaver/Quaver#2390]
Hi there!  My name is Razorflame, and I always get extremely distracted by the two score displays at the top of the screen and I was wondering if you could add a new feature that would allow us the option to remove those score displays if possible? 

Thanks,
Razorflame

**Comment by YaLTeR** [comment]
I believe you can move them out of the visible area in skin.ini.

**Comment by Reyder95** [comment]
I think having something similar to osu would be nice where it's toggle-able.

**Comment by KenZync** [comment]
press tab?

**Comment by Reyder95** [comment]
> press tab?

That's like not at all what is being talked about. He's referring to the things at the top like accuracy, score rating, etc.

**Comment by Razorflamekun** [comment]
Yeah, I find things like that extremely distracting for me and I really wish there was an option to turn of those displays without having to go through the process of editing the skin.ini file.

**Comment by Razorflamekun** [comment]
This issue is now resolved with the addition of the UI hiding. I am therefore closing this.
