### ISSUE TITLE
Korean Translations

### ISSUE THREAD

**Issue by apple1367** [Quaver/Quaver#2396]
**Is your feature request related to a problem? Please describe.**
There is no korean translation. almost half of mania rankers are korean. 
maybe the major user(of major popular users) are korean.
and lots of korean players will consider turning to quaver if this game has korean support.

**Describe the solution you'd like**
please add korean translation

**Describe alternatives you've considered**
if you cant fine nice translators, i can translate it for free. apple191246@gmail.com

**Additional context**
my translation skill is better than writting skill in english

**Comment by Swan** [comment]
Localization will most likely come at a later date for many languages

**Comment by apple1367** [comment]
Ok thanks.

2020년 7월 16일 (목) 오후 9:57, Swan <notifications@github.com>님이 작성:
