### ISSUE TITLE
When Visual Delay is set to negative, it causes hit notes to "disappear" before it has reached receptors.

### ISSUE THREAD

**Issue by Prankster855** [Quaver/Quaver#2400]
**Is your feature request related to a problem? Please describe.**
Visual Delay when set to negative causes hit notes to disappear before reaching the receptors.
This has been a problem in cases where I've tapped early and causes the approaching hit note to disappear, which can and is distracting and has caught me off guard on the most severe cases of hitting way too early.

**Describe the solution you'd like**
Simply allow the hit notes to keep falling until it reaches the destination it would have gotten to if visual delay was set to 0.

Video Demonstration
[https://www.youtube.com/watch?v=zIL2_uMqdyE](https://www.youtube.com/watch?v=zIL2_uMqdyE)

**Comment by Swan** [comment]
This is what visual offset is intended to do.
