### ISSUE TITLE
autoplay misses on notes that do not overlap

### ISSUE THREAD

**Issue by slAcc** [Quaver/Quaver#2401]
as demonstrated in the video the notes did not overlap yet autoplay still misses
 below is the beatmap in question, hard difficulty about combo 900
[Amuro_vs_Killer_-_Mei_-_5731572.zip](https://github.com/Quaver/Quaver/files/4930508/Amuro_vs_Killer_-_Mei_-_5731572.zip)

and here is the video demonstration
https://www.youtube.com/watch?v=uWppTbJcwNU

**Comment by mmiiqquueell** [comment]
I don't know if it's the same. (1:35): https://youtu.be/5Toi4wTHSj0
