### ISSUE TITLE
Drag & Drop doesn't working

### ISSUE THREAD

**Issue by KeepSOBP** [Quaver/Quaver#2413]
**Describe the bug**
Title

**To Reproduce**
1. open Quaver
2. drag any files(.mp3, gp) into the game

**Expected behavior**
detect files

**Screenshots**

![image](https://bread.shx.gg/NR1h3p.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise LTSC
 - Browser Chrome
 - Version ??

**Additional context**
idk

**Comment by lilxleb** [comment]
Press cancel and go out of the editor, and then drag it in.

**Comment by KeepSOBP** [comment]
@lilxleb nothing works
![bug](https://bread.shx.gg/y74iby.gif)

**Comment by Swan** [comment]
Duplicate of #384. Not sure what's causing this for some users but we're tracking it.
