### ISSUE TITLE
After-map problem 

### ISSUE THREAD

**Issue by ZmanAce** [Quaver/Quaver#2423]
**Describe the bug**
After playing a few maps, BEATen of failed (sorry for the pun), the game turns black (Almost. You can only barley see).

**To Reproduce**
1. Boot up the game. 
2. Click on 'Singleplayer'
3. Play a few maps
4. Look at the (not so) black abyss

**Expected behavior**
To go to map/song select in singleplayer mode

**Comment by Swan** [comment]
Please open the issue back up providing your `runtime.log` file located in the `Logs` folder.

**Comment by ZmanAce** [comment]
How to get to it tho

**Comment by ZmanAce** [comment]
Seems fixed anyway... huh
Welp, whatever
