### ISSUE TITLE
Avatars re: Ingame/Profile 

### ISSUE THREAD

**Issue by AlyxiaFox** [Quaver/Quaver#2428]
Native Avatar support, with support for APNG/WebM/Gif for Donators. 

Making steam avatar your default avatar when you join with the option to change it separate from the steam client.

**Comment by YaLTeR** [comment]
Why?

**Comment by AlyxiaFox** [comment]
You are going to have to be more specific on what you mean by "Why".

Why do I want native avatar support on the website?
Why do I want APNG/WebM/Gif support?
Why do I think steam avatars should be used as default?
Or D all of the above?

**Comment by YaLTeR** [comment]
Why, as in why are Steam avatars not sufficient? Introducing our own avatars involves considerable effort and significant additional complexity, so there should be a good motivation.

**Comment by AlyxiaFox** [comment]
Avatar updates from steam to Quaver takes a few hours to sync. Having your own system would eliminate that problem. As well as some players most likely feel like I do and would like to use a different avatar than steam. Also Animated avatars are cool and adds to the list of perks for Donators, some players may donate just based off this feature. You could tie the entire system to a Donator only perk as well, You already offer the ability to have a custom banner, I would love to see that extended to the avatars as well.

Lastly I'm not looking to give you motivation for a feature, this is just an idea/suggestion. If yourself and the team like the idea then cool, i'm glad I can help. If you don't like it, that's okay too. Either way I will continue to monetarily support the game monthly.

Thank you for taking the time to respond. :)

**Comment by Prankster855** [comment]
There are people who would want a separate image for Quaver from Steam, and it being to make it animated could be the perk you receive for being a donator. There probably someone who wants their favorite anime character or whatever as their Quaver profile pic, and a funny meme on their steam. The same way that Quaver has a separate user page from steam, they serve different purposes.

**Comment by YaLTeR** [comment]
> Avatar updates from steam to Quaver takes a few hours to sync.

That wasn't the case for me, Quaver picked my new Steam avatar pretty much instantly.

> The same way that Quaver has a separate user page from steam, they serve different purposes.

Quaver has a lot of statistics to display on its user page. With friends, Quaver has to support an important use-case that Steam lacks (non-mutual friends). With avatars the usefullness is much more subjective.

Anyhow, thanks for expanding on the idea, this is the kind of explanation I was looking for.
