### ISSUE TITLE
Add non-release style long notes (holds) in addition to regular LNs in standard gameplay 

### ISSUE THREAD

**Issue by yeetpreet** [Quaver/Quaver#2429]
## Terminology

In this post, I'm going to be referencing different types of "notes" from several different rhythm games, and since Quaver players may come from a variety of rhythm-gaming backgrounds, let me be extremely explicit about what I am talking about when I refer to different things:

- **Regular Notes**: The bread-and-butter rhythm game note— you just press it at a certain timing and get a judgment for the note. No holding, releasing, or anything.
- **LNs**: "Long notes" as they are currently implemented in Quaver. The player must hit the start of the note at a certain timing (judged within a timing window), must keep their key held down for the duration of the note, and must _release_ their key at the end of the note, which is also judged within a timing window.
- **Holds**: I'll use to refer to holds as they implemented in games like DDR, StepMania, ITG, etc. The player must hit the start of the note at a certain timing (judged within the timing window), at which point the note becomes active. The player must keep the note active until the end of the duration of the hold, where they either get a "good" judgment for holding it down for the whole period, or a "bad" judgment if they let go of the hold early. _The player may keep the note held down past the end of the hold with no penalty;_ all the game looks for is if they held the note down during the period the hold was active. It should be mentioned that in some games you can release the hold in the middle and the game gives you a short buffer period to get back on the hold to keep it active. This is sometimes used to "ghost step," but it won't be important for our discussion here.

In a nutshell, what I will refer to as _holds_ are essentially LNs in Quaver that you do not have to release at a precise timing and are not judged for— you just have to hold to the end.

## Feature Request

I strongly request that Quaver implements holds alongside LNs in regular gameplay; not as a modifier or anything, but as a 3rd fundamental type of note in the game (joining regular notes and LNs). 

## Why Having Just LNs Is an Issue

I recognize that this is a fundamental change to the gameplay, but having just LNs is a poor rhythm game design decision and should not have been the case from the beginning. Here's why:

### Musical Elements

(I will be using the terms "chart" and "map" interchangeably).

As most people that have ever dabbled in charting/stepping/mapping before know, the notes in a chart should represent elements in the music so that it feels like players are tapping, moving their feet, playing their guitar, etc. along with the instruments, drums, and so on in a piece of music. (For this discussion, we will be ignoring "dumps," charts that shove a large volume of notes that do not exist in the song musically for the sake of difficulty, a joke, or w/e).

For LNs, you receive two judgments, one for hitting the initial note and one for releasing at the end of the note. Both of these events are explicit actions performed by the player that are scored and must be timed at a particular moment in the music, So, both the initial note and release should line up with musical elements in the song. However, this is where the root of the problem lies.

If you go ahead and download a couple popular ranked charts on Quaver, you will notice very quickly that the releases of LNs are frequently placed inappropriately in the chart and do not line up with a musical element. 

(Before we go any further, a lot of people will probably mention here about LN spam in high level charts and the state of the high level meta in general. I'll talk about that a bit more later on, but for now, we are _not_ talking about very challenging charts where LNs are used to simply create difficulty, but more about medium-hard and lower difficulty charts where you expect LNs to be used sensibly with the music).

So this is a problem in and of itself. LNs are being used poorly in ranked, moderate difficulty charts where you would expect them to go with the music. But more fundamentally, this is partially the fault of the decision itself to _solely_ have LNs (and not regular holds)— they are limiting from a charting perspective.

### Charting with LNs

Let's say you wanted to chart a moment in a song that often occurs in electronic music where there are big identical synth+kick hits on the quarter notes (or some other quantization) and nothing else in the music, like this:
https://clyp.it/bel0fq2u?token=608f56402a1fc594bf143616b9ae7f67

A sensible way to chart something like this would be to have identical kicks on the quarter notes with holds that cut off a bit before the following note, and this is what I would do in many games:

<img src="https://i.imgur.com/ZsvzjGy.jpg">

In this example, I made the holds 3/16ths long, leaving a 1/16th gap between the notes. Even though musically the duration of the synth hit extends all the way to the next hit, we aren't worried about the hold ending a bit early since we're not judged on the exact release timing and we still get the sensation of holding down notes on the sustained synth hits, not to mention we want to add a bit of space between them anyways for readability.

However, with LNs in Quaver, there is an immediate problem. Suddenly I now have to release the holds at a specific timing even though there is no element in the music that the release timing goes to. You may say, "make them on different keys and extend the holds to be the entire quarter note," but then I can't have them be the same jumps repeatedly which is what I want since the music is playing the same hit. Not to mention, what if I felt the synth hits were particularly powerful and wanted to make them be 3-notes or 4-notes simultaneously? There is no good way to go about this situation with just LNs— they add musical cues where there are none.

Another problematic situation is when you have a long, sustained note in a song that slowly decays out until it is silent. With holds, you can just have the hold extend until the note becomes quiet enough that you can't hear it and then end the hold. With LNs, you can do the same thing, but 1) you have to time a release and get a judgment on a silent musical cue which is ultimately arbitrarily placed as people will likely differ on when they decide the note is "quiet enough" to warrant the end of the LN, and 2) both the initial hit and release of the LN have the same impact in terms of scoring and judgment, yet musically speaking, the initial attack of a sustained note has nowhere near the same emphasis as the point at which it becomes inaudible.

These are just two examples in the sea of common musical elements that are frustrating to chart when only having access to LNs. When working on charts for Quaver, I get incredibly frustrated with LNs introducing extra musical cues where I don't want there to be any, and it can be a very big pain to work around. 

### Don't Ditch LNs

To be clear, this is _not_ to say that LNs are bad. I am saying that _only_ having LNs, and not having holds, is bad. LNs can be a fantastic tool for creating expressive charts with really cool and interesting techniques, and I wouldn't want them to be replaced with holds. Again, having _only_ LNs forces them to be used when any kind of sustained note is desired, often introducing extra musical cues that simply do not exist in the music and making chart writing frustrating.

### Some Counter-Arguments

I'd like to pre-empt some points that people may make against this argument or alternatives they may suggest.

- **Many other rhythm games have just LNs as well:** Quaver is Quaver, not another rhythm game. It's not like the overwhelming majority of rhythm games have solely LNs. Many games have just holds, many have both (LNs are sometimes called "lifts" in other games), some have neither, and some have a bunch of other stuff. As a new, open-source rhythm game, I don't think Quaver should be so limited as to just having LNs.
- **Quaver is based off of X game that has just LNs as well:** Correct me if I'm wrong, but I don't believe Quaver is emulation software. Basing Quaver off of some other game is no reason to avoid expanding on it and adding more features that improve the game. 
- **Just have holds be a modifier that replaces LNs:** This doesn't solve the underlying issue and just makes it so that players who don't enjoy playing LNs don't have to deal with them. Not to mention, this would likely be a score-disqualifying option, and even if it wasn't, hold-scores would be definitely looked down upon against LN-scores.

### LNs in High-Level Charts

This is slightly unrelated, but I do want to discuss the saturation of LNs in high-level charts briefly as well. Many of the very difficult Quaver charts are extremely dense LN charts, and if that's what the high-level players want to play, that's obviously fine, but there is a sizeable fraction of people who do not enjoy LNs and may be put off from the game given that the high end is packed with them. Introducting holds could add some variety to the upper end and potentially soften this issue somewhat.

## Wrap-Up

As mentioned earlier, I do recognize that this is a fundamental gameplay change and will require fairly heavy development effort, but please do consider the change to improve the quality of charts in this game and the enjoyment for many players. At the moment, I'm very much on the fence about spending time playing and writing a lot of charts for this game, so I hope this post and the following discussion can push things in the right direction.

**Comment by citrus3301** [comment]
I think there should be a mod to turn off release timings for sure as this would make playing imported etterna maps that were charted without release timings in mind much easier, whether or not the full note gets added to the mapping editor or not I have no strong opinions on. But adding the mod would be much easier to do in the first place, would make playing a lot of etterna maps more fun, and wouldn't require huge changes to the editor and engine.
