### ISSUE TITLE
Name change stops me updating my maps

### ISSUE THREAD

**Issue by H1Pur** [Quaver/Quaver#2434]
I just changed my name but when I went to update one of my maps I got the message that the map did not belong to me. 

The map I am attempting to update is Aleph-0 if that is required to be known.

![7192020 15-50-47-467](https://user-images.githubusercontent.com/68507481/87877698-aadd4180-c9d7-11ea-86bf-f74658f802b0.jpg)
![image](https://user-images.githubusercontent.com/68507481/87877721-d52eff00-c9d7-11ea-9b13-90ce793985d4.png)

**Comment by AntecMoma** [comment]
Are you editiing the metadata or the map file
