### ISSUE TITLE
Seperate 4k and 7k skin selection

### ISSUE THREAD

**Issue by Simply420** [Quaver/Quaver#2435]
I play both 4k and 7k, and would like to not have to manually change skin when I switch game modes. I love how there is already a separate scroll speed selector.

Separating the skin selection based on game mode would be ideal, players can use 2 different skins and seamlessly transition game modes without manually changing their skin selection. Thank you for considering!

**Comment by IceDynamix** [comment]
Quaver's skinning system is designed in such a way, that it makes merging two different skins for the gamemodes very easy. Check your skin's folder, you'll see a 4k and 7k folder. Copy (replace) the one over to the other and copy (replace) the 7k section of the skin.ini file over as well. That's it! Nothing else to do.

**Comment by Simply420** [comment]
Oh, that's really easy. Thank you!
