### ISSUE TITLE
High CPU usage while alt tabbed

### ISSUE THREAD

**Issue by darian777** [Quaver/Quaver#2436]
Option to 'Lower FPS On Inactive Window' doesn't seem to work when you are in song but paused.

**To Reproduce**
1. Have Lower FPS on Inactive Window enabled.
2. Pause while playing.
3. Alt tab

**Expected behavior**
I expected this feature to work :).

**Screenshots**
![obraz](https://user-images.githubusercontent.com/54085525/87884071-f6a9de00-ca0b-11ea-969c-62329127a9a5.png)

**Desktop (please complete the following information):**
 - OS: win10

**Comment by Swan** [comment]
This is by design. It will not limit during gameplay or the editor.

**Comment by robby250** [comment]
it should probably still limit during gameplay while paused but it's a pretty specific case
