### ISSUE TITLE
Discord Lag Issue

### ISSUE THREAD

**Issue by XTLOL1** [Quaver/Quaver#2437]
While on Windowed Mode, haven't tested with the rest of the modes, when i get a message notification on discord my monitor stops displaying 144hz for some time, this is connected to Quaver because it's the only game that has this issue that i play.

**To Reproduce**
1. Have a 144hz Monitor.
2. Use Windowed Mode any where in the game, menus included.
3. Get a Message Notification on Discord.
4. ???
5. See error

**Expected behavior**
The monitor should stay on 144hz.

**Screenshots**
Can't really screen shot this. :(

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: Dunno

**Additional context**
I will look at my posts frequently, so ask anything in case of doubt.

**Comment by Swan** [comment]
Windows taskbar notifications are known to do this across a lot of games - not just Quaver.
