### ISSUE TITLE
Unable to LM click on maps in song selection menu

### ISSUE THREAD

**Issue by Belotti01** [Quaver/Quaver#2441]
Opened the game today and I'm unable to click on songs to select them, which has never happened since I started playing. Using the keyboard arrows to move between songs works fine, as does the middle click to quickly go through the maps.

Edit: Restarting the game fixed the bug

**Comment by qusteka** [comment]
I am frequently able to reproduce this behavior by hitting CTRL + O to open the options in the score screen or otherwise unusual UI environments.
