### ISSUE TITLE
Achievements Buggede

### ISSUE THREAD

**Issue by asdounwaiudna** [Quaver/Quaver#2446]
I do not know if it is a problem with Steam or what, however certain milestone achievements (combo = 500, 1000, 2000, 2500 etc...) hit on a map and no achievements pop up; acts as if I never achieved them! Not a game breaking bug but just something I have noticed! 

Again I fail to know if it's a bug via steam or with the game itself!

**Comment by Swan** [comment]
Duplicate of #2324
