### ISSUE TITLE
NVIDIA Custom Resolutions not working

### ISSUE THREAD

**Issue by barkshark** [Quaver/Quaver#2447]
**Describe the bug**
With a custom resolution applied in the NVIDIA Control Panel, running Quaver in fullscreen will cause this setting to revert to the last used non-custom resolution

**To Reproduce**
Steps to reproduce the behavior: (Requires an NVIDIA graphics card and a monitor capable of being configured with the tool)
- Close Quaver
- Open the NVIDIA Control Panel (A lot of systems hiccup a bit in this app for some reason, don't worry if it takes a while to pop up or is slow.)
- Under "Display", head to "Change resolution".
- Click "Customize..."
- Click "Enable resolutions not exposed by the display"
- Click "Create Custom Resolution"
= NOTE = | This usually requires the use of an external monitor capable of some custom settings. For best results, a high refresh rate monitor is recommended.
- Set the Refresh Rate to something more than 1 lower than the current number, I.E. 55 Hz.
- Test it, and make sure that it still displays.
- If it does, click yes, and then wait for the control panel to finish flickering and refreshing. 
- Select the new custom resolution, click apply, and click "Yes".
- If your monitor or display has such a feature, check your current refresh rate, or in my case "Vertical Frequency."
- Start Quaver, and set the game to run in full-screen.
- If this is reproducible, your monitor should flicker, and the game will show up. Check your refresh rate again- it will have returned to whatever your normal refresh rate is (typically 60.)

**Expected behavior**
When entering fullscreen, it should generally use the resolution and refresh rate the system was already using, but in this case, it always resets it to 60.

**Screenshots**
(Video - And yes, I'm using a smart TV as a monitor. Shh. It works and I can still get mid A ranks, still learning.)
https://www.dropbox.com/s/jfw60079q5zhj69/what.mp4?dl=0

**Desktop (please complete the following information):**
 - OS: Windows 10 2004 (BUILD 19041.329, WFEP 120.2202.130.0)
 - Browser MSEdge Chromium (Why is this a thing?)
 - Quaver v0.20.0 (Or latest steam version as of issue submission.)

**Additional context**
This isn't exactly high priority, and I'm also not sure about the ease of a fix. My bet's on either agonizingly painful or ludicrously easy.

**Comment by Prankster855** [comment]
If you are just using NVIDIA custom resolutions to overclock the refresh rate, I've had similar issues in the past with certain games as well in regards to the game not reacting properly. The only real fix i found is to use [CRU (Custom Resolution Utility](https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU)) which is a much more powerful and proper utility for monitor overclocking/EDID editor.

**Comment by barkshark** [comment]
Interesting, I didn't know about CRU before now. It seems to be working under that. Shame on NVIDIA for incompatibility?
