### ISSUE TITLE
Hidden/Hiddenoffset/Flashlight/Fade-In modifiers (+Bug)

### ISSUE THREAD

**Issue by Vortical8** [Quaver/Quaver#2449]
**I literally can't play quaver**, this because i use Hidden to read better, yes, to **read better**.
I can't read the patterns without hidden, i tried to modify the skin receptors but, when i put the "auto-hidden" receptors, the HitPosition started at the tip of the png i selected.

For being graphic:
![image](https://user-images.githubusercontent.com/68624736/88125899-a74be500-cba6-11ea-8cff-29dab3b31ec0.png)

Also, i don't know how the game files work, possibly there's a solution for this, but is easier to **make a hiddenmod**.

**As a solution, I propose:**
HiddenMod: A fade that increments its size when the combo rises (Reference: Osu!Mania Hidden Mod)
HiddenOffsetMod: A fade that's always in the top (Reference: Stepmania Etterna HiddenOffset Mod/Osu!Mania Hidden Skins)
FadeIn: Same as HiddenMod, but it starts in the opposite side of the scroll (Reference: Osu!Mania FadeIn Mod)
Flashlight: Like HiddenMod and FadeIn mixed, but static (Reference: Osu!Mania Flashlight Mod).

**As alternatives**, i want to add this as a toggle in options menu, **not as a modifier**. Remember that modifiers also appears in the final score of the song, if you play 1.3x, the score will display as 1.3x The same thing happens with HiddenMod: if you play 1.3x + Hidden, the score will display 1.3x, Hidden. If this were an option and you play 1.3x + Hidden, the score will display only 1.3x modifier.

**There's a lot** of HiddenMod, FadeIn, Flashlight and HiddenOffset **mains**, like me. Someone plays because it looks harder to other people, other because the Silver-S Rank in osu looks like "Wow a silver S, such a pro", other because they play better with those mods, and other, because they literally can't play without the mods (as example, me).
Thank you all for reading, hope this wouldn't get ignored or discussed in the past.

**Comment by Swan** [comment]
There's already lane cover options that does exactly what you've described out of the box. It's adjustable via the options menu. 

[Skinning](https://i.imgur.com/XPv9bRx.png)

![img](https://i.imgur.com/XPv9bRx.png)

Options: 

![img](https://i.imgur.com/WHxmxvo.png)
