### ISSUE TITLE
pressing esc and back is always confusing

### ISSUE THREAD

**Issue by apple1367** [Quaver/Quaver#2466]
**Is your feature request related to a problem? Please describe.**
idk when to press esc and when to press back.
sometimes it wokrs identical but sometimes, make you go to the previous screen (such as in the multiplayer)

**Describe the solution you'd like**
1. rename 'back' butten. (like 'leave butten in match)
like 'back to title' or 'main'

2. when i press esc in the 'group by playlist', make it go to 'group by none' menu.

3. always make esc double tap when esc goes to the title or multi robby

**Describe alternatives you've considered**

**Additional context**

**Comment by Swan** [comment]
The priority is as follows for every screen:

- Right side panel
- Left side panel
- Exit Screen
