### ISSUE TITLE
LN% is not working

### ISSUE THREAD

**Issue by apple1367** [Quaver/Quaver#2468]
**Describe the bug**
LN% says it has LN, but there is no LN 

**To Reproduce**
https://quavergame.com/mapset/map/15540
there is an example.

**Expected behavior**
LN% hac to shown other numbers.

**Screenshots**
https://i.imgur.com/7ikzt2s.jpg
https://i.imgur.com/vylJ3z4.jpg

**Desktop (please complete the following information):**
windows 10 64bit 2004
newest version at 2020 07 25

**Additional context**

**Comment by KitsuneDeity** [comment]
You have the NLN (no long note) modifier on, dude.
