### ISSUE TITLE
Changing rates causes crashes on very large osu.db files when filtering song select on rapid rate changes.

### ISSUE THREAD

**Issue by qusteka** [Quaver/Quaver#2476]
**Describe the bug**
Changing rates will frequently lead to crashes on maps that are from Osu!Mania when the results of the song select screen are filtered on very large song databases.

**To Reproduce**
1. Go to 'Single player'
2. Apply several search filters (e.g.: d>10 d<20)
3. Rapidly change rates on different songs
4. Game eventually crashes.

**Expected behavior**
Rate change without crash.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome (irrelevant?)
 - Version latest

**Comment by Swan** [comment]
Please re-open the issue with your `runtime.log` file located in the `/Logs/` folder.
