### ISSUE TITLE
Hide Map and hide Mapset functionality on song select.

### ISSUE THREAD

**Issue by qusteka** [Quaver/Quaver#2480]
**Is your feature request related to a problem? Please describe.**
When I'm playing the game sometimes i come across a map or even an entire mapset that i don't want to have to deal with currently or potentially forever. I'd rather not delete it in case I'll multi someone that wants to play it or if i change my mind at a later point in time.

**Describe the solution you'd like**
Allowing the player to hide individual Maps and entire Mapsets from song select on a case by case basis that is easily reversible on a case by case basis. This should hide them regardless of search parameters without deleting them. This would also save you some server/data bandwith 😏. 

**Describe alternatives you've considered**
Opening the folder and moving the map/mapset to a different folder. It's wildly impractical but it works.

**Comment by Swan** [comment]
Not seeing the full point in this. You can either delete it or skip to the next song.

**Comment by qusteka** [comment]
The point of this is to save you bandwidth and me headache. I don't want Songs that I tried and decided I don't like to show up in my 'maps' download tab nor my library. If I delete them I'm just gonna keep downloading them again and again by accident.
