### ISSUE TITLE
'Unable to find requested files' error while export replays on Pop OS

### ISSUE THREAD

**Issue by zrksrynt** [Quaver/Quaver#2489]
So I try to use export replays feature and suddenly many new file explorer open and there is error sign about 'can't find requested file'. Im currently using Pop! OS, Ubuntu-based Linux Distro. Please fix this so I can share my replay to non quaver players.
Thanks!
![Screenshot from 2020-07-27 13-10-19](https://user-images.githubusercontent.com/61215583/88509550-8272ca00-d00b-11ea-9b6a-7bd5da17e2bb.png)

**Comment by YaLTeR** [comment]
Could you tell me where your Quaver is installed? Like, the full path. Also what exactly you're doing. Additionally, could you provide `Logs/runtime.log` contents after this issue happens?

**Comment by zrksrynt** [comment]
This is my full path for Quaver installation folder : /home/zero/.steam/debian-installation/steamapps/common/Quaver
And this is my Logs/runtime.log after try to export replays: [runtime.log](https://github.com/Quaver/Quaver/files/4980287/runtime.log)

**Comment by YaLTeR** [comment]
Do you have `/home/zero/.steam/debian-installation/steamapps/common/Quaver/Data/r/85.qr` as it says in the log? What if you try `nautilus /home/zero/.steam/debian-installation/steamapps/common/Quaver/Data/r/85.qr` from the terminal manually?

**Comment by zrksrynt** [comment]
I do have /home/zero/.steam/debian-installation/steamapps/common/Quaver/Data/r/85.qr and if i try to directly open it with nautilus 85.qr file is exist
Here i provide the screenshot of nautilus:
![image](https://user-images.githubusercontent.com/61215583/88510430-2a3cc780-d00d-11ea-8ebb-d7b063df7cfd.png)

**Comment by YaLTeR** [comment]
Reproduced it on my machine with export map. I'll look into it.
