### ISSUE TITLE
Bad hit conversion between ranked judge window (J4/standard) and higher judge window

### ISSUE THREAD

**Issue by aphelionosu** [Quaver/Quaver#2491]
For example like this. I did FC on this map with J5 (strict)
![7282020 10-41-28-6](https://user-images.githubusercontent.com/41836319/88616857-67fa2880-d0bf-11ea-8876-1589cbb9c1c6.jpg)

while in J4 (standard), this doesn't count FC
![7282020 10-41-36-178](https://user-images.githubusercontent.com/41836319/88616880-7a746200-d0bf-11ea-990a-430dfdcf73d1.jpg)

**Comment by Fretzi** [comment]
That can happen. The miss-hitwindow is bigger on Standard, so if you for example hit a key about 165ms off, it would be too far for the Strict window, but be right in the miss window for Standard.

**Comment by qusteka** [comment]
Please elaborate how 127ms (or whatever the strict miss window is) can ever be bigger than 165ms.

**Comment by Fretzi** [comment]
The miss window for Strict is 149ms and the miss window for Standard is 165ms, so if you hit a key 164ms early, it will count as a miss for Standard, but be too early for Strict and thus not be a miss.

**Comment by qusteka** [comment]
So hitting early is never a miss? That seems a little confusing.

**Comment by Fretzi** [comment]
If you hit super early or super late, it won't count as anything, no.
This would allow you to fail the map immediately by mashing the keys in the first few seconds.

**Comment by qusteka** [comment]
> If you hit super early or super late, it won't count as anything, no.
> This would allow you to fail the map immediately by mashing the keys in the first few seconds, or during a break time.

Alright I think I get it now:
Hitting 160 ms early on standard->Miss
Hitting 151 ms early on strict->Miss
Hitting between 150-164 ms early on strict->Nothing

**Comment by Illuminati-CRAZ** [comment]
yes
