### ISSUE TITLE
Autoplay bug

### ISSUE THREAD

**Issue by chitudorin** [Quaver/Quaver#2493]
Disabling autoplay in the song select doesn't let you search for other songs after switching from view map. 
https://youtu.be/0wzuRGu-0yo

**Comment by mmiiqquueell** [comment]
I don't think it's a bug, I think the game captures the keyboard for play in the viewer. 

Anyway I found some bugs.
**Related to the song selection**: Rarely all the notes on the track disappear, the notes reappear when changing the map selection ↑/↓ or ←/→.

**Related to the autoplay**: When selecting a map with autoplay rarely stops working and sometimes lost all life and show the scoring screen with an F and other times the autoplay stops working but the game continues. https://imgur.com/a/TtkQ8hH
