### ISSUE TITLE
Game fails to start silently because of skin

### ISSUE THREAD

**Issue by LevFlavien** [Quaver/Quaver#2496]
Game fails to start silently (Quaver.exe disappears without leaving an error message).  
It is because of my `skin.ini` according to the logs. It's the only one I got installed.

Log: https://pastebin.com/raw/MTh2p0wg
skin.ini: https://pastebin.com/raw/tAHxdHXC

**Desktop**
 - OS: Windows 10 64bit (Build 18363)
 - Version v0.21.0

**Comment by IceDynamix** [comment]
You can fix the skin.ini by resolving following line:
```ini
Author: TouchFluffyTail's IIDX Mania with PouletFurtif's modifications
```
The game doesn't start up because it's failing to interpret that line, as ini values are assigned with an equals (=) and not with a colon (:). Compare the other lines.

Just change the colon to an equals and it should start up again.

**Comment by LevFlavien** [comment]
Thank you

Actually I reported this for the lack of error message.

**Comment by LevFlavien** [comment]
Great thanks
