### ISSUE TITLE
cant import beatmaps from the game itself.

### ISSUE THREAD

**Issue by CRAZECRAZE** [Quaver/Quaver#2508]
hi, i cant download maps from the game itself.
every time i try, it wont work and i get that error
![image](https://user-images.githubusercontent.com/67030091/88981068-ce549600-d2cd-11ea-9f1a-84f93d4c8987.png)

if i try download the map from the web, it will work. but from the game, it just wont.

**Comment by Swan** [comment]
Please provide your log files located in the `/Logs/` directory and re-open the issue.
