### ISSUE TITLE
[Bug] When failed press retry will enter black screen in specific songs.

### ISSUE THREAD

**Issue by Kotoki1337** [Quaver/Quaver#2512]
**Describe the bug**
When a specific song failed, press the retry button at the same time will enter the black screen. but the game is still in progress at this time.

***Note: that the song has requirements***
Currently, I only found this one:
[Lil Peep & XXXTENTACION - Falling Down](https://quavergame.com/mapset/map/14709) - **Mimi's Easy**&**Normal** with **1.5x speed**

**To Reproduce**
1. Play the specific song
2. Lets this game failed
3. **Hold** the Retry button during the frozen animation of Failed(You can hear the retry hitsound after that), and it will enter a black screen after the animation ends
4. You will see the issue

**Expected behavior**
Forbidden to use retry during fail animation or perfectly supports retry actions during fail animation

**Screenshots**
https://youtu.be/JLrmAEKblr8
I have no any cut.

**Desktop:**
 - OS: Windows 10 2004
 - Browser: Edge Developer 86.0.587.0(Official Build)...... Wait it doesn't matter?
 - Version: Steam release

**Additional context**
This is very weird. I have made many attempts and found that only reproduce in these two difficulties(Easy and Normal), and not every time it can be reproduced successfully. I initially thought that this bug might be caused by the Skip part at the beginning of the map, but not all maps can be restored.

**Comment by shinkyi** [comment]
several topics like these already but will soon be merged prolly ;p

**Comment by Kotoki1337** [comment]
> several topics like these already but will soon be merged prolly ;p

oh really? my bad
