### ISSUE TITLE
Config file is never written

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#2520]
Config file is never updated. All setting changes persist only until a game restart.

Not sure when this started happening, but it's consistently happening on Steam 0.21.0. Information of interest includes that I'm running Fedora 32 and my quaver.cfg is a symlink. However, when I've been running local builds of Quaver previously, I've had the exact same setup and had no issues.

**Comment by robby250** [comment]
probably has something to do with https://github.com/Quaver/Quaver/pull/2502/files
