### ISSUE TITLE
Got the achievement "Perfectionist" from failing

### ISSUE THREAD

**Issue by supeunsun** [Quaver/Quaver#2523]
Got the achievement "Perfectionist" when I had failed

**To Reproduce**
1. Go to Map GENS D'ARMES
2. Play the Map
3. Get one perfect note
4. Fail the Map
OS is Windows 10 
Screenshot of achievement 
(https://user-images.githubusercontent.com/69278205/89470121-fc602d00-d748-11ea-93fd-ebf19e15a733.png)

**Comment by mmiiqquueell** [comment]
The same thing happened to me yesterday (Win 7). I was trying to adjust the timing and I do a little randomness to see if the game was going better and for no reason the achievement appeared, I was only testing and didn't even complete the (ramdom) map.

**Comment by DolphinChips** [comment]
Just encountered this, accidentally pressed the keyboard while trying to pause the game with my broken pause button

**Comment by choskyo** [comment]
Encountered this on https://quavergame.com/mapset/map/13329
With the attached score:. 
![2020-08-09-155548_2560x1440_scrot](https://user-images.githubusercontent.com/14852622/89735257-1c4d6480-da59-11ea-9e3b-22f0f1e0f474.png)
