### ISSUE TITLE
Yellow update button on in-game leaderboards reverts to old version of the charts.

### ISSUE THREAD

**Issue by Razorflamekun** [Quaver/Quaver#2528]
**Describe the bug**
If you press the yellow "update" button found on the leaderboards for the map you just saved but did not upload, it reverts to the previous version of the chart and completely undoes any changes made to the chart.

**To Reproduce**
1. Go to a map in the editor.
2. Make changes to the map in the editor.
3. Save the map in the editor.
4. Exit the editor 
5. Click on the yellow "update" button on the leaderboards for that map.

**Expected behavior**
The map should automatically upload the map and any changes that are made to it instead of reverting to a previous version of the map.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 22.0

**Comment by Fretzi** [comment]
It should be like this, so that if you accidentaly mess up and for example delete a large portion of the map, you can easily revert to an earlier state of the map.
There is also no reason to have multiple ways to update the map anyway.
