### ISSUE TITLE
favourite maps

### ISSUE THREAD

**Issue by H1Pur** [Quaver/Quaver#2531]
I think players should be able to favourite a map, as a form of map rating.
This could also be used to show the communities' favourite maps.

If an unranked map is loved enough it could be made a "community favourite" where it is like a ranked map but without the rating, letting non-donors see the maps leaderboards.
Any maps that are "community favourites" could also have a separate filter to ranked and unranked maps.

Just an idea that would let the maps that cant be ranked still get the attention they deserve if people like it enough.

**Comment by llAnasll** [comment]
do you mean something like this? I have already a request created if you want to check it: https://github.com/Quaver/Quaver.Website/issues/190
![image](https://user-images.githubusercontent.com/46055365/89700226-e7dc8a00-d92c-11ea-8fcf-e511718eca22.png)

**Comment by H1Pur** [comment]
> do you mean something like this? (screenshot from etterna website) I have already a request created if you want to check it: [Quaver/Quaver.Website#190](https://github.com/Quaver/Quaver.Website/issues/190)
> ![image](https://user-images.githubusercontent.com/46055365/89700226-e7dc8a00-d92c-11ea-8fcf-e511718eca22.png)

**Comment by H1Pur** [comment]
yes i do mean something like this but also more similar to the osu! loved feature where some maps that wouldnt be ranked still get leaderboards and count towards ranked score but not overall ranking
