### ISSUE TITLE
Grades listed next to charts don't match personal best grade

### ISSUE THREAD

**Issue by LaplaceFox** [Quaver/Quaver#2533]
**Describe the bug**
On the map selection, when sorting by difficulty, there are grades listed next to the individual charts, but when I play a song and improve my score, these grades don't seem to update, and there's no clear way to refresh these grades.

**Expected behavior**
I'd expect that the grade of the best score I've received would display next to the song in the score selection. If it's not possible to update these individually when a song is played, maybe refreshing them with a button in the settings or at game start would be possible.

**Screenshots**
![image](https://user-images.githubusercontent.com/59992815/89705747-a1d3f600-d92d-11ea-8fa2-89e55bba48ff.png)
![image](https://user-images.githubusercontent.com/59992815/89705801-26bf0f80-d92e-11ea-9da8-7795abe49a9c.png)

**Desktop (please complete the following information):**
 - Windows 10 Home, ver 1903

**Comment by IceDynamix** [comment]
It will display the grade of the best **submitted** score. Change your ranking leaderboard to global and it will update, given that your scores have submitted when you made them.

**Comment by LaplaceFox** [comment]
Ah, thanks, that clears it up. I still feel like there should be a way to mass-update them though.
