### ISSUE TITLE
Skipping long intros before the fadein ends cause quaver to crash

### ISSUE THREAD

**Issue by marcostudios** [Quaver/Quaver#255]
**Describe the bug**
Skipping long intros (on this example there's a 4 min intro) before the fadein ends cause quaver to be stuck and then it crashes

**To Reproduce**
1. Start the map
2. Skip when you see the skip image and before the fadein ends
3. Quaver crashes

**Expected behavior**
The intro is skipped

**Screenshots**
https://i.imgur.com/Qrxtm6d.gifv

**Desktop (please complete the following information):**
 - OS: Windows 10 

**Additional context**
I don't know how long the intro should be to replicate this bug.

**Comment by YaLTeR** [comment]
Does this still happen? Could you attach an example map which triggers the issue?

**Comment by marcostudios** [comment]
It doesn't happen anymore
