### ISSUE TITLE
Keybinds aren't being bound after being inputted fast enough into the Gameplay Layout screen

### ISSUE THREAD

**Issue by kochav** [Quaver/Quaver#256]
**Describe the bug**
As in the title, keybinds aren't being bound when you try to bind your layout fast enough.

**To Reproduce**
Hit the keys fast (like doing stairs for example) on Gameplay Layout key change screen.
Video down here: https://youtu.be/CBk6L5Nae-A

**Expected behavior**
No matter the input speed that's being done by the player, the game should catch it properly and set it in the order as it were pressed.

**Comment by malfple** [comment]
Apparently, in my machine, keeping some keys pressed prevents the input of other keys. Example: A, spacebar
