### ISSUE TITLE
[Editor] BPM on "DETAILS" panel doesn't dynamically update

### ISSUE THREAD

**Issue by Jolomann** [Quaver/Quaver#2561]
**Describe the bug**
If you change the initial BPM of a map, the BPM on the "DETAILS" panel doesn't update to the new value until you re-enter editor

**To Reproduce**
1. Go to editor
2. Change BPM of the first timing point 
3. Details panel still shows the old value
4. Re-enter editor
5. Value has updated

**Expected behavior**
The BPM value should dynamically update if you change the initial BPM

**Screenshots**

Old value in "DETAILS" panel, new value in timing point editor
![bpm](https://bries.s-ul.eu/DKjZMWGW.png)

**Desktop (please complete the following information):**
 - Quaver v0.22.0

**Comment by IceDynamix** [comment]
Relevant function
https://github.com/Quaver/Quaver/blob/eb663b1ee768e0c9f3f5f5cca69337f820bafff6/Quaver.Shared/Screens/Edit/UI/Panels/EditorPanelDetails.cs#L203
