### ISSUE TITLE
Maps imported with early alpha client have no LN% or NPS stats

### ISSUE THREAD

**Issue by Jolomann** [Quaver/Quaver#2562]
**Describe the bug**
Some of my imports are from very early alpha, and their LN% and NPS stats show up as 0, which means they're included with a search like `ln=0` even though LNs can be present. The stats are not updated on re-import

**To Reproduce**
1. Skip to 4 if you have maps imported during the first alpha key wave (or around that time)
2. Somehow get an early alpha client
3. Import map on that
4. Observe LN% and NPS showing as 0 on newest client for the early alpha imported maps

**Expected behavior**
The stats should be generated after import or during reimport if they're not present

**Screenshots**

Searching for `ln=0`
![search](https://cdn.discordapp.com/attachments/398037301696921600/744539595944886312/980610_20200816145339_1.png)

Map is included in search while it has LNs because of missing stats
![editor](https://cdn.discordapp.com/attachments/398037301696921600/744539644485435403/980610_20200816145353_1.png)

**Desktop (please complete the following information):**
 - Quaver v0.22.0

**Comment by Swan** [comment]
Best thing to do would be to re-import them. The alpha client is considered obsolete at this point.

**Comment by Jolomann** [comment]
I repeat, stats are not updated on re-import

**Comment by Swan** [comment]
Are you deleting first and then re-importing?

![img](https://i.imgur.com/UwAtZ28.png)

**Comment by Jolomann** [comment]
Oh, that may be the issue. I didn't delete them first. Will scores disappear if I delete and then re-import?

**Comment by Swan** [comment]
They shouldn't as long as it's the same exact file you had imported previously.

**Comment by Jolomann** [comment]
Sweet, I'll consider this solved
