### ISSUE TITLE
Text on the chat text box doesn't show spaces

### ISSUE THREAD

**Issue by marcostudios** [Quaver/Quaver#257]
**Describe the bug**
Spacing after writing a word causes the text to get the last letter removed or the space isn't shown but it's counted and it's showed when you write other text

**To Reproduce**
1. Write a word (test)
2. Add a space
3. The last word has one letter removed (tes) or the space isn't shown
4. Write a letter
5. Now the text is shown correctly and the space is counted correctly

**Expected behavior**
The text should be correct

**Screenshots**
https://i.imgur.com/fnkknbz.gifv

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by YaLTeR** [comment]
Does this still happen?

**Comment by marcostudios** [comment]
It is still happening, sorry for the late response
