### ISSUE TITLE
Compatibility mode?

### ISSUE THREAD

**Issue by Smiglet** [Quaver/Quaver#2574]
Recently my client has started running at around 10 FPS, when it was running fine before. I have the same problem in osu! unless compatibility mode is turned on. Will this ever become a feature? It's really annoying not being able to play at all, but until this is added, I can't play.

**Comment by Swan** [comment]
What does compatibility mode do?

**Comment by enoslayd** [comment]
it converts opengl "calls" (idk what that means) to direct x 9 equivalent

**Comment by Swan** [comment]
DX is windows only.
