### ISSUE TITLE
[Skinning] Some elements are default even though, they shouldn't   Linux

### ISSUE THREAD

**Issue by Pebor** [Quaver/Quaver#2587]
When i load up a new skin, something almost always stays the default, even though the files are different. This mainly happens on skins hit objects.

![image](https://user-images.githubusercontent.com/32438954/90972120-96c8ba80-e516-11ea-9e76-e0308ac04437.png)
Sorry for bad screen, but the problem is visible

 - OS: [Ubuntu 20.04]

In the screenshot am using Yugen, one of the most popular skins. I also tried a lot of new and old stuff, but am just most of the time getting the default skin... for bars at least, idk if it is on the other ones too.

**Comment by Jolomann** [comment]
Lots of skins are broken following update 0.23.0, including Yugen https://steamcommunity.com/games/980610/announcements/detail/2736453958208789052

It can take a while before everybody has updated their skins, so check if they've been updated on 21/08/2020 or after. Dates can be seen on the right side of workshop item pages
![date](https://bries.s-ul.eu/GHSxvnnq.png)

Known updated skins so far(from the #workshop channel on Quaver's discord)
[Alice Schuberg v1.4](https://steamcommunity.com/sharedfiles/filedetails/?id=2162352829)
[Clearium](https://steamcommunity.com/sharedfiles/filedetails/?id=2149852369)
[O2Jam](https://steamcommunity.com/sharedfiles/filedetails/?id=2164273711)

[Default Arrows](https://steamcommunity.com/sharedfiles/filedetails/?id=2163713057)
[Default Bars](https://steamcommunity.com/sharedfiles/filedetails/?id=2162713645)
[Default Circles](https://steamcommunity.com/sharedfiles/filedetails/?id=2163546266)

**Comment by Pebor** [comment]
Hey! Sorry i didn't specify this. The skinning problem was happening to me since day one.. that's the update 0.22.0 for me.

**Comment by Jolomann** [comment]
Oh, in that case it might be a simple fix. Try switching the "Default skin" option where you change skins

**Comment by Pebor** [comment]
I just tried the skins you listed as up to date and they work for me. Maybe that update fixed it for me normally?
I swear i had default hit objects on every skin before. But it seems to work fine now! Thanks!
