### ISSUE TITLE
SM Files are massively out of sync

### ISSUE THREAD

**Issue by TheROPFather** [Quaver/Quaver#259]
**Describe the bug**
When playing any .sm file that has been imported, the sync is completely broken. It feels like it isn't taking the offset into account, or it's parsing the offset incorrectly.

**Desktop (please complete the following information):**
 - OS: Windows 7

**Comment by Swan** [comment]
This is known. I'm not sure if it is an error with the actual conversion or if the offset is completely off in the original file. 

[Parser](https://github.com/Quaver/Quaver.API/blob/581c837820937dfe4926e1b23d747e9ed61d3a65/Quaver.API/Maps/Parsers/StepManiaFile.cs)

**Comment by TheROPFather** [comment]
Someone had a theory that you may have flipped the sign on the offset, because SM is weird and it doesn't work the way you expect - it was just a hunch someone had, but it sounds like the kinda dumb thing that could cause the bug and make it hard to pinpoint.
