### ISSUE TITLE
Can't find my mapset on Online Listing

### ISSUE THREAD

**Issue by Jessematics** [Quaver/Quaver#2594]
**Describe the bug**
I recently uploaded a mapset made by myself, but I can't find it on Online Listing. The website says "404 Mapset Not Found".

**To Reproduce**
1.When choosing the map to play in single play mode, click right mouse button.
2.Select "Online Listing".
3.A website show up, but says "404 Mapset Not Found".

**Expected behavior**
The website should show the information of my mapset. 

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
1.My map ID are 23474-23478, mapset ID is 3000.
2.Sorry, my English is poor. If there is something that you are not understand, please ask me for more information.

**Comment by Swan** [comment]
The set has been restored. This can happen if you press the delete button on the website.

**Comment by Jessematics** [comment]
Thanks! I truly pressed the delete button once because I uploaded it wrongly before it was finished. My fault. Anyway, thank you very much!!
