### ISSUE TITLE
On-Screen Text with 100% Background Brightness

### ISSUE THREAD

**Issue by fint54321** [Quaver/Quaver#2602]
**Is your feature request related to a problem? Please describe.**
On certain maps, some of the on-screen text becomes very difficult to read with 100% background brightness because the background can match the colour of the text. Image example below.

**Describe the solution you'd like**
If you're familiar with the Minecraft crosshair, it changes colour based on what's behind it. It basically changes to different shades of grey, but it doesn't change as a whole; different areas of it change according to what's behind it, as if it were translucent. The same thing could be done with the text.

**Additional context**
![Screen Shot 2020-08-27 at 6 53 42 PM](https://user-images.githubusercontent.com/70301751/91513388-0cc37d80-e899-11ea-813e-ae9f886089b0.png)
Obviously only the text in the top-right is hard to read in this image, but you can imagine so would everything else if the background image were the right colour in the right places.

**Comment by YaLTeR** [comment]
Maybe adding a black outline to some of these skin elements would work, plus a background panel for the FPS counter (see how it's done in osu!).
