### ISSUE TITLE
Desync between Map Audio, Map Visuals, and Play Button during Replay

### ISSUE THREAD

**Issue by dylan-park** [Quaver/Quaver#2608]
**Describe the bug**
When viewing the replay for a map that has a skippable section at the beginning, clicking the play button right as the map loads before elapsing the skippable time, or just skipping, will cause a desync between the play button, map audio, and the replay's notes. This makes the map audio play when the play mode is on, and the audio pause but the map's notes scroll when the pause mode is on.

**To Reproduce**
1. Open the replay for any map that has a skippable intro
2. Right as you load the replay quickly click the play button before the map starts
3. The audio for the map will start while the actual map does not scroll
4. Clicking on the play button to pause will stop the map audio but start scrolling

**Expected behavior**
I would probably expect the play button to be disabled during the initial map skip time, or for the play button to continue to reflect and update both the state of the replay of the map and the map audio.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.24.0

**Additional context**
While not a specifically important or game breaking bug in the grand scheme of things, it was some interesting behavior that I think is unintended. I've tested this method on multiple songs with and without scroll speed modifiers, but all maps with skippable intros face this issue regardless.

**Comment by davidlinye** [comment]
This also applies to the autoplay mod, since it's basically a 100% replay of the map.
