### ISSUE TITLE
FPS Counter overlapping with the remaining length of the track

### ISSUE THREAD

**Issue by aitor98** [Quaver/Quaver#261]
As you can see, once you activate both settings, the FPS counter overlaps with the remaining length of the track, making it really hard to visualize while playing. 

![ss 2018-12-21 at 02 01 32](https://user-images.githubusercontent.com/29734268/50318913-90be4300-04c4-11e9-95d4-3816b0fa4ecf.jpg)

**Comment by JaanJah** [comment]
Fixed https://github.com/Quaver/Quaver/pull/271
