### ISSUE TITLE
Measure line is flashing at low scroll speeds

### ISSUE THREAD

**Issue by hippostars** [Quaver/Quaver#2613]
**Describe the bug**
The Scrolly Thing In The Middle Just Starts Shaking
**To Reproduce**
Im Not Sure How To Repoduce It.

**Expected behavior**
Same Thing Happens Every Time It Just Starts Doing It For 5 Seconds Then Stops.

**Screenshots**
Attached Video
https://drive.google.com/file/d/1iZvkh4JT-k-CnuK89eKfJsAl66Ex7emo/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version Latest From Report

**Additional context**

**Comment by hippostars** [comment]
Watching back at the recording it looks a lot worse when its not recorded, however i don't believe its a performance issue due to my fps staying at 60

**Comment by IceDynamix** [comment]
Probably related to the 1 pixel issue and it's more noticable since you're using a slow scroll speed here. If you're distracted by it then you can always disable measure lines in the options. Also, please edit the issue title to "Measure line is flashing at low scroll speeds".

**Comment by hippostars** [comment]
> Probably related to the 1 pixel issue and it's more noticable since you're using a slow scroll speed here. If you're distracted by it then you can always disable measure lines in the options. Also, please edit the issue title to "Measure line is flashing at low scroll speeds".

I Wasn't Able To Find That In The Options Where Exactly Would It Be?

**Comment by hippostars** [comment]
> Probably related to the 1 pixel issue and it's more noticable since you're using a slow scroll speed here. If you're distracted by it then you can always disable measure lines in the options. Also, please edit the issue title to "Measure line is flashing at low scroll speeds".

Ok I Found The Option, But It Still Does The Same Thing, Even When Its Disabled
