### ISSUE TITLE
Can't log in the servers

### ISSUE THREAD

**Issue by PeterGalax** [Quaver/Quaver#2614]
So I downloaded the game from Steam and I can't log in the servers. I use Xubuntu 20.04 LTS, got an I3 with 3,1 GHz, 4 GB of RAM and a GeForce GT 710. I'm from Brazil and my internet is fine so I don't know what is happening. What should I do?

At first it stuck like this:

![image](https://user-images.githubusercontent.com/70556258/91789787-b7170a00-ebe5-11ea-818a-0ce4236c3c60.png)

Then I restarted the game and after a while, this appears:

![image](https://user-images.githubusercontent.com/70556258/91788828-95b51e80-ebe3-11ea-94b1-d419c3df36d5.png)

I put my nickname and this screen shows up:

![image](https://user-images.githubusercontent.com/70556258/91788929-d6ad3300-ebe3-11ea-8da1-44456cdd5239.png)

But it keeps going back to "choose my nickname" screen and cycling between the last two images again and again.

At last, I checked my notifications and these errors where there:

![image](https://user-images.githubusercontent.com/70556258/91790366-f4c86280-ebe6-11ea-8e8f-2786e8917260.png)

This game seems very cool and interesting but with this problem It seems that I can't download maps/songs. I don't know what to do. Thanks in advance.

**Comment by hippostars** [comment]
Are You Logged Into Steam Servers?

**Comment by PeterGalax** [comment]
Yes, I do.

Em ter, 1 de set de 2020 00:43, hippostars <notifications@github.com>
escreveu:

**Comment by PeterGalax** [comment]
![image](https://user-images.githubusercontent.com/70556258/91794469-82a94b00-ebf1-11ea-9590-8559eb773160.png)

**Comment by ItzFireable** [comment]
You're not connected to the friends server. Click on friends and on the popup, click connect.

Not sure if it'll help or not, but try it.

**Comment by PeterGalax** [comment]
It worked! Thanks a lot, I really appreciate.

**Comment by YuriFernandes150** [comment]
I am also getting this exact same error, and logging into the friends server does not fix it. Im using Deepin 20.1.
