### ISSUE TITLE
Approaching Blue Zenith bug.

### ISSUE THREAD

**Issue by Bentacool** [Quaver/Quaver#2621]
I got the Blue Zenith achievement even though I am rank 600 global in 7k

I should not have the Blue Zenith achievement

![20200904075358_1](https://user-images.githubusercontent.com/70726419/92177639-3aee2200-ee84-11ea-98d4-f3dc848e8d3c.jpg)

![20200904075519_1](https://user-images.githubusercontent.com/70726419/92177659-43def380-ee84-11ea-85d3-7ba6f4ca624d.jpg)

version 0.24.0

**Comment by Suprnova123** [comment]
This issue still exists in 0.25.0, in my experience it happened after completing a 4k map. For one reason or another, the game thought that I was in 1st globally, as shown in [this screenshot](https://cdn.discordapp.com/attachments/603730493074046978/762844100407328808/unknown.png) (possibly from connection issues). It was at this point that I got the achievement.

**Comment by VRcontrib** [comment]
This issue still exists in 1.2.0! Not on my account, but I noticed it on a steam friend's account. User ID is [507704](https://quavergame.com/user/507704) if that helps. They're nowhere near #100 rank, but they somehow got the achievement on August 19, 2023.
