### ISSUE TITLE
Weird difficulty calculation for some vibro maps.

### ISSUE THREAD

**Issue by cleanaa** [Quaver/Quaver#264]
**Describe the bug**
Some maps are extremely overrated compared to extremely similar vibro LN maps.

Has to do with LN Vibro Spam

https://www.twitch.tv/videos/351939675
at 37:50 you can see it has almost a 50 rating for a map that seems to be identical in patterns as maware.

**Comment by staravia** [comment]
The Difficulty Calc for the current build is outdated. It will be updated in #330 once approved.
