### ISSUE TITLE
Game crashes when downloading a large amount of songs

### ISSUE THREAD

**Issue by MileStone1263** [Quaver/Quaver#2644]
**Describe the bug**
When downloading a large amount of songs Quaver would crash.

**To Reproduce**
1. Go to 'Download Songs'
2. Download a large amount of songs
3. Press the "Esc" key to go to main menu
4. Game crashes

**Expected behavior**
I would be able to go to main menu then to single player mode to import all my downloaded songs.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [1903]

**Additional context**
It can also happen in the Song Download section.

**Comment by KaidenFrizu** [comment]
Issue already mentioned in #2345
