### ISSUE TITLE
Quick Restart Input

### ISSUE THREAD

**Issue by XTLOL1** [Quaver/Quaver#2660]
I can't set the "ç" key to the quick restart input, it just shows "None" (guessing it doesn't recognise the input).

1. Go to the Settings.
2. Click on Input.
3. Scroll down to "Quick Restart Input".
4. Select the "ç" key as input.
5. See error.

It should assign the "ç" key to the Quick Restart Input, but it doesn't.

Desktop (please complete the following information):
 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [24.00]

Can provide more info if needed.

**Comment by KaidenFrizu** [comment]
Can't tell the exact solution but try checking #297 and #401
