### ISSUE TITLE
Refresh Skin Button

### ISSUE THREAD

**Issue by loafusofbread** [Quaver/Quaver#267]
When making changes to a skin, you have to load another skin to switch off of it, then choose the one you want to reload if you want to see the changes you made. This is a minor inconvenience but adds up to a lot of time wasted and unnecessary mouse clicks. Easy solution is a reload button that skips straight to reloading only your skin, easy peasy. Would make skinning a lot easier. Pictured is my high effort portrayal to illustrate what I mean
![quaver mspain art](https://user-images.githubusercontent.com/41889550/50323476-001d3e00-0497-11e9-9446-3d3101a58ac9.png)

**Comment by loafusofbread** [comment]
That looks awful but it's a reload button take my word for it

**Comment by JaanJah** [comment]
I think also a key combination would be fine for this. For example osu! uses Ctrl+Alt+Shift+S key combination to reload the skin.
