### ISSUE TITLE
Remove "comma-separated" from the Tags input field placeholder 

### ISSUE THREAD

**Issue by PianoLuigi** [Quaver/Quaver#2673]
Currently, the placeholder text in the Tags input field says "Enter comma-separated tags to help players find your map". 

While using commas to separate tags might be useful in cases where a tag consists of multiple words, it's not a common practice among the mappers, not required anywhere in the ranking criteria and has already caused misunderstandings regarding whether they are actually required or not (see the on-hold wave [here](https://discordapp.com/channels/354206121386573824/757657241837895771/762874349211746314)). 

Removing the "comma-separated" from the placeholder would simply and quickly fix this, unless the intention is at some point to actually require comma-separated tags.

**Comment by Razorflamekun** [comment]
I actually always separate my tags with commas, and I think I know of a few other mappers that do this, but for the most part, I'd agree with you.

**Comment by Striikerr** [comment]
Personally, I separate with commas, as it's much easier to read IMO, and as you mentioned, allows the distinction between multi-word tags and single. In the event that the outcome is to make them optional, I would say removing the placeholder when initially entering the tags would be appropriate. Although I still believe the addition of commas to be better, I'm impartial to the outcome.
