### ISSUE TITLE
I was able to play the game last night but today, it isn't working.

### ISSUE THREAD

**Issue by jakuuuuub** [Quaver/Quaver#2676]
The game doesn't open when steam says it is running. When/If it does open, it is after several minutes and it either doesn't load or it runs at like less than 1 fps.

1. Open

Expected behavior:
It opens, without error.

OS:
Microsoft Windows 10 Pro Build 19041 x64

I've played this game for the past month without error. I tried looking in task manager, only sometimes could I find Quaver. Idk what is happening lol

Edit: It opened after 20 minutes and it crashed when I clicked singleplayer.

**Comment by chirijikaiser** [comment]
Do you mind posting your logs in here? That would help you solve your problem.
