### ISSUE TITLE
Perfectionist glitch

### ISSUE THREAD

**Issue by RowanOwO** [Quaver/Quaver#2677]
I got the perfectionist bug by accident, not even getting 100% on a chart. I was testing whether the purple or yellow excellent judge was "marvelous" or "perfect."

1. Go onto any map
2. Get 1 marvelous and let yourself fail, not pressing anything else
3. You get the perfectionist achievement

 - OS: Win10
 - Version: .25.0

**Comment by CelluloidRacer2** [comment]
@Swan I can confirm this issue still exists.
