### ISSUE TITLE
Make No Pause a setting instead of a mod

### ISSUE THREAD

**Issue by loafusofbread** [Quaver/Quaver#268]
No Pause is something that players probably wont be toggling on and off depending on the map, therefore the modifications tab is the wrong place for it, especially since the tab is reset every time the game is closed, i.e. you have to re-enable it every time.

**Comment by Sublimity** [comment]
#273 Swan decided on just completely removing this. Pls close the issue thx <3

**Comment by Sublimity** [comment]
@Swan close this issue thanks

**Comment by Swan** [comment]
Resolved by #273
