### ISSUE TITLE
internet connection isn't stable when playing multyplayer

### ISSUE THREAD

**Issue by reinance** [Quaver/Quaver#2688]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by chirijikaiser** [comment]
Please explain the error of the issue. Also, please put your runtime.log and network.log from your Logs folder in here.

**Comment by reinance** [comment]
So I’ve quit the game so tomorrow I will send the image.ok?  Sent from Mail for Windows 10 From: chirijikaiserSent: 12 October 2020 13:12To: Quaver/QuaverCc: reinance; AuthorSubject: Re: [Quaver/Quaver] internet connection isn't stable when playing multyplayer (#2688) Please explain the error of the issue. Also, please put your runtime.log and network.log from your Logs folder in here.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
