### ISSUE TITLE
Implement MASHPOOR Judgement

### ISSUE THREAD

**Issue by Agrrox** [Quaver/Quaver#2689]
It would be great if the game had MashPoor judgement, that would prevent players from spamming walls with all keys.

There is no difference in score between player who:

> - presses only corresponding keys to a objects in a measure 
> - player that press all keys at once

Other rhythm games, especially BMS players, like Lunatic Rave 2 (legacy) or [beatoraja](https://github.com/exch-bms2/beatoraja) (modern java bms player) have MashPoors that lower your accuracy when you press keys before empty measure.

Look at these wall patterns:
![gap_walls](https://user-images.githubusercontent.com/10901821/95740337-9504b300-0c8c-11eb-956e-0f827de98e99.png)

**Comment by Agrrox** [comment]
I wonder what other people think about this.

**Comment by LevFlavien** [comment]
I like LR2's engine but it's not very beginner friendly.

Technically speaking, an easier solution would be a bigger miss timing window, etterna like.
