### ISSUE TITLE
Auflösungbug 

### ISSUE THREAD

**Issue by jaaaannnnnnnn** [Quaver/Quaver#2697]
Hi,
Wenn ich das spiel auf mein bildschirm größe anpasse (wqhd) habe ich nur noch ein kleinen bildausschnitt auf den bildschirm, selbst bei Full HD! ich müsst das spiel in 720p Fullscreen oder Im Fenstermodus spielen, Bei allen anderen spielen ist das kein problem. 

**Screenshots**

![20201014182317_1](https://user-images.githubusercontent.com/72880889/96018176-36396800-0e4b-11eb-8bbb-865091ee3503.jpg)
![20201014182331_1](https://user-images.githubusercontent.com/72880889/96018179-36396800-0e4b-11eb-9a1f-11044bc75a5d.jpg)
![20201014182339_1](https://user-images.githubusercontent.com/72880889/96018180-36d1fe80-0e4b-11eb-87f3-70f55ac6d095.jpg)

**Desktop :**
 - OS: Windows

**Comment by IceDynamix** [comment]
translation of issue to englisch:
> adjusting my window to my actual screen size (wqhd) clips the window outside of the screen, i would need to play in windowed mode or in 720p full screen. no one else has that issue.

der grund warum das passiert ist weil deine fensterskalierung in deinen windows einstellungen aus etwas höheres als 100% gesetzt ist. rechtsclick auf dem desktop um schnell an die bildschirmeinstellungen zu kommen und setze es auf 100%. bitte poste deine probleme nächstes mal in englisch damit mehr leute dir im falle helfen können. 

translation for the answer:
set your window scaling to 100%, right click on the desktop to get to the settings quickly. please post your next issues in english.

**Comment by Swan** [comment]
Duplicate of #362
