### ISSUE TITLE
AutoScratch for 7k+1 

### ISSUE THREAD

**Issue by antip0is0n** [Quaver/Quaver#2708]
AutoScratch is a mod that would automatically "play" the scratch lane .The +1 in 7k+1.
![10202020 0-4-56-656](https://user-images.githubusercontent.com/24892545/96519353-1a7bfa80-126d-11eb-95cf-16be0434a1b5.png)
The scratch lane is in the red box.
The scratch lane is a mechanic that can be quite difficult to master .Even when you take away the scratch mechanic the charts are still of quality .It will appear as a mod and will only work on 7k+1
https://www.youtube.com/watch?v=6tgc8re1VwQ
Here is an example video of auto scratch .It should not give combo and hp ,but the keysound if present should be played.

**Comment by Kizuna-dev** [comment]
I support that idea, considering this feature is hugely used in bms i think it would be a nice add-on for supporting people coming from that game, plus it add the ability to enjoy 7+1k as 7k and especially all the converted bms chart

**Comment by LevFlavien** [comment]
BMS players usually have the ability to either display dummy notes like the video shows, or hide the whole lane with a cover.
Being able to apply the 7k skin would be handy.
