### ISSUE TITLE
Tournament Mode Lag?

### ISSUE THREAD

**Issue by CommandoBlack** [Quaver/Quaver#2709]
**Describe the bug**
When playing tournament mode sometimes notes drop (clips at screenshots for instances)

**To Reproduce**
1. Play tournament mode.
2. Be spectated by a referee
3. Unsure of other exact details 

**Expected behavior**
When playing tournament mode some key inputs may not register.

**Screenshots**
Not screenshots. But here's clips
https://clips.twitch.tv/RefinedSneakyWatermelonPastaThat
https://clips.twitch.tv/BlushingSpeedyMouseOMGScoots
https://clips.twitch.tv/BoldGoodLampCopyThis
https://clips.twitch.tv/DreamyTolerantSnailWholeWheat

**Desktop (please complete the following information):**
 - OS: Windows | Build 19041 | 10.0.19041
 - Browser Opera | Why?
 - Version 0.25.0

**Additional context**
Other users reported weird timing windows. Ive also noticed slight differences on how im being judged while playing tournament mode. i.e needing to hit slightly earlier at some spots.

**Comment by Swan** [comment]
Tournament mode only tells the server to save the replay even if it's not a personal best.
