### ISSUE TITLE
SeekTo: "Part Picker" for Practice

### ISSUE THREAD

**Issue by justcfx2u** [Quaver/Quaver#2712]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A new Unranked Modifier which gives the ability to start a map at an arbitrary point in order to practice sections.

**Describe alternatives you've considered**
N/A

**Additional context**
I have a functioning prototype running in a Local Development Build. https://gyazo.com/2a23d1e613b2f98e0789b254507516ff
I'm on the Quaver Discord as "AJ".

**Comment by Swan** [comment]
The editor allows you to do this
