### ISSUE TITLE
Instant pause

### ISSUE THREAD

**Issue by PigNuggets** [Quaver/Quaver#2713]
Just a little thing that could be helpful. Maybe a setting so you can lower how much time you have to hold esc to pause, or a toggle to just make it pause instantly. Ill sometimes be in the middle of a level, and i suddenly get an itch in my eye. Pausing the game takes to long, so usually I'll just wait out the itch, but now its just getting annoying. Thanks!

**Comment by YaLTeR** [comment]
You're looking for:

![image](https://user-images.githubusercontent.com/1794388/97311663-a5648280-1875-11eb-8bcb-5599e7e54126.png)
