### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by KeinNameLP** [Quaver/Quaver#2716]
So I changed the resolution of my game and then the game was so big that I can now only see the upper left corner of the game
now I cant change the settings anymore because its not visible on my screen

https://user-images.githubusercontent.com/73701057/97706929-c7991300-1ab6-11eb-842e-e44ab05886be.png

**Comment by IceDynamix** [comment]
open up the quaver folder and edit `WindowHeight` and `WindowWidth` in the quaver.cfg file to your desired ones

**Comment by KeinNameLP** [comment]
thx
