### ISSUE TITLE
Game won't respond, no explanation.

### ISSUE THREAD

**Issue by jakuuuuub** [Quaver/Quaver#2719]
Quaver does not respond when opened, and it runs at like 0.2 fps. Other Steam games run perfectly. Quaver used to run perfectly at triple-digit fps before. This has been ongoing for about 2 days. Sometimes shows in Steam "running" with nothing in Task Manager sometimes. When it is visible in Task Manager, it won't go over 0.1% CPU. Pressing "stop", does nothing. Deleting game files and reinstalling didn't help. Now the game crashes when I accept Terms and Conditions. What should I do?

Windows 10 Build 19041 x64 (i think)
Version 0.26.2

**Comment by chirijikaiser** [comment]
Hello.

Could you please send your runtime and network log files in here? It would help us solve your problem. Thank you very much.

**Comment by jakuuuuub** [comment]
[network.log](https://github.com/Quaver/Quaver/files/5468649/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/5468650/runtime.log)

**Comment by jakuuuuub** [comment]
[network.log](https://github.com/Quaver/Quaver/files/5468749/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/5468750/runtime.log)
The game crashed at about 3:04 am.
