### ISSUE TITLE
Incorrectly Displayed rank(dont know how it happened)

### ISSUE THREAD

**Issue by WWTGs** [Quaver/Quaver#2727]
I was playing a 7k map and once I completed it, quaver seemed to bug out and think i was 1# in the world so it gave me the 'Approaching The Blue Zenith' Achievement without me actually doing much at all, for reference according to my profile which has the right information displayed i am 1,800th about in 7k and 4k. 

I restarted Quaver and it fixed itself but sadly I don't think there's any way to get rid of that achievement.

![how though 3](https://user-images.githubusercontent.com/73992801/98228525-cbdc9900-1fac-11eb-93de-33c87235872c.PNG)
![how though 2](https://user-images.githubusercontent.com/73992801/98228051-30e3bf00-1fac-11eb-9bf6-40c3a1c72c99.PNG)
![how though](https://user-images.githubusercontent.com/73992801/98228057-3214ec00-1fac-11eb-826b-3e31c77abd11.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 1909 64x
 - Version 0.26.2.0

**Comment by chirijikaiser** [comment]
This is a known bug. Please check previous issues when reporting a found bug next time. Thank you for your cooperation. You may close this issue.
 
See the following links:
https://github.com/Quaver/Quaver/issues/2696
https://github.com/Quaver/Quaver/issues/2635
