### ISSUE TITLE
Stage borders from a custom skin should be disabled in the Editor.

### ISSUE THREAD

**Issue by chirijikaiser** [Quaver/Quaver#2729]
**Describe the bug**
Some custom stage borders from a skin(like Nimbus) are overlapping the Editor. This is also the same issue as this one before: https://github.com/Quaver/Quaver/issues/2356

**To Reproduce**
1. Go to song selection menu
2. Right click on any map of your choice
3. Select 'Edit' in the options.
4. Editor opens, and voila!

**Expected behavior**
It should be just a normal editor where you can just edit maps or create a map.

**Screenshots**
![1192020 14-40-50-616](https://user-images.githubusercontent.com/55966752/98518928-08f5a380-22ab-11eb-9eb6-78ba8f1e1074.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Opera GX
 - Version: LVL 2 (core: 71.0.3770.310)

**Additional context**
The stage borders of a custom skin should not be loaded in the editor or should be disabled.

**Comment by Janko5** [comment]
the best solution is to change the order of the "layers". if editor layer will be  higher than the playfield layer, it wont overlap editor.
