### ISSUE TITLE
Export to osu/malody map

### ISSUE THREAD

**Issue by QiuFeng54321** [Quaver/Quaver#2731]
**Is your feature request related to a problem? Please describe.**
I've created a map from malody and imported it into quaver and edited it further for scroll speed, but now my friends wants to play that map in malody. 

**Describe the solution you'd like**
Maps convertable to malody/osu maps

**Describe alternatives you've considered**
qua2osu and osu2mc on Github, but it doesn't work somehow

**Additional context**

**Comment by Janko5** [comment]
I don't think it will ever be planned for a game. It is not beneficial for the developer to introduce something into the game that would transfer players to another game. If someone will do it for fun, then it will exist but thats all.

**Comment by IceDynamix** [comment]
> qua2osu [...] on Github, but it doesn't work somehow

Try my rewrite [qua3osu](https://github.com/IceDynamix/qua3osu) instead, the conversion is lot better and sturdy. There's no graphical interface right now, so you'll have to use the command line. PM me on Discord if you need any help with that @IceDynamix#7153
