### ISSUE TITLE
Game crashing while downloading 3+ songs

### ISSUE THREAD

**Issue by def750** [Quaver/Quaver#2736]
Hello, I want to report bug.
This happens whe I try to download three or more songs at the same time. Game is not crashing immadently but after about 30-90 seconds.
First it lags a lot. Game is working fine but music is cutting and then it stops for next ~20 seconds. After that game crashes.

**Comment by Razorflamekun** [comment]
This has been the case for me as well.  The easy thing to do with this is to just not download more than three songs at a time.  Depending upon your Internet speeds, it can be very easy to do so.  I do want to point out that this doesn't happen every time I try to download three songs, but it does happen every once in a while, so it might be difficult to reproduce.
