### ISSUE TITLE
Can't upload maps without background

### ISSUE THREAD

**Issue by leikas123** [Quaver/Quaver#274]
Tried to upload a map without background and it said "Error InternalServer", once I added background to the map I was able to upload it.

**Comment by leikas123** [comment]
Apparently the maps got uploaded, but it said "Error"

**Comment by leikas123** [comment]
![image](https://user-images.githubusercontent.com/1362980/50351873-22bd5e80-054c-11e9-9110-36bc0b2b54b7.png)

**Comment by Swan** [comment]
Forwarded to the correct repo
