### ISSUE TITLE
Quaver Crashes When I'm idle 

### ISSUE THREAD

**Issue by Rinka-Sei** [Quaver/Quaver#2741]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by chirijikaiser** [comment]
Please provide your runtime.log and network.log files here. They are located in your Logs folder.

**Comment by Rinka-Sei** [comment]
[network.log](https://github.com/Quaver/Quaver/files/5546205/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/5546206/runtime.log)

**Comment by Rinka-Sei** [comment]
Quaver stopped working again after playing a chart

**Comment by Rinka-Sei** [comment]
[network.log](https://github.com/Quaver/Quaver/files/5546288/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/5546289/runtime.log)
