### ISSUE TITLE
Can't detect osu map when archieved in subfolder

### ISSUE THREAD

**Issue by Uskrai** [Quaver/Quaver#2746]
**Describe the bug**
I am trying to  convert my local osu map with compressing them to zip and changing the name to .osz, but it doesnt work.

**To Reproduce**
1. go to /path/to/map
2. add folder map to archive with .osz extension or zip -r0 "mapname.osz" "mapname/"
3. drag and drop the map
4. go to the quaver song
5. map folder empty

**Expected behavior**
Drag and drop the .osz file, The Game tried to import, no error message after the map is imported and i can't find the map, map directory exist but empty

**Desktop (please complete the following information):**
 - OS: Fedora 33
 - Browser Firefox
 - Version 26

**Additional context**
it does work when i tried to compress the content (without folder) instead of the folder

**Comment by Jolomann** [comment]
Just as a sanity check, are you zipping the song's folder (so it appears as a folder in the archive) or only zipping the contents inside (so you only see the contents and no folder)?

Only the latter would result in a correct archive, which should look like this
![osz](https://bries.s-ul.eu/b8bX4wSC.png)

**Comment by Jolomann** [comment]
woops didn't read additional context, my bad.

"it does work when i tried to compress the content (without folder) instead of the folder"

this is the way .osz files are structured so this issue isn't a bug. you're not following the correct file structure when zipping a folder inside
