### ISSUE TITLE
Revert old LN rendering change regarding negative SVs

### ISSUE THREAD

**Issue by Illuminati-CRAZ** [Quaver/Quaver#2751]
**Is your feature request related to a problem? Please describe.**
The current method of rendering LNs (implemented in #2033) limits the usable SV gimmicks during sections containing LNs. 
It effectively limits the usable positions to those within a LN, as notes before and after the LN start and end positions can become obscured. This rendering change broke Abyss of Frobenoid, as recognized in the PR, and restricts the more "ambitious" sv effects utilizing negative sv (such as [keepstills](https://github.com/Illuminati-CRAZ/KeepStill)) to rice only. "Ambitious" SV LN maps pretty much can't exist right now.

**Describe the solution you'd like**
Revert LN rendering behavior back to using the absolute value of the length of the LN, instead of using the earliest and latest LN position.

**Describe alternatives you've considered**
Use big numbers to break LN rendering. Didn't get desirable results, but did result in this dumb [map](https://quavergame.com/mapset/4037) being made. 

**Additional context**
Reverting _might_ break something, but I'm not aware of any gimmicks that make use of the newer rendering method.

**Comment by YaLTeR** [comment]
The old LN rendering is not correct when SV direction changes in the middle of LN. Imagine the playfield going back and forth within one long held LN, shrinking the distance every cycle. With the old rendering if I'm not mistaken it'll always draw the LN full length even though it doesn't go up to its full length after a back and forth.

I am therefore against this. Gimmicks do not justify introducing bugs to the renderer. A better idea is to somehow allow more intentional control over the playfield or the renderer, e.g. modcharts.

**Comment by Kizuna-dev** [comment]
One solution could be the use of versioning of a .qua file as mentionned by Swan in the previous PR, first it add compability, and second it can allow a user to set his map to an older version in which that rendering update was not present

**Comment by Illuminati-CRAZ** [comment]
I think we have a misunderstanding here.

Take for example an LN that goes forward 200 units, backwards 200 units, and then forwards 100 units.
I believe the LN is currently rendered as 200 units long, and then after the back and forth shows as 100 units long, and then 0.
What I think you are saying is that I want it rendered as an initial 500 units long that constantly decreases to 0. 
What I desire is for the LN to initially be 100 units long, after the back and forth still show as 100 units long, and then 0.

(I hope this makes sense)

**Comment by Illuminati-CRAZ** [comment]
> One solution could be the use of versioning of a .qua file as mentionned by Swan in the previous PR, first it add compability, and second it can allow a user to set his map to an older version in which that rendering update was not present

I think there should definitely be a versioning system implemented, but I'm ambivalent about keeping old maps compatible by allowing them to use old rendering systems. If older rendering systems are allowed, I'm afraid that they would be seen less as old versions and more as "alternative" versions.

**Comment by Swan** [comment]
The goal is to remove bugs, not intentionally add them into the game again.
