### ISSUE TITLE
Can't launch game on os x el capitan 

### ISSUE THREAD

**Issue by xDestx** [Quaver/Quaver#2762]
**Describe the bug**
Can't launch game using steam. Steam says starting game... and steam says I'm in game for a few seconds then turns blue again (not in game) and the game doesn't show up during this time.

**To Reproduce**
1. Install game
2. Click on PLAY
3. Nothing happens except my status changes -> in-game -> no longer in-game

**Expected behavior**
The game to launch :(

**Screenshots**
https://imgur.com/a/lcOMSs6
First image is before clicking launch
Second image is the game "launching"
After failing to launch it looks the same as the first image again

**Desktop (please complete the following information):**
 - OS: OS X El Capitan 10.11.6
 - 10.11.6

**Additional context**
None
I've searched for about 10 minutes for any similar issues but I couldn't find any solution so I decided to make this issue. I found someone with a similar problem on the steam forums here https://steamcommunity.com/app/980610/discussions/0/2977404149642964587/

**Comment by HevyMonkey** [comment]
Hello,
I too can't start up the game (Quaver) on my Macbook Pro running Mac OS X El Capitan (10.11.6).
When launching what appears to be the games executable file in the games local folder I get the following message from the terminal:
<img width="1167" alt="Screenshot+2021-01-12+11 13 20" src="https://user-images.githubusercontent.com/30057094/104380851-efcbd600-552b-11eb-8235-1e5cd2c94b93.png">
By reading the text in the terminal my guess is that the current solution is to update/upgrade your OS to Mac OS X Sierra (10.12.x) which I sadly won't do.

**Comment by xDestx** [comment]
To add to this, after updating the OS I was able to launch the game (now Catalina 10.15.7)
