### ISSUE TITLE
Single player Menu dosen't show up.

### ISSUE THREAD

**Issue by Flucama** [Quaver/Quaver#2769]
This is a one cool game i like it. Single player Menu doesn't up after i did push on: show the map button.  An including that, I guess I could restart game with the hope that it will be back on 100% still i did click on show map, i did go back on main menu and after that back to single player mode, and a thing is that a song list wasn't showing. Still, overall game is cool I enjoy it.

**Comment by chirijikaiser** [comment]
Can you show the screenshots of how you managed to produce this kind of bug?

**Comment by xHorrorxSansx** [comment]
i have the same problem like i even turned off my computer to see if it would come back but the songs didn't. i love this game in general and i hope this can be fixed soon.

**Comment by chirijikaiser** [comment]
> i have the same problem like i even turned off my computer to see if it would come back but the songs didn't. i love this game in general and i hope this can be fixed soon.

Please provide screenshots.

Also, please put your runtime logs in here so we could see what would be the problem.

I think you should also provide what OS do you use, too.

**Comment by Swan** [comment]
Closing due to no response
