### ISSUE TITLE
Add import folder option for other game charts

### ISSUE THREAD

**Issue by xDestx** [Quaver/Quaver#2770]
**Is your feature request related to a problem? Please describe.**
Currently you can import songs from osu! Using import from other games, however StepMania songs all located within specific folders. This means if you want to import all of your SM songs, you have to individually drag each one. This isn't an issue if you had 5-10, but if you have over 1000 it can get quite tedious.

**Describe the solution you'd like**
The normal way to distribute SM packs is by folder, so adding a "import folder" option could be a good addition for players who are migrating from SM (like me). Also, support dragging and dropping a folder onto the game window, just like you would a regular chart.

**Describe alternatives you've considered**
I don't think there are any normal alternatives besides this.

**Additional context**
None!

**Comment by Jolomann** [comment]
Importing packs already works with etterna, so what you could do for the time being is launch etterna once instead of stepmania with your songs and let them import that way

**Comment by xDestx** [comment]
Thanks for the info! I'll do that for the time being. I also wrote something kind of quickly which seems to work here #2771
