### ISSUE TITLE
Add the feature to hide receptors

### ISSUE THREAD

**Issue by Yuuksters** [Quaver/Quaver#2776]
I understand that there are ways to hide them, but I'm not good at skinning. I feel like it would help if you could add some sort of modification to remove them (maybe even give it tiny score boost). Thank you so much!

**Comment by chirijikaiser** [comment]
You can just join the Quaver Discord server and I can help you there regarding skinning.

**Comment by Yuuksters** [comment]
I’m already there! @chirijikaiser

**Comment by Swan** [comment]
Most likely won't be added as a feature, since you can just skin it.
