### ISSUE TITLE
Client crashes when trying to load lots of sound effects(?)

### ISSUE THREAD

**Issue by ghost** [Quaver/Quaver#2783]
Initially I was not going to open this issue but it's become increasingly annoying. Right now, I am working on a converter that will take a BMS folder, and convert it to something that Quaver can use. This obviously means that there will be many sound effects/keysounds. These are assigned to `CustomAudioSamples`. One of the .qua files: [example.txt](https://github.com/Quaver/Quaver/files/5683944/example.txt)

When trying to view this level in the client using Autoplay, before the first sound effect can sound off, the client will crash. Notably, it does not crash on devices which have better specs and can load the sound effects faster. I added the question mark because it might also have to do with one sound effect acting as the background music, which makes it typically 3-4 MB.

This is one of the converted files in which the client on my device will *always* crash before it can play the first sound effect. https://www.mediafire.com/file/u73s5pes3keufzd/Miracle_5ympho_X.qp/file

**Comment by YaLTeR** [comment]
I wonder if it's a different effect of the issue that also causes #1333.

**Comment by vysiondev** [comment]
Just got the issue again, this time I have the error message.

`ERROR: Wobble.Audio.PlayableAudioDisposedException: Cannot create an AudioSampleChannel from a sample that is already disposed.`
