### ISSUE TITLE
Add scrollbar to skin selection

### ISSUE THREAD

**Issue by NeonDrakon** [Quaver/Quaver#2790]
**Is your feature request related to a problem? Please describe.**
In the skin selection when exceeding a certain amount of skins any skins at the bottom of the list becomes unable to be selected.

**Describe the solution you'd like**
A way to scroll in the skin selection.

can't take a especially good screencap of the problem mb

**Comment by Swan** [comment]
You can scroll while your mouse is hovered over the dropdown, but keeping open because it doesn't seem to have a scrollbar.

**Comment by NeonDrakon** [comment]
On my device i seem to only be able to scroll while my cursor is not hovered over the menu window. 
Would describe it as the menu window taking priority as a scrolling action over the skin menu, meaning that to scroll you need to hover outside of the menu window as shown in the recording

https://user-images.githubusercontent.com/76176278/103444656-caf17c00-4c6a-11eb-83c6-0abb3212c1d3.mp4
