### ISSUE TITLE
Screen resolution bug

### ISSUE THREAD

**Issue by darkcatsenpai** [Quaver/Quaver#2791]
I cant access game window if resolution is changed to fullscreen and I cant change the resolution to full HD (1920x1080)

1. Go to the settings page. 
2. Change to fullscreen
3. quit and restart quaver
(if the bug doesnt show up try pressing alt+tab and then pressing it again)

The monitor´s task bar jumps around the screen, then changes back but quaver wont open 

 - OS: Windows 10
 - Browser Opera Gaming gx
 - Version 0.26.2

**Comment by Swan** [comment]
Turn window scaling down to 100% on your PC

**Comment by darkcatsenpai** [comment]
Thanks, it worked.
