### ISSUE TITLE
I can't seem to upload a level I made to the server.

### ISSUE THREAD

**Issue by CassyG** [Quaver/Quaver#2793]
I can't seem to get my level, Reality Check Through the Skull, to upload to the severs. Every time I have tried to upload it I keep getting an error that says this. "One or more of your map files are invalid! (No objects, timing points?)!" I really would like to be able to upload this so I can share it with my friends, anyone know why this is happening? I don't want to have to completely start from scratch as it took me days to make this.

**Comment by Swan** [comment]
Do you have any other .qua files in the folder?
