### ISSUE TITLE
[Maps Download/Metadata] Increase visibility of non-anime content

### ISSUE THREAD

**Issue by Adrriii** [Quaver/Quaver#2794]
**Is your feature request related to a problem? Please describe.**
A majority of the potential playerbase doesn't want to deal with heaps of anime or similar songs. We already have osu! for anime. Quaver has more diversity relatively speaking, but it's not standing out enough. This is a very specific problem so a specific solution could be considered.

**Describe the solution you'd like**

The Download menu is the first appreciation any player will have of the game's content. Since many people will straigth up judge the game for it, they need to be able to remove anime suggestions by some mean. There are ways to go about it, but since the same potential players that will need this feature could correlate with unexperienced players, it would need to be quite obvious.

**1. Filter anime out :**

Maps could be marked as anime, manually and independently of existing metadata. The tag system could be an already implemented solution if correctly enforced but it requires updating the map, meaning all the currently ranked maps (with TONS of anime) would be unaffected.

Then in song search we could just toggle the visibility of anime maps. 
This is the most straightforward and obvious way to solve the issue, but maybe it is too straightforward.

**2. Increase possibilities with genre-wise searching :**

There is a system of the sort in osu!, but it obviously hasn't been successful. Maybe we can do better by making search by genre stand out more. One problem is that we don't have a definitive list of genres as people are free to use any tags to describe it, quoting ranking criteria "Tags must contain the genre of the song", which is enforced but lightly for ranked maps and not at all for unranked maps.

We could aggregate the current tags in ranked and unranked to see which genres are most often used and start to elaborate a genre list mappers could select from a dropdown in the metadata. This does not need to affect the checksum of the maps. Choices can be added as time passes and default to "Other".

Then, it would be possible in song download to filter out or by genres, with "Anime" obviously being on top with alphanumeric sorting ;)
This is a heavier solution, but it could be a small quality of life refactor for the game's contents.

**Describe alternatives you've considered**
Feel free to contribute new ideas or improvements

**Additional context**
Seam reviews

**Comment by Adrriii** [comment]
UI example : 
https://cdn.discordapp.com/attachments/412000948752351252/792418749411622922/unknown.png

**Comment by Adrriii** [comment]
Important to note : Tags could be searchable
https://cdn.discordapp.com/attachments/412000948752351252/792419340082741258/unknown.png

Would just be a filter view so the whole state of the tags would be preserved.

Also, since aggregating all the used tags ever could be too much, we could limit the results API wise to the top k results.

**Comment by Swan** [comment]
This is kinda complicated to do unless it's a manual thing. Going through thousands of sets isn't really feasible either. Not all tags will contain "anime" or something the user would want to filter out.

But adding negative keywords is something we can do.
