### ISSUE TITLE
[Skinning] skin.ini value DrawLongNoteEnd=False visual bug.

### ISSUE THREAD

**Issue by chirijikaiser** [Quaver/Quaver#2795]
**Describe the bug**
This bug usually can be seen with arrow or circle skins that have similar style of receptors. I tested one of my skins and set the DrawLongNoteEnd value to `False` to see if it's working well. Turns out, the note-holdhitobject and note-holdbody elements are not going the way as expected. Setting the value back to `True` just turns it back to normal.

**To Reproduce**
1. Pick any skin of your choice (preferably Arrows or Circles) and open its skin folder.
2. Open the skin.ini
3. Change the value of `DrawLongNoteEnd` from `True` to `False`
4. Save the file.
5. Go back into the game, and refresh the skin.
6. View any maps or use AutoPlay and view the gameplay.

**Expected behavior**
I expected that the hold ends to disappear and the gameplay just to be fine.

**Screenshots**
![12272020 14-49-14-297](https://user-images.githubusercontent.com/55966752/103165943-bc652800-4858-11eb-9eaf-5e615b29cba6.jpg)
![12272020 14-53-58-879](https://user-images.githubusercontent.com/55966752/103165946-c38c3600-4858-11eb-8b92-073c41385b9e.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Opera GX
 - Version: LVL 2 (core: 72.0.3815.459)

**Comment by YaLTeR** [comment]
If you mean lns going past receptors then it's intentional, as in we understand this is bad but couldn't come up with an alternative solution that wouldn't have other issues. There was a more in-depth explanation in another issue but I don't remember which issue it was.

**Comment by YaLTeR** [comment]
This one: https://github.com/Quaver/Quaver/issues/612
