### ISSUE TITLE
Quaver takes forever to start and crashes after logging in

### ISSUE THREAD

**Issue by PyroIsDumb** [Quaver/Quaver#2799]
**Describe the bug**
The game takes about 10 to 20 minutes to start up.
And when i try to log in, Windows prompts that the app isn't responding and after that. it closes down.
I have tried re-installing and opening from local files several times

**To Reproduce**
1. Go to 'Steam -> Quaver'
2. Click on 'Play'
3. Click on 'Login'
4. See error "Quaver is not responding" and crashes

**Expected behavior**
I was expecting for the game to run like normal.

**Screenshots**
I can't take a screenshot, as it captures everything, but the Quaver window

**Desktop (please complete the following information):**
 - OS: Windows 10 Home (x64)
 - Browser: Brave (Chromium based)
 - Version: 1.18.75 on Chromium engine version 87.0.4280.101

**Comment by chirijikaiser** [comment]
Please provide your runtime and network logs in here. They're located in your Logs folder.

**Comment by PyroTheProto** [comment]
[runtime.log](https://github.com/Quaver/Quaver/files/5764992/runtime.log)
[network.log](https://github.com/Quaver/Quaver/files/5764993/network.log)
