### ISSUE TITLE
An issue with a downloaded song

### ISSUE THREAD

**Issue by chep6j** [Quaver/Quaver#2800]
I downloaded a song called "an unwavering jason derulo" and when I went to single player to play it, the game completely crashed. I didn't even have the chance to click the song, as it crashed once the song icon was visible on the single player menu. I know this song is the cause of the crashing because I searched it up and it crashed once the song icon came up.  In summary, I cannot choose this song in the menu for unknown reasons.
Below is a screen recording showcasing the problem:
https://user-images.githubusercontent.com/76893052/103589549-43497e80-4eb1-11eb-8fba-bc333a0fe459.mp4

OS: Microsoft Windows 10 Pro
Browser: Microsoft Edge, Chrome
Version 10
Additional information: I do not know how to replicate this problem because of how other people have played it in the past. I simply downloaded the song, and the game crashed once the icon showed up. Note that I have downloaded other songs after this one, and they have worked fine. I have also tried deleting songs, but that seems to worsen the problem as the song icon is immediately visible once the single player menu is opened.
Please let me know if I missed any guidelines so I can better explain this problem.

**Comment by namazso** [comment]
related / duplicate: #2848 #2852

While neither of these issues reproduced on my machine, I took a look at the mapset's image, and that it's resolution is 4896x3060, so I went and resized mine to 19584x12240 to account for my probably-better gpu. This reproduced symptoms similar to described in these three issues. Frame drops, lags spanning multiple seconds, bugged fonts and other skin elements, generally erratic behavior.

Could you tell the graphics card you were using? Also, could you try if replacing the jpg in the song's directory with a smaller resolution one fixes the problem?
