### ISSUE TITLE
Track issue

### ISSUE THREAD

**Issue by Ben9744** [Quaver/Quaver#2811]
So this isn’t really a bug but basically I made a track but turns out I just made a new difficulty of someone else’s track and now I can’t upload it. Is there a way to convert it to a new track? I’m new to the game.

**Comment by KitsuneDeity** [comment]
Delete the difficulties aren't yours. Go inside your difficulty's .qua file and change the mapset and map IDs to -1 and save (make sure Quaver is closed while this happens). In the editor go to the metadata window and change the creator name to your Quaver username. You should be good to go for uploading after doing all that.

**Comment by Ben9744** [comment]
I deleted all the other maps and did all that but it’s still not working. What do I open the .qua file with?

**Comment by KitsuneDeity** [comment]
You can just open qua files by notepad or anything else like Sublime Text.

**Comment by Ben9744** [comment]
How do I delete all the other difficulties? I did everything u said but it still says it’s not mine.
