### ISSUE TITLE
Scroll Velocity Editor not showing up

### ISSUE THREAD

**Issue by Ben9744** [Quaver/Quaver#2813]
In the editor, whenever I try to open the scroll velocity editor, it doesn’t come up and when I click on tools again it has the check. Does anyone else have this problem? Can anyone help?

**Comment by gabRielfjp** [comment]
I have this bug to and idk how to fix it :/

**Comment by Ben9744** [comment]
> I have this bug to and idk how to fix it :/

**Comment by Ben9744** [comment]
> I have this bug to and idk how to fix it :/

well how I fixed it was before I knew you could just click the check box again to make it go away, I moved it to like the very edge of my screen making it not visible. I remembered I did that and I went to try as click and drag it out and it worked. Maybe you did the same thing
