### ISSUE TITLE
Resolution Bug

### ISSUE THREAD

**Issue by MrGhost7969** [Quaver/Quaver#2828]
**Describe the bug**
Whenever I switch to 1920 x 1080 (my native res) some part of the screen gets cut off.
**To Reproduce**
1. Go to 'Options'
2. Click on 'Resolution'
3. Scroll down to '1920 x 1080'
4. See error-which is what I just described above.

**Expected behavior**
I was expecting the game to fill out my entire screen, but it didn't.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [N/A]

**Additional context**

**Comment by IceDynamix** [comment]
![image](https://user-images.githubusercontent.com/22303902/105651677-cf026980-5eb7-11eb-8eb4-244f30b4116f.png)

**Comment by MrGhost7969** [comment]
Ah I see!  Thanks man!
