### ISSUE TITLE
Mirror changes

### ISSUE THREAD

**Issue by ChristmasBear** [Quaver/Quaver#2829]
**Is your feature request related to a problem? Please describe.**
I personally think that it would be cool if whenever mirror is on, the music would also mirror. 
**Describe the solution you'd like**
For example, the left ear track will be played in the right ear and vice versa.
**Describe alternatives you've considered**

**Additional context**
This is just a concept and does not really do much, but it would be nice to see the detail.

**Comment by Zephyr3755** [comment]
I don't see why dev should implement this, they only modified the game inside with addition (.qua, menu, UI, modifier & rates) but not the original file (.mp3, .png / jpg). Otherwise the game isn't rhythm game anymore, but audio editor instead (the focus will be on .mp3 more than the game)

**Comment by IceDynamix** [comment]
Playing back the mp3 with left and right channels switched isn't really audio editing though

**Comment by lonelylittlelucas** [comment]
Things like what ear the audio are entirely captured into the audio file. To make changes like that would require changing how the audio engine runs almost entirely.

**Comment by IceDynamix** [comment]
I'm nearly certain that this would not require changing anything about the audio engine. It's already possible to extract the data for left/right channels separately (refer to [Waveform](https://github.com/Quaver/Quaver/tree/ui-redesign/Quaver.Shared/Screens/Edit/UI/Playfield/Waveform)) and it's also possible to create a new track from custom track data, so I don't think manipulating them to have high and low bits swapped would be any issue.

**Comment by Zephyr3755** [comment]
I see, my bad. I thought it has something to do with audio engine

**Comment by lonelylittlelucas** [comment]
Waveform is only used to generate the waveform you see in the editor (its possible you looked at #2495 and that it was dealing with the audio playing). Unless they have pan settings built into Wobble, and are dealing with the left and right audio tracks individually ***during*** gameplay, then this change would most likely be too difficult to add for a purely aesthetic reason.

**Comment by Jolomann** [comment]
Audio engine stuff aside..

A lot of maps place notes according to pitch and that's more common than placing notes for left/right panning. I think this feature won't really solve mirror mod feeling "off" outside of edge cases with heavy panning. Not against the idea but I'm questioning how much it'll achieve
