### ISSUE TITLE
Game hasn't been able to open since September on Windows 10.

### ISSUE THREAD

**Issue by jakuuuuub** [Quaver/Quaver#2840]
**Describe the bug**
Game is "running". No window or window opens after 20 minutes, freezes after I click anything. The game never uses more than 0.1% CPU in Task Manager for some reason. I think the problem started after an update but I'm not sure. Other Steam games run perfectly. Stop button in Steam doesn't respond.

**To Reproduce**
1. Click "Play" on Steam.
2. Disappointment.

**Expected behavior**
Opens.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Versions: 0.25.x - 0.27

**Additional context**
I tried to put in a bug report more than once and I was either asked to give them the log files and then didn't get a response back or was never responded back to. I've been playing using a Mac ever since. I've tried reinstalling the game, deleting save files, etc.

**Comment by chirijidev** [comment]
Can you provide your specs? Quaver has issues running on Intel Graphics. I suggest to use NVIDIA Graphics by going in the NVIDIA Control Panel > Manage 3D Settings > Program Settings. Add a program and find Quaver (quaver.exe). This is located in your Steam folder. Steam > steamapps > common > Quaver > `quaver.exe`

After that, select NVIDIA processor as the preferred graphics processor for the program and click Apply.

Finally, try to re-run the game and see if the solution works.

**Comment by jakuuuuub** [comment]
I do have Intel Graphics, and I am running this on a old dual-booted Mac, but it runs perfectly on MacOS. Here's the specs.

Thanks.
![image](https://user-images.githubusercontent.com/72528425/106542909-56f4fe80-64ca-11eb-9e12-f36830569889.png)
