### ISSUE TITLE
Crashes while playing.

### ISSUE THREAD

**Issue by Elxusaki** [Quaver/Quaver#2841]
**Describe the bug**
I try to play but it crashes when I enter to play..

**To Reproduce**
1. Go to 'play'
2. Click on 'single player'
3.  It crashes

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Opera]
 - Version [20H2]

Sorry for my english but i am spanish :c

**Comment by Mempler** [comment]
^ reproducable on my machine. Doesn't occur on Default skin. i used a skin called `Anas`
