### ISSUE TITLE
Donator leaderboards from osu don't always correspond to natively quaver-imported versions

### ISSUE THREAD

**Issue by Emptiest** [Quaver/Quaver#2844]
**Describe the bug**
One of the features of Donator is leaderboards on unranked maps. This functionality seems to break on certain osu!mania maps. Specifically, the behavior is that a given osu!mania map may have a distinct and separate leaderboard from its quaver-imported counterpart. This seems like a bug because there **are** some osu!mania maps that share leaderboards with their quaver-imported versions.

I have noticed that this seems to primarily be an issue on maps with SV, but there may be a different reason for it. Here is one example of a map that displays this behavior: https://osu.ppy.sh/beatmapsets/239943#mania/554655

**To Reproduce**
1. Use Quaver's "Other Games" detection to play a map from osu!mania
2. Import the same map into Quaver and play the imported version
3. Compare leaderboards; they won't always be the same

**Expected behavior**
I think the expected behavior is that the same map, whether imported or detected from osu's library, should share leaderboards.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Any

**Additional context**
Regarding version, I have experienced this behavior since the start of the open beta in July 2020 til now.

I have only so far experienced this issue with osu!mania maps, but it is possible that Etterna converts could experience something similar. I don't play Etterna, so I haven't tested this.

After going through currently open issues, I suspect that the problem I'm reporting here may be related to #1446

**Comment by CelluloidRacer2** [comment]
Admittedly I'm not a Quaver dev, so I apologize I can't fix your issue. I can try and help diagnose the issue and maybe a dev will see this issue down the line.

Does this only occur with Loved maps from osu!mania?

**Comment by Emptiest** [comment]
Not at all. It happens with many maps. I'll link a few more including some not loved.

Cyber Inductance (Speed up Ver.) https://osu.ppy.sh/beatmapsets/827679#mania/1938170
Future Dominators https://osu.ppy.sh/beatmapsets/657648#mania/1393027
#1f1e33 https://osu.ppy.sh/beatmapsets/1184620#mania/2469420
AO-INFINITY https://osu.ppy.sh/beatmapsets/934974#mania/1951921

These span graveyard, loved, and ranked in osu. The status is definitely not what causes this issue.

On the other hand, there are many maps where there are no problems in sharing leaderboards between imported and "Other Games" maps. I do not know the root cause.

Apologies for the delayed response, I didn't expect anyone to actually look at these issues for a while.

**Comment by IceDynamix** [comment]
The leaderboards differ if the computed md5 checksum of maps are different.
Relevant code: [MapsetHelper](https://github.com/Quaver/Quaver/blob/ui-redesign/Quaver.Shared/Database/Maps/MapsetHelper.cs#L30)

**Comment by Emptiest** [comment]
I had a feeling it might be something like that. So I guess for some reason some maps getting imported directly into the game are coming out to a different md5 checksum vs. their "Other Game" counterparts.

As a player I would expect imported maps to have the same leaderboard as a game being played out of an external library however, so there must be an issue with one or the other that is causing a different hash. Personally I only have a loose idea of these concepts and am not a developer myself, so I may just be spouting nonsense.

**Comment by Illuminati-CRAZ** [comment]
It looks like .osu files and .qua files get hashed in slighly different ways.
[Here](https://github.com/Quaver/Quaver/blob/b1369ddc62a5c62b5da7806021da20c081732f3f/Quaver.Shared/Database/Maps/Map.cs#L345) in map.cs it appears that .qua files get hashed using [MapsetHelper](https://github.com/Quaver/Quaver/blob/b1369ddc62a5c62b5da7806021da20c081732f3f/Quaver.Shared/Database/Maps/MapsetHelper.cs#L25-L39), while [here](https://github.com/Quaver/Quaver/blob/b1369ddc62a5c62b5da7806021da20c081732f3f/Quaver.Shared/Database/Maps/Map.cs#L626-L630) it appears that .osu files, after being converted into .qua "files", use [CryptoHelper](https://github.com/Quaver/Quaver.API/blob/b640d94277ca9adc6568b1385bb6fe8b945b38cd/Quaver.API/Helpers/CryptoHelper.cs#L17-L38).
I don't know if these are functionally equivalent or not.

**Comment by Illuminati-CRAZ** [comment]
On a related note, it also appears that any osu convert that's uploaded to quaver won't ever share the same leaderboard as the original .osu file, due to the quaver version having a map and mapset id and the osu version not having them. 

I think it'd be better to hash using only a map's hitobjects, timing points, and svs so that minor difference in metadata (such as tags) don't cause an entirely new leaderboard to be made.

**Comment by Illuminati-CRAZ** [comment]
could be possible for notes in a chord to be in different orders, resulting in different hashes
