### ISSUE TITLE
Quaver cannot detect my osu file

### ISSUE THREAD

**Issue by WinterIsPretty** [Quaver/Quaver#2847]
For some reason nothing can detect my osu file not even osu lazer so what can I do about this or what can be fixed so just quaver can find my osu file

**Comment by chirijidev** [comment]
Go to your settings. Under Miscellaneous tab, click the `Detect Songs From Other Installed Games` and set the `Load Songs From Other Installed Games` into `On`.

**Comment by WinterIsPretty** [comment]
It only loads etterna songs

**Comment by WinterIsPretty** [comment]
I should be seeing 10k+ songs from osu lol

**Comment by chirijidev** [comment]
Okay.

Go to your osu folder. Drag the file name `osu!.db` on the Select Song Screen. That should work.

**Comment by WinterIsPretty** [comment]
Crazy lol and I predicted I had around 10k maps this is gonna take a while

**Comment by WinterIsPretty** [comment]
I should try this with osu lazer

**Comment by chirijidev** [comment]
osu lazer doesn't work the same way btw.

it'll duplicate your files and drain your storage.

**Comment by WinterIsPretty** [comment]
Osu lazer has so many fixed issues than osu stable and I cant even use it because it doesnt find my osu file neither can osu direct
