### ISSUE TITLE
Judgments for notes after other notes have already passed

### ISSUE THREAD

**Issue by Emptiest** [Quaver/Quaver#2854]
**Describe the bug**
Suppose the following scenario: a series of fast jacks in a map. The player misses the first jack but manages to play the other jacks. The expected outcome would be a miss, then normal judgments for the subsequent two hits. Instead, what happens is the following: 2 Okay's and a Miss. I'm unsure precisely of what order these would have happened. This likely could result in major CB rush errors, creating an inflated sense of difficulty on dense and faster maps.
![](https://cdn.discordapp.com/attachments/360308402896896001/810000133818286150/unknown.png)

**To Reproduce**
1. Play a map with fast jacks 
2. Miss one note but continue playing the rest as normal

**Expected behavior**
This is what I would expect to see happen:
![](https://cdn.discordapp.com/attachments/360308402896896001/810002209089257472/unknown.png)

This image was obtained by watching the same replay and going to the same spot in the map, but with judgments set to the 'Extreme' preset instead of 'Standard'. Of additional potential interest, the combo in this screenshot is higher than in the first image because a series of hits earlier in the play was considered a miss on Standard, but judged as lower hits instead on the Extreme preset. To be clear, my use of the 'Extreme' preset here is **NOT** to complain that a harder judgment window removes misses, but merely to help illustrate what the expected behavior should look like.

**Additional context**
I noticed this issue while watching a replay of Crz Arkener's 1.20x play of this map: https://osu.ppy.sh/beatmapsets/855073#mania/1793734

The jacks in question are the set that begin at 3:28 of the song.

I believe the argument could be made that the current behavior is intended to punish players for missing on particularly fast maps, but hits that come **after** note 2 shouldn't count as part of note 1's judgment. That just doesn't make any sense. I'm no expert so I don't know what sort of solution would be the best for this scenario; perhaps flooring judgment windows so if another note in the same column has passed the game gives you a miss? Or perhaps with notes that come in rapid sequence like this, squishing the judgment window so a hit only applies to the judgment for the nearest note. These are just examples; it is not my intent to actually propose a solution.

I'd also like to clarify that while I don't think CB rushes in general are a bad thing to have, CB rushes happening in this fashion seems like a bug.

Just in case the replay gets lost for some reason, I've also attached it here.
[Crz Arkener - Laur - Sound Chimera - Chilly's Phenotype.zip](https://github.com/Quaver/Quaver/files/5976522/Crz.Arkener.-.Laur.-.Sound.Chimera.-.Chilly.s.Phenotype.zip)

**Comment by Illuminati-CRAZ** [comment]
discussion in discord: https://discord.com/channels/354206121386573824/398037301696921600/810242434621636680
