### ISSUE TITLE
Waveform abruptly stops for very long maps

### ISSUE THREAD

**Issue by Illuminati-CRAZ** [Quaver/Quaver#2859]
**Describe the bug**
When loading the waveform of a 30+(?) minute long map, at some point in the song, the waveform will abruptly stop.
The point in time it stops is consistent for a map.

**To Reproduce**
1. Load a very long map (such as [Force Full Album](https://quavergame.com/mapset/323) or [Across the Solar System](https://quavergame.com/mapset/3596)) in the editor
2. Enable waveform and wait for it to load
3. Scroll to some point far into the map
4. See that waveform doesn't exist

**Expected behavior**
For a waveform to be showing at all point in the map where there is audio

**Screenshots**
![2182021 0-48-31-341](https://user-images.githubusercontent.com/42056854/108333572-f500ee00-7185-11eb-8bd1-e56b1c5c68cb.jpg)
![2182021 0-52-47-980](https://user-images.githubusercontent.com/42056854/108333579-f6321b00-7185-11eb-8bb0-c8ed62018b9b.jpg)
![2182021 0-54-25-308](https://user-images.githubusercontent.com/42056854/108333575-f5998480-7185-11eb-91d5-5297658a8242.jpg)

**Additional context**
Mapset | Map Length | Time Waveform Stops | Audio File Bitrate (kbps) | Additional Notes
-------- | ------------- | ------------------------ | --------------------------- | -------------------
[Across the Solar System](https://quavergame.com/mapset/3596) | 59:42 | 9:06 | 112
[Weathering With You Soundtrack](https://quavergame.com/mapset/1037) | 65:07 | 1:58 | 98 | qua file used for testing was different than uploaded, but audio file is the same
[Force Full Album](https://quavergame.com/mapset/323) | 62:52 | 12:21 | 101 | Drater was able to reproduce this
[S3RL Presently Presents](https://quavergame.com/mapset/2156) | 37:47 | N/A | 128 | Doesn't load

**Comment by Emptiest** [comment]
I experienced this issue as well while mapping this song: https://quavergame.com/mapset/4984

Map length is 30:02, audio file bitrate is 192kbps, and the waveform never loads.

**Comment by Illuminati-CRAZ** [comment]
Something's going wrong with Bass.ChannelBytes2Seconds()

Gives 118.05024943310657 seconds for weathering with you.
Gives -2.834467120181406E-06 seconds for s3rl presently presents

**Comment by Illuminati-CRAZ** [comment]
On further investigation it appears Bass.ChannelGetData() doesn't return enough data.

Possibly because of https://github.com/ManagedBass/ManagedBass/blob/43f9d4b363f51e27819b033c66eae7084257581e/src/Bass/Shared/Bass/PInvoke/Channels.cs#L801-L802?

**Comment by Illuminati-CRAZ** [comment]
Skalim found the bug on a short map about a minute in: https://quavergame.com/mapset/4435
