### ISSUE TITLE
After watching a replay with 2x speed on, the song will be set to 2x on my end

### ISSUE THREAD

**Issue by carmlem** [Quaver/Quaver#2872]
**Describe the bug**
If I watch a replay where the player increased the speed, I'll have the speed change applied to my own game without setting it myself

**To Reproduce**
1.) Pick any song
2.) Watch a replay of that song where the player uses a speed mod
3.) After the replay is over, the speed should have changed without you actually adjusting it

**Expected behavior**
I would just expect that my speed would remain at whatever I set it to, like I only play on 1x so I would expect it to remain there after watching a replay.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 86

**Additional context**

**Comment by CelluloidRacer2** [comment]
I think it's a feature as I've always had the speed modifier get updated to match replays
