### ISSUE TITLE
[Feature Request] Ability to Disable the UR Bar from Play Field During Gameplay

### ISSUE THREAD

**Issue by LeonsOnline** [Quaver/Quaver#2877]
**Is your feature request related to a problem? Please describe.**
Quaver has a lot of customization options when it comes to gameplay and skinning, and the option to disable the UR bar from appearing on the play field during gameplay would be a great addition to Quaver's customizable options. I have issues focusing on the gameplay when the UR bar is present and end up choking constantly because I can't stop my eyes from wandering to glancing at the bar. Coming from playing other similar games where it can be disabled to Quaver where it can't is the only thing holding me back from playing Quaver more over other games. 

**Describe the solution you'd like**
There's a few ways this change could be implemented. It could be an asset included with the Gameplay Overlay and be toggled on and off with shift+F6 / the options menu or it could be added as another toggled option under User Interface, preferably the latter.

**Additional context**
If there's already a way to disable this and I'm just blind / it's hidden / manipulable only through skin.ini tinkering please let me know just in case this feature can't / won't be considered. Thank you!

**Comment by Kizuna-dev** [comment]
There is the line "HitErrorPosY" in the skin.ini of your skin, can you put that value to like -1500 if you don't want to see it.

**Comment by chirijidev** [comment]
Yes. It can be configured in skin.ini

The values are `HitErrorPosX` and `HitErrorPosY`. Just set them into like above 1000 and they won't be in your gameplay screen.

Look in the skinning wiki next time. 😊

**Comment by LeonsOnline** [comment]
Thanks y'all! I must've missed it when glancing over the wiki. Though it still wouldn't hurt to have it as an option in the UI menu so that people new to the game who don't know about skinning don't make the same mistake I did by putting in a request / have to scour for information on it with limited knowledge. All good now for me though!
