### ISSUE TITLE
Quaver is not loading on EndeavourOS (Arch Linux based)

### ISSUE THREAD

**Issue by cainy-a** [Quaver/Quaver#2879]
**Describe the bug**
On my linux, quaver does not launch.

**To Reproduce**
1. Install through Steam
2. Hit play
3. It won't launch

**Expected behavior**
The game launches

**Screenshots**
https://user-images.githubusercontent.com/19270622/110224403-3ce87a80-7ed3-11eb-9236-cfd3259b3735.mp4

**Desktop (please complete the following information):**
 - OS: Linux (Endeavour OS / Arch Linux)

**Comment by YaLTeR** [comment]
Please attach `Logs/runtime.log`.

**Comment by cainy-a** [comment]
[runtime.log](https://github.com/Quaver/Quaver/files/6096880/runtime.log)

**Comment by cainy-a** [comment]
wait what it says windows 10?

oh that must have been cause when it didnt work i tried proton

**Comment by YaLTeR** [comment]
Yeah please attach a proper log.

**Comment by cainy-a** [comment]
ok here's a fresh log [runtime.log](https://github.com/Quaver/Quaver/files/6096883/runtime.log)

**Comment by cainy-a** [comment]
ah it looks to be audio

**Comment by YaLTeR** [comment]
Yeah, that's your system misconfiguration. Here's a checklist: https://github.com/Quaver/Quaver/issues/2578#issuecomment-675865182

**Comment by cainy-a** [comment]
hmm ok

**Comment by cainy-a** [comment]
oh i'm using JACK hold on lemme disable that and try again :\

**Comment by cainy-a** [comment]
Yeah it just didn't like JACK.

**Comment by cainy-a** [comment]
Enabling the `ALSA => JACK (plugin)` bridge in cadence works too
