### ISSUE TITLE
Steam Achievement Reach top100 global triggered on top100 country rank.

### ISSUE THREAD

**Issue by Xassie** [Quaver/Quaver#2883]
**Describe the bug**
An achievement "Approaching The Blue Zenith" that requires you to reach top 100 global rank in any game mode was given upon reaching rank #99 in country [7k], while global rank is ~#2.5k.

**Expected behavior**
I mean I don't mind this achievement but I didn't really **earn** it.

**Screenshots**
![image](https://user-images.githubusercontent.com/55048254/110302175-864bdd80-802b-11eb-9836-5d99a4886aef.png)

**Comment by chirijidev** [comment]
It's a known bug. Devs will fix this soon.

Please check if there is/are similar issues regarding the bug you're going to report next time. Thanks for your cooperation, though.
