### ISSUE TITLE
Skins working partially in the Linux version of the game.

### ISSUE THREAD

**Issue by Heeenriqueee** [Quaver/Quaver#2884]
**Describe the bug**
Skins working partially in the Linux version of the game. Only some elements are from the selected skin in the options, and the most part of the elements are from default skin.

**To Reproduce**
1. Press CTRL + O
2. Click on "Skin"
3. Choose any skin other than default.
4. See the feature that is broken.

**Expected behavior**

**Screenshots**
Using skin:
![image](https://user-images.githubusercontent.com/30459284/110307273-7c02f280-7fdd-11eb-925c-a992448d2ed1.png)

Default skin:
![image](https://user-images.githubusercontent.com/30459284/110307385-9b9a1b00-7fdd-11eb-8dbe-8f108dbd8ebd.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux  (Kernel 5.11.1-1-MANJARO)
 - GPU: RX 550
 - CPU: i3-3250

**Additional context**
Edit: The skin https://steamcommunity.com/sharedfiles/filedetails/?id=2211669677
Tried to workaround using the Windows version of the game with Proton but it instantly crashes when clicking play

**Comment by Heeenriqueee** [comment]
workaround to get skins fully working

1. Go to yoursteamfolder/workshop/content/980610
2. Go inside your skin folder
3. Rename "4K" and "7K" to lower case "4k" and "7k"

**Comment by namazso** [comment]
This is a skin problem, the docs have the folder names correctly: https://wiki.quavergame.com/docs/Skins/Keys
The fact that these incorrect skins happen to work on windows is not a Quaver problem imo
