### ISSUE TITLE
Cannot open game on mac

### ISSUE THREAD

**Issue by MajinCanon** [Quaver/Quaver#2889]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by chirijidev** [comment]
Steam servers are currently down. This isn't Quaver's problem. Please be patient for the servers to go up again. Thank you very much.

**Comment by CelluloidRacer2** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Additional context**
> Add any other context about the problem here.

Please fill out this template. It's there because we can't help you if you don't provide any information.

**Comment by chirijidev** [comment]
This issue has been already resolved. Please close it. Thank you very much.
