### ISSUE TITLE
Game doesn't launch

### ISSUE THREAD

**Issue by MightDarkGames** [Quaver/Quaver#2896]
**Describe the bug**
Launching the game provides no window, in steam, it says "Playing" for a few seconds and then changes to "Play", it also doesn't show in the Task Manager.

**To Reproduce**
1. Press "Play" in Steam

**Expected behavior**
Game to launch.

**Desktop (please complete the following information):**
 - Windows 10 Pro
 - Brave
 - 20H2

**Comment by AiAe** [comment]
Please join our Discord server for us to be able to debug it more quickly why it might not start. https://discord.gg/quaver
Use #help channel and post your issue.

**Comment by InspectorIris** [comment]
If you have this issue, try manually setting the graphics processor for the quaver app to something that isn't integrated graphics if possible. Thanks @Jianshyy on the linked discord server.

**Comment by MightDarkGames** [comment]
> If you have this issue, try manually setting the graphics processor for the quaver app to something that isn't integrated graphics if possible. Thanks @Jianshyy on the linked discord server.

How do I do this?

**Comment by InspectorIris** [comment]
windows
settings > system > display > graphics settings > Browse > [game install direcory] > Quaver
to find the install directory 
in steam, right click Quaver > manage > Browse Local Files

**Comment by MightDarkGames** [comment]
> windows
> settings > system > display > graphics settings > Browse > [game install direcory] > Quaver
> to find the install directory
> in steam, right click Quaver > manage > Browse Local Files

It didn't work...
