### ISSUE TITLE
Maybe make a multi delete thing available for songs?

### ISSUE THREAD

**Issue by Loyencer** [Quaver/Quaver#2900]
I have lots of songs and want to delete them but I don't want to spend hours clicking buttons to delete my songs.
Also I'm not sure if there is already a easier way

**Comment by Loyencer** [comment]
Oh oops I think I put this in issues.

**Comment by Illuminati-CRAZ** [comment]
This is the correct place to put this

**Comment by Loyencer** [comment]
Oh alright
