### ISSUE TITLE
Can't connect to the servers

### ISSUE THREAD

**Issue by Kumagia1** [Quaver/Quaver#2903]
**Describe the bug**
I keep disconnecting and reconnecting to the server which won't allow me go to multiplayer and download songs off the game.

**To Reproduce**

Happens every time I launch the game

**Expected behavior**
Every time I launch the game, I connect to the server then it disconnects me then I get reconnected and so on so fourth.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version [quaver 0.27.0]

**Additional context**

I have reinstalled the game, verified the game files, and restarted my router.

**Comment by LuminousLevi** [comment]
I am having the same problem, but im using a Mac, and quaver v0.30.1

**Comment by Stateofreflex** [comment]
I'm also experiencing this problem, I'm on Windows 11 using the newest format of quaver
