### ISSUE TITLE
Linux: Song preview downloads fail - SSL issue?

### ISSUE THREAD

**Issue by saucyfox** [Quaver/Quaver#2912]
**Describe the bug**
Song previews haven't played on the map download screen since my initial install. I didn't realize this was an issue until I saw other users (who I presume were on Windows) stream the game. My ALSA/pulseaudio settings are configured correctly, and I don't have any issues with previewing, playing, or editing downloaded maps.

**To Reproduce**
When I run the Steam release with the command `LD_DEBUG=libs %command% > ~/out 2>&1`, I see this in the log when selecting maps to download:
```
     51263:     /usr/lib/libssl.so.1.1: error: symbol lookup error: undefined symbol: SSL_library_init (fatal)
[7:14:01] - NETWORK - ERROR: Wobble.Audio.AudioEngineException: Cannot call AfterLoad if stream isn't loaded.
   at Wobble.Audio.Tracks.AudioTrack.AfterLoad()
   at Wobble.Audio.Tracks.AudioTrack..ctor(Uri uri, Boolean preview, Boolean autoDispose)
   at Quaver.Shared.Screens.Downloading.DownloadingScreen.<>c__DisplayClass148_0.<<LoadAudioPreview>b__0>d.MoveNext()
```
`SSL_library_init()` isn't provided by either libssl or libcrypto:
```
[user@host lib]$ nm -Dg libssl.so.1.1 libcrypto.so.1.1 | grep SSL_library_init
[user@host lib]$ 
```

...and according to the [OpenSSL Docs](https://wiki.openssl.org/index.php/Library_Initialization), that shouldn't be used with this version (1.1.1). I do also have openssl-1.0 installed on my system, but Quaver expects `libssl.so.1.1`.

I was able to see the same behavior when I cloned the repo and built/ran the game as instructed. Additionally, when I add this debug line to the [AudioTrack()](https://github.com/Quaver/Wobble/blob/5efe6424d64d9def1e5283b096559fc199f69fed/Wobble/Audio/Tracks/AudioTrack.cs#L267) method before AfterLoad() is called:
```csharp
Logging.Logger.Debug($"libbass error: {ManagedBass.Bass.LastError.ToString()}", Logging.LogType.Network);
```
...the error code "SLL" is printed; meaning [SSL support isn't available](https://github.com/ManagedBass/ManagedBass/blob/b38c3cc27bf311c8b3c9e316e0bc6485fbc7cd8b/src/Bass/Shared/Errors.cs#L69).

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Quaver Version: 0.27.1 (Steam release)
 - Kernel Version: 5.11.10

**Additional context**
Another user made a comment about what I suspect is the same issue on #2586, but the issue was already closed before the comment was made.

**Comment by YaLTeR** [comment]
Isn't this a dotnet issue? I don't think Quaver does any direct libssl interaction.

**Comment by saucyfox** [comment]
I'm thinking it might be an issue with the libbass specifically? I don't have any issues actually downloading maps through the client - only song previews.

I just installed [libbass 2.4.15](https://aur.archlinux.org/packages/libbass/)/[libbass_fx 2.4.12.1](https://aur.archlinux.org/packages/libbass_fx/) from the Arch User Repository and deleted libbass*.so from the Quaver project directories, and it's actually loading song previews now. The version you're shipping is 2.4.13.8, and I'm not sure what the implications of a version bump would be (I'm not familiar with libbass or this project at all).

**Comment by YaLTeR** [comment]
Shouldn't be an issue to bump the version Quaver bundles.
