### ISSUE TITLE
Long Notes in Test Play (Editor)

### ISSUE THREAD

**Issue by oxamera** [Quaver/Quaver#2919]
**Describe the bug**
LN Ends are displayed as normal notes until shortly before you hit them in Test Play (Editor)

**To Reproduce**
1. Open a Map in the Editor
2. Scroll up to some LNs
3. Click on Test Play
4. Watch the LN end

**Expected behavior**
The LN displays the same way as in normal play.

**Actual behavior**
The LN is cut off and a normal note is displayed instead of the LN end, then shortly before you hit the note it goes back to normal.

**Screenshots**
Test Play:
![image](https://user-images.githubusercontent.com/68203946/113699078-687aa280-96d5-11eb-9469-0f61fac69078.png)
How it should look like:
![image](https://user-images.githubusercontent.com/68203946/113699110-72040a80-96d5-11eb-8215-51fda64d345f.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Version Latest (0.27.0?)

**Comment by oxamera** [comment]
All Problems were due to integrated graphics, with Nvidia graphics card it works.

**Comment by fuzzbuzzbay999** [comment]
this is also a problem in the 0.28.0 linux release
