### ISSUE TITLE
Option to only import osu! maps with 1.0x rate

### ISSUE THREAD

**Issue by Yokkako** [Quaver/Quaver#2927]
Issue:
Since you have the option to change rates ingame, this would be very convenient. Having to manually delete all audio files / map difficulties of an imported osu! map with rates takes a very long time, and if you don't delete them it can take up a lot of unnecessary space really quickly. (example https://osu.ppy.sh/beatmapsets/480479#mania/1026063 this map has a 1.0x difficulty, but also additionally has 1.1, 1.2, 1.3 and 1.4 which will be imported as well, which costs a lot of space on your drive)

Solution:
Give the option to be able to not import the higher rates of osu! maps by default. (!!!!!Make it possible to toggle this option so you can still merge maps to create marathons!!!!!)
-> possible way to do this might be to make the game search for keywords when importing, or compare the files note positions but idk anything about coding lol

Useful Alternative / Additional Request:
Option to select & delete several difficulties of a map at the same time, including the audio file because as far as I'm aware it stays even when you delete a maps difficulty.

**Comment by IceDynamix** [comment]
There's no way of detecting rate difficulties reliably, not feasible to implement

**Comment by Emptiest** [comment]
While this may be difficult to implement directly, I think that if #2477 is addressed, this issue would be easier to get around as well, since all you would need to do is remove the map files for uprated difficulties prior to import.
