### ISSUE TITLE
Easy way to create marathons in Quaver

### ISSUE THREAD

**Issue by Yokkako** [Quaver/Quaver#2928]
Request:
Would be a cool feature to be able to easily merge maps / have them properly timed to create marathon maps (such as Dan Courses) 

Solution:
Have the option in the editor or similar to choose several maps and their order, time gap between them and possibly rate/mods for the maps.

ⁱᵐ ᵃᵈᵈⁱᶜᵗᵉᵈ ᵗᵒ ᵐᵃʳᵃᵗʰᵒⁿ ᵐᵃᵖˢ ᵖˡᵉᵃˢᵉ ʰᵉˡᵖ

**Comment by Emptiest** [comment]
Not a dev, but from a player perspective I could see playlists being a useful avenue for making this possible.

**Comment by Yokkako** [comment]
youre a genius I didnt think of that yoooo
