### ISSUE TITLE
Doesn't launch on arch linux, as it would seem.

### ISSUE THREAD

**Issue by ghost** [Quaver/Quaver#2930]
**Describe the bug**
Seems like the game does not open, i know for a fact that my system meets the requirements. Running arch linux, not sure if missing libraries or not, but does not seem to run

**To Reproduce**
Launch the game from the stream launcher

**Expected behavior**
*hopefully* launch.

**Screenshots**
![2021-04-17_18-24](https://user-images.githubusercontent.com/17504205/115130153-453fd500-9faa-11eb-85cc-2ae5e2c4ae97.png)

**Desktop (please complete the following information):**
- OS: Arch Linux
 - Browser: Firefox
 - Version: 0.28.0

**Additional context**

**Comment by TheSmallTeaBoi** [comment]
it isn't launching here either, Garuda Linux with Zen kernel too. It used to work while I was using Ubuntu with RT kernel, wonder if the Zen kernel has something to do with it?

**Comment by TheSmallTeaBoi** [comment]
Fixed it!
Turns out Quaver won't launch if you have a ~/.asoundrc file, for some reason.

**Comment by YaLTeR** [comment]
If you have `~/.asoundrc` with invalid configuration probably

**Comment by YaLTeR** [comment]
Anyway follow this checklist to diagnose audio and not launching issues: https://github.com/Quaver/Quaver/issues/2578#issuecomment-675865182

**Comment by TheSmallTeaBoi** [comment]
> If you have ~/.asoundrc with invalid configuration probably

Could you please expand on what "invalid configuration" means? AFAIK mine was working.

**Comment by YaLTeR** [comment]
See that comment I linked

**Comment by GamingInfinite** [comment]
using manjaro, I cannot boot quaver, and I don't have any of those overriding pulseaudio config files (alsa comes preinstalled in the distro btw)

**Comment by LexiSuzuki** [comment]
Can confirm with Manjaro that it wont start. Launching it on terminal seems to show an issue with the IPS server and after setting it to global it looks like it wants to run but just closes with no errors. screenshot of what happens
![Screenshot_20221014_215626](https://user-images.githubusercontent.com/107337101/195963821-527656e7-758d-4ec1-86d0-e010a992497e.png)

**Comment by YaLTeR** [comment]
Try the canary beta branch on Steam, it should fix the ICU issue.

**Comment by LexiSuzuki** [comment]
Alright, I'll give that a try and if the issue continues I'll mention it here

**Comment by WingofaGriffin** [comment]
Confirming Canary fixes issues on my end on Arch.
