### ISSUE TITLE
Quaver won't start

### ISSUE THREAD

**Issue by PawelGamer** [Quaver/Quaver#294]
Quaver won't start on my laptop
In logs I saw this error: RUNTIME - ERROR: System.InvalidOperationException: This image format is not supported ---> Microsoft.Xna.Framework.Graphics.MonoGameGLException: GL.GetError() returned 1281

I'm using Windows 8.1 64bit

**Comment by sinewaveslicer** [comment]
Got the same issue but on Windows 10 Pro, 64 bit. Feel like I should point that out because it might rule out potential OS/driver oddities.

**Comment by doughn0** [comment]
Same issue on my laptop, my guess is the GPU doesn't support the required api version

**Comment by Reyder95** [comment]
Are you using intel integrated graphics? This could be the problem.

**Comment by doughn0** [comment]
yeah intel hd 3000. dx 10.1, ogl 3.1 are supprted

**Comment by sinewaveslicer** [comment]
Same as doughn0 here, intel HD 3000 running off a Thinkpad T420 with a i5-2520M

**Comment by Reyder95** [comment]
Intel integrated gfx have been known to cause issues.

**Comment by PawelGamer** [comment]
I'm using AMD (ATI Mobility Graphics 4200) Graphics Card. My CPU is AMD V120

**Comment by Kuronaaa** [comment]
Same problem on my laptop
I'm using AMD Radeon HD 6520G
