### ISSUE TITLE
Recursive cloning of this repository fails

### ISSUE THREAD

**Issue by Sceptimis** [Quaver/Quaver#2941]
It seems that [this repo](https://github.com/MrHelmut/NVorbis) got deleted. Would probably be best to update MG too.

[gitlog.txt](https://github.com/Quaver/Quaver/files/6363958/gitlog.txt)

**Comment by YaLTeR** [comment]
Should be fixed by https://github.com/Quaver/MonoGame/pull/8

**Comment by YaLTeR** [comment]
Fixed by https://github.com/Quaver/Quaver/pull/2943
