### ISSUE TITLE
Complex Beat Snaps do not copy-paste correctly

### ISSUE THREAD

**Issue by XeZey** [Quaver/Quaver#2944]
**Describe the bug**
When copying complex snapped notes (for example 1/7 or 1/13), notes will not align correctly after pasting.

**To Reproduce**
1. Use a custom snapping (for example 1/13) and create any pattern
2. Copy and paste it

**Expected behavior**
Notes should align correctly with their respective beat snapping

**Screenshots**
![bug](https://user-images.githubusercontent.com/83080509/115890952-cfc67f80-a455-11eb-9e02-5c334be8c62c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version 1.23.71

**Additional context**
The notes seem to snapping to the closest possible standardized snap (1;2;3;4;6;8;12;16)

**Comment by IceDynamix** [comment]
ctrl shift v
