### ISSUE TITLE
Disable Alt+Enter toggle during gameplay

### ISSUE THREAD

**Issue by nebneb0703** [Quaver/Quaver#2945]
### **Is your feature request related to a problem? Please describe.**
Because of my keybinds, I sometimes accidentally hit Alt and NumpadEnter with my pinkies during gameplay. This changes to windowed mode as intended, and moves the window slightly off centre due to the resolution, but it's distracting and I end up failing or missing unnecessarily. 😭 

### **Describe the solution you'd like**
Either this is disabled entirely or maybe add some kind of config option. I'm fine if it remains in a config file rather than the full in game settings since its a minor thing and doesn't need to be modified multiple times. Although I don't think this necessarily needs to be configurable.

**Comment by Grandzam** [comment]
I want to add on to this feature request. I play 7k with a 2 thumbs playstyle where I use both my right arrow key and alt. Right now, to minimize distraction from the volume popup I cover the right side of my monitor when I play. To facilitate use of a wider variety of keybinds, I think there should really be way to change the keybinds of these alt key commands in game play.
