### ISSUE TITLE
Multiplayer UI introduction for newbies

### ISSUE THREAD

**Issue by Lefi121** [Quaver/Quaver#2949]
**Is your feature request related to a problem? Please describe.**
I've noticed more than once that a lot of new people have been receiving some rude treatments because they can't seem to figure out how to download the map and ready-up in your typical multiplayer lobby, I have also seen multiple instances where people seemed confused because nobody is talking to them on the lobby without knowing that a match is currently in progress.

**Describe the solution you'd like**
A simple Highlight or an Introductory screen presented to the player upon entering the lobby for the first time pointing out:

-  The necessary place to look at in order to know if they already have the map or if they need download it, mainly the "Box" on the left side. Even though it already has a highlight of "Click here to download Beatmap" I think most people are quite non-observant and still misses it.

- The button they have to press to let everyone in the lobby know that they are ready which is the "ready up" button, I think this one in combination to the doownloading part has roused the ire of impatient players prompting them to start saying not so nice things to newbies.

- In addition to those 2 I think also pointing out the status of the current lobby (i.e. A match is in progress) could be pointed out as well, or having an addition of a (Playing) status besides the names of the players currently in-game can be an option too! It's true that the lobby list already has this feature but again a lot of newbies just seem to miss this one quite a lot as well.

I think all of these can also be introduced upon entering "Multiplayer" for the first time in the form of "Cards" That people can shuffle around pressing a Next button or just a single image which shows those 3 being highlighted with respective brief explanations or even Highlights whenever they enter a lobby for the first time, but whatever the case I think something along the lines of:

- "This shows the current status of the match, Whether it is currently in progress or if a Host is picking a map." For the room status.

- "This Box shows the current map that is selected, it's information and whether you have the map or not, If you don't you can simply click on the bax and the game will automatically do the work for you!" For the map download/info.

- "This is the Ready Up button, pressing this button will allow the host and other players to know that you are ready to play the map." For the Ready UP button.

A rough illustration:
![szPgUFH](https://user-images.githubusercontent.com/83143826/115984104-eac0fd00-a5d7-11eb-94ad-2919a6c2706c.png)

Hopefully this helps newbies avoid getting rude treatments and keep the impatient or just A-holes in general at bay.

**Comment by QiuFeng54321** [comment]
Also a lot of people are getting confused with difference of usages of the ready button between when they are a host and when they are a normal player. They sometimes ready with their host identity and started the whole game again so I think mentioning this in the ready-up button desc is also important.
