### ISSUE TITLE
Mouse cursor stays visible after pressing retry on a song

### ISSUE THREAD

**Issue by TP-Nibbe** [Quaver/Quaver#295]
**Describe the bug**
When you start a song and then hold escape and press retry. The mouse cursor decides to stay visible, which might be distracting for  many.

**To Reproduce**
1. Pick a random song 
2. Hold down 'ESC' or die 
3. Press 'retry'
4. The mouse cursor stays visible

**Expected behavior**
The mouse cursor should disappear after pressing retry.

**Screenshots**

This was before pressing retry
![beforepressingretry](https://user-images.githubusercontent.com/46053008/50368962-9da76900-058e-11e9-98dd-76138adbfa69.png)
This was after pressing retry
![afterpressingretry](https://user-images.githubusercontent.com/46053008/50368979-e5c68b80-058e-11e9-90de-a98f3aa4bcc3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 
**Additional context**
I have tried on several songs and restarting the game. It still happens.

**Comment by JaanJah** [comment]
Fixed with this PR: https://github.com/Quaver/Quaver/pull/371
