### ISSUE TITLE
A map disappears from the song selection but it still detects the map

### ISSUE THREAD

**Issue by sandrochkhe** [Quaver/Quaver#2952]
![4262021 0-1-44-716](https://user-images.githubusercontent.com/81629763/116007823-a73fb080-a622-11eb-8634-d0a82dc07be3.jpg)
While I was scrolling through the song selection, I noticed that there was a gap in between songs, when I scroll to it by using arrows, it detects the map.

**Comment by Illuminati-CRAZ** [comment]
Gonna close this as #3280 also covers this issue and has more info regarding the bug
