### ISSUE TITLE
incorrect screen scaling

### ISSUE THREAD

**Issue by enderpizzaman** [Quaver/Quaver#2959]
**Describe the bug**
changing the resolution above 1280 x 720 will screw up the screen scaling

**To Reproduce**
1. Go to settings
2. Click on resoltuion
3. Scroll down to 1920 x 1080 and click 
4. See the incorrect scrreen scaling

**Expected behavior**
increase pixel and playat 1920 x [1080](

![Quaver v0 28 0 2_05_2021 12_04_15 AM](https://user-images.githubusercontent.com/83021317/116784886-00ec2300-aada-11eb-980f-8936689d75fb.png)
![Quaver v0 28 0 2_05_2021 12_04_23 AM](https://user-images.githubusercontent.com/83021317/116784888-02b5e680-aada-11eb-8ed4-3862980191a1.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Browser Opera GX
 - Version N/a

**Additional context**

**Comment by AiAe** [comment]
Open the game directory, and find Quaver.exe
Right click and go to properties
Under Compatibility tab click Change high DPI settings
Check the first checkbox "Use this setting to fix scaling problems..."
And Click OK and Apply.

That should solve the issue.
