### ISSUE TITLE
Pressing F1 in song select removes mouse cursor 

### ISSUE THREAD

**Issue by gitithubby** [Quaver/Quaver#296]
**Describe the bug**
When you press F1 to bring up the modifiers menu and close it after you've selected your modifiers, your cursor disappears.

**To Reproduce**
1. Go to Song Select Screen
2. Press F1 to go to modifiers
3. Close out the menu

**Expected behavior**
To see my cursor.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
It might go away if you tab out.

**Comment by Swan** [comment]
Can you share a video of this? This shouldn't happen during song select, however I'm aware of the issue being present when pausing/going to the results screen.
