### ISSUE TITLE
Perfectionist Achievement Unlock

### ISSUE THREAD

**Issue by xrbiay** [Quaver/Quaver#2965]
Multiple issues opened, but I hunted the bug down.

**Describe the bug**
Perfectionist achievement given despite criteria not met for it.

**To Reproduce**
1. Play a song - and hit a few perfect/marvelous hits.
2. After that, do not press any keys - and just let the map miss until you fail.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Version: v0.28.0

**Additional context**
I personally did this on "saradisk - 222- wewewe (Normal 1.55)"

**Comment by Grandzam** [comment]
This worked for me haha
