### ISSUE TITLE
High offset needed with manual adjustments not working, changing maps causes global offset to not work

### ISSUE THREAD

**Issue by MarcusKulik** [Quaver/Quaver#2968]
after running the calibration tool for global audio offset multiple times I kept getting strangely high offsets (-56 to -86ms give or take) this allowed me to play a map I was testing with well, with everything falling on beat.

1. the offset seemed way too high - tested against other rhythm games and in the others I didn't need to touch calibration at all.
2. when picking another map it suddenly felt like the global audio offset that I just calibrated wasn't being applied, after failing the map and selecting fix local offset I was always given a value very close to what the global offset should have been applying (-86ms)
3. manually changing the global audio offset before or after calibration had no affect on gameplay. after playing the map I was testing with the calibrated offset I manually changed the offset to +300ms and the map played just as it had before changing the global audio offset

I tested with 2 keyboards, plugged into rear IO USB, my headphones plugged into my USB preamp and directly into rear IO, restarted the game, uninstalled and reinstalled the game, rebooted pc, nothing made any changes. 

I did notice at the beginning of some maps right as the first bars start to come on there is a little stutter where they stop moving for a few frames, possibly related to this sync issue

**To Reproduce**
for me at least - open game and play any map then fail from the audio being so out of sync with the bars
go to options > audio > global audio offset > calibrate
calibrate global offset
go back to map that was failed and replay
sync issue is gone on that map
pick a new map and play it, then fail from the same sync issue
click fix local offset and have the game give you the same value the global was supposed to be applying. 
repeat for every map

go back to first map that does not have local offset and manually change global audio offset to +300ms and replay, no difference

**Expected behavior**
Reasonable global offset from calibration given hardware (everything wired, adequate PC/ peripheral specs)
global audio offset to apply to every map
manually changing global audio offset to have an effect

**Screenshots**
This was a map played after calibrating the global audio offset and getting -56ms
![image](https://user-images.githubusercontent.com/16007873/116830492-70f0bc80-ab5f-11eb-8c46-2ad2c0af40a4.png)

This is the same map played again right after manually changing the global audio offset to +300ms
![image](https://user-images.githubusercontent.com/16007873/116830504-8960d700-ab5f-11eb-852a-4bfcc20141a2.png)

going to a different map after resetting calibration:
![image](https://user-images.githubusercontent.com/16007873/116830574-1c9a0c80-ab60-11eb-859d-dc40b308966d.png)

![image](https://user-images.githubusercontent.com/16007873/116830583-2459b100-ab60-11eb-90ec-25b13d7f0975.png)

results after playing with local offset applied
![image](https://user-images.githubusercontent.com/16007873/116830770-992ceb00-ab60-11eb-8a43-4e95c96051af.png)

Testing vs osu mania with no adjustment to offset - osu has no sync issues on my system
![image](https://user-images.githubusercontent.com/16007873/116830534-c62cce00-ab5f-11eb-871d-e66bf68fff3b.png)

**Desktop**
 - OS: Windows 10 version 20H2
 - RTX 2080 GPU
 - Ryzen 9 3950x CPU
 - 64GB 3600mhz RAM
 - game installed on nvme ssd
 - 60 hz 4k monitor
 - headphones: AKG K712 Pro  via  focusrite scarlett solo USB preamp
 - KB: 0.01 Z70, razer blackwidow fullsize

**Additional context**
[runtime.log](https://github.com/Quaver/Quaver/files/6412450/runtime.log)
runtime log attached, opened game, reset global calibration to 0ms, ran calibration and accepted recommended value, played first map, manually changed global offset to +300ms, played first map again, played a different map, failed, applied recommended local offset value then replayed that map, passing it.

**Comment by Emptiest** [comment]
Not a dev, but I suspect the hitpos on your skin might not be where you're used to having it. Maybe try adjusting that? No amount of global offset would fix a hitpos issue.

**Comment by MarcusKulik** [comment]
> Not a dev, but I suspect the hitpos on your skin might not be where you're used to having it. Maybe try adjusting that? No amount of global offset would fix a hitpos issue.

I encountered this problem right after I downloaded the game, no custom skins or anything like that. only thing I did was change it to circles instead of rectangles but I had the same problem with rectangles.

**Comment by Adrriii** [comment]
Was fixed on discord, there doesn't seem to be a problem (at least, after running quaver once in administrator)

**Comment by MarcusKulik** [comment]
> Was fixed on discord, there doesn't seem to be a problem (at least, after running quaver once in administrator)

Thank you again for your help

To recap before closing the ticket for anyone that runs into similar issues:

- If offset settings aren't having any affect, restart game as admin and see if that helps
- disable hit sound effects in audio options when calibrating to avoid "speech jamming" when the sound effect plays out of time with your key press (this got me pretty bad)
-the weird stair-stepping in the deviance graph is because my expensive mechanical keyboard had a low polling rate - fixed by switching to a decade old razer gaming keyboard that polls at 1000hz
