### ISSUE TITLE
"None" & Duplicate Keybindings

### ISSUE THREAD

**Issue by alexisgruny** [Quaver/Quaver#297]
Some binding are called NONE .
So if you press another key who is called NONE too you can have like 3 key for 1 binding.

You can bind the same key for all binding so you can have a layout like "AAAA".

**Comment by EliteDreamer** [comment]
Update:
Keys ò,à,ù,è are considered "None" and hitting one of them is considered hitting them all.

**Comment by Adrriii** [comment]
you might want to look at #401, it was marked as duplicate but included some hints
