### ISSUE TITLE
Selecting a skin does not refresh current screen

### ISSUE THREAD

**Issue by Sceptimis** [Quaver/Quaver#2981]
**Describe the bug**
When selecting a skin, the current screen does not refresh/update to reflect the applied skin's changes (textures & configuration)

**Pics**
Before skin applied (with default skin):
![572021 23-52-55-371](https://user-images.githubusercontent.com/6015313/117476070-5a979600-af8f-11eb-9cbf-2fe779a3c3ac.jpg)

After skin applied (with workshop skin "KS_PinkDiamonds + PloxMyuka + BlackPink"):
![572021 23-53-39-82](https://user-images.githubusercontent.com/6015313/117476162-74d17400-af8f-11eb-9e19-e52d74440deb.jpg)

What is to be expected:
![572021 23-54-42-26](https://user-images.githubusercontent.com/6015313/117476588-9cc0d780-af8f-11eb-86ee-929dc9e4f82d.jpg)

**Comment by Sceptimis** [comment]
Selecting a different map seems to update a few elements, but still not all of them
![572021 23-59-10-97](https://user-images.githubusercontent.com/6015313/117477189-4738fa80-af90-11eb-8fad-0b38409d7059.jpg)

This is still without forcing a refresh of the screen (ie. going to main menu and back into select screen)

**Comment by makaiiart** [comment]
Additional comment to say this also includes refresh an already selected skin (Ctrl + S)
