### ISSUE TITLE
Allow users to adjust location/size of UI elements.

### ISSUE THREAD

**Issue by purplepity** [Quaver/Quaver#2984]
**Is your feature request related to a problem? Please describe.**
Sometimes during play I find it difficult to look at various elements of the screen due to their size/positioning.

**Describe the solution you'd like**
In the options, include a button that says "Adjust UI" that allows players to click and drag UI elements (scoreboard, accuracy #, etc.) 
****
**Describe alternatives you've considered**
-  a slider that can adjust the scale of the UI elements
-  a "UI layout" option where players can select from several preset locations for the UI elements

**Additional context**

**Comment by IceDynamix** [comment]
You can already do this with Quaver's skinning functionality. You can refer to the wiki for more information, or join the Discord to ask for more information.

- https://wiki.quavergame.com/docs/skins
- https://wiki.quavergame.com/docs/skins/skin.ini

**Comment by TheSmallTeaBoi** [comment]
I don't think they mean while skinning, but rather etterna-style UI customizing function. This would be a very welcomed improvement imo
