### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by semyon422** [Quaver/Quaver#300]
I got the key, used it to download the game in Steam, launched the game, but could not log in. Also I can not log in on the site.
![20181222145714_1](https://user-images.githubusercontent.com/9976948/50374109-fb24cf80-05f9-11e9-8ed6-d346a47ebf82.jpg)

**Comment by Sublimity** [comment]
Up in the top right it says that your name is Player, did it give you an option on the first startup of the game to choose a username?

**Comment by semyon422** [comment]
> Up in the top right it says that your name is Player, did it give you an option on the first startup of the game to choose a username?

No, I didn't get any option to choose username.

**Comment by Sublimity** [comment]
Weird, on the first run you should be able to choose a username. If you were coming from a dev build and copied your config, that might be a problem. On dev builds, the default name is just Player, which is why I asked. 

Try reinstalling and then verifying the integrity of your game files.

**Comment by semyon422** [comment]
> Try reinstalling and then verifying the integrity of your game files.
I tried to fully remove and reinstall the game, but nothing has changed.

**Comment by semyon422** [comment]
Also I tried to change my username in quaver.cfg manually but I still can not log in.

**Comment by Sublimity** [comment]
Changing your username in **quaver.cfg** does nothing, that's simply for offline play. Quaver works by using the steam-works API to find your steam account's id, which is then used for verifying who you are to the quaver servers, You also get to choose a username for quaver when you first start the game.

Seeming you did not get the option to choose a username, I advise you to contact @Swan on discord, so he can delete your user entry in their user database, then you can reinstall quaver on steam and retry creating a username.

**Comment by Swan** [comment]
Working with him directly on this now. Seems to be an issue with his client not sending the appropriate data necessary to login.

**Comment by YaLTeR** [comment]
@Swan did you solve this?

**Comment by Swan** [comment]
Yes, it's solved.

**Comment by Tigerhunter32** [comment]
I think I may have this same issue considering I verified gamefiles and reinstalled several times and gave up about a month ago but was randomly seeing if there was something new about this and stumbled upon this.. Is there anyway to contact someone to fix this issue?

**Comment by YumeMuzi** [comment]
search and open quaver.cfg, 
AcceptedTermsAndPrivacyPolicy = True
then u will get to `choose a username` panel
