### ISSUE TITLE
quaver crashes randomly

### ISSUE THREAD

**Issue by Gustiviy** [Quaver/Quaver#3000]
**Describe the bug**
quaver just closes randomly. it isnt just for me, my friend has this problem aswell.

**To Reproduce**
none. it just happens

**Expected behavior**
the game to run like normal

**Screenshots**
how am i supposed to screenshot nothing

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser opera gx (shut up)
 - Version latest

**Additional context**

**Comment by AiAe** [comment]
Please provide runtime and network logs after your game crashes. 
You can find Logs folder in game directory.
