### ISSUE TITLE
Keys changing their supposed funcion

### ISSUE THREAD

**Issue by EliteDreamer** [Quaver/Quaver#3002]
Describe bug:
Keys change their supposed function, for now it seems to be limited to the "Enter" key.

1.The bug will start with the game starting up.

The second time i encountered the bug i did this before encountering it.
1.The game process starts.
2.Was on google chrome.
3.Game starts.
4.Alt+Tab to exit out the game tab to get to the chrome tab.
5.While doing so i alt+Z and opened nvidia's "GeForce Experience" and closed it.
6.Realizing i can't get out of loading screen i start spamming "Enter" and as a resoult it become, "swap between Full and Windowed Screen", and that's the bug.

Expected behavior:
The key "Enter" should keep the function it was selected in the game options.

Screenshots:
//

Desktop (please complete the following information):
 - OS: w10
 - Version 19041.928

Additional context:
This may not be a game bug but my keybord bug since it's pretty old and have heard that if you hit too hard a key some keyboards might bug out and changing keys functions.
But since it's the second time happening it may be worth documenting it.
The first time it happend the "Enter" key become or at least had the function of "Esc" key wich was to quit.
The second time as i say in how to reproduce it became "swap between Full and Windowed Screen" of wich i can't seem to find a keybind.
Wanned to record the bug happening but i Alt+Tab and then once again Alt+Tab and Alt+Z but the bug was already gone.For the first time i had to restart the game and went back to normal.

**Comment by Illuminati-CRAZ** [comment]
sounds like the alt input was for some reason being held while enter was being pressed
