### ISSUE TITLE
Changing "BgMaskAlpha"s value has no effect on the opacity of the Stage Bg Mask

### ISSUE THREAD

**Issue by cindsa** [Quaver/Quaver#302]
No matter what value I try the Stage Bg Mask stays pitch black.
If I understood it correctly from reading the wiki changing "BgMaskAlpha"s value in skin.ini supposed to change the opacity of the stage-bgmask.png
I tried values 0.0; 0.5; 1.0 and it didn't have any effect.

**Comment by Swan** [comment]
@cindsa I'm not able to reproduce this. On a fully black bg mask, this is working for me. Could you provide your skin?

![img](https://i.imgur.com/tq8IWQ9.png)

**Comment by cindsa** [comment]
After looking at your screenshot I figured it out, my bad.
I had "f" written after the value like "BgMaskAlpha = 0.2f" because in the default skin it is "BgMaskAlpha = 1f" and I assumed that the "f" is supposed to be at the end. Removing it fixed the problem and it's now working properly.
