### ISSUE TITLE
Mapping using keys

### ISSUE THREAD

**Issue by StockNebula** [Quaver/Quaver#3024]
I would like to be able to map songs using my keyboard. e.g you play the song and use your keys to place down notes where you want them to be. You press your right key and the note pops up where you are in the song.

**Comment by Illuminati-CRAZ** [comment]
There's an option to map with number keys

**Comment by OselotubeSucks** [comment]
where is the option tho

**Comment by IceDynamix** [comment]
![image](https://user-images.githubusercontent.com/22303902/182051902-fb93f4a2-4ff2-4e76-a32c-9755959ca492.png)
