### ISSUE TITLE
The problem that is developing for me is that when I play a song it marks me that I do it wrong and because of that I lose and it happens to me in all the tires even in the easiest ones and at first I thought it was me who had gotten worse but not when I played multiplayer I realized it was a bug, because when I was tired I died and I marked that it made it orrible but when later they showed the results it made me get super good grades, and I love quaver to stop playing it because of this bug. I also thought that it was because of the skin that had a bad imput but it does not happen to me with all skins. I did not have this problem when I started playing, and sorry if something badly written comes to be, I do not speak English and I am writing this with google translate

### ISSUE THREAD

**Issue by Sebas040** [Quaver/Quaver#3029]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Yokkako** [comment]
Kind of hard to understand your english, but the way I understood it I think this might be your issue:

you accidentally enabled the hardest judgement in the "modifiers" window. You can change this by doing what is shown in the following screenshots: 

![5272021 18-44-16-764](https://user-images.githubusercontent.com/76214999/119865216-bb294b80-bf1b-11eb-917e-e39b74487939.jpg)
![5272021 18-45-6-241](https://user-images.githubusercontent.com/76214999/119865223-bd8ba580-bf1b-11eb-9fc7-37850ba82cdc.jpg)

If this was not the issue you are having please let me know by replying

**Comment by Sebas040** [comment]
Thank you very much, problem fixed
I'm sorry that my English has been difficult to understand
<3
