### ISSUE TITLE
Problem to export on Mac

### ISSUE THREAD

**Issue by Xploser1** [Quaver/Quaver#3036]
**Describe the bug**
I can't export a map i have made to someone. When i try to open the song folder, nothing happens and when i use a command, the game just crashes.

**To Reproduce**
1. Go to 'editor'
2. Click on 'file'
3. Scroll down to 'open song folder'

**Expected behavior**
Seing the files, being able to export the map.

**Comment by AiAe** [comment]
What macOS version do you use? Export works under Big Sur it just does not open in Finder. 
Also what command are you using, what for?

Please provide runtime log file after the game crashes, so we can see what the issue is.
