### ISSUE TITLE
Screen going black

### ISSUE THREAD

**Issue by Fliimsy** [Quaver/Quaver#3048]
Anytime I click on a song and try to play it after selecting the difficulty, (doesn't matter which song or difficulty) the screen goes entirely black and crashes after a few minutes.

**Comment by webas3** [comment]
I have reinstalled the game already 4 times for the same reason

**Comment by webas3** [comment]
a temporary solution would be that instead of giving it to play directly, you give it right click to the difficulty you want to play and enter the editor mode and there you press test play
