### ISSUE TITLE
Overall Input/Rank Confliction

### ISSUE THREAD

**Issue by brightbeginner** [Quaver/Quaver#3053]
**Describe the bug**
On The date of June 9, 2021. I brightbeginner noticed something strange such as when I play through a song to its completion, My percentages and response times are very out of whack. This has been ongoing now for at least a couple of months. I recently checked for lots of various Updates and there were no updates to be added. So I uninstalled Quaver off of the steam website and re-downloaded it on steam. Went back into the game, and played a few songs and the same errors arose. it did not give me any error messages. It just hindered my Ranking a lot. 
Thanks for Understanding during these Hard Times, 

Sincerely, 

brightbeginner

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Enn3Developer** [comment]
So the bug is the Quaver is wrongly calculating your score? Are you sure it's not an hardware problem? Maybe if you can clarify a bit it'd be really helpful

**Comment by brightbeginner** [comment]
As far as I know, it is not a hardware issue, but however I recently got a
message but it was a while ago that said that I was not connected to the
server. But it is like my hit position in songs is way above where I had
set my hit position to.

**Comment by Enn3Developer** [comment]
Have you changed your skin recently? If yes, that's the problem. Btw, I don't think that the server problem (can't connect to server) causes this.
Another cause may be the offset, check that, too

**Comment by brightbeginner** [comment]
Thanks for the tip!
