### ISSUE TITLE
Please add 6k support

### ISSUE THREAD

**Issue by citrus3301** [Quaver/Quaver#3058]
6k sm/osu mania maps cannot be played in quaver and I would like to be able to play them

Do not add a 6k leaderboard as that would be dead, but add support for quaver to read and play 6k maps

I cannot think of an alternative, either 6k is added or it is not

Let people map 6k maps in the quaver map editor.

**Comment by fuzzbuzzbay999** [comment]
what about imported 6k maps are played in the 7k player and scores are recorded in the 7k leaderboard

**Comment by citrus3301** [comment]
That's a good idea, im not sure about the leaderboard part though

-------- Original Message --------
