### ISSUE TITLE
[wine] No sound

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#306]
**Describe the bug**
There's no sound.

**To Reproduce**
1. Launch Quaver on wine.

**Expected behavior**
There's sound.

**Desktop (please complete the following information):**
- OS: Arch Linux x64
- wine 4.0 rc2 with a 64-bit prefix with Steam

**Additional context**
I imported maps from osu! so there should be some stuff playing.

Here's a gist with runtime.log, network.log as well as a huge wine logfile with a bunch of sound-related debug options enabled: https://gist.github.com/YaLTeR/dd2096d209e30f479a9b815282b43650 I guess it could help debug the issue (or forward it to wine). To create that log file I ran Quaver with
```
WINEDEBUG=+tid,+seh,+mmdevapi,+winmm,+driver,+msacm,+midi,+dsound,+dsound3d,+xaudio2,+xapofx,+dmusic,+mci,+pulse,+oss,+alsa,+coreaudio,+timestamp
```
, then skipped the intro screen with Enter, tried pausing and unpausing the currently playing track in the top right, and then quit the game.

It's worth noting that there _is_ sound in the Steam overlay (if I play some Steam music through it for example), so it shouldn't be a wine audio misconfiguration issue on my side.

**Comment by Sublimity** [comment]
That sounds like a problem related to Wine itself, and not Quaver.

Even tho Wine has been out for ages, it might not fully support .net core.

**Comment by YaLTeR** [comment]
Yeah, I'd report the bug to wine but the Quaver devs know the underlying audio code and might have an idea of what's wrong (and therefore are able to produce a better bug report), as well as can make and link a debug build for the wine devs.
