### ISSUE TITLE
a suggestion about speed rate change

### ISSUE THREAD

**Issue by foxy1459** [Quaver/Quaver#3068]
Now we can only change the song rate by 0.05, and for some hard beatmaps ,the difficulty will differ a lot even when changing the speed rate by 0.05. So I'm writing to ask if it's possible to add a new button that allows players to change the speed rate by 0.01,which will definitely help us practice more flexibly.

**Comment by Helzspring** [comment]
The problem with that would be the difficulty engine with how it outputs difficulty for ranks.
