### ISSUE TITLE
My combo counter is not being displayed.

### ISSUE THREAD

**Issue by Matt1337Umai** [Quaver/Quaver#3069]
**Describe the bug**
I have not changed any coutner/combo settings in the settings menu although the combo counter is not displaying.

https://user-images.githubusercontent.com/86125928/122602168-09dd8780-d07b-11eb-9b39-5fd70927ff60.mp4

**Desktop**
I am using a MacBook Air. (MacOS)

**Comment by QiuFeng54321** [comment]
When you are playing, press control + fn + shift + F6. It turns on the gameplay overlay.
