### ISSUE TITLE
Discord Status Rank Bug

### ISSUE THREAD

**Issue by blendarr** [Quaver/Quaver#3070]
**Describe the bug**
My normal rank in my country is 351 but when i checked again on discord it was 70, 5 minutes later and it was back at 351
**To Reproduce**
1. Go to Discord
2. Click on Your Profile
3.  See error

**Expected behavior**
Normally it is my normal rank now its 70

**Screenshots**
https://cdn.discordapp.com/attachments/851119284339343440/855567687248642088/unknown.png (idk if this link works)

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser Opera GX
 - Version idk

**Comment by Enn3Developer** [comment]
This may be correlated to the server recalculating everything
