### ISSUE TITLE
Issue with a map i created

### ISSUE THREAD

**Issue by SirWaffles456** [Quaver/Quaver#3071]
**Describe the bug**
Any time the map is interacted with, it causes the game to freeze for up to a minute or longer, and also has apparent issues with downloading, as wen playing with a friend for feedback, he was not able to play the map, despite the game telling him the map was downloaded. Another example of this is in the editor, where every note takes a few seconds to be placed, and the chart updates very slowly.

**To Reproduce**
I have no idea how or why this happens.

**Expected behavior**
I expected it to work smoothly, as the other map in the set.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: v0.29.1
 
 - **Additional context**
One factor may have been me making the chart using the editor from someone else's chart.

**Comment by Enn3Developer** [comment]
Could you send the map here?

**Comment by SirWaffles456** [comment]
> Could you send the map here?

the name of it is atsuover - Unleashed, don't know how to send it otherwise

**Comment by Emptiest** [comment]
Map is here https://quavergame.com/mapset/7878

I checked the qua file and it seems you have somehow created a hitobject at -maxInt on your 4k diff.

To fix, you will need to manually edit the qua file and delete the following lines near the top of the file:

```
- StartTime: -2147483648
  Lane: 2
  KeySounds: []
```

**Comment by SirWaffles456** [comment]
I have found something while seeing if it was eligible for a rank, it says there is a note placed at the negative 32-bit integer limit.

**Comment by SirWaffles456** [comment]
what do i change the lines to?

**Comment by Enn3Developer** [comment]
Delete those lines

**Comment by SirWaffles456** [comment]
ok thanks
