### ISSUE TITLE
Lagging Notes and screen tearing on linux

### ISSUE THREAD

**Issue by AndrewDuffyJr** [Quaver/Quaver#3073]
**Describe the bug**
Notes will lag/jitter as they fall down even at high fps.  The game also has very bad screen tearing even with vsync on.

The game menu and mouse cursor run fine at 144hz it is only the in game notes that run at a low fps.  The notes will run fine for the first few seconds but after that lag.  

**Expected behavior**
Notes to fall straight down smoothly. 

**Desktop**
 OS: Pop!_OS 20.10 with GNOME Desktop
 GPU: RX 570
 CPU: R5 2600
1x 144hz monitor
1x 60hz monitor

**Additional context**
Problem occurred after a quaver update last week.

**Comment by YaLTeR** [comment]
What GPU? What packages updated last week?

**Comment by AndrewDuffyJr** [comment]
Rx 570 and i only updated quaver

**Comment by YaLTeR** [comment]
Try running a Wayland session instead of X11, then enabling Prefer Wayland in Quaver and using Wayland VSync frame limiter option.

**Comment by AndrewDuffyJr** [comment]
I ran it in wayland and i still have issues with the frame rate. The screen tearing is gone but wayland vsync locks my fps at 75 which my secondary moitor is clocked at. For some reason the first note of a map runs smoothly at 144 but then after that it lags for the rest of the song.

**Comment by YaLTeR** [comment]
> wayland vsync locks my fps at 75 which my secondary moitor is clocked at

Hmm that shouldn't be happening. If you go to system settings About, what GNOME version is it?

**Comment by AndrewDuffyJr** [comment]
3.38.3

**Comment by YaLTeR** [comment]
Are you sure it's using your rx 570 and not integrated gpu or something?

**Comment by AndrewDuffyJr** [comment]
I am using a r5 2600 which does not have a igpu sorry for not mentioning that.  I also am getting ~900fps in game

**Comment by AndrewDuffyJr** [comment]
the game menu runs at 144 hz its just the notes that lag

**Comment by ottersarecool** [comment]
I have the same problem, I have a 60hz monitor and the notes are very laggy.

Having a RX 590 running KDE, tried to disable compositor but no luck
