### ISSUE TITLE
Game is capped at 20fps and its impossible to play

### ISSUE THREAD

**Issue by Lazoooo** [Quaver/Quaver#3074]
So my game is capped at 20fps and I've tried to tamper with some settings to try and fix it and nothing has worked. I'm on the steam client of the game and whenever I try to play the game it feels like there's sand in my keyboard and sand on my screen and also sand in my eyes and also I'm buried in sand, please fix this bug.

**Comment by Enn3Developer** [comment]
For the sand, take a shovel and dig it out of your house.
PC specs and what are your display options (in Quaver)?

**Comment by Lazoooo** [comment]
I'm not sure my exact pc specs (I have a prebuilt), but it runs games that are way more advanced than quaver just fine at 60fps, and my display options are in the attached screenshot
![game](https://user-images.githubusercontent.com/86312873/122961088-10595100-d352-11eb-8fab-4a1a144c1c62.jpg)

**Comment by Enn3Developer** [comment]
Click on the list box "Frame Limiter" and choose "Unlimited"

**Comment by Lazoooo** [comment]
I have, it doesnt fix anything.

**Comment by Enn3Developer** [comment]
It's "Limited" in the screen above

**Comment by Lazoooo** [comment]
I just tried changing it to unlimited again, and it did nothing.

**Comment by Enn3Developer** [comment]
If you're on Win, press CTRL+SHIFT+ESC, extend the window (there should be a little arrow in the bottom right corner), go on the Performance tab and send a screen (the fastest way to know your specs)

**Comment by Lazoooo** [comment]
the only problem that I see in the performance is my memory, but I have a pretty large hard drive that I put a lot of stuff on.
![image](https://user-images.githubusercontent.com/86312873/122964996-d5591c80-d355-11eb-88cd-762b92a88bea.png)

**Comment by Enn3Developer** [comment]
Click on CPU and send screen (while we're here, send processes screen as well)

**Comment by Lazoooo** [comment]
![image](https://user-images.githubusercontent.com/86312873/122965677-78aa3180-d356-11eb-838e-d5e2aecdaeaf.png)
![image](https://user-images.githubusercontent.com/86312873/122965719-8495f380-d356-11eb-92e1-d78b017f192c.png)

**Comment by Enn3Developer** [comment]
Try this: reboot PC, when it booted up stop **all** applications and start Quaver
Does the problem still exists?
No: good, next time you want to play make sure to close everything
Yes: strange
