### ISSUE TITLE
Game's polling/input detection is tied to the framerate.

### ISSUE THREAD

**Issue by Bamks** [Quaver/Quaver#3076]
Game detects inputs every frame, leading to lower input detection cycles per second with lower framerates. If your FPS is capped at 60, then your inputs will look as if your keyboard is 60HZ. Why is this bad?
Slower input cycles per second will cause inputs coming into the game to be locked at whatever millisecond value between frames. On songs with BPMs syncing to these values, inputs may come in at set values, leading to the keypress being detected at set intervals, but never in between. In a high accuracy play, the keypress could perfectly at the 100 percent mark, but due to the polling rate, it would be delayed until the next cycle. In this example with 60 FPS, the input could be delayed at much as around 17 milliseconds. This is a significant delay and could lead to many inputs going into the perfect zone, even though they were well into the marv area.

Stemming from this, chords also suffer. A chord hit at the boundary of a polling cycle may have its inputs delayed until the next. At 60FPS, This is a 17 millisecond delay. 

This also means that higher polling rate keyboard will not receive any benefits of high polling. Devices with lower performance, which may not be able to hit 1000FPS, will also suffer from this problem. 

I can reproduce this just by switching to Vsync and seeing the polling lines on the input graph (songs around 220, or 120BPM [or multiples of these] seem to produce the clearest polling lines).

**Comment by Enn3Developer** [comment]
As I know they should already be separated (you get the fps counter along with the input per second counter).
So, this is what the game should do: create a thread exclusively for input and clock it at the max possible. It sends at every his clock all the input at the game thread. The game thread is clocked at what it can render and reads all the input that got buffered when it was doing his calculations.
As you can see, it doesn't matter what you do, if the game does 60 fps this is the maximum inputs per second that it can read
