### ISSUE TITLE
Editor hitsound offset

### ISSUE THREAD

**Issue by huoyan1231** [Quaver/Quaver#3077]
Audio offset does not take effect for hitsound in Editor
my audio offset : 60

**Comment by Jolomann** [comment]
This is intended so you don't end up syncing the song to your specific offset rather than offset 0. The hitsounds will sound off on 0 offset so use the waveform to time instead

**Comment by huoyan1231** [comment]
> This is intended so you don't end up syncing the song to your specific offset rather than offset 0. The hitsounds will sound off on 0 offset so use the waveform to time instead


How can I solve this problem?
Now the editor sound effects are chaotic
