### ISSUE TITLE
Pressing Keys and dont work.Some times dont work the keys and get only miss, im new on this game

### ISSUE THREAD

**Issue by PaltonGames** [Quaver/Quaver#3078]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Enn3Developer** [comment]
First of all, please when opening a new issue compile the form that GitHub presents you.
What do you mean? You press some keys and they don't work? Are you sure you're pressing the right keys?
