### ISSUE TITLE
Dance With Intensity Simfile Won't Load (.dwi)

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [Quaver/Quaver#3081]
**Describe the bug**
When i tried to convert dance with intensity charts it didn't work. In fact, it didn't show anything!

**To Reproduce**
Try Loading Maps Which Only Contains .dwi Simfile

**Expected behavior**
Loading Maps With Only Contains .dwi Simfile Converts To Quaver

**Desktop (please complete the following information):**
 - OS: Windows Embedded 8.1 Industry Pro
 - Browser: Chrome
 - Version: 91.0.4472.114

**Comment by Enn3Developer** [comment]
The only supported games should be osu and etterna
