### ISSUE TITLE
Conversion of a pack from .osz files

### ISSUE THREAD

**Issue by EliteDreamer** [Quaver/Quaver#309]
When .osk files are dragged on the game the converter will only  convert part of the pack.

1. Go to https://osu.ppy.sh/beatmapsets/891164#mania/1862876 and download the pack;
2. Drag on the client;
3. Go into the songs folder (since no map will appear becouse of the name bug);
4. There will be bgs and songs of every map but only the .qua of the first map.

Expected behavior:
Every map should appear in the folder.

Desktop:
 - OS: windows 10;
 - Version from the repo but never updated since yesterday/2 days ago.

Additional context:
Had to modify some code (probably did it inefficently) to be able to have a lane cover (osu style):
-In "GameplayPlayfieldKeys.cs" line 77:
-- from "return WindowManager.Height - (skin.ReceptorPosOffsetY + LaneSize * skin.NoteReceptorsUp[0].Height / skin.NoteReceptorsUp[0].Width)" to "return WindowManager.Height - LaneSize - skin.HitPosOffsetY";
-In "GameplayPlayfieldKeysStage,cs" line 268:
-- from " Position = new ScalableVector2(posX, ReceptorPositionY)" to " Position = new ScalableVector2(posX, Skin.ReceptorPosOffsetY)";
It's not a suitable modification since it's a bit buggy when modifyng the two variables (dunno why) and shouldn't be a problem since i converted https://osu.ppy.sh/beatmapsets/891157#mania/1862841 with this modification.

UPDATE: 
New part of the bug found:

On converting this osz https://osu.ppy.sh/beatmapsets/536309#mania/1135861 the only file inside the folder is the difficulty "IX" no bgs nor songs nor the "X" difficulty.
On converting this osz https://osu.ppy.sh/beatmapsets/590852#mania/1390933 there will be no bgs only the song and difficulty "XI" no song nor map of "XII" difficulty

UPDATE 2:
This pack [ELPIS LN I](https://www.dropbox.com/s/7qxhxh1myt11giy/Various%20Artists%20-%20ELPIS%20LN%20I.osz?dl=0) doesn't even get coverted, no folder is created.
I think the pack is gliched on osu website https://osu.ppy.sh/beatmapsets/758327#mania/1595151

**Comment by EliteDreamer** [comment]
Also if noone reported (i think someone did tho) some maps (for now i could be bothered just to check lns) are "speed up" especially more dense ones (not sure tho).To play them properly you have to decrease your scroll, if needed i'll open another bug issue with all the maps in wihch i found this bug.

**Comment by EliteDreamer** [comment]
Updated

**Comment by EliteDreamer** [comment]
Updated

**Comment by Swan** [comment]
Works on the latest develop branch.
