### ISSUE TITLE
make 8 keys in 4K

### ISSUE THREAD

**Issue by OwUGa** [Quaver/Quaver#3090]
hey
i want to add a suggestion that could help some players like me
allow 8 keys on 4K
where basicaly lets say for ppl like me that use WASD they can use arrow keys to make there hands less tired

**Comment by Crafty-The-Fox** [comment]
1. this isnt standard in any other game
2. you could use AHK to double bind i guess
3. just use spread layout

**Comment by IceDynamix** [comment]
yeah just use spread layout
