### ISSUE TITLE
Editor Freezes when manipulating notes.

### ISSUE THREAD

**Issue by ApolloBirb** [Quaver/Quaver#3093]
Any attempt to place, move, extend (long notes) or delete notes will cause the editor to freeze for 1-2 seconds

1. Go to Editor, any song or map
2. Click on Add notes, click anywhere on the editor map
3. See error

Something may be pulling unnecessary resources from the computer. changing the settings such as the measure increment 1/4, 1/6, 1/8, changing playback speed or any other setting has no effect, only placing or modifying notes causes a game freeze

 - OS: Win 10 Home - Ver. 20H2 - OS Build 19042.928 - Windows Feature Experience Pack 120.2212.551.0
 - Browser Chrome Version 91.0.4472.114 (Official Build) (64-bit)
 - Version v0.29.2

Thanks,
Z

**Comment by Emptiest** [comment]
Do you experience this with every map or just with specific map(s)?

**Comment by ApolloBirb** [comment]
> Do you experience this with every map or just with specific map(s)?

it seems to be one specific map, there are no other maps associated with the song, do you think it can be an issue with the audio or cache?

also, this song is by no means the longest in my library.

QUA File
https://www.dropbox.com/s/0axmwblso3xrtb9/DM%20Dokuro%20-%20Universal%20Collapse%20%5B%5D%20-%201624851049000.qua?dl=0

**Comment by Emptiest** [comment]
Not sure how you did it, but you have a hitobject at -maxInt. Open your qua file with a text editor and delete the following lines:
```
- StartTime: -2147483648
  Lane: 2
  KeySounds: []
```

I've seen this happen a few times but still not really sure how people do it.

**Comment by ApolloBirb** [comment]
i wish, i grabbed it off the browser. seems like the wiki needs a section on things like this, it also causes havoc on all other systems of the game.
