### ISSUE TITLE
Make individual sound effects turn on and off

### ISSUE THREAD

**Issue by NatJanzn** [Quaver/Quaver#3097]
I want to hear the tap of each key, but in harder maps, i keep hearing a water droplet sound effect or something of that nature, and it is starting ti get irratating.

I'd like if you could have each sound effect have its own sound bar to slide so you can decide how loud each sound effect is.

Another alternative is you just have each sound effect have an on and off bar to turn on and off.

**Comment by IceDynamix** [comment]
You can use skinning to adjust specific sound effects or even replace, please feel free to ask on the Quaver Discord in the #skinning channel if you need help
