### ISSUE TITLE
sound problem

### ISSUE THREAD

**Issue by prcups** [Quaver/Quaver#3098]
I use Arch Linux with linux-lqx kernel. The game doesn't make sound although the volume indicator shows that the ALSA PLUG-IN has outputs.
Entering the game is OK but sounds, but when I start to play, the notes hang on the top and no sound is made,too.

**Comment by YaLTeR** [comment]
Hello,

![image](https://user-images.githubusercontent.com/1794388/124141791-5e78fd80-da92-11eb-8c99-242c361d76b5.png)

**Comment by YaLTeR** [comment]
Did it work?

**Comment by prcups** [comment]
> Did it work?

Sure. I found Cadence made a .soundrc to my home dir automately. I changed the alsa loopback settings and the problem solved.
