### ISSUE TITLE
Black Screen When I Play

### ISSUE THREAD

**Issue by ImNotTemplate** [Quaver/Quaver#3106]
**Describe the bug**
Ok so, when i try and play my song in the edit or the single player it becomes a black screen.
Or it's because it's not submited.

**To Reproduce**
1. Go to 'Single Player'
2. Click on 'A random song'
3. Click on 'Edit'
4. Click 'Test Play'
5. Then there is a black screen

**Expected behavior**
I expected just to test the song.

**Screenshots**
this will actually be a video sorry :c ( https://www.youtube.com/watch?v=lnstS4YKbg8 ).

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Google]
 - Version [29]

Contant me on Email

Hdibenga2009@gmail.com

**Comment by maxwellzhang2011** [comment]
then error is still not fixed even 5 years have passed

**Comment by AiAe** [comment]
> then error is still not fixed even 5 years have passed

And where are the logs, how do you expect us to help you.
