### ISSUE TITLE
Implement ColumnSpacing in skin.ini

### ISSUE THREAD

**Issue by vcbiwjs13** [Quaver/Quaver#311]
I propose to add an additional option to the skin.ini which would be the ColumnSpacing which would allow a desired gap between the different columns, it would allow an additional option of customization of skin for the players.

I think this option especially affects people playing with a large skin

**Comment by Swan** [comment]
`NotePadding` might be what you're looking for.

Reopen the issue if it isn't.

[Wiki](https://quavergame.com/wiki/Skins/Skin.ini)
