### ISSUE TITLE
Lag when game open for a long time

### ISSUE THREAD

**Issue by zachhill7714** [Quaver/Quaver#3111]
Very weirdly specific bug. Whenever the game is open for 1hr+, I start getting lag spikes everytime I hit a chord of 2 notes or more, and inputs stop registering. This doesn't happen in other rhythm games such as Osu!, so I know my keyboard is not an issue. The lag gets worse the longer the game is open for, and around 2 hours in jumptrills/quads become impossible to hit.

To reproduce:
Don't know if it'll work for everyone, but:
1. Have the game open for 1-2 hours
2. Play any map

Desktop:
 - OS: Win 10
 - Browser: Google Chrome
 - Quaver Version: 0.29.2

Video:
Made a short map to test out the lag. To confirm, there are no SV changes in it.
https://youtu.be/BCvBNOtfSpU

**Comment by Helzspring** [comment]
If you're alt + tab often, or have apps such as Discord open, this can cause lag spikes. Simple reboot will fix this problem.

Please make sure your program is set for full screen move, as well have "enable high process priority" turned on.
