### ISSUE TITLE
Country Issue

### ISSUE THREAD

**Issue by JoazkY** [Quaver/Quaver#3114]
I created an account on quaver 4 days ago and the country hasn't appeared yet

Since when i created my account on quaver the country hasn't appeared, it only shows a question mark, i've already entered the settings and others places but can't find anything to solve this problem, my country is brazil btw and the account on quaver is "JoazkY is Happy"

**Comment by IceDynamix** [comment]
please visit the quaver discord and open up a ticket in #create-a-ticket

https://discord.gg/quaver
