### ISSUE TITLE
Songs not playing

### ISSUE THREAD

**Issue by Zomg15** [Quaver/Quaver#3117]
**Describe the bug**
None of the songs are playing in-game or in the menus, even if volume is turned up. 

**Expected behavior**
Songs play during gameplay or in the menus.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91

**Additional context**
Sound effects are working normally. The MP3 files for the songs also work fine.

**Comment by Helzspring** [comment]
This can be a problem with your computer, make sure the program isn't choosing any other audio output while running.

you can double check and change the output [here](https://winaero.com/audio-output-device-apps-individually-windows-10/)

**Comment by Zomg15** [comment]
I tried manually setting the output for the game, but the problem still persists.

Also, when I try to calibrate offset, the game shows a mostly black screen, with UI elements barely visible.

![image](https://user-images.githubusercontent.com/43176997/126162266-367679e8-6121-474f-ab7c-dceedeb7c5a8.png)
