### ISSUE TITLE
Black Screen when I try to test play my song

### ISSUE THREAD

**Issue by Corn645** [Quaver/Quaver#3119]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
The screen goes black when I try to test play my song. I use quaver from steam. Version v0.29.2

**Comment by Krayfighter** [comment]
I have this exact problem and additionally whenever I try to play a song I have mapped.

when test playing {
1. drag song into quaver
2. edit song arbitrarily (it does not matter what you enter into the song)
3. click test play
4. screen goes black
}
expected screen to lighten revealing the song I had created

when playing the map in solo play {
1. drag song into quaver
2. edit song arbitrarily (it does not matter what you enter into the song)
3. click file->save
4. click file->exit
5. enter solo play
6. click song on any difficulty
7. screen goes black
}
expected screen to lighten revealing the song I had created

OS: Pop!_OS 20.04 LTS x86_64 
Host: HP EliteBook 840 G2 A3009D51030 
Kernel: 5.11.0-7620-generic 
Shell: bash 5.0.17 
Resolution: 1366x768 
DE: GNOME 
WM: Mutter 
CPU: Intel i5-5300U (4) @ 2.900GHz 
GPU: Intel HD Graphics 5500 
Memory: 7800MiB

I use quaver from steam. Version v0.29.2

in after.png nothing is visible IRL and the faint background only appears in the screenshot
![before](https://user-images.githubusercontent.com/60051238/125872826-7866e18c-3b4b-498e-a57c-4d9b364d9770.png)
![after](https://user-images.githubusercontent.com/60051238/125872828-d2d80dc2-41a5-4006-970f-5ffb6e06a17c.png)

**Comment by Krayfighter** [comment]
edit: the background is again invisible when posted to Github. I have no idea why.
