### ISSUE TITLE
Delayed Crash After Trying to Convert a Score

### ISSUE THREAD

**Issue by TheFinalDawn** [Quaver/Quaver#3125]
**Describe the bug**
Upon attempting to convert any saved score (can either be a saved score or one just achieved), Quaver will crash after ~2-3 seconds, regardless of further input.

**To Reproduce**
1. Open Quaver
2. Open a Saved Score or Play Any Song (completion irrelevant, just get the end screen to appear)
3. Click "Convert Score". Nothing happens
4. Wait a few seconds, feel free to touch anything you want

**Expected behavior**
I expected to bring up the timing presets list.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OS Version: 10.0.19042
 - Version: 0.29.2

**Additional context**
Was only tested with scores from Milky's Improbable Outset Normal map and a custom Friction map, but should work with any map/replay.

**Comment by AiAe** [comment]
Cannot replicate + no runtime logs provided
