### ISSUE TITLE
I try to open Quaver and it doesnt start

### ISSUE THREAD

**Issue by Theswearhole** [Quaver/Quaver#3136]
**Describe the bug**
I try to launch Quaver and it doesnt feel like starting i guess
It sais that im playing it on my profile and my friends can see it, but then after about 8 seconds it sais that i am no longer playing it
**To Reproduce**
1. Go to Steam Library
2. Click on Quaver
3. Click on Play

**Expected behavior**
Quaver launches properly so that i can play Quaver

**Screenshots**
runtime.log
![image](https://user-images.githubusercontent.com/87924864/126890114-86971c4b-87ae-4653-9bfc-6d26d6963dc0.png)
network.log
![image](https://user-images.githubusercontent.com/87924864/126890124-ccb7b352-0fd1-4626-b54f-f748b1807304.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10.0.19042
 - Browser: Google Chrome
 - Version [e.g. 22] no clue

**Additional context**
It has been working since the day that i started playing it July 12 but today it doesnt start for some reason, i did nothing different other than pulling out at putting back the HDMI cable for my screen, in case this has anything to do with it.

I have also verified the game files multiple times and it found nothing wrong.

I have also tried starting it in the canary beta thing to see if it would work and it didnt start there either, logs are the same other than the timestamps.

---VERY IMPORTANT---
I made it work now, it seems that my audio program called voicemeeter banana is causing problems with Quaver. So closing it then starting Quaver makes it work, its just that if i start Voicemeeter again music stops playing.
Allthough going into my windows settings advanced audio settings "app volume device preferences" and changing Quavers output to my voicemeeter banana, then closing and opening Quaver made it work with it.

This is very weird because it has been working fine with Voicemeeter untill today, it seems that me pulling out and putting the HDMI back into my screen must have done something with my audio settings because i heard Quaver through my screen when i had Voicemeeter closed

**Comment by obj-graphite** [comment]
thx bro for posting the solution, I had virtually the same issue😂
