### ISSUE TITLE
Softlock in Multiplayer if Opponent Leaves Mid-Match

### ISSUE THREAD

**Issue by TheFinalDawn** [Quaver/Quaver#3140]
**Describe the bug**
If you play a 1v1 against someone and they close the game in the middle of the match, the game softlocks upon finishing the song.

**To Reproduce**
1. Play a 1v1 match with someone
2. Have them alt+f4 out of the game before they finish the song
3. Finish the song on your end
4. Watch as they cannot rejoin, and you are now softlocked.

**Expected behavior**
It really should either pretend the player has finished, or close the match entirely when this happens.

**Screenshots**
![image](https://user-images.githubusercontent.com/45810243/126916855-a6abff6a-cd4f-4556-997f-d9a6e494f257.png)
I had this screen for over 10 minutes, nothing happened. So I closed the game.

**Desktop (please complete the following information):**
 - OS: Windows 10, Latest
 - Quaver Version: Latest (as of 7/25/2021)

**Additional context**
I triggered this with a friend who alt+f4'd in the middle of the match, but I was playing on 2x speed for a meme so I finished soon after they quit.
Also, I played Improbable Outset but got the image for M.I.L.F, the song I played last round. Friend was host previous round, I was host this round.

**Comment by Swan** [comment]
Fixed server side.
