### ISSUE TITLE
Settings dropdown scroll doesn't cancel scrolling through settings

### ISSUE THREAD

**Issue by makaiiart** [Quaver/Quaver#3163]
**Describe the bug**
Scrolling through a dropdown, like a long list of installed skins, scrolls away from the setting closing the dropdown. 

Only workaround is holding cursor on the bottom of the dropdown, or on the part of the dropdown extending beyond the settings window. 

This is very user un-friendly.

**To Reproduce**
- Install a lot of skins.
- Try and scroll through them, with your cursor inside the dropdown, but not at the bottom.

**Expected behavior**
Scrolling with cursor inside the dropdown would be an isolated action and not affect the settings window.

**Screenshots**
![xx1WSiQBLK](https://user-images.githubusercontent.com/53101675/128737877-87e20183-95ff-4ff6-bcb8-d4f3694fc7ba.gif)

**Desktop (please complete the following information):**
- Windows 10 Pro 21H1 19043.1110
- Quaver 0.29.4

**Additional context**
None

**Comment by Sadkawt** [comment]
Also adding a slider bar like the one featured in the screen resolution drop down would be nice and make things more consistent. 
![Skärmbild 2021-08-10 100929](https://user-images.githubusercontent.com/48724395/128831869-8ddcce0c-4779-4f38-9981-30dfef0f6a0b.png)
