### ISSUE TITLE
Disconnects during multiplayer match shouldn't drop you into the main menu

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#3203]
**Describe the bug**

I'm sometimes getting disconnects in multiplayer during a match (e.g. 1006), which exits me to the main menu.

**To Reproduce**

1. Play in multiplayer
2. Get disconnected

**Expected behavior**

I continue playing because it's likely that I reconnect in a few seconds. If I don't reconnect by the end of the map then with a timeout it can exit me to the main menu.

**Comment by QiuFeng54321** [comment]
I believe this issue should be reopened, as this is not fixed and does bring a lot of inconvenience to players. Random disconnections happen often on me when playing multiplayer, and continued to trigger me every time. The multiplayer plays should really behave like in singleplayer on disconnection, which:
+ does not quit the player from playing whatsoever
+ displays the results (except force quitting)
+ tries to submit results regardless of any internet issues

Optionally, the game should try to rejoin the room upon disconnection, but I believe it is also acceptable to place players out of the room and not rejoin them, as long as they get their scores submitted.

**Comment by Swan** [comment]
I will open it back up. It is a very difficult task because of how much state the server has and the changes on the client that would need to happen, but it is doable.

**Comment by Swan** [comment]
I added a fix to this in #3859. It won't boot you to the main menu anymore when you disconnect, but you won't be able to reconnect to the game automatically (it's just way too complex with too many variables). At least this way, you'll still be able to submit your score.
