### ISSUE TITLE
Deletion of maps < or > than difficulty X

### ISSUE THREAD

**Issue by daehworra** [Quaver/Quaver#3223]
**Is your feature request related to a problem? Please describe.**
Lower difficulty maps really start clogging the map list and it's really annoying to have to manually delete every single map that's too easy to have fun with. I don't want to delete the entire mapset because the higher difficulties are fun to play, so I have to go by every low-rating version and open the menu, click delete, click confirm, and then repeat that 50 times.

**Describe the solution you'd like**
A simple option to remove all maps below or above a specified difficulty.

**Describe alternatives you've considered**
It could be done like osu! where you can search for difficulties, and then remove all maps from the search results.
Something like a "lock" function would also be nice, where those "locked" maps aren't affected by the removal.

**Comment by makaiiart** [comment]
Been wanting this as well, personally believe the osu-like search result method is most versatile, and therefore most useful. Especially with all the search tags Quaver already offers.

I think "locking" maps from deleting would be cumbersome.

I'd propose instead that just map author matching with logged in user are ignored from deletion, unless done manually one by one. WIP maps gone from batch deletion sucks. For other maps you can simply re-download.

**Comment by 1111-glitch** [comment]
Hate to necro but was this implemented? I can't seem to find a way to bulk delete charts.

**Comment by Warp9000** [comment]
> As far as I know, nothing related to this was ever implemented since 2021. What you could do though if you know a bit of SQL and really want to get rid of your maps is manually deleting them from your quaver.db file with a simple query which would look something like
> `DELETE FROM map WHERE Difficulty10X < 10` (This would delete all maps that have a difficulty lower than 10 on 1.0 speed)
> I'd suggest you to make a backup from your file ASAP if you plan to do that in case anything goes wrong

removing maps from the db wont actually remove them.
if you were to press f5 to reload all maps they would be back.
