### ISSUE TITLE
Scores on leaderboard using old diff calc.

### ISSUE THREAD

**Issue by Sadkawt** [Quaver/Quaver#3224]
**Describe the bug**
Scores on leaderboard use charts rating from old diff calc.

**To Reproduce**
1. download following ranked chart https://quavergame.com/mapset/map/12726
2. On the difficulty "Ron's Insane" you can see that it's impossible to beat the  #"1 score by VanWilder, even when using the same mods as them.

**Expected behavior**
For the score to update and use the new diff calc.

**Screenshots**
https://i.imgur.com/qMIpYKd.jpg <-- you can see that I am using the same rate mod as #1 but the warning that i can not beat it still shows.
https://i.imgur.com/HVDKDjs.jpg <-- when clicking into the score the true rating shows. Does not update on leaderboard however.

**Additional context**
People who have not logged in since the diff calc change will not have their scores updated. Looking at VanWilders top plays you can see that he has scores that are no longer achievable but they still give him rating.

**Comment by AiAe** [comment]
Issue seems to be resolved
