### ISSUE TITLE
Crash upon clicking upload to workshop

### ISSUE THREAD

**Issue by FIshJuiceS** [Quaver/Quaver#3229]
When clicking on 'upload to workshop' under skins in the options menu the game will crash

**To Reproduce**
Go to options > Skins 
Click on `upload to workshop`

**Expected behavior**
The skin should be uploaded to the workshop

**Desktop:**
 – OS: MacOS - 11.2.2 (Apple Silicon)
 – Version 0.29.4 - Steam

**Comment by Swan** [comment]
if this is still happening, open again with logs
