### ISSUE TITLE
Mapset/Difficulty Page Redirection from Profile Doesn't Direct Properly

### ISSUE THREAD

**Issue by BreadDawt** [Quaver/Quaver#323]
**Describe the bug**
Trying to go to the mapset/difficulty page from the profile score doesn't redirect to the right page as it should (example in video).

**To Reproduce**
https://streamable.com/mps7h

**Expected behavior**
The redirection should redirect to the right page.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Opera

**Additional context**
Looking at the URLs, the correct page has the /map/ tag while the redirection just ignores that completely, moving you to a mapset instead with that id. This occurs with sets of multi-difficulties.

**Comment by Swan** [comment]
Thanks. I've forwarded this over to our website repo.
