### ISSUE TITLE
Alt + Enter Fullscreen Toggle Count As Normal Enter Press

### ISSUE THREAD

**Issue by makaiiart** [Quaver/Quaver#3234]
**Describe the bug**
When pressing alt + enter to get out or into fullscreen, it still counts the enter tap so you end up starting a song.
Seems to mainly happen when on non-native resolution, or when spamming it. 
Sometimes this happens: https://github.com/Quaver/Quaver/issues/2083

**To Reproduce**
100% success steps to reproduce the behavior:
1. Set resolution to non-native. (In my case: 1920x1080 on 25601440)
2. Go to Song Select screen
3. Alt + Enter
4. You've now started a map.

Less repeatable version:
1. Set resolution to native (in my case: 2560x1440)
2. Go to Song Select screen
3. Spam Alt+Enter
4. You've now started a map (and sometimes triggered above mentioned bug)

**Expected behavior**
Would only toggle fullscreen and ignore the enter tap.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Windows 10 Pro 10.0.19043 Build 19043
 - Quaver 0.29.x

**Additional context**
Usually done to take smaller area screenshots without the jank of fullscreen or borderless windowed.

**Comment by QiuFeng54321** [comment]
This happens when the sort is on "Difficulty" or when choosing the difficulty for one mapset. When started with this method the long notes will be glitched at the beginning, just like when testplaying it from the editor.
Also when Alt+Enter is pressed inside the mp room it makes you quit the room.
