### ISSUE TITLE
Please add text boxes to scroll speed and offset in settings

### ISSUE THREAD

**Issue by citrus3301** [Quaver/Quaver#3238]
**Is your feature request related to a problem? Please describe.**
Its annoying when i try to change my offset or my scroll speed in menus but the sliders are so weird and never go to the number I want, It would be much easier if there was also an option to add a number manually like you do for custom judgement windows

**Describe the solution you'd like**
A text box to input exact values menually for scroll speed and offset

**Describe alternatives you've considered**
Straight up replacing the slider with the text box
**Additional context**
That's it

**Comment by Illuminati-CRAZ** [comment]
arrow keys can be used to precisely adjust the value while the cursor is hovering over the slider
