### ISSUE TITLE
Combo counter is stuck at 0

### ISSUE THREAD

**Issue by AyaMaruyama** [Quaver/Quaver#3244]
**Describe the bug**
mentioned in the title

**To Reproduce**
play any map

**Expected behavior**
combo should increase as I hit the notes on time

**Screenshots**
quick demo, as you can see the 'max combo' is 0x. it also shows like that in the lb
![image](https://user-images.githubusercontent.com/55572366/134055810-cbacf459-eeca-4f4a-94bc-dfe722878a92.png)
![image](https://user-images.githubusercontent.com/55572366/134056435-2d2f9065-7a32-4505-b94f-46ea167d2702.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: v9.20.2021 [canary]

**Additional context**
swag yeezy foam runners

**Comment by Swan** [comment]
What are your judgement window settings?

**Comment by AyaMaruyama** [comment]
oh nvm i found out it was because of the combo break judgement thing. mb lol
