### ISSUE TITLE
Long break skip feature appears too early when an LN is final note before break

### ISSUE THREAD

**Issue by ph03n1xm** [Quaver/Quaver#3245]
This is a Canary build bug.

When the last note before a long break is an LN, you are able to skip the break before you release the LN, which would automatically score a late Good for the release.

1. Go to any map with an LN before a long break (I uploaded an example map here, in the "bugged long break skip" diff: [Here](https://quavergame.com/mapset/map/59476) )
2. Play the map 
3. When the long LN prior to the break arrives, skip the break before the LN ends
4. The LN is scored as a good

**Expected behavior**
The option to skip should appear after the LN is released.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Canary 9.20.2021

**Comment by ph03n1xm** [comment]
Ewan#4143 found this issue too, and attached this screenshot.
![9202021_21-41-27-109](https://user-images.githubusercontent.com/69484229/134065591-e5fefb19-3e37-4bf0-9c06-4715d69c967b.jpg)

**Comment by Swan** [comment]
Reverting this for now. Requires a lot of changes to get this working properly. It'll come at a later date.
