### ISSUE TITLE
Your mapset contains files of an invalid type

### ISSUE THREAD

**Issue by AstraeaTG** [Quaver/Quaver#3247]
**Describe the bug**
Invalid type of file but I have no clue what file it is, I tried deleting the background image, tried deleting the qp file and I just will not upload. I spent literal hours making this map for it to not work
**To Reproduce**
Steps to reproduce the behavior: Literally just trying to upload a beat map
1. Go to 'editor'
2. Click on 'new map'
3. Spend hours working on a map then it 'doesn't work'

**Expected behavior**
I expect it to just say "Upload Success" or something like that
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Opera GX]

**Additional context**
![9222021 21-52-6-265](https://user-images.githubusercontent.com/91239896/134456302-663a147d-a4cc-4f29-8e5f-8ed4a57492bc.jpg)

**Comment by Swan** [comment]
Something about your mp3 file is off. Use a different one.
