### ISSUE TITLE
on the new canary mods dont show speed like 1.1x or 1.5x only NLN FLN and inverse

### ISSUE THREAD

**Issue by flouncy301nanny** [Quaver/Quaver#3248]
the mods leaderboard dont show the speed only the new ones

**Comment by Swan** [comment]
I don't know what this means. Send a map and/or a screenshot.

**Comment by flouncy301nanny** [comment]
![image](https://user-images.githubusercontent.com/67694435/134525905-d91054f4-3144-4048-9ac0-111737028ddb.png)
this is on 1.05x speed and nln yet it showed my 1.1x nln score

**Comment by flouncy301nanny** [comment]
FUCK WRONG SS

**Comment by flouncy301nanny** [comment]
swan i am so god damn sorry give me a minute

**Comment by flouncy301nanny** [comment]
![image](https://user-images.githubusercontent.com/67694435/134526471-ad2062de-26fb-47ee-8522-5ad03b79f370.png)
ok here this is it

**Comment by Swan** [comment]
The mods leaderboard now only takes into account modifiers that change the actual map (Mirror, NLN, FLN, INV) regardless of the rate. It is working as intended.

**Comment by flouncy301nanny** [comment]
> The mods leaderboard now only takes into account modifiers that change the actual map (Mirror, NLN, FLN, INV) regardless of the rate. It is working as intended.

alright thx
