### ISSUE TITLE
add an option to choose a skin for 7k and a different for 4k 

### ISSUE THREAD

**Issue by flouncy301nanny** [Quaver/Quaver#3249]
literally the most annoying shit is playing a 4k only skin and go to play some 7k with it and get accuracy fucked

**Comment by Swan** [comment]
Theres a 4K and a 7K folder in your skin for a reason.

**Comment by YaLTeR** [comment]
This would actually be pretty useful, especially for players who use arrows for 4K and bars for 7K. I'd add it and also get rid of the "skin type" thing while at it (move it to skin.ini)

**Comment by flouncy301nanny** [comment]
> This would actually be pretty useful, especially for players who use arrows for 4K and bars for 7K. I'd add it and also get rid of the "skin type" thing while at it (move it to skin.ini)
yes and especially to the people with low end pcs and laptops (like me) that take time to load skins putting an option for a 4k skin and a diffrent for 7k will help alot

**Comment by Swan** [comment]
You can already use arrows for 4k and bars for 7k. They are separate skins...

**Comment by Swan** [comment]
We provide folders and skin.ini options so that you **can** have different skins per mode. Adding a setting for this is extremely redundant. 

> yes and especially to the people with low end pcs and laptops

You would be loading one skin versus two if you do it with the way that already exists.

**Comment by flouncy301nanny** [comment]
alright sorry
