### ISSUE TITLE
[Canary] "All" leaderboard have donator text overlapping with "global" LB

### ISSUE THREAD

**Issue by Kizuna-dev** [Quaver/Quaver#3250]
When selecting "All" in the leaderboard filter on a ranked map, it show the "you must be a donator to access this leaderboard" text overlapping with the result of the "global" filter.
![9232021 19-4-54-970](https://user-images.githubusercontent.com/68703144/134552658-d861e6a2-62dd-40f6-a686-1a1319fc5fe6.jpg)

**Comment by Swan** [comment]
Fixed
