### ISSUE TITLE
separated 4k and 7k visual offset

### ISSUE THREAD

**Issue by Sadkawt** [Quaver/Quaver#3252]
A request to have two different visual offsets, one for 4k and one for 7k instead of having one for both.

Seeing as scroll speed is already separated by keymode i dont think also making offset key dependant is too far of a fetch, personally my 4k and 7k skin are very different resulting in having to change offset whenever I wanna switch keymode.

**Comment by YaLTeR** [comment]
Does this actually make sense? Visual offset compensates for input and monitor latency, which is not affected by skin or scroll speed.

**Comment by Illuminati-CRAZ** [comment]
Sounds like the hit positions of the skins should be adjusted in the skin.ini

**Comment by Swan** [comment]
Won't add
