### ISSUE TITLE
[Canary] Error trying to quit score display screen

### ISSUE THREAD

**Issue by QiuFeng54321** [Quaver/Quaver#3253]
**Describe the bug**
Runtime error while trying to quit the score display screen from local score.  
[runtime.log](https://github.com/Quaver/Quaver/files/7229008/runtime.log)

**To Reproduce**
1. Go to 'Leaderboards'
2. Click on a score
3. Press escape

https://user-images.githubusercontent.com/32996262/134754217-f93fa43d-0515-4d60-99c5-0f63fd0c65b3.mp4

**Expected behavior**
...not having error?

**Screenshots**
I recorded it.

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser ?
 - Version 0.30 Latest Canary

**Additional context**

**Comment by Swan** [comment]
If you remember what your screen resolution was, could you provide it?

**Comment by QiuFeng54321** [comment]
> If you remember what your screen resolution was, could you provide it?

WindowHeight = 800
WindowWidth = 1280

**Comment by AiAe** [comment]
Tested with same res under macos cannot replicate, will close issue since it might been resolved
