### ISSUE TITLE
Fps drops below 30 when dragging fast with your mouse over the screen

### ISSUE THREAD

**Issue by Boem22** [Quaver/Quaver#3258]
**Describe the bug**
The fps drops from 2000 to below 30 when moving my mouse around quickly

**To Reproduce**
1. Move your mouse quickly around the screen
2. See error

**Expected behavior**
Not the fps to drop significantly

**Desktop (please complete the following information):**
- Brave
- I7 11700 + 3060ti

**Comment by Swan** [comment]
Can't reproduce. Open again with a video + logs. The client will drop to 30 fps when you are tabbed out if you have that setting on.
