### ISSUE TITLE
visual bug - black flashing shapes

### ISSUE THREAD

**Issue by tsuriquaver** [Quaver/Quaver#3259]
**Describe the bug**
Flashing black shapes throughout all menus in the game.

**To Reproduce**
None. It happens randomly (85% of the time) after opening Quaver.

**Expected behavior**
To not have these flashing black shapes while playing because they strain the eyes.

**Video**
Here is a video showing an instance of this bug.
https://youtu.be/yrN69mLQh6U
I can also provide more videos of different menus showing this as well.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version [21H1]

**Additional context**
Processor: Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz 1.19 GHz (if this helps?)

**Comment by Swan** [comment]
Looks like a driver issue rather than an issue with the game itself. Make sure everything is updated, and try again.
