### ISSUE TITLE
Bug with QR values (on imported maps from other games with rates)

### ISSUE THREAD

**Issue by PuzzlyPop** [Quaver/Quaver#3266]
**Describe the bug**
It seems that when you play imported maps from other games with rates the submitted PR scores get a little wonky. Im unsure if this is a cache issue as my local plays are listing the PR as the expected values (and the difficulty that the play feels) whereas the online/submitted scores on the website are values that seem way too high. 31-30 PR plays are turning into 40 PR ala Zigby-style. This may just be a cache issue but the submitted values seem very strange to me. See screenshots for examples. 

**To Reproduce**
Pick an easier diff map from osu (in the 10-15 pr range.) 
Uprate to 1.5+. 
Submit the score (need donator for unranked maps)

**Expected behavior**
Your local play value will be the expected pr (31~ range as an example) but the online values will be extremely high (40+)

**Screenshots**

![an1](https://user-images.githubusercontent.com/89084502/135698341-40d9b23d-7f02-4241-9699-06db1846b8b4.jpg)

![an2](https://user-images.githubusercontent.com/89084502/135698376-17d0b829-ddd5-462e-9f67-b632f912bb50.jpg)

Map - https://osu.ppy.sh/beatmapsets/296478#mania/667785

![wat](https://user-images.githubusercontent.com/89084502/135698266-93248161-5674-4ff6-b26e-1f0a022dfdb0.jpg)

![wat2](https://user-images.githubusercontent.com/89084502/135698274-68f0511f-410c-4ad9-91d9-a20fcfc4ab65.jpg)

 Map - https://osu.ppy.sh/beatmapsets/429664#mania/927048
 
Play feels much closer to a difficult 32 pr like a standard uprate than nearly 41

![huh](https://user-images.githubusercontent.com/89084502/135698430-e49c42d6-8182-4725-b28f-f54884a1cf77.jpg)

![huh2](https://user-images.githubusercontent.com/89084502/135698434-6e53cf25-7eef-4ae0-ae75-2e988176d1a2.jpg)

Map - https://osu.ppy.sh/beatmapsets/557428#mania/1179492

**Desktop (please complete the following information):**
 - OS: Windows 10 

**Additional context**
Im really unsure if this is just a cache issue; but the values seem very off to me. It also seems applicable to just about any imported osu map. However, if I uprate Quaver maps; the values you get are about what you'd expect.

**Comment by Swan** [comment]
This is due to the copy of the map on the server being different than the one locally, and it's using that to calculate the rating. Already tracking this issue elsewhere
