### ISSUE TITLE
Client freeze during playback, replicates in replay

### ISSUE THREAD

**Issue by PuddyUK** [Quaver/Quaver#3272]
- **Overview of the Issue** - My game client froze for ~20 seconds during playback, causing the song to fail after an abnormal amount of time. It's viewable in the replay attached.
- **Reproduce the Error** - not sure if it's reproducable, but I'll include the replay in this report. 
- **Related Issues** - I've had crashes and freezes before, yes, but not with the same outcome.
- **Suggest a Fix** - N/A.

[Puddy - THE ORAL CIGARETTES - WARWARWAR - Eternity.zip](https://github.com/Quaver/Quaver/files/7316121/Puddy.-.THE.ORAL.CIGARETTES.-.WARWARWAR.-.Eternity.zip)

**Comment by PuddyUK** [comment]
I just tried playing the replay again and it no longer freezes for me either. 

If there's any more info I can provide that might help track down the issue I'd be happy to provide it. 

I've checked my logs in steamapps\common\Quaver\Logs but there's nothing indicating any issues.

**Comment by Swan** [comment]
Cannot replicate either, so we can't really do much with this report. If this is still happening, open the issue again with a video, logs, and your PC specs
