### ISSUE TITLE
one or more files do not have completed media data

### ISSUE THREAD

**Issue by JediGoldenpig** [Quaver/Quaver#3273]
When I try to upload my map it says "one or more files do not have completed media data" and I don't know what to do. 

Expected behavior
The successfully upload the map to the sever.

![image](https://user-images.githubusercontent.com/92202519/136672259-257c93a6-5ae4-441f-b3d4-604ea5bce974.png)

Desktop
 - Windows 10

**Comment by Illuminati-CRAZ** [comment]
Press F1 in the editor and fill in the fields
