### ISSUE TITLE
Discord Screen Share Audio Doesn't Work on Mac

### ISSUE THREAD

**Issue by budchopsticks** [Quaver/Quaver#3275]
**Describe the bug**
When screen sharing the game on Mac via discord I get no audio on the other side of the stream, even though I know from other people it works just fine on windows.

**To Reproduce**
1. Screen share the game from a Mac computer or OS (Presumably) on Discord
2. Have someone watch the stream
3. They shouldn't be hearing audio

**Expected behavior**
I expected my friends to be able to hear my stream.

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur 11.4
 - Version 30

**Additional context**
I just wanna stream the game to my friends with sound

**Comment by Swan** [comment]
This is out of scope for us. You probably want to ask Discord support for help instead.
