### ISSUE TITLE
Unchangeable zoom into the top left corner

### ISSUE THREAD

**Issue by Krayfighter** [Quaver/Quaver#3278]
unchangeable zoom into the top left corner after using the "prefer Wayland" option

**To Reproduce**
1. Install quaver from steam
2. start quaver
3. enable the "prefer Wayland" option
4. close quaver
5. re-open quaver
6. see the zoomed screen
(the only way to fix is to uninstall quaver, delete all game files and re-install)

**Expected behavior**
normal startup with either window view or maximized view

**Screenshots**

**Desktop (please complete the following information):**
OS: Manjaro Linux x86_64 
Host: Laptop A3 (framework laptop base model DIY edition)
Kernel: 5.13.19-2-MANJARO 
Shell: zsh 5.8 
Resolution: 2256x1504 
DE: GNOME 40.5 
WM: Mutter 
CPU: 11th Gen Intel i5-1135G7 (8) @ 4.200GHz 
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] 

**Additional context**

**Comment by Swan** [comment]
@YaLTeR Can we close?

**Comment by YaLTeR** [comment]
I think we can close this, eventually we'll figure out proper HiDPI and until then there's the 100% scale workaround that exists on any Linux desktop.
