### ISSUE TITLE
quaver has trouble switching revolutions

### ISSUE THREAD

**Issue by RUSSELLAHHHHHH** [Quaver/Quaver#3279]
I play with my laptop docked so I could play on it like a tower, but I have trouble transitioning to my laptop screen, the screen is smaller so the laptop makes the icons bigger text size same ect, but quaver can not swich resolutions it only shows the top right of my smaller screen and not the full thing.

**Comment by Swan** [comment]
Open the issue again with an image/video of what you're seeing
