### ISSUE TITLE
Really thin hitobjects flicker during gameplay

### ISSUE THREAD

**Issue by Illuminati-CRAZ** [Quaver/Quaver#3282]
**Describe the bug**
Hitobjects with heights of like a few pixels flicker during gameplay. When the scroll velocity is 0 some notes visually disappear.

**To Reproduce**
1. Use a skin with very thin hitobjects ([Example skin uploaded as a zip file](https://github.com/Quaver/Quaver/files/7402183/thin.zip))
2. Open gameplay preview of a map
3. Observe notes flickering
4. Pause the music, causing gameplay to pause and notes to stop scrolling
5. Observe that some notes are visually missing

**Expected behavior**
For notes to not flicker in and out of existence.

**Comment by Swan** [comment]
This will happen because you're using a texture with a 1px height... Use a normal skin lol
