### ISSUE TITLE
Editor Function: Time-based Scrolling

### ISSUE THREAD

**Issue by Kubeon4** [Quaver/Quaver#3283]
**Is your feature request related to a problem? Please describe.**
Right now you can pretty easily navigate the map using your scroll wheel, but the issue arises when your map has a high bpm or you are mapping with a high grid count. Scrolling becomes pretty inconvenient in those situations since it only skips to the next grid of the map.

For example, I am mapping RoughSketch - 666, which has a bpm of 666 so I would have to switch my grid to 1/1 to navigate effectively.

**Describe the solution you'd like**
Keep the current scroll method, but create a function that lets you scroll based on seconds or any unit of time that you could activate using a hotkey like Shift + Scroll or other hotkeys.

**Comment by Swan** [comment]
Probably won't add as a feature in the editor because not many songs have this
