### ISSUE TITLE
Notes are constantly flickering

### ISSUE THREAD

**Issue by sugarplushie** [Quaver/Quaver#3287]
**Describe the bug**
Notes are constantly flickering during the game, in any map, with any skins.

**To Reproduce**
1. Play any map
2. There you go

**Expected behavior**
Notes should go down normally.

**Preview**
https://imgur.com/a/Tos8Ay7

**Desktop:**
 - OS: Arch Linux
 - Browser: Brave
 - Version: Latest from Steam, not sure

**Comment by Sceptimis** [comment]
I used to have the same issue here on Arch too, I was never able to pinpoint exactly what was causing the flickering, but I noticed that the longer I kept the game open, the worse it would get.

I suspect that it could be related to PulseAudio's timer-based scheduling implementation, which has been known to cause issues with ALSA drivers, causing some audio latency and glitchiness, which could possibly affect Quaver's scrolling of notes in gameplay which depends on the position of the current track.

Some things to try:
- [Disable tsched/timer-based scheduling](https://wiki.archlinux.org/title/PulseAudio/Troubleshooting#Glitches.2C_skips_or_crackling)
- Try modifying [BASS's device period option](https://www.un4seen.com/doc/#bass/BASS_CONFIG_DEV_PERIOD.html) via the `DevicePeriod` and `DeviceBufferLengthMultiplier` variables in `quaver.cfg` in Quaver's installation directory
    - note: `DeviceBufferLengthMultiplier` is just a multiplier for the value of `DevicePeriod`, not a separate BASS option

Also:
- What desktop environment are you using?
- What GPU/driver?
- Do these stutters happen instantaneously after starting Quaver, or do they appear after x amount of time playing?

**Comment by ottersarecool** [comment]
I found a solution that worked very good for me, I installed the following packages `pipewire` and `pipewire-pulse` rebooted my computer and the notes were perfectly smooth, I suppose this is a pulseaudio related problem, could you maybe try this out and give me feedback if it worked for you aswell?

**Comment by sugarplushie** [comment]
Thank you! Actually, it fixed itself after a few days (I didn't really do anything, no system updates, no reinstalling, nothing), but either way this will be nice for other people that run into that :D

I just forgot to update the issue when it fixed itself

**Comment by Merlin04** [comment]
also had this issue, found restarting the pipewire service fixed it. still unsure what caused it in the first place
