### ISSUE TITLE
Settings restart upon reopening the Game

### ISSUE THREAD

**Issue by TotallyNotSalty** [Quaver/Quaver#3288]
I don't know if this is intentional but it has been happening to me lately, this is my second day playing quaver and this bug keeps happening

To cause this bug, just open the game, change your settings, close the game and reopen it, your settings will go to default

did anyone else had this to happen?

**Comment by beari22** [comment]
I also started playing and **all** my setting get reset after reopening

any help?

**Comment by Swan** [comment]
How are you exiting the game? If you're force closing it probably won't save properly. You should be closing via the x button or through the main menu

**Comment by beari22** [comment]
ok.......
it's somehow fixed 

when I **had** this issue I closed it whit the main menu

idk this might only happen for new players
