### ISSUE TITLE
Steam not letting me open Quaver

### ISSUE THREAD

**Issue by SlippyBananas** [Quaver/Quaver#3289]
Hello, I have a problem with my Quaver, the problem is that it won't load anything just a black screen, I've tried reloading it, reinstalling  it, restarting my computer, etc. And this has never happened to me. So if you guys can help me please feel free to reply on this comment.

Regards, SlippyBananas

![Screen Shot 2021-10-29 at 8 01 29 PM](https://user-images.githubusercontent.com/75511669/139514716-2bd09ca8-3df6-49ab-b76a-0714f43121bc.png)

**Comment by Swan** [comment]
Re-open the issue with logs (you can find this in the logs folder)

**Comment by SlippyBananas** [comment]
Sorry I don't know how to reopen it with logs. And I don't know where the logs folder is.

Feel free to contact me in discord SlippyBananas#7862

**Comment by Swan** [comment]
They are located in the `Logs` folder inside the game's directory. There is a `runtime.log` file.
