### ISSUE TITLE
Laggy notes in Linux

### ISSUE THREAD

**Issue by ottersarecool** [Quaver/Quaver#3291]
**Describe the bug**
The notes seem to be lagging though the game runs at stable 60fps with vsync enabled

**To Reproduce**
1. Have Arch Linux (5.14.14-arch1-1) installed with Plasma X11 or Wayland
2. Start Quaver and select any song of your likings
3. See laggy notes that sometimes will be smooth for 2-3 seconds

**Expected behavior**
A buttersmooth experience

**Desktop (please complete the following information):**
OS: Arch Linux x86_64 
Kernel: 5.14.14-arch1-1
DE: Plasma 5.23.2 
CPU: AMD Ryzen 7 2700 (16) @ 3.800GHz 
GPU: AMD ATI Radeon RX 580
Monitors: 2x 1920x1080@60Hz

**Additional context**
I tried various settings, literally all combinations but it would not work whatsoever, if I start the Wayland session its the exact same behaviour, waylandvsync does nothing and if I turn off vsync completely the game is completely out of sync and unplayable, also tried a completely different computer with different hardware, it's all the same, this problem is specific to quaver, osu!lazer does not have this issue

**Comment by YaLTeR** [comment]
Could you check if this issue is similar and if the response helps? https://github.com/Quaver/Quaver/issues/3287#issuecomment-955159320

**Comment by ottersarecool** [comment]
> Could you check if this issue is similar and if the response helps? [#3287 (comment)](https://github.com/Quaver/Quaver/issues/3287#issuecomment-955159320)

This surprisingly fixed it for me! Thank you very much for pointing it out!

What I did to fix it was to modify the quaver.cfg and set the value of `DevicePeriod` to `15` just like the example in the documentation Sceptimis linked stated, works for me now!

**Comment by YaLTeR** [comment]
Fwiw a period of 15 is pretty big and can cause audio latency, you'll probably be fine with a smaller value like 5.

**Comment by ottersarecool** [comment]
> Fwiw a period of 15 is pretty big and can cause audio latency, you'll probably be fine with a smaller value like 5.

I actually found a better solution that lets me keep the value low at around 5, I simply installed `pipewire` and `pipewire-pulse` completely fixed it for me

**Comment by YaLTeR** [comment]
Yeah, pipewire's great, glad it works better for you.
