### ISSUE TITLE
Scale imgui elements of editor depending on resolution

### ISSUE THREAD

**Issue by Illuminati-CRAZ** [Quaver/Quaver#3292]
I can barely read the stuff

![10302021 6-7-25-860](https://user-images.githubusercontent.com/42056854/139534227-f606ed1b-bf0a-41d1-b17a-c6b9d8357c2b.jpg)

**Comment by Swan** [comment]
Not sure if this is possible. Will need to look more into the API

**Comment by Emik03** [comment]
Shouldn't this issue be closed now that this option is in the game?

![image](https://github.com/Quaver/Quaver/assets/14614115/d4242b22-db43-468e-ba22-61cde9e19cde)
