### ISSUE TITLE
Map won't play if a player's game crashes when a game starts

### ISSUE THREAD

**Issue by IGotTheHub** [Quaver/Quaver#3294]
When you are starting a multiplayer game, if the game crashes for someone when the game starts, the map will not play and everyone will be forced to quit.

To see this error, join a multiplayer server, start a game and when the counter goes below 0 and the game starts, someone will force quit to trigger this error.

My expected behaviour for this is that the game will automatically kick the player that got out and will play the map regularly for everyone who is still playing.

(unfortunately, I don't have any screenshots)

**Comment by Swan** [comment]
Already tracking this issue elsewhere, thanks
