### ISSUE TITLE
Disable [Chat]

### ISSUE THREAD

**Issue by GrpeApple** [Quaver/Quaver#3299]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but I do not want to chat at all, I could just ignore it but that does not really make much sense to me though (?).
Sorry if that did not make much sense, but really just adding an option to disable the chat would be helpful (?).

**Describe the solution you'd like**
Add a disable button I guess

**Describe alternatives you've considered**
Closing all channels seem to work fine, until restarting the application, the channels just reopen, these issues #178, #1236 might be related.

**Comment by Swan** [comment]
Then don't open the chat

**Comment by GrpeApple** [comment]
bruh moment
