### ISSUE TITLE
LB's aren't showing up and maps turn to unranked when clicked on. 

### ISSUE THREAD

**Issue by UnlawfulFoxy** [Quaver/Quaver#3301]
When I click on a (ranked) map the leaderboard says I need to be a donator to view it, and when I click on a map the green ranked symbol on it changes to the red unranked one. Uninstalling and verifying the game files do not work, and Ai am not using any unranked modifiers.  I can provide a video if needed.

**Comment by Illuminati-CRAZ** [comment]
Sounds like you're looking at the "all" leaderboard and not the "global" leaderboard. The ranked changing to unranked bug is already documented.
