### ISSUE TITLE
Cursor Not Changing 

### ISSUE THREAD

**Issue by Personmanthin** [Quaver/Quaver#3304]
**Describe the bug**
Whenever i Change Skin My Cursor is the only thing that doesn't change
**To Reproduce**
when i go to skins to change it i choose a skin with a complete different cursor and it switches to the original cursor for when you dont have a skin 
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
os idk Browser chrome version latest
**Additional context**

**Comment by Swan** [comment]
Duplicate of #2724
