### ISSUE TITLE
Mods leaderboard not working

### ISSUE THREAD

**Issue by SamuKWasNotAvailable** [Quaver/Quaver#3305]
**Describe the bug**
The "mods" leaderboard no longer shows scores that have the same modifiers as you

**To Reproduce**
1. Go to single player
2. Click on any map
3. Change the leaderboard to "Mods"

**Expected behavior**
I expected to see scores with the same modifiers that I was using.For example if I wasn't using any modifiers i would expect to see scores that don't use modifiers

**Screenshots**
![11112021 16-53-54-944](https://user-images.githubusercontent.com/94122620/141319106-c1f8f1c1-7f0a-4f0e-87fa-9dc35382f7f7.jpg) 
![11112021 16-54-15-300](https://user-images.githubusercontent.com/94122620/141319230-3ee96442-fdb2-45e0-b825-570c6d962372.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Google Chrome(I don't know why you would want to know since it's on steam)
 - Version v0.30.1

**Additional context**
It used to work just fine and show scores that were using the same modifiers as me.I'm not sure if it's a bug but I really liked to try to get the best no mods scores.If it was intentionally removed i would love to see a seperate no mods leaderboard in the future.

**Comment by Swan** [comment]
Use the rate leaderboard instead. The mods leaderboard only works for mirror, fln, and inv.
