### ISSUE TITLE
Updated grade/New grade of map is not showing up next to map name.

### ISSUE THREAD

**Issue by Kibachan** [Quaver/Quaver#3308]
Anytime I finish a map and gain a new updated score the map does not update. Lets say I get an new letter grade of 'A' on the map, the last score lets say letter 'B' is still next to the name of said map. Same issue with a new map that does not have a letter grade. Even though I complete said new map the grade does not show up next to the name of the song. The letter grades only show up on the leaderboard. Can this issue please be fixed?? I tried to refresh maps and update them...nothing is working.
I've been playing Quaver for the past 3 months, never had this problem until this week.

**Comment by QiuFeng54321** [comment]
are your scores submitted and ranked? The letter grade next to map name updates as your ranked score on it. You need to select the map and wait for it to load the global leaderboard so it gathers your ranked score.

**Comment by Kibachan** [comment]
Yes my scores are submitted and ranked. Still does not change grade or show up a grade on a new map that I completed for the first time. It does show up in global as well. This is a bug.

**Comment by Swan** [comment]
The letter grade currently only shows up once you load an online leaderboard for the map. Tracking this issue here #1150

**Comment by Kibachan** [comment]
I have tried that and it did not want to show up. Hence making a thread about this. Refreshing it for the 3rd time seemed to make it work. Thanks.
