### ISSUE TITLE
I guess something with offset is wrong or something like this?

### ISSUE THREAD

**Issue by Ilanek256** [Quaver/Quaver#3310]
So long story short i downloaded today quaver and i go to map and when arrow come close and i click them it always says miss [yes im pressing right buttons] but when i click really too early it hits them. When i try to click them moment when they just are about to hit always miss and i cannot play like this so yeah... would be nice if someone helped with this. Thanks for reading this i guess =)

well i cannot give good screen but i can show u this i guess? this one arrow i expect it to be hit when i click button but it just misses and i have to click a lot quicker and for me bar where i should click it just doesnt exist its like im hitting in air.
![image](https://user-images.githubusercontent.com/94438779/141946821-632f74de-2495-44de-97ce-d54dd90911f0.png)

Windows
Chrome
0.30.0

**Comment by QiuFeng54321** [comment]
Go Settings -> audio -> Calibrate
Close your eyes and follow the beat (left right repetitive)

**Comment by IceDynamix** [comment]
skin related issue, probably need to change hit position

ask around in the #skinning channel on the discord for more instructions

**Comment by Swan** [comment]
It's one of three things, and not a bug. I'd suggest asking for help on [Discord](https://discord.gg/quaver) instead:

- Your audio offset is configured incorrectly.
- Your visual offset is configured incorrectly.
- The hitposition in your skin is configured incorrectly.
