### ISSUE TITLE
90.00% acc shows as B grading

### ISSUE THREAD

**Issue by thesussycat** [Quaver/Quaver#3312]
I played A.G.O.T.I - Screenplay (2 months ago) and got an accuracy of 90.00% but when i check the grading i got it showed as B, and not an A. 

![image](https://user-images.githubusercontent.com/94925576/143076306-a943d103-0256-4c2f-a093-798665c92855.png)

**Comment by IceDynamix** [comment]
this comes from rounding, your true accuracy is somewhere between 89.995% and 90.000% so it gets rounded up to 90.00. you will only get the A rank if your true accuracy is above or equal to 90%.
