### ISSUE TITLE
resolution is too large

### ISSUE THREAD

**Issue by cqstellation** [Quaver/Quaver#3314]
Bug: I was testing out different screen resolutions in the options menu when I accidentally set it to a resolution that was too big for my screen. The new resolution was zoomed in, so I couldn't go back to options and change it. I've tried changing window size in the config file, which didn't work. This is on a M1 MacBook Air (Monterey).

1. Go to options
2. Click on Video -> Screen Resolution
3. Change to larger resolution (I can't remember the exact numbers)

Expected Behavior: I was expecting it to zoom in, yes, but I was also expecting it to change the window size in accordance with the resolution, which it didn't do.

Screenshots:
<img width="1440" alt="Screen Shot 2021-11-24 at 2 14 42 PM" src="https://user-images.githubusercontent.com/94995312/143307494-831f293f-83eb-4fc8-8744-3331318c5568.png">
<img width="1440" alt="Screen Shot 2021-11-24 at 2 14 56 PM" src="https://user-images.githubusercontent.com/94995312/143307522-c51ffae5-6859-4581-ae8e-44ea40418e17.png">

Device:
 - OS: MacOS (Monterey)
 - Browser: Safari
 - Version: 12.0.1

**Comment by Swan** [comment]
Make sure the game is closed before changing the config file. Alternatively, you can change it to windowed mode and set whatever size you want.
