### ISSUE TITLE
Quaver appears to only use integrated graphics if given the option in windows 11

### ISSUE THREAD

**Issue by Sylvester334** [Quaver/Quaver#3317]
**Describe the bug**
Windows 11 completely controls which graphics processor is used for each program and appears to default to using integrated graphics when quaver is launched. Even if the operating system is told to use the dedicated graphics card for the quaver.exe it continues to use the integrated graphics.

**To Reproduce**
1. Have windows 11 installed with two graphics processors (Integrated graphics and dedicated GPU)
2. Run quaver.exe
3. Notice that the integrated graphics gpu is under load.
4. Open Windows settings and set quaver.exe to use dedicated GPU
5. Re-open quaver
6. Notice that integrated graphics are still being under load.

**Expected behavior**
Expectation is that when quaver is run, that the dedicated graphics card is used to render the game.

**Screenshots**
Screenshot showing Windows is told to use dedicated graphics card for quaver.
![GPU set](https://user-images.githubusercontent.com/95444325/144504018-6ca84d71-19bd-4a21-add3-33f6f45b066b.png)

Screenshot of task manager during quaver gameplay with unlimited frames setting. Note that integrated graphics are under heavy load while dedicated graphics card is under some load.

![Quaver Unlimited Frame rate](https://user-images.githubusercontent.com/95444325/144504282-4fa9a6c0-5835-445b-b912-a938a1453b78.png)

Screenshot of task manager during use of alternate game set to use dedicated graphics card to show what expected behavior should look like.

![Halo infinite task manager](https://user-images.githubusercontent.com/95444325/144504691-10fd0060-d552-4f0e-8bf0-82313ea00625.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Version [0.30.1]

**Additional context**
This may be bug specific to my hardware setup or even a bug specifically with windows 11, confirmation of this behavior from additional sources should be made.

Potentially related issue: Disabling integrated graphics through device manager in an attempt to force the use of the dedicated GPU prevents quaver from starting up at all.

**Comment by Sylvester334** [comment]
Quaver crash runtime log when integrated graphics is disabled.

[runtime_disabled_int_graphics.log](https://github.com/Quaver/Quaver/files/7646438/runtime_disabled_int_graphics.log)

My uneducated opinion is that there is an issue between quaver and my hardware configuration. quaver only notices my integrated graphics as a suitable graphics device and does not consider the dedicated GPU at all.

**Comment by chirijidev** [comment]
Have you tried using the NVIDIA Control Panel and going into Manage 3D Settings and set Quaver's preferred graphics processor to NVIDIA? Maybe this will work.

![image](https://user-images.githubusercontent.com/55966752/144574930-1d1d27ef-0153-41f5-b9d4-5cd3602d78b4.png)

**Comment by Sylvester334** [comment]
Using Nvidia's Control panel seems to have done something, as the load on my gpus has shifted a little towards the dedicated GPU. Task manager still says quaver is using the intel graphics as the gpu engine for quaver.

![image](https://user-images.githubusercontent.com/95444325/144685133-b7fd826e-5456-425c-b7be-9d90ea5c7a38.png)
![image](https://user-images.githubusercontent.com/95444325/144685243-be551e1c-5934-4f76-8698-f31c5c78a385.png)

**Comment by Swan** [comment]
This unfortunately is not an issue with the game itself, so we can't really provide support here. You can ask on the Discord if you're still having issues though.
