### ISSUE TITLE
A few suggestions 

### ISSUE THREAD

**Issue by KcHecKa** [Quaver/Quaver#3320]
_most of these are kind of arbitrary so feel free to dismiss_

- list number of #1 scores on profile in some way. either on the main stats, or where the scores are listed, also could there be a leaderboard for #1 scores? 
- have a leaderboard for ranked scores or maybe ranks/accuracy or something, opposed to total hits. 
- show what rank you got on a map on the results screen? (maybe only if you got top 10 or top 50)
- a white/light theme for the website
- an additional graph of your grades progression

**Comment by chirijidev** [comment]
Regarding the leaderboard, you can sort it based on certain selected mods, rates, country, global, local, and friends.

I'm pretty sure you can see leaderboards based on the rating of the map too, but that's just in-game only. I believe AiAe will implement this sorting in the website in near future updates.

I like the suggestion of which ranking are you in the leaderboards in the results screen after a gameplay.

As for other stuff you suggested regarding the website, I believe it's better to be suggested in [here](https://github.com/Quaver/Quaver.Website) but I think it's fine here too.

**Comment by Storn42** [comment]
For the record, there already exists a list of your first place scores. Any score you have thats #1 on the global leaderboard will appear on your profile on the website. Just look under scores and click the "first place" tab and you'll see the list.

**Comment by Swan** [comment]
Open up one issue per suggestion, and it's worth mentioning that things related to the website should go [here](https://github.com/Quaver/Quaver.Website)
