### ISSUE TITLE
Pause w/o waiting

### ISSUE THREAD

**Issue by BurAndBY** [Quaver/Quaver#3322]
**Is your feature request related to a problem? Please describe.**
To pause the game you need to press ESC button for X seconds.  I want an setting that disables this delay.

**Describe the solution you'd like**
 I want an setting that disables this delay.

**Describe alternatives you've considered**
There are none.

**Comment by AiAe** [comment]
Press F1 twice

**Comment by Cuckson** [comment]
There's an option already for this - it's called "Enable Tap To Pause", which removes that delay

**Comment by KcHecKa** [comment]
the delay is so clunky, but im afraid i'll tap esc on a really really good score. so i leave it on XD
