### ISSUE TITLE
I can't see the notes

### ISSUE THREAD

**Issue by itsmekiller360** [Quaver/Quaver#3332]
Yesterday I was quietly playing quaver and everything was fine but today when I wanted to play the notes were not visible and I tried to remove that and I have not found a way to remove the notes so that I could see the notes well someone knows how to remove it

![12142021 19-56-5-492](https://user-images.githubusercontent.com/96142430/146062119-8a3117dc-3c45-4728-9fe1-9e0e0b28c720.jpg)

**Comment by QiuFeng54321** [comment]
You have lane cover on in settings. Please turn them off.
