### ISSUE TITLE
i made a playlist and Quaver Broke none of the songs were appearing

### ISSUE THREAD

**Issue by Ant260530** [Quaver/Quaver#3335]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Ant260530** [comment]
So i made a Playlist And then quaver "hid" all of the songs i have to restart the whole game just to try to get the right song on the right difficulty

**Comment by AiAe** [comment]
You probably selected to see only playlists

**Comment by Ant260530** [comment]
thanks i didn't see that
