### ISSUE TITLE
Importing maps from other games

### ISSUE THREAD

**Issue by Mattkk04** [Quaver/Quaver#3341]
hi, sometimes when i want to import map from other games the game doesnt detect them.(trying to import from osu!stable)
+ osu!lazer isnt still detected

**Comment by Swan** [comment]
Drag the .db file into the game. osu!lazer isn't supported because the game isn't complete.

**Comment by prank855** [comment]
Any updates on whether or not osu!lazer will be supported now?

**Comment by Warp9000** [comment]
it wont
