### ISSUE TITLE
Quaver.db corrupted / suggestion

### ISSUE THREAD

**Issue by ARGOSkby** [Quaver/Quaver#3342]
I recently updated Etterna and moved the folder to an other place, played a bit and added maps into it. The problem is when i started Quaver all my Etterna maps were gone, that's kinda logic as i moved the folder. 

I putted the new folder location in Quaver.cfg and restarted the game. All my old/new maps were here as expected but i cannot play them except the new maps that i've added after.

To fix this problem i had to reset the Quaver.db file which i guess contain all the maps metadata but here's the problem, it contain everything useful: **Playlists, custom judgements, local profiles, ect..** It's pretty annoying to lose them. 

Isn't it possible to store them differently to avoid losing them by a corrupted Quaver.db file ?

**Comment by Swan** [comment]
Make backups if you're editing things manually next time.
