### ISSUE TITLE
Some special characters don't get a name if you try to bind them

### ISSUE THREAD

**Issue by MarkimusZer0** [Quaver/Quaver#3343]
**Describe the bug**
Pretty simple, some special keys don't get bound and are simply labeled as "None" if you try to bind them

**To Reproduce**
1. Go to 'Options'
2. Click on 'Input'
3. Click on 4k Gameplay Layout
4. Try binding a key like Ç or `

**Expected behavior**
The expectation was for it to correctly show what binds i had, it's not a major thing but it should get fixed in my opinion

**Screenshots**
![image](https://user-images.githubusercontent.com/73902340/147502848-38922fb3-848c-4967-950e-7528f8fcf2d6.png)
My current 4k Gameplay Binds, the keys i have bound are ASLÇ

![image](https://user-images.githubusercontent.com/73902340/147502952-ed49caff-3ae1-47b9-8e4a-27730fd4b261.png)
How they appear inside a song

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version: The latest steam release as of 27/12/2021

**Additional context**
I have not tested all keys but it appears most special characters suffer from this issue

**Comment by Swan** [comment]
Other kb layouts aren't supported right now
