### ISSUE TITLE
Suggestion: Per collumn hit-lighting

### ISSUE THREAD

**Issue by MarkimusZer0** [Quaver/Quaver#3344]
**Is your feature request related to a problem? Please describe.**
It is a minor problem but i personally use an FNF skin, FNF features differently colored note pops for each note, emulating this is currently not possible on quaver

**Describe the solution you'd like**
A solution i'd like is pretty simple, hit lighting per collumn so each note can pop a different color, the issue mainly affects me since FNF was my first rhythm game but i do think other probably suffered from the same issue due to Quaver only supporting one hit lighting sprite for all notes on a note skin

**Describe alternatives you've considered**
A different, probably more difficult to implement solution is making the skinning system be RGB, that way not only would users be able to easily customize stuff like note colors without manually having to make a whole new skin and hit lighting per collumn would be an option, as said this solution is probably more difficult to implement and honestly i feel like it would be too much effort for little gain but that's ultimately up to you developers

**Additional context**
The skin i use had a pretty nice setup for a possible hit lighting file system addition
![image](https://user-images.githubusercontent.com/73902340/147503440-e2bc5e6c-0d00-4d12-a3b8-6ccdd1a6935c.png)

**Comment by MeowcaTheoRange** [comment]
Uh-oh
