### ISSUE TITLE
Cursor lag with graphic tablet

### ISSUE THREAD

**Issue by DJMakerMusician** [Quaver/Quaver#3346]
**Describe the bug**
Cursor Lag when using tablet

**To Reproduce**
1. Open Quaver
2. Use tablet as a mouse
3. Error reproduced

**Expected behavior**
The cursor shouldn't lag, just as if I was using a mouse (which works on 100%)

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Not Applicable (Using Desktop app from Steam)
 - Version: 0.30.1

**Additional context**
Whenever I try to use the tablet as a mouse, my cursor lags for a second every about 1.5 seconds. When I use my normal mouse, as well as using a tablet in any other program, the problem doesn't occur.

**Comment by Swan** [comment]
Out of scope.
