### ISSUE TITLE
Headphone Removal Causing Songs To Not Play Sound

### ISSUE THREAD

**Issue by BreadddSticksss** [Quaver/Quaver#3347]
Quaver will go through a whole list of songs when I unplug my headphones, I can play the maps though, just with no music nor hit-sounds.
**To Reproduce**

1. Open Quaver
2. Play 1 or 2 songs
3. Unplug headphones
4. The bug appears

**Expected behavior**
Songs should start seeking and would not have any music.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Swan** [comment]
Duplicate of #569
