### ISSUE TITLE
Auto mod should check for BPMs left at 0ms

### ISSUE THREAD

**Issue by Storn42** [Quaver/Quaver#3349]
Going through the ranking queue, its an often occurrence that the only timing point in songs is left at 0ms. There hasn't been a single instance where the 0ms timing point is actually accurate to the music and a significant portion of queue is filled with these maps.

Having a simple automod check to stop these maps from constantly being submitted to queue would be nice so i can stop wasting my time looking at maps that have 0 chance of being accepted.

**Comment by Illuminati-CRAZ** [comment]
0 ms offset commonly works for fnf songs

**Comment by Storn42** [comment]
I have yet to see one where its actually correct. and in the case that is is, it could be moved 0.1ms and with how many people just rip the audio off of yt its likely no longer accurate anyways. Either way, the amount of maps that wrongly have the first bpm set at 0 is simply too high to the point where SOMETHING needs to be done about it. and an automod message that appears before people try and submit to queue just seems like a good solution.

**Comment by Swan** [comment]
Not really a valid solution imo because there *are* songs that work with 0 offset, and it's not that black and white. Also, if we're programatically checking for correct timing, it might as well be built into the game itself at that point.
