### ISSUE TITLE
The visuals stutters when playing more than 1 one at the time

### ISSUE THREAD

**Issue by geradeaus007** [Quaver/Quaver#3352]
**Describe the bug**
When playing for a random amount of time the visuals stutters, when playing more than 1 note at the same time. The sound and the inputs don't stutter, only the visuals stutter.

**To Reproduce**
1. open Quaver
2. play for a while
3. see the notes stutter when playing 2 or more notes at a time

**Expected behavior**
The game is still smooth and doesn't stutter during gameplay when playing more than 1 note.

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 21H2 (Build 19044.1415)
 - Quaver Version: neuest version (06.01.2022) 
 - Steam Build-ID: 7424782
 - CPU: AMD Ryzen 5 3600 (6 cores 12 threads)

**Additional context**
 I only experienced this bug in 4K I don't know if it occures in 7K. 
 I looked in task manager and saw Quaver was only using 1 CPU thread insted of 4 how it usually does.
After restart Quaver uses 4 threads again.

**Comment by batamhaha** [comment]
What i can suggest you :

⚪ - Try running in Windowed Mode
⚪ - Use Limited Frame Limiter to your screen Hz
⚪ - Reduce Scrolling Speed 
⚪ - Enable High Process Priority if not Enabled.

Reply to this post if none of these suggestions works for you

> **Describe the bug** When playing for a random amount of time the visuals stutters, when playing more than 1 note at the same time. The sound and the inputs don't stutter, only the visuals stutter.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. open Quaver
> 2. play for a while
> 3. see the notes stutter when playing 2 or more notes at a time
> 
> **Expected behavior** The game is still smooth and doesn't stutter during gameplay when playing more than 1 note.
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 10 Version 21H2 (Build 19044.1415)
> * Quaver Version: neuest version (06.01.2022)
> * Steam Build-ID: 7424782
> * CPU: AMD Ryzen 5 3600 (6 cores 12 threads)
> 
> **Additional context** I only experienced this bug in 4K I don't know if it occures in 7K. I looked in task manager and saw Quaver was only using 1 CPU thread insted of 4 how it usually does. After restart Quaver uses 4 threads again.
