### ISSUE TITLE
Multiple instances of the "There were manual changes detected in the .qua..." message popping up when charting, even when not manually editing anything

### ISSUE THREAD

**Issue by MazeGM** [Quaver/Quaver#3355]
Whenever I test play a map I've charted in the editor, after a certain period of time multiple instances of the "There were manual changes detected in the .qua..." message will start coming up.
As far as I'm concerned I am the only one seeming to have this problem, as I have not found any records of anybody else having it.
I can't really describe it any further than this.

![Video Example](https://user-images.githubusercontent.com/68865326/148631791-0c15190d-7a4a-42ae-a292-2ee4dd34a030.mp4)

Shortened Specs and OS if needed:

Specs:
Ryzen 5600x
Asus ROG STRIX B550-F GAMING
G.Skill Ripjaws V 16 GB (4 x 8 GB) DDR4-3600 CL16
Aorus Master 3070

OS:
Win10 Pro 21H1 19043.1415

**Comment by antoneser1** [comment]
Did you find a solution?
