### ISSUE TITLE
Fake top/bug on rating

### ISSUE THREAD

**Issue by Ganon130** [Quaver/Quaver#3356]
I played a LN map getting a 99.39% but when I finish the game registered me with the maximun rate, putting me in top 1 of the map, even when there are many better rates
Something that I notice is when you put the replay, you can see the real rate you got

![Opera Instantánea_2022-01-10_170053_quavergame com](https://user-images.githubusercontent.com/97482693/148852905-814262fc-590d-44da-ac0a-6eebf7e09d05.png)
![20220110170247_1](https://user-images.githubusercontent.com/97482693/148853017-4c85ba8a-69f2-44a3-bf55-a02c9ac54fe1.jpg)
![20220110161552_1](https://user-images.githubusercontent.com/97482693/148853043-3aa6601b-d7ec-4aec-b43f-2876ec5cc0aa.jpg)

**Comment by chirijidev** [comment]
That is because there is an ongoing difficulty calculator changes for the game and website. This is pretty normal as the scores are still on their way for the recalculation. Once the difficulty calculator is done, you will not have that #1 spot. It's not a bug.

**Comment by Ganon130** [comment]
> 

In my long time playing Quaver I haven noticed this before so I was worried about getting banned or something like that
Thanks for the clarification
