### ISSUE TITLE
no sound on arch linux

### ISSUE THREAD

**Issue by TheN001** [Quaver/Quaver#3357]
when i enter the game, has no sound, songs won't play, etc. i tried installing pulseaudio instead of pipewire, didn't work. i had same issue with osu!lazer so maybe it will work here as well, but idk how can i change the output device for quever. am running it nativly trough steam for linux. 
my neofetch 
![image](https://user-images.githubusercontent.com/53063352/149269955-b83527ba-c7a7-42f5-9dcc-c168a683c561.png)

my logs
[network.log](https://github.com/Quaver/Quaver/files/7860106/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/7860107/runtime.log)

if more info is needed, ask
if there is already a solution to this problem, redirect me

**Comment by YaLTeR** [comment]
(I already pasted the usual steps in Discord but they didn't help?)

> i had same issue with osu!lazer so maybe it will work here as well, but idk how can i change the output device for quever

So what you're saying is that you got osu!lazer working by switching to a different audio device? Did you try this step:

> 6. Make sure `aplay` can play back audio files without any extra configuration (using the default device). That is, `aplay path/to/sound.wav` should work.

**Comment by TheN001** [comment]
just tested aplay now, i forgot to do it the first time i was troubleshooting, lets say it plays _a sound..._

**Comment by YaLTeR** [comment]
Well, you need might to fix your default ALSA device then as Quaver can't currently change the device unfortunately.

**Comment by TheN001** [comment]
kk, ill see what i can do about default ALSA device

**Comment by Swan** [comment]
Any update? @TheN001

**Comment by TheN001** [comment]
> Any update? @TheN001 

srry for late response, i forgot to update the post. yes, it works now, i changed the device in candence in ALSA section to *(none)* and it worked
