### ISSUE TITLE
Right click to delete beatmap

### ISSUE THREAD

**Issue by Reyder95** [Quaver/Quaver#336]
It would be nice to delete beatmaps, sometimes I either grow old of certain maps or just mistakenly download a terrible map and a deletion option would be great. Perhaps when right-clicking the map you get certain options, and one of those could be a deletion option.

**Comment by Sublimity** [comment]
Right-Clicking is used for traversing backwards to the mapset selection menu, how about making it so deleting of mapsets/difficulties is done through the use of the DEL (delete) key, and the target map has to be selected first.

**Comment by Reyder95** [comment]
That makes sense, i always used esc didnt know right click did that, lol

**Comment by Sublimity** [comment]
Yeah, my pr for it was only recently merged, so you probably didn't notice if you didn't update to the latest dev build.
