### ISSUE TITLE
Only a portion of window is used to render

### ISSUE THREAD

**Issue by QiuFeng54321** [Quaver/Quaver#3365]
**Describe the bug**
as title says. See screenshots.

**To Reproduce**
1. Run Quaver on mac (not fullscreen)

**Expected behavior**
The grey region is supposed to be used to render also.  
Before 0.31.0 this is not an issue.

**Screenshots**
Before:  
<img width="1440" alt="Screen Shot 2021-11-24 at 9 24 18 PM" src="https://user-images.githubusercontent.com/32996262/150662127-a154ea2d-6819-488f-a8a8-559e1f8b7276.png">  
after
<img width="1440" alt="Screen Shot 2022-01-23 at 10 05 12 AM" src="https://user-images.githubusercontent.com/32996262/150662076-29ca84fc-2e63-4192-88a3-c404f8a0f3aa.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Browser Chrome, Safari
 - Version 0.31.0

**Additional context**
Fullscreen mode is not having this issue.  
after this update, whenever I run Quaver the screen will first shine grey color for a moment and back to normal.

**Comment by Swan** [comment]
Fixed in the latest build
