### ISSUE TITLE
Color picker in waveform settings not working well

### ISSUE THREAD

**Issue by QiuFeng54321** [Quaver/Quaver#3366]
**Describe the bug**
It will force bouncing back to 3 values when I delete characters.   
Deleting `0,200,255` to `0,200,` will make it bounce back to `255,255,255`  
This makes it impossible to set color to smth like `123,100,231`

**To Reproduce**
1. Go to 'Views->Waveform->Color'
2. Delete characters
3. See bouncing back

**Expected behavior**
It should act like layer color picker, where deleting characters completely is allowed.  
`0,200,255` -> ``: OK!

**Screenshots**  
It's a screen recording

https://user-images.githubusercontent.com/32996262/150662487-9741eda9-82e5-4f3b-8f27-e2c241dac6f9.mov

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Browser Chrome
 - Version 0.31.0

**Additional context**

**Comment by Kizuna-dev** [comment]
In the meantime you can bypass that issue by CTRL+A the value and pasting the new one
