### ISSUE TITLE
Mayflash GameCube Controller Adapter crashes Quaver on startup

### ISSUE THREAD

**Issue by Motorjam** [Quaver/Quaver#3368]
**Describe the bug**
When you have the Mayflash Gamecube Controller Adapter (on PC Mode) plugged in, the game will not start up.

**To Reproduce**
1. Plug in Mayflash Gamecube Controller Adapter
2. Launch Quaver
3. The game will not launch

**Expected behavior**
The game should launch.

**Desktop (please complete the following information):**
 - OS: Windows 11

The following is the runtime log for this crash.
[runtime.log](https://github.com/Quaver/Quaver/files/7921669/runtime.log)

**Comment by YaLTeR** [comment]
That backtrace is very strange; as far as I can tell, there's nothing at that line in that file which can overflow.

**Comment by Swan** [comment]
Fixed in the latest build
