### ISSUE TITLE
when i delete a map in a mapset, the adjacent audio and images doesnt delete

### ISSUE THREAD

**Issue by obj-graphite** [Quaver/Quaver#3371]
**Describe the bug**
as in title. not sure if its a bug or intentional. occurs when you have a beatmapset (map pack) of different songs (eg from osu). the only file deleted is the .qua file. redundant audio and image files take up a huge amount of space, while the .qua is often only kbs worth

**To Reproduce**
1. Go to a mapset
2. Click on a map and click "delete map"
3. Go to mapset folder

**Expected behavior**
the audio and images for the map gets deleted

**Screenshots**
highly replicable, so no screenshot. i spent hours deleting the leftover files to save some space.

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chome
 - Version 0.31.0

**Additional context**
none

**Comment by Swan** [comment]
Intentional
