### ISSUE TITLE
Suggestion: bookmarks/tagging for songs in selection menu

### ISSUE THREAD

**Issue by obj-graphite** [Quaver/Quaver#3373]
**Is your feature request related to a problem? Please describe.**
Sometime hard to find maps to play in menu. For instance some maps I downloaded are also high quality but I almost never play them after the first shots, and only play those I'm familiar with, which is not beneficial for improvement. The advanced filters is just not as versatile.

**Describe the solution you'd like**
A bookmarks/tagging system in the selecting songs menu, rather tan tediously going to edit mode and changing its metadata. You can have for example a number of freely editable bookmark folders (eg. nice maps by xxx, songs by xxx, jumpstream (splittrill training), jack (super heavy chordjacks) etc.) Maybe put it in the "sort by" section? idk in my idea you can just right click on a song and add it to a bookmarks folder.

**Describe alternatives you've considered**
This is the best that I could get, the editor is too tedious, and advanced filters not as versatile and user-friendly. 

**Additional context**
none

**Comment by Reihynn** [comment]
Use Playlists?

**Comment by obj-graphite** [comment]
> Use Playlists?
GOD. I'M TOO RETARDED TO EVEN BE AWARE OF THAT FEATURE😭
