### ISSUE TITLE
Submitting score on unranked beatmaps

### ISSUE THREAD

**Issue by jbantequera** [Quaver/Quaver#338]
**Describe the bug**
If you finish an unranked beatmap, on the result screen it will show "Submitting Score".

**To Reproduce**
1. Play an unranked beatmap.
2. See the result screen.
3. See error

**Expected behavior**
I think the "Submitting Score" tag should only appear on ranked beatmaps.

**Screenshots**
![20181223140852_1](https://user-images.githubusercontent.com/32770909/50383988-2f61c400-06be-11e9-9049-8a24dded8191.jpg)

**Comment by YaLTeR** [comment]
Does this still happen?

**Comment by Swan** [comment]
Yes, there needs to be a check upon import and/or map selection to retrieve the ranked status. Currently it only does so if the user has one of the online leaderboard sections selected. Until that happens, all scores are submitted and the server rejects the unranked ones.

**Comment by Swan** [comment]
Closing as we actually *want* this to happen now
