### ISSUE TITLE
Imported Map Note Desync

### ISSUE THREAD

**Issue by chipgeekjr** [Quaver/Quaver#3387]
**Describe the bug**
When importing some Stepmania maps, such as [this one](https://github.com/Quaver/Quaver/files/8009821/Little.princess.has.no.identity.sm.zip), the chart desyncs with the music, often by several seconds.

**To Reproduce**
1. Import the map.
2. Try playing it.
3. The audio ends a few seconds before the notes do.

**Expected behavior**
The map to import without desyncs.

**Screenshots**
Screenshot of the map in the editor, note the steps placed after the end of the song: 
<img width="1361" alt="QuaverDesync" src="https://user-images.githubusercontent.com/26667926/152674606-1b291143-9b8c-48a6-8ece-fc5863a302f2.png">

**Desktop**
 - OS: MacOS Big Sur
 - Quaver v0.31.1

**Comment by Swan** [comment]
Aware of the conversion issues and tracking elsewhere
https://github.com/Quaver/Quaver.API/issues/103
