### ISSUE TITLE
My game opens weird

### ISSUE THREAD

**Issue by Gooby123321f** [Quaver/Quaver#3389]
The game will say it starts and runs in the background with task manager, and after i wait for like 10 minutes it runs really slow, and pauses very frequently

**To Reproduce**
Click start on steam or double click the shortcut of quaver

**Expected behavior**
the game should open

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox
 - Version 91.0.22
It was working perfectly fine a couple days before the issue first started to happen

**Comment by Swan** [comment]
Make sure the game is running with your gpu instead of integrated graphics. If it still doesn't work, your hardware may not be supported.
