### ISSUE TITLE
Color Coded Scroll Bar

### ISSUE THREAD

**Issue by Kubeon4** [Quaver/Quaver#3390]
**Is your feature request related to a problem? Please describe.**
It's more a thing of intuitiveness. In song select, you can middle click the screen in order to scroll to the location where your cursor is relative to the scroll bar. It's a nice feature, but it would be much more useful if we knew where we were going. If you are looking for a 10 difficulty map, or if you're looking for the purple zone, there is no point of reference to go off of so it may take a few tries to get to where you want to be.

**Describe the solution you'd like**
A simple solution would be to color code the scroll bar to the difficulty color of the maps (white -> purple). This way, it would be incredibly out of the way while still showing useful information.

**Additionally,**
It would be cool if hovering over the scroll bar displays the difficulty of the map closest to the cursor. Just a nice little thing, albeit unnecessary.

**More context**
Of course, you can middle click multiple times to get to where you want to be, but I still think it would be super nice to know the destination right off the bat. This feature would be even more useful for people with especially high map counts.

**Comment by Swan** [comment]
You can hold the middle mouse button down and scroll where you need to. You don't have to guess and click.
