### ISSUE TITLE
Dropped inputs randomly due to newest update(?)

### ISSUE THREAD

**Issue by IntellectualPotato** [Quaver/Quaver#3391]
so here is my problem:
So, i started the game back up after a bit, after the most recent update, played a few maps, got HORRIBLE scores even for my skill level. i got like 10 misses when i know i didnt miss any, as if my inputs were dropping for some reason. i have no idea why but i can give specs if that would help with anything

specs:
windows 10 home 64 bit
intel core i5
16gb ram
radeon rx 480 graphics

i also have a second monitor connected, 2 keyboards connected. but it worked all fine previous to this update with all that stuff so im just confused right now
i tried osu, fnf, etc and that al lworked fine with no dropped inputs but i prefer quaver due to customizability, so if this could be resolved that would help alot!

**Comment by Swan** [comment]
Can't really do anything with this information... Are you dropping frames? How often? Is it consistent? Every 30 seconds, minute, etc, or is it random? Have you looked into your own system (closing background programs, locking/unlocking the frame limiter, etc)?

**Comment by IntellectualPotato** [comment]
Tried with newly restarted, started for awhile, etc, and my fps is actually stable,  yet for some reason some of my inputs simply dont go through as i KNOW i hit them which is very odd example is like 10 misses on song i easily got like 1 miss or fcd before,  and i usually know when i miss it myself or by my own fault but i know i hit them and it still misses
