### ISSUE TITLE
Editor stuck after full audio played

### ISSUE THREAD

**Issue by QiuFeng54321** [Quaver/Quaver#3397]
**Describe the bug**
Listen to the audio till the end.
audio progress then stuck to 0:01.000. Cannot scroll.

**To Reproduce**
1. Play an audio to the end

**Expected behavior**
Not stuck

**Screenshots**
<img width="1273" alt="Screen Shot 2022-02-13 at 2 49 11 PM" src="https://user-images.githubusercontent.com/32996262/153742409-a6c4a40c-5cb4-4b2e-be95-6681bcad9f11.png">

[runtime.log](https://github.com/Quaver/Quaver/files/8055092/runtime.log)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Version: 0.31.2

**Additional context**

**Comment by Swan** [comment]
What happens if you place a timing point?
