### ISSUE TITLE
Is Quaver just going to be (Step/osu!)mania style?

### ISSUE THREAD

**Issue by simplesentai** [Quaver/Quaver#3398]
Normally, I'd just say `title`, and nothing more. Today, however, I have an legitimate question: Will Quaver (the game) *always* be a mania-style game? If not, are there plans to add other gamemodes, such as custom-made gamemodes (somewhat like in osu!lazer) or a taiko-style mode? If not, and if I was to make a pull req. with that implemented, what would happen?

ありがとう, 

simplesentai

**Comment by Swan** [comment]
Yes
