### ISSUE TITLE
Reinstalling Quaver from Steam 

### ISSUE THREAD

**Issue by thesussycat** [Quaver/Quaver#3404]
(Im sorry if this not a bug report btw 😅)
Hello! ive been thinking about starting again my quaver experience by reinstalling the game and going back to where i start. and i saw in your privacy policy that, and i quote, "Once deleting your account, you will not be able to return to Quaver." Is this true? Cause i might reconsider my choice.

**Comment by Swan** [comment]
Your Quaver account is tied to your Steam profile. Reinstalling the game will preserve your old account and stats.
