### ISSUE TITLE
Game won't launch/too long to launch

### ISSUE THREAD

**Issue by ZeroTooMany** [Quaver/Quaver#3413]
The game takes about 70 minutes to launch, and when it does launch, it loads a frame every 5 minutes if it manages to pass the "Press Enter to Skip" screen, which it doesn't at all and instead window says "Quaver is not responding"

**To Reproduce**
Just open the game, watch youtube to pass the time, cause it takes about an hour, and once it loads, it should say "Quaver isn't responding" although it used to function normally, even perfect, but I think since the update it's just not launching.

**Expected behavior**
When you start, it usually took me a few seconds to get to the main menu screen

**Additional context**
I tried on my laptop and it works but it fails after I submit a few scores, either that or I just closed the app and it stopped working, but I don't know. Prior to this week, it was working normally and I was just playing the game to have more games than just osu! mania, but after a while it just wouldn't start. I joined the discord and asked how to fix it, someone suggested to restart steam but it didn't work. I also saw at least two other people in the server have the same problem so I'm not sure if it's fixed and I'm just writing this for no reason but it's just kind of annoying that once I open quaver and I remember it's not working, I have to wait an hour to close the application.

**Comment by Swan** [comment]
Make sure the game is running off your GPU. It has trouble with integrated graphics.

**Comment by ZeroTooMany** [comment]
I don't have a graphics card yet :(
