### ISSUE TITLE
Game won't open

### ISSUE THREAD

**Issue by ikergameplaysyt** [Quaver/Quaver#3422]
**Describe the bug**
The game won't open. It shows up on Task Manager sometimes and others it doesn't. It shows up as "running" on Steam all the time, but the game doesn't open at all. I've tried everything I could think about: updating the GPU drivers, closing apps that could make a conflict, reinstalling the game, reinstalling Steam itself, opening the game on compatibility and administrator modes, switching steam account, disabling overlays, etc. The game used to work completely fine but a week or two ago it stopped working. I've been trying to solve this on my own but I don't know what more I can do, this has come to a point where I have no ideas.

**To Reproduce**
1. Go to 'Steam'
2. Click on 'Quaver'
3. Click on 'Play'
4. See how the game doesn't open

**Expected behavior**
The game to open normally

**Runtime logs:**
[4:19:03] - RUNTIME - DEBUG: OS: Microsoft Windows 10.0.19044
[4:19:03] - RUNTIME - IMPORTANT: Config file has been successfully read.
[4:19:03] - RUNTIME - IMPORTANT: Started IPC server on port: 43596
[4:19:03] - RUNTIME - IMPORTANT: Successfully initialized and logged into Steam as : G2 CHUPABALAS <76561198404865901>
[4:19:03] - RUNTIME - IMPORTANT: Found 0 subscribed workshop items | # of subscribed: 0 | Entries: 0
(Yes, that's it, it doesn't say anything more)

**Screenshots:**
![image](https://user-images.githubusercontent.com/101515309/158067563-1bf6894f-99b9-4ad5-af4d-5b9ff21aa369.png)
_The game task at the Task Manager and Steam showing it's running._

**Desktop (please complete the following information):**
 - OS: Windows 10 (latest version)
 - CPU/GPU (in case it's not compatible or something idk): R7 2700/RTX 2060 Super
 - Browser: Chrome
 - Version: Quaver is updated [0.31.3]

**Comment by Swan** [comment]
@ikergameplaysyt Make sure the game is running off your GPU. From your task manger, it doesn't look like it is.

**Comment by ikergameplaysyt** [comment]
Is there any way I can force the game to run off my GPU? I mean, it should be running off it because I don't have an integrated one of my processor, but, anyway, can I force the game to run off of my graphics card? If so, how can I do it?

**Comment by ikergameplaysyt** [comment]
SOLVED! The game didn't open because apparently there's an incompatibility with the Raphnet adapter for a guitar (Guitar hero) when I unplugged the guitar, it worked. When I plug it on, the game instantly crashes.
