### ISSUE TITLE
Allow the player to have no black backdrop behind the notes.

### ISSUE THREAD

**Issue by megaman15** [Quaver/Quaver#3424]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I think it would be nice to actually see the background image as you are playing a beatmap
**Describe alternatives you've considered**
Make it translucent
**Additional context**

**Comment by nonameorous** [comment]
...except it's already a feature?
skin.ini exists and you can just use `BgMaskAlpha = 0`
