### ISSUE TITLE
I don't hear anythingg

### ISSUE THREAD

**Issue by nekoproVT** [Quaver/Quaver#3425]
The songs in the menu change all the time and Idon't hear anything, could you fix it?

**Comment by IceDynamix** [comment]
your audio device could be set incorrectly or maybe your in-game volume is set to 0 which you can fix with alt+scroll wheel

**Comment by Illuminati-CRAZ** [comment]
Gonna go ahead and close this since it's either volume being set to zero or a bug report lacking useful information.
