### ISSUE TITLE
Can't pause/exit while watching a replay

### ISSUE THREAD

**Issue by SuShi2801** [Quaver/Quaver#343]
**Describe the bug**
While watching a replay, you can't pause/exit 

**To Reproduce**
1. Go to a map and click on a replay
2. Click on 'Watch Replay'
3. Try to 'press Esc (Pause) or press F1 (Quick exit)' 
4. See the error

**Expected behavior**
What I expected to happen is: Pausing a replay when pressing the right key / Exit the replay when pressing the right key

**Desktop (please complete the following information):**
 - OS: Windows 10
 
**Additional context**
I don't know if that's only my problem.

**Comment by YaLTeR** [comment]
Does this still happen?
