### ISSUE TITLE
Autohost multiplayer lobbies

### ISSUE THREAD

**Issue by IceDynamix** [Quaver/Quaver#3432]
autohosted lobbies by quaver itself and always open, with 8 skill-locked lobbies each for each keymode

- automatically picks maps from the ranked mappool in a given rating range
  - no time wasted picking maps
  - no host (rotation) confusion
- picked maps are filtered
  - 4min max, to keep rotation times low
  - only maps that naturally dont have svs, no surprises with memo/unsightreadable sv maps
- start the lobby automatically after 1 minute
  - no issue of hosts afking
- if youre the only one in a lobby then allow singleplayer play inside the lobby
  - incentive to join, even if the lobby is empty at the moment
- lobbies in steps of 5, so one lobby for 0-5, 5-10, 10-15 etc up until 40
  - lobby in your skill range is ALWAYS available, no matter how good or bad you are
  - if the demand for a given skill range is too large, make multiple lobbies for that skill range

**Comment by Swan** [comment]
Implemented to spec aside from the following differences:

- Starts the match after 90 seconds instead of 1 minute.
- SV maps aren't filtered. There's no easy way to check if there are SVs in the map at the moment.

**Comment by Illuminati-CRAZ** [comment]
What about a implementing a blacklist and manually adding ranked sv maps to them? I don't think there are that many and they could probably be easily found by searching "sv" or by looking through some sv playlists.

**Comment by nebneb0703** [comment]
Suggestion:
- "Ready Up" should be disabled in AutoHost lobbies, to allow the most amount of time for people to join. The wait time is not too long anyway so the people already waiting to start the next game shouldn't be too bored.

**Comment by Cuckson** [comment]
> What about a implementing a blacklist and manually adding ranked sv maps to them? I don't think there are that many and they could probably be easily found by searching "sv" or by looking through some sv playlists.

I think an actual solution should be implemented instead as that list is ever-expanding, and this would require manual intervention each time a new one is ranked.

**Comment by IceDynamix** [comment]
while not a complete solution, an easy way to filter most sv maps would be to check for "sv" in tags. it should get like at least 80%, which is still a lot better than 0%.

**Comment by Reihynn** [comment]
> while not a complete solution, an easy way to filter most sv maps would be to check for "sv" in tags. even if it doesn't accurately catch all sv maps there are, it should get like at least 80%, which is still a lot better than 0%. and it's relatively easy to implement

it still would filter out maps that doesn't have sv in it (as in another difficulty in the same mapset) so i don't think its a good solution

**Comment by Swan** [comment]
There's really no good way to handle it, as all options have drawbacks. Instead, I enabled free mod. If you don't want to play SVs, then you can enable NSV.
