### ISSUE TITLE
option to delete all of your maps

### ISSUE THREAD

**Issue by Spo0dsE** [Quaver/Quaver#3435]
**Is your feature request related to a problem? Please describe.**
i think deleting all of your maps is frustrating, even when you delete the files, your maps still show up but just don't work and manually deleting all of them is really slow too

**Describe the solution you'd like**
a button in the "options" menu to delete all of your maps

**Describe alternatives you've considered**
a better way of managing the map files so that when you delete them they disappear too

**Additional context**
![image](https://user-images.githubusercontent.com/102416027/160237778-d042eb36-3f6b-4f2a-b78e-f95226f7eb2c.png)

**Comment by Swan** [comment]
Press F5
