### ISSUE TITLE
all maps i touch become unranked 

### ISSUE THREAD

**Issue by mogegh** [Quaver/Quaver#3441]
i just am in the chose songs menu and any map i hover over to view map or select to play it just becomes unranked even if i just downloaded it from ranked
![image](https://user-images.githubusercontent.com/102669761/160835226-9bcbbfb8-8e8e-4398-b3e6-599bc0a4eea3.png)
![image](https://user-images.githubusercontent.com/102669761/160835319-93fe4827-abd2-48e4-9113-6286cabbbfc8.png)
(context on how it becomes unranked)
 i use windows
 i use chrome
and use the most recent version of quaver

**Comment by Illuminati-CRAZ** [comment]
probably same issue as #3257
