### ISSUE TITLE
discord will not stream with audio

### ISSUE THREAD

**Issue by pepsi-i** [Quaver/Quaver#3447]
**Describe the bug**

for some reason, if i stream quaver on discord, it doesnt stream with audio at all, the app isnt too quiet or anything and ive ran it as admin.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

 - Chrome
0.31.3

**Additional context**

**Comment by Swan** [comment]
Consult Discord. We don't handle that issues like that here.
