### ISSUE TITLE
Three Key Command Not Working

### ISSUE THREAD

**Issue by MandarinOG** [Quaver/Quaver#3448]
I'm not doing all that extra stuff but here is the bug I noticed.

I changed my keys to f,g,k,l on 4k. When I try to hit a triple chord the keys will not work. The game seems incapable of using all three keys at once. I did make sure I was hitting them at the same time, and played around a bit to make sure it really was not working / not me. The combinations: g,k,l and f,k,l work. The combinations: f,g,k and f,g,l do not work. Using beta version (installed 03/22), windows 10, steam.

**Comment by Illuminati-CRAZ** [comment]
This is most likely an issue with your keyboard
