### ISSUE TITLE
Song cleared when steam shows that it didnt

### ISSUE THREAD

**Issue by ChaosIsDaddy** [Quaver/Quaver#3454]
Im experiencing an issue where i beat a map on quaver and on the bottom it stays stuck as submitting score and when i close out of it, on the leaderboard on the left, it shows my score, my accuracy, the usual but i dont get any rank points or get a lower rank. sometimes, it doesnt even show the submitting score thing but still does not give me any ranks. i wanted to see how to fix it and at the main menu, if i press on my profile top right, go to view profile on steam and go to the recent songs, i see all of the songs that i have clearly beaten, show up as Fs. please fix this bug, i work very hard on beating the maps, waste so much time and energy on them. 
EDIT: and the "submitting score thing stays stuck on loading till i leave the screen and after i beat any other song right after that bug happens, none of my songs on steam show that they were cleared
![Capture0](https://user-images.githubusercontent.com/104076812/164235170-a613a9f3-d5cf-4c0f-8ee2-036f5c69ffd3.PNG)
![Capture1](https://user-images.githubusercontent.com/104076812/164235195-5cdc8511-fa95-4295-aaa3-c35b8d6a953d.PNG)
![Capture2](https://user-images.githubusercontent.com/104076812/164235209-616b1536-1316-45f6-9327-9c68e4470cf0.PNG)
![Capture3](https://user-images.githubusercontent.com/104076812/164235222-9ebc16c1-edb2-43f6-8c9e-b930d71a7b84.PNG)
![image_2022-04-20_161138011](https://user-images.githubusercontent.com/104076812/164237959-48cd1f85-645c-43c9-8945-028582b771ca.png)

**Comment by Swan** [comment]
Your judgement windows are on peaceful which makes the game easier client-side. Change it to Standard if you want it to be the same.
