### ISSUE TITLE
There Was A Problem Creating A New Mapset.

### ISSUE THREAD

**Issue by Hypertknois** [Quaver/Quaver#3459]
Every time I drag a mp3 file, It comes up with this message. 
Is it just because a map has been created before with this mp3?

![532022 16-33-37-377](https://user-images.githubusercontent.com/89292908/166413064-549fba47-6172-42fc-b662-8bed5b2105fb.jpg)

**Comment by Swan** [comment]
Open the issue back up with logs if you're still having issues. Can't do anything with this.
