### ISSUE TITLE
Crash when trying to play maps with unromanized names

### ISSUE THREAD

**Issue by QiuFeng54321** [Quaver/Quaver#3460]
**Describe the bug**
I am aware that an unromanized map is not allowed in ranking criteria and is not recommended. I believe it worked well before the update with the steam rich presence (which is exactly what the stack traces to in the runtime log)

I think this issue has been brought up by someone(me?) before, but I can't find it in github issues.

**To Reproduce**
1. Make a map with unromanized characters
2. Play it
[network.log](https://github.com/Quaver/Quaver/files/8650183/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/8650184/runtime.log)

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/32996262/167378447-c4a1c6ee-d6d5-4451-b35c-5fda3c6885ba.mp4

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15
 - Browser chrome
 - Version 0.31.3

**Additional context**

**Comment by Swan** [comment]
@QiuFeng54321 Can you copy-paste the specific text you're trying to use?

**Comment by QiuFeng54321** [comment]
> @QiuFeng54321 Can you copy-paste the specific text you're trying to use?

七瀬光 - ユメのなかノわたしのユメ
Author - Map name
