### ISSUE TITLE
Quaver does not launch on Arch Linux, but works completely fine on other distros

### ISSUE THREAD

**Issue by kittehsq** [Quaver/Quaver#3462]
**Describe the bug**
Installed Quaver, clicked play, and the game does not launch. Tried playing through Proton Experimental to no avail.

**To Reproduce**
1. Install a fresh copy of Arch Linux
2. Go to Steam
3. Double click on Quaver
4. Wait for Stop button to change back to Play

**Expected behavior**
I expected Quaver to launch.

**Screenshots**
![image](https://user-images.githubusercontent.com/97140641/167753691-6bc429d5-8388-4274-86a7-1c9dcdb11059.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64
 - Browser: Mozilla Firefox 100
 - Version: 0.31.X

**Additional context**
Fresh Arch install, not much more than Xfce and Steam.

The game does launch perfectly fine on Linux Mint 20.3 and Fedora 35, maybe missing unlisted dependencies???

Using Pipewire with Wireplumber, Pipewire-Pulse, Pipewire-JACK, Pipewire-ALSA, and all Testing repos (including gnome-unstable and kde-unstable)

Tried a workaround (https://steamcommunity.com/app/980610/discussions/0/3266808619799649134/) and it worked fine, until I realized that it was stuck loading for a reeeealy long time before it got to the main menu.

**Comment by Swan** [comment]
@YaLTeR

**Comment by YaLTeR** [comment]
Hello, this is because ICU in the newest distros has been updated to a version that's too high for dotnet 3 that Quaver is using. Until we figure out what to do about this situation, you can play Quaver on Steam from Flathub, which at the moment has a slightly older, compatible ICU.

**Comment by ichiniro** [comment]
Hi, you can try forcing Quaver to use the steam linux runtime in the compatibility section, I did that and now it works flawlessly.
