### ISSUE TITLE
Sorting maps by min/max difficulty is broken

### ISSUE THREAD

**Issue by green3554** [Quaver/Quaver#3464]
When searching for maps to download with the minimum difficulty sort turned on, it gives you a few easy maps and very quickly scales up to the hardest of hard, and then if you keep scrolling it goes back to easy and then up to hard, etc.
Maximum difficulty suffers from the same issue.

I'm not sure if this is some sort of weird intended feature, but it really shouldn't be like that. It should go through all the maps linearly from easiest to hardest or from hardest to easiest, so that new and veteran players can quickly find all the maps of their skill level. 

Here is a clip showing how it sorts: https://medal.tv/games/quaver/clips/kCU5Ijpso5Lhr/d1337jsZal9N?invite=cr-MSwzNWwsNjIyODM1NSw

Edit: Additionally, sorting the difficulty rating with certain parameters gives unexpected results. I sorted 7key maps from difficulty 0 to 2, and it gave me only 11 maps. I believe this is because it searches for maps where all of the difficulties available fit within those parameters.
![image](https://user-images.githubusercontent.com/102485284/168411278-61e15b9d-800d-4a62-b541-53e048f62032.png)

Windows 10
Quaver v0.31.4

**Comment by Swan** [comment]
Duplicate issue
