### ISSUE TITLE
Objects placed after the audio ends issue. They are all not placed after the audio's endpoint. (Mapping)

### ISSUE THREAD

**Issue by Autumcized** [Quaver/Quaver#3468]
Whenever I start mapping there is an issue where the object in a columm is placed after the audio ends. Although, everything would seem to be fine, but according to Automod it isn't. I've tried downloading the same song from different websites and even trying other songs to map and it all shows the same object issue. Is there a specific place I need to get my songs from? Or is there a way to swap the mapsets song by any chance?
![image](https://user-images.githubusercontent.com/105564788/168446681-5d43e4b9-0e5a-4c13-8bd5-a59df8c852f7.png)

**Desktop (please complete the following information):**

**Comment by nonameorous** [comment]
Your map audio isn't .mp3

**Comment by Autumcized** [comment]
> Your map audio isn't .mp3

Just tried with a .mp3 file, same issue

**Comment by Jolomann** [comment]
this issue usually comes up when your mp3 is an mp4 in disguise. you can try to get the mp3 from a different source or re-export it yourself with something like audacity to fix it

**Comment by Autumcized** [comment]
> this issue usually comes up when your mp3 is an mp4 in disguise. you can try to get the mp3 from a different source or re-export it yourself with something like audacity to fix it

If it works is there a way to like replace the mapset song? Doesnt really work through file replacement. Or maybe im just blind and cant see a feature that can remove the mapsets mp3, i dunno.

**Comment by Jolomann** [comment]
while you're in editor try ctrl+r, then exit and enter editor again. it forces a refresh

**Comment by Autumcized** [comment]
> 

It just removed the audio completely. i might aswell just remap it
