### ISSUE TITLE
Cannot re-download skin from workshop after manual deletion through files

### ISSUE THREAD

**Issue by Kuneii** [Quaver/Quaver#3472]
-
I don't know if this is considered a bug or not, but I wanted to find out how to remove unwanted skins, so I just deleted the whole file of the skin through the skin folder. Then I suddenly had the urge to re-download it again so I went back the Quaver Skin Workshop and it said I was already subscribed to the skin, I just unsubscribed and subscribed again and checked if I got the skin but I didn't. How do I get it back?

**To Reproduce**
1. Download a sample skin from the workshop
2. Go to the skin folder and delete the folder of the sample skin
3. Head back to the workshop to re-subscribe to the same skin
4. See if you got the skin

**Expected behavior**
I expected the skin to be in my skin folder, but it isn't.

**Desktop:**
 - OS: Windows
 - Browser: Microsoft Edge
 - Version: 10

**Comment by nonameorous** [comment]
don't delete workshop folders lmao. 💀
you have an option to unsubscribe from a workshop item.

**Comment by Kuneii** [comment]
> don't delete workshop folders lmao. 💀 you have an option to unsubscribe from a workshop item.

I was new lmao
