### ISSUE TITLE
Game doesn't launch on Steam

### ISSUE THREAD

**Issue by SaamariYT** [Quaver/Quaver#3473]
**Describe the bug**
I click on the launch button, steam cloud sync popup comes as usual, then everything comes back as if i didn't launch the game.

**To Reproduce**
I don't really know how to reproduce the bug because it litterally started to bug from nowhere.

**Expected behavior**
I would have expected the game to launch obv.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera
 - Version ?

**Additional context**

**Comment by not-nef** [comment]
I had that issue too, it worked after i restarted my pc.
