### ISSUE TITLE
Sections

### ISSUE THREAD

**Issue by not-nef** [Quaver/Quaver#3474]
It would be cool to be able to split maps  in sections that you can jump to, just like the game CloneHero has.

**Comment by nonameorous** [comment]
imo that would be pretty cool for full album marathon maps specifically tho idk if a feature like this would fit in a game that is not guitar hero inspired.

**Comment by not-nef** [comment]
I would find it super useful, because sometimes i only want to play a specific part of a map, to practice for example

**Comment by nonameorous** [comment]
> I would find it super useful, because sometimes i only want to play a specific part of a map, to practice for example

you can do it in a map editor

**Comment by not-nef** [comment]
Still think that sections would be better

**Comment by Reihynn** [comment]
ngl it would be less of a struggle than editing a map and making a practice diff

**Comment by nonameorous** [comment]
> Still think that sections would be better

again, Quaver is not a guitar hero inspired game. i don't think majority of players would really want something like this unless they played guitar hero or clone hero. (myself included)

**Comment by nonameorous** [comment]
> ngl it would be less of a struggle than editing a map and making a practice diff

you can playtest from a specific moment

**Comment by Reihynn** [comment]
> > ngl it would be less of a struggle than editing a map and making a practice diff
> 
> you can playtest from a specific moment

i do that currently but its way harder to read

i mean if you can press F4 on song select to playtest a part then it would be cool ngl

**Comment by Janko5** [comment]
if we could add it to the game:
- first the mapper would have to create start-end points for these sections, 
- so not all maps will have sections because it will not be mandatory, 
- so if you would like to play a section in such a map, you would have to add them to the map in the editor by yourself, 
- so you might as well create practice diff by pasting only the part you want to play. The effect will be the same

**Comment by not-nef** [comment]
> so if you would like to play a section in such a map, you would have to add them to the map in the editor by yourself,
Thats atleast better than always going to the part in the editor

**Comment by Janko5** [comment]
> so if you would like to play a section in such a map, you would have to add them to the map in the editor by yourself,
> >Thats atleast better than always going to the part in the editor

again: so you might as well create practice diff by pasting only the part you want to play. The effect will be the same

**Comment by not-nef** [comment]
> again: so you might as well create practice diff by pasting only the part you want to play. The effect will be the same

Wouldnt that like flood your map list if you do that for multiple maps? idk. there are multiple ways of seeing this, but extra features are never bad imo

**Comment by not-nef** [comment]
> > Still think that sections would be better
> 
> 
> 
> again, Quaver is not a guitar hero inspired game. i don't think majority of players would really want something like this unless they played guitar hero or clone hero. (i never touched any gh games)

If someone doesnt want that, they just dont use it!

**Comment by not-nef** [comment]
Well i would if i knew this language

**Comment by IceDynamix** [comment]
great, welcome to the intricacies of development and why not every feature can be added on the spot

**Comment by not-nef** [comment]
Well why did you close it? It can be added

**Comment by not-nef** [comment]
And i always knew that this isn't something that could be "just added". I just wouldve enjoyed having this feature
