### ISSUE TITLE
Random frame drops

### ISSUE THREAD

**Issue by ABA3685** [Quaver/Quaver#3477]
Whenever I am playing there always seems to be random and sudden frame drops/stutters that tend to be combo and run killers. I love this game, but this honestly makes the game unplayable which sucks because it is so much better than osu mania. 

This happens every time that I play a song with random intervals and lasts for what seems to be the same amount of time every time.

All I ask is that this issue get looked into and possibly fixed just so I can play the game completely without these run killing stutters 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 10
**Additional context**

**Comment by Swan** [comment]
- Close background programs (Discord, Chrome, anti-virus, etc)
- Limit your frames (Don't play on unlimited if your computer can't handle it)
- Enable/disable the high process priority setting
- Upgrade your PC if it's too weak.
