### ISSUE TITLE
I keep trying to connect to server but it keep saying failed authenticate everytime I try

### ISSUE THREAD

**Issue by T6KP** [Quaver/Quaver#3481]
**Describe the bug**
Oneday I opened quaver, it said failed to authenticate to server, I thought it's normal and I tried to to connect the server again, but it didn't work even I reinstall it and reopen my computer again 
**To Reproduce**
1. Go to menu 
2. Click on login and click on log in 
3. No matter how many times I try it always says failed to authenticate to server

**Expected behavior**
Every time I launch the game, I connect to the server and then it disconnects

**Screenshots**
![圖片_2022-05-29_140702334](https://user-images.githubusercontent.com/106463179/170854625-ded74e62-a521-48e7-b23b-2ce61630326a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera GX
 - Version 0.31.0 (the newest

**Additional context**
Resinstalled the game, rerun my game again and again also reopen my computer

**Comment by Reihynn** [comment]
servers are down so just keep your game open to submit your scores

**Comment by T6KP** [comment]
oh the servers are down? i didnt know that, anyways thanks for the
information

Reihynn ***@***.***> 於 2022年5月29日 週日 14:09 寫道：

**Comment by callmekiwi8109** [comment]
> **Describe the bug** Oneday I opened quaver, it said failed to authenticate to server, I thought it's normal and I tried to to connect the server again, but it didn't work even I reinstall it and reopen my computer again **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to menu
> 2. Click on login and click on log in
> 3. No matter how many times I try it always says failed to authenticate to server
> 
> **Expected behavior** Every time I launch the game, I connect to the server and then it disconnects
> 
> **Screenshots** ![圖片_2022-05-29_140702334](https://user-images.githubusercontent.com/106463179/170854625-ded74e62-a521-48e7-b23b-2ce61630326a.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 10
> * Browser: Opera GX
> * Version 0.31.0 (the newest
> 
> **Additional context** Resinstalled the game, rerun my game again and again also reopen my computer

same thing happened to me

**Comment by Reihynn** [comment]
servers are down please read the other issues first
