### ISSUE TITLE
Failed to connect to server

### ISSUE THREAD

**Issue by Autumcized** [Quaver/Quaver#3482]
Anytime I open Quaver, it does not connect me to the server no matter how many times I try to do it myself manually by pressing 'Log in'. My account is connected on my steam, everything seemed to be in normal shape, but after I open the game after a couple of days it will not sign/connect me in the server. Is there a problem with the server itself or with my account, because I got good wifi (cabled) and this has never been an issue.

**Comment by Illuminati-CRAZ** [comment]
servers are currently down
