### ISSUE TITLE
Steam edition of quaver crashing randomly offline

### ISSUE THREAD

**Issue by cheepling** [Quaver/Quaver#3483]
**Describe the bug**
When playing the steam port of Quaver offline, every time a song is played an error comes up saying "Score could not be submitted! Trying again soon." or something similar. After enough of these, when selecting a new song the screen will not load and the game seems to freeze, needing to be rebooted from the steam client.

**To Reproduce**
1. Put steam into offline mode and run quaver
2. Play around 20 songs (sometimes more, sometimes less)
3. Eventually your client crashes.

**Expected behavior**
I expected there to be a way to turn off score submissions to stop it crashing.

**Desktop (please complete the following information):**
 - OS: Mac OS X (Big Sur 11.6.5)
 - Browser: Brave Browser (am playing through steam however)
 - Version: Quaver version v0.31.0

**Additional context**
I have an older laptop so this may be an error specific to me. Sorry if that's the case, I can deal with it if there isn't a fix available.

**Comment by Swan** [comment]
@cheepling Can you send logs after you get it to crash? They're located in the logs folder in the game's directory.

**Comment by cheepling** [comment]
Will do (sorry I think we might be in different timezones)

**Comment by cheepling** [comment]
The game isn't actually crashing - it just remains on a black screen when loading a song. I booted it up just now in offline mode and the game isn't loading.

Is there a way to stop it from submitting scores when steam is offline?

**Comment by cheepling** [comment]
Did a little more testing, I can open the editor from the main menu button and use the editor. I can even use test play mode and it loads fine, but using the singleplayer song select specifically causes it to fade to black and not work.

**Comment by cheepling** [comment]
Not exactly sure what has been happening, it's worked fine over the past few days with no issues at all. Think it might be something to do with the steam integration?

In any case, it's loading fine now and the error submitting scores still comes up. Steam doesn't count the hours I play offline when I go back online, but that seems to be a steam problem.

Thanks for your time, I know you guys are really busy with this stuff. If you have any time, how does the chart reading system work?

**Comment by cheepling** [comment]
Sorry to reopen this again, I worked it out after a few trials.
If you boot up steam in online mode and then take your computer offline without shutting steam down, it's still able to be played normally.
However, when booting it up in offline mode you cannot play single player (and presumably multiplayer).
In both cases it doesn't change hours and ranking, although scores will still appear on your local leaderboards.
Is it possible to detect if Quaver is offline and cache scores into an online folder, then submit them when online again?

**Comment by Swan** [comment]
Please provide logs after crashing, so I can investigate.

And no, if you're offline while playing they cannot be submitted once you go online.

**Comment by cheepling** [comment]
It doesn't crash, but the screen fades to black and it becomes unresponsive to all inputs.
Previously when online I have been able to pause and leave map without being able to see, but there aren't any keysounds or visible icons when attempting offline.
Is it possible that it's attempting to sync data or use a dependency online before starting the map which is causing it to crash when unavailable?

Due to having to manually reboot the game by either force quitting or stopping through steam there aren't any crash logs, although it's possible they've been overwritten when steam syncs my files. I can't access Quaver at the moment but when I can I'll send through the existing logs after crashing.

It's also worth mentioning that my laptop has had issues with dependencies before (being a mac without arch64 architecture, but also being unable to run 32bit dependencies). This has caused issues with compiling, so it's possible that this is specific to me. If this can't be reproduced I can probably backdate my OS to support them.
