### ISSUE TITLE
Export to different formats

### ISSUE THREAD

**Issue by cheepling** [Quaver/Quaver#3484]
**Is your feature request related to a problem? Please describe.**
I want to share my replays with friends who don't have Quaver, but they can't read the replay files. 

**Describe the solution you'd like**
It would be most convenient to export to an mp4, but I understand how difficult this is. 

**Describe alternatives you've considered**
If you can create a replay format to export to that can be converted to other formats. .qr files can't be converted to other formats to my knowledge.

Is it possible to write a plugin that allows this exporting? I'd be happy to work on it in my own time if I knew how to get started.

**Comment by IceDynamix** [comment]
if you'd like a video to share please go ahead and use OBS or any other screen recording software to record your replay

other than that, there are no viable means of converting a replay to a video, both as an existing solution as well as to implement
