### ISSUE TITLE
Quaver can't submmit scores, fetch/download beatmaps and steam overlay browser redirecting to firefox

### ISSUE THREAD

**Issue by stationaryStation** [Quaver/Quaver#3485]
**Describe the bug**
Quaver can't submit scores to the servers, fetch and download beatmaps from the internet, fetch the latest news and chat messages don't appear. Also the Steam Overlay is not showing up when I click on "View Profile"

**To Reproduce**
1. Install Quaver from Steam
2. Profit

**Expected behavior**
Fetch/Download beatmaps from the internet and submit scores

**Proof**

https://user-images.githubusercontent.com/81704775/171298895-db736ea4-5f68-4268-b089-980896e1a17a.mp4

**Desktop (please complete the following information):**
 - OS: Fedora 36 (Running Gnome 42.1 w/ Wayland)
 - Browser: Firefox 100.0.2 Stable
 - SteamAPI Version: v020

**Comment by stationaryStation** [comment]
It might be an issue with my steam installation but I will leave this issue open just in case

**Comment by stationaryStation** [comment]
> When you say you can't download beatmaps from the internet, do you mean through the quaver app or the quaver site?
> 
> The browser default thing would definitely be a steam issue, and the can't submit score problem would probably be due to offline mode, I had a similar problem.

Through the quaver app, and yes, it was indeed a steam issue. I installed steam through flatpak and it seemed to fix the issue.

Also my native steam app reports that it is online but the overlay doesn't even appear when using shift+tab.

**Comment by cheepling** [comment]
So were all the problems fixed by reinstalling steam or are there still issues?
(Sorry for late response time)

**Comment by TheGloriousDuck** [comment]
I also cannot download any beatmaps on Windows 10. no other problems in this issue are apparent to me though

**Comment by cheepling** [comment]
@TheGloriousDuck is this through the site, the app or both?
Also have you tried putting a beatmap file in your songs folder to see if it's just an issue with loading?

**Comment by TheGloriousDuck** [comment]
**FIX (i guess?):** This line of code inside the file `APIRequestMapsetSearch.cs` fixes the issue. This may cause other problems though, I'm not sure.
`System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;`
