### ISSUE TITLE
Uploading Mapset Issue

### ISSUE THREAD

**Issue by ThePieSkyHigh** [Quaver/Quaver#3487]
**Describe the bug**
Will not let me upload my mapset, this is very frustrating as it thinks I'm trying to "Update a non-existent" map.

**To Reproduce**
Upload a Map
Make a change to the metadata after you've uploaded it
Re-Upload (Update)
Delete the song through the quaver site
Try to upload the song again through the Song Editor (should give you the error)

**Expected behavior**
The editor will no longer allow you to "update" the map as it doesn't exist.

**Screenshots**
![image](https://user-images.githubusercontent.com/92952875/172072104-22191bd2-2ae2-4f98-b28c-e0036dff8e9a.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Opera GX]

I deleted my first map as it contained a typo, seeing as the typo was not fixed after editing the metadata for the song.
The plan was to delete the first version, and re-upload the new, typo-less one. Gives error above ^

**Comment by Reihynn** [comment]
go to the .qua file of the map and change the map id and the mapset id to -1

**Comment by ThePieSkyHigh** [comment]
> go to the .qua file of the map and change the map id and the mapset id to -1

I have 3 difficulties, which one do I open?
I'm guessing you meant "Open with Notepad" and "change the map & mapset id to have -1 value" (e.g. 587235 -1 = 587234)
Didn't work either way, ended up saying "You are not the creator of this mapset!" so I had to revert it, only to get the same error

**Comment by Reihynn** [comment]
you're supposed to change it to "-1" and do it on all difficulties

**Comment by ThePieSkyHigh** [comment]
Ah I see, weird

Well, it worked! Problem now is the banner won't display on the site? Will that load in or is that related

**Comment by Reihynn** [comment]
no idea but banner just refuses to display sometimes so its probably not something you have control of

**Comment by ThePieSkyHigh** [comment]
Got it, thank you so much. It's hard to find help regarding these things.
