### ISSUE TITLE
Random position for all notes in each round.

### ISSUE THREAD

**Issue by YagaoDirac** [Quaver/Quaver#3490]
I'm from O2jam, so you probably already knew what I was looking for. I believe this feature is already implemented, but I didn't find it.
So, anybody help? Where's the lovely random button? Thanks.

**Comment by Illuminati-CRAZ** [comment]
The random mod is accessible from the mods panel, which you can bring up by pressing the modifiers button at the bottom of the screen in song select, or you can bring the mods panel up by pressing F1.
