### ISSUE TITLE
Unable to receive RestClient request bodies

### ISSUE THREAD

**Issue by TheGloriousDuck** [Quaver/Quaver#3491]
**Issues**
1. News fails to load (Not sure where it is supposed to be though, because this has been an issue since the first time I started playing.)
2. Global chat messages do not work
3. Download menu search doesn't work 
4. Unable to download any map I don't have in multiplayer

**Expected behavior**
All 3 issues to work/load.

**Desktop:**
 - OS: Windows 10 21H2 (19044.1706)
 - Version: Not sure, latest one as of the time of making

**Potential Fix**

After a bit of troubleshooting with the help of @AiAe, I tried logging the RestClient response HttpStatusCode and it came up as 0. After googling around I found the solution [here on StackOverflow](https://stackoverflow.com/a/51678282). 

`System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;`

I only put this line of code before the download menu search request and I was able to search for maps and download them. However, I assume it should be added before any requests are made, when the game is starting up, and that may fix the other issues as well. The issue here seems to be that when certain RestClient GET requests are sent, it is not using the correct TLS level or something? Not exactly sure.

**Comment by Swan** [comment]
This is an issue with your system. It's supposed to use whatever the default is, so you're going to have to fix that on your end. Can't accept the PR either.
