### ISSUE TITLE
all my song dissapeared when i made a playlist

### ISSUE THREAD

**Issue by amiano711u** [Quaver/Quaver#3493]
**Describe the bug**
i was going to make a playlist for the tricky fnf songs but then when i did all of my songs dissapeared 

**To Reproduce**
1. Go to song "select"
2. Click on 'create new playlist and make one'
3. Scroll down to 'see all of your songs fucking missing'

**Expected behavior**
all of the songs that you own will go poof

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by nonameorous** [comment]
switch from playlists to songs 🤦‍♂️

**Comment by makaiiart** [comment]
![Quaver_4KuNYQUC69](https://user-images.githubusercontent.com/53101675/172985659-415d26f9-7ef7-4040-8425-b4f495c337f5.png)
