### ISSUE TITLE
Song keeps playing when entering maps download page before it started

### ISSUE THREAD

**Issue by not-nef** [Quaver/Quaver#3494]
If you enter the map download menu before the background song started (when starting the game), the song will keep playing (and overlap with the song preview of maps) until you go back to the map selection

**To Reproduce**

1. Open the game
2. Immediately go to the download maps page before the bg song starts playing (important)
3. Song will start to play and wont stop when listening to the song previews

**Expected behavior**

Song will not start

I am on Windows 11

https://user-images.githubusercontent.com/83908932/173130707-adaa3d5b-ab7a-4f52-b994-dd10d7f8a28b.mp4

(i am terribly sorry for the quality my pc is too bad)

**Comment by Illuminati-CRAZ** [comment]
I can't reproduce this, probably related to performance? Seems similar to #3293.

**Comment by not-nef** [comment]
Its also not laggy at all when im not recording so i dont think its performance related

**Comment by Illuminati-CRAZ** [comment]
Tried it a few more times, still can't reproduce it, maybe someone else will be able to

**Comment by not-nef** [comment]
If i think about it, it could be performance related, because for you, the song maybe starts, before you can enter the menu (if you have a good pc). But even then, its still a bug, just more likely to appear for low-end machines (if this is the case)
