### ISSUE TITLE
Add extra time when playtesting from start in the editor

### ISSUE THREAD

**Issue by not-nef** [Quaver/Quaver#3496]

**Comment by Swan** [comment]
Just go to the start and play test it....

**Comment by not-nef** [comment]
> Just go to the start and play test it....

that will put me directly into it, which gives me like 0 reaction time u understand?

**Comment by Swan** [comment]
Alright. Instead there can be some extra time added before the play test starts rather than a new button

**Comment by not-nef** [comment]
thanks a lot

**Comment by not-nef** [comment]
A hotkey would also be completely fine, dont need a button tbh
