### ISSUE TITLE
Cannot find other songs database even when manually pointing it to the Directory

### ISSUE THREAD

**Issue by VB304** [Quaver/Quaver#3500]
**Describe the bug**
With some of the existing "won't import osu songs" and somewhat similar. No matter how much reinstallation I do to the game, It just can't find the song database. I changed quaver.cfg file to point to the directory but every time I relaunch it would clear the directory and just report can't find the song database

**To Reproduce**
I don't even know how this happened, I didn't change the game's directory. Just reinstalled and then poof, broken. Please comment to gather more information from me as I don't know why did this even happen, I might just be an idiot.

**Expected behavior**
Detecting osu's song database

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2 19044.1741
 - Browser Chrome
 - Version 102.0.5005.63

**Additional context**
It worked before but very and I mean VERY slow startup because of the sheer amount of mania maps I had, I didn't play the game for a while and increased it's number of beatmaps so that might be one of the reasons

**Comment by IceDynamix** [comment]
in your osu directory, drag and drop the osu!.db file into the quaver window

**Comment by VB304** [comment]
> in your osu directory, drag and drop the osu!.db file into the quaver window

Thank you so much, just as you said it immediately found the songs after being detected and relaunching the game. Is this found on the wiki? I couldn't find any info about it but thanks so much though, solved my problem in an instant

**Comment by Azaleas0** [comment]
> in your osu directory, drag and drop the osu!.db file into the quaver window

i got the exact same problem i've tried everything i can think of and i've tried what you suggested and it keeps sayingthat it can't find the database despite osu being in it's default location and the quaver cfg directed at the database, i am using osu stable for this too

**Comment by 7ef38c** [comment]
Check #4407 - osu pushed a change a couple days ago breaking our db reader

**Comment by Azaleas0** [comment]
> Check #4407 - osu pushed a change a couple days ago breaking our db reader

ah alr, thank you
