### ISSUE TITLE
uploading mapset - mapset contains invalid file type

### ISSUE THREAD

**Issue by Kokorune** [Quaver/Quaver#3501]
it's literally just the audio file and the qua file what, i don't see anything invalid there. i even removed the backrounds

**Comment by IceDynamix** [comment]
your mp3 file is probably a scuffed one. chances are you downloaded using a youtube downloader website or something, in that case it's possibl3 your mp3 is just going to be a mp4 in disguise (yes that's a thing) so run it through ffmpeg if you know how to or try to find another audio source
