### ISSUE TITLE
Speed selection formula correction.

### ISSUE THREAD

**Issue by YagaoDirac** [Quaver/Quaver#3509]
**Is your feature request related to a problem? Please describe.**
I personally would say this is an error. I appreciate that you have made the play speed adjustment feature. It's way easier to find something to practice with.
The only issue is that, the formula is too simplified.
![image](https://user-images.githubusercontent.com/16892000/173554472-f63aa1b4-a4da-4c20-8e13-7632279a2577.png)
The formula should be:
RATIO = pow(1, (1/12.0))
result = pow(RATIO, adjustment_as_int)
For the case in the print screen, the adjustment_as_int is -6, the result should slightly greater than 0.7. Not a good example.
float and double both do the job, or even float16.

**Describe the solution you'd like**
Please replace the formula with 
RATIO = pow(1, (1/12.0))
result = pow(RATIO, adjustment_as_int)

**Describe alternatives you've considered**
Idk. I only have one solution at this moment.

**Additional context**
The formula is from real music theory, not from any video game. I believe people have trained the hearing would prefer this tiny change a lot. Sorry for my poor English, I can't explain it.

**Comment by Swan** [comment]
No thanks. We're trying to keep it simple here.
