### ISSUE TITLE
Failed to Submit Score 

### ISSUE THREAD

**Issue by Puumpkin** [Quaver/Quaver#3510]
**Describe the bug**
I was just playing, then suddenly after completing a map I got a notification saying failed to submit scores. I found it odd, kept playing and none of my scores are being submitted. Eventually, new scores could be submitted, but my old ones never appeared.

**Expected behavior**
Old scores be submitted.

**Screenshots**
https://imgur.com/a/J6wjT3B

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox

**Comment by Swan** [comment]
This was during downtime. Should be fixed now.

**Comment by Puumpkin** [comment]
All scores that failed to submit during the downtime still aren't submitted

**Comment by IceDynamix** [comment]
score will only try to resubmit as long as you keep the game open, if you closed the game at any point then they're gone
