### ISSUE TITLE
Getting a tone of errors

### ISSUE THREAD

**Issue by ASPMint** [Quaver/Quaver#3523]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by AiAe** [comment]
Please give us more information, upload your runtime and network logs in the game directory > Logs

**Comment by ASPMint** [comment]
> Please give us more information, upload your runtime and network logs in the game directory > Logs

i accedently pressed enter but i figured it out and fixed it

**Comment by AiAe** [comment]
> > Please give us more information, upload your runtime and network logs in the game directory > Logs
> 
> i accedently pressed enter but i figured it out and fixed it

Would be good to know what exactly the issue was, so we can fix it

**Comment by Swan** [comment]
Closing. Open the issue back up w/ more info
