### ISSUE TITLE
Changing volume with the knob of a kb makes the mapsets disappear

### ISSUE THREAD

**Issue by EliteDreamer** [Quaver/Quaver#353]
Using the knob of my kb to change the volume of windows makes the mapsets disappear.
The direction in wich the knob rolls doesn't matter.

1. Go to single player;
2. Roll your knob;
3. Mapsets disappear.

Expected behavior:
Just an increase in volume.

![image](https://user-images.githubusercontent.com/46053396/50387339-baac7b00-06f9-11e9-922e-5f919db57d5f.png)

 - OS: w10;
 -Always the same version of the game.

Additional context:
My kb is a logitech orion g610 brown.
I think this bug is caused becouse the game takes as imput for writing the knob (doesn't with the other special inputs like skip, go back and pause)
Yep it's pretty much it

**Comment by Sublimity** [comment]
I think you are correct about the knob being taken as an input, seeming its a logitech keyboard, the knob might be bindable, check your logitech settings.

**Comment by EliteDreamer** [comment]
Nop can't find anything about a bindable knob
