### ISSUE TITLE
List of minor and less frequent bugs

### ISSUE THREAD

**Issue by Mattkk04** [Quaver/Quaver#3540]
when I type numbers in the plugin menus SOMETIMES the game places notes in their respective columns ignoring the plugin dialog.

when I quit a multiplayer lobby and rapidly get in song selection me after starting the game i get bumped in the previous multi lobby again.

when changing default system audio device quaver completly bugs.

downloading a mapset from the steam in-game browser is now not possible (error -302)

**Comment by Swan** [comment]
One issue per bug please.
