### ISSUE TITLE
bugs with Audio Output Device feature in newest update

### ISSUE THREAD

**Issue by Notempo** [Quaver/Quaver#3548]
**Describe the bug**
Audio "glitchy" when switching audio output devices using the new feature

**To Reproduce**
1. Go to Audio in Options
2. Click on Audio Output Device
3. Change your audio output device
4. Hear error

**Expected behavior**
Being able to listen to music and hitsounds with no delays, clipping, or even silence (in-game, music and hitsounds are split)

**Desktop (please complete the following information):**
 - OS: Windows 10 & Manjaro Linux

**Comment by Swan** [comment]
@Notempo Does it work when you set a new audio device and restart the game? Or is it only after changing?

**Comment by Notempo** [comment]
@Swan I'm not quite sure actually, but reloading the skin fixes it for that session. Relaunching the game without changing anymore settings causes music to play but not hitsounds. Weird, have to look more into it.

**Comment by Notempo** [comment]
This was fixed in another update; resolving.
