### ISSUE TITLE
Long Notes

### ISSUE THREAD

**Issue by PytRessark** [Quaver/Quaver#356]
**Describe the bug**
You don't have to let go of long notes.

**To Reproduce**
Hold a long note and keep holding after it ends.

**Expected behavior**
It would be better to give the player a miss so that *person* knows he did something wrong.

**Additional context**
I know that it already drains your hp and gives you a bad rating but the combo doesn't break so 
you can't really "feel" the mistake on harder maps.

**Comment by Sublimity** [comment]
This isn't specifically a bug, holding long notes after they have finished work correctly by giving the user an **okay** judgement, I think making them award the user with a miss for holding the LN after it has ended is a bit much. Maybe with a stricter judgement position in your skin can achieve this.
