### ISSUE TITLE
Game Freezes everytime I place a note in the chart editor (Windows 10)

### ISSUE THREAD

**Issue by fishfries** [Quaver/Quaver#3565]
**Describe the bug**
Everytime I place a note in the chart editor it laggs, eventhough I get arround 120 while playing. I've tried changing resolution, optimization, closing all my application in the background, changing the fps limiter. This is happening recently, but before this was happening it was working perfectly fine and I had average fps.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Google
 - Version 10

**Comment by chirijidev** [comment]
Maybe try doing this again and provide your runtime.logs file from your Logs folder in Quaver.

**Comment by fishfries** [comment]
[runtime.log](https://github.com/Quaver/Quaver/files/9125815/runtime.log)

**Comment by fishfries** [comment]
> Maybe try doing this again and provide your runtime.logs file from your Logs folder in Quaver.

yeah sorry, new to this
