### ISSUE TITLE
No Miss mod failing to automatically retry on a miss

### ISSUE THREAD

**Issue by sSolle** [Quaver/Quaver#3567]
**Describe the bug**
Sometimes, seemingly very rarely as this has only happened once to me so far, the No Miss mod doesn't properly make you fail upon missing. In the video I am using a custom judgement where anything below perfect is a combo break. I get a "good" hit but it doesn't reset me, instead seeming to deplete all of my health but somehow not counting it as a fail. At the end of the video it correctly resets me upon missing another note.

**To Reproduce**
Unknown

**Expected behavior**
Automatic retry upon missing

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 0.32.2

**Additional context**
none

https://user-images.githubusercontent.com/101608016/179601794-473d14c3-8133-4f40-b0f1-f41f78e74ad1.mp4

**Comment by Swan** [comment]
Fixed in #3568
