### ISSUE TITLE
Main menu music player overlaps songs

### ISSUE THREAD

**Issue by Jolomann** [Quaver/Quaver#357]
**Describe the bug**
The music player in the main menu has keyboard shortcuts which are very useful, but when spammed the songs start overlapping and it results in earrape. The songs continue no matter what you do so you have to restart the game to get things under control.

Here's a clip of it
https://streamable.com/26j0r

**To Reproduce**
1. Spam Z X C V while on main menu
2. Enjoy

**Expected behavior**
One song should play at a time

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Hydrofurious** [comment]
This also works in map select, by spamming right- and left arrow keys
