### ISSUE TITLE
Remove battle royale settings

### ISSUE THREAD

**Issue by QiuFeng54321** [Quaver/Quaver#3570]
**Describe the bug**
You can still find settings of it 

**To Reproduce**
Find them in Options -> Gameplay -> Multiplayer

**Expected behavior**
Options removed since Battle Royale is removed

**Screenshots**
![Screen Shot 2022-07-20 at 8 59 09 AM](https://user-images.githubusercontent.com/32996262/179873004-575a0e5f-97dc-4aae-aa11-345911c1ede1.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Version 07.19.2022

**Comment by Illuminati-CRAZ** [comment]
Fixed with #3617
