### ISSUE TITLE
Allow 1 player to start a multiplayer game.

### ISSUE THREAD

**Issue by YagaoDirac** [Quaver/Quaver#3571]
**Is your feature request related to a problem? Please describe.**
The rule of at least 2 players to start a multiplayer game force people to wait before there is a second guy, which prevent people from trying multiplayer mode.

**Describe the solution you'd like**
1 player case should work the same as a plain single player game which doesn't send anything to server. It's similar to a purely waiting while playing solo. When a second player comes, notice the host with a ui anything. This makes it easier for people to host a 1guy game room longer.

**Describe alternatives you've considered**
Or you can make invitation system which is way harder than let people wait while playing.

**Additional context**
Then you don't need the auto host rooms, which select random songs and wait super long before start games.

**Comment by IceDynamix** [comment]
> The rule of at least 2 players to start a multiplayer game force people to wait before there is a second guy, which prevent people from trying multiplayer mode.
you can already start multiplayer games when you're alone

> 1 player case should work the same as a plain single player game which doesn't send anything to server. It's similar to a purely waiting while playing solo. When a second player comes, notice the host with a ui anything. This makes it easier for people to host a 1guy game room longer.
as mentioned, this is already a thing

> Or you can make invitation system which is way harder than let people wait while playing.
you can already invite people to your multiplayer room

> Then you don't need the auto host rooms, which select random songs and wait super long before start games.
?
