### ISSUE TITLE
Better rating filter in map download.

### ISSUE THREAD

**Issue by 5h1zuy4** [Quaver/Quaver#3574]
The min rating filter should only filter out maps when its hardest difficulty is still lower than the min rating, and vise versa for max rating filter.
Currently, if there is a map with diff spread of 5-30, it won't show up when the min rating is set to 10, or when the max rating is set to 20. However, it should appear in both since there are difficulties in the mapset that satisfies this condition.

**Comment by Swan** [comment]
Already tracking this elsewhere, so gonna close
