### ISSUE TITLE
When I tried uploading my map it said invalid file type and I restarted quaver and now I can't open it at all

### ISSUE THREAD

**Issue by NoisyCaptain512** [Quaver/Quaver#3579]
A made a mapset on quaver. and then when I got finished I uploaded it it said invalid file type something like that. And now I can't even open it at all and it says this error.
![image_2022-07-30_032953715](https://user-images.githubusercontent.com/92732863/181880026-dcaa2325-90ac-4af1-b12f-73ef17379d29.png)

**Comment by NoisyCaptain512** [comment]
i did get it to open but im having this issue now
![image_2022-07-30_034611817](https://user-images.githubusercontent.com/92732863/181880518-0e22ffbc-63ec-462f-b150-8b6e998a76fc.png)

**Comment by Swan** [comment]
You need to change the mp3 file your map is using. It isn't a proper mp3 file, so the server is rejecting it. This can happen if you've used a youtube to mp3 downloader.
