### ISSUE TITLE
[Editor] Certain panels appear above top bar menus on canary build

### ISSUE THREAD

**Issue by Jolomann** [Quaver/Quaver#3582]
**Describe the bug**
Some panels appear above top bar menus even though the top bar menus should always be on top
EDIT: Confirmed to be caused by showing gameplay preview by Storn

Panels wth the issue
- Details
- Composition tools
- Hitsounds

Ironically, the 'layers' panel doesn't have this layering issue.

Only present on canary and not stable.

**To Reproduce**
1. Use canary build (v7.19.2022)
2. Go into editor
3. Enable gameplay preview
4. Top bars will now appear below panels

**Expected behavior**
Top bar menu always on top

**Screenshots**
![](https://cdn.discordapp.com/attachments/461621899320098816/1003369602203525180/unknown.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Quaver v7.19.2022 (Canary)

**Comment by Storn42** [comment]
Seems to be related to displaying gameplay preview

https://user-images.githubusercontent.com/68167130/182041200-5d517eba-915a-49a9-8149-13656bc467cf.mp4

**Comment by Illuminati-CRAZ** [comment]
I'm guessing this has the same cause as the one for #3583

**Comment by Swan** [comment]
Fixed
