### ISSUE TITLE
Add a prompt in song selection panel to prompt which songs other players can not download.

### ISSUE THREAD

**Issue by YagaoDirac** [Quaver/Quaver#3585]
Or if it's possible to ensure all the songs can be downloaded by all the players.
Or at least a tiny prompt, then people can avoid these songs.

**Comment by Swan** [comment]
There's a badge on the maps which say if it's unsubmitted or not.

**Comment by IceDynamix** [comment]
You can use the search filter "status!=notsubmitted" or "s!=n" for short
