### ISSUE TITLE
Show the main mod on entries in multiplayer game list.

### ISSUE THREAD

**Issue by YagaoDirac** [Quaver/Quaver#3586]
All the long notes related mods, inv, fln, should also be shown on game entries. Since they are too drastic. Especially 7k inv.

**Comment by Swan** [comment]
Not sure what this means.

**Comment by IceDynamix** [comment]
I think they mean that LN heavy maps or maps with inverse patterns specifically should be labeled as such in song select

**Comment by Swan** [comment]
Closing since the author provided no clarification.
