### ISSUE TITLE
Combo achievements not given on map fail

### ISSUE THREAD

**Issue by AidanHsiao** [Quaver/Quaver#3589]
I'm assuming that Steam achievements are given when a map is completed; however, they are not given when the map is failed, even when the initial conditions are met.

1. Go to a map with a combo higher than an achievement (I used the Camellia feat. Nanahira marathon)
2. Play it until you have the desired combo
3. Fail

I should be given the achievement on Steam. Even Quaver's own site recognizes that I have over 7000 combo, but the achievement is still not there.

![image](https://user-images.githubusercontent.com/49498006/182895544-b271edec-e89c-44d9-86b9-207243e0767f.png)
![image](https://user-images.githubusercontent.com/49498006/182895599-410aa546-d7db-414e-a7e4-1195a540b6e8.png)
Even though the site says I have over 7000 combo, I don't have the achievement on Steam or Quaver's official site. My username is Sweetplum123 and my profile URL is https://quavergame.com/user/Sweetplum123.

 - OS: Windows 10 (should not be important)
 - Quaver Version 0.32.2

Sorry if this came off as a little needy, I'm not great at wording things. I don't really care about the fact that I didn't get the achievement, I just figured I'd send in a bug report because I think it IS a bug (and if it isn't, then the achievement should have a clause about needing to pass the map).

Thank you for your time.

**Comment by Swan** [comment]
It's not a bug. You need to pass in order to gain achievements.

**Comment by AidanHsiao** [comment]
gotcha, thanks for the clarification.
