### ISSUE TITLE
Occasional Lag Spikes During Gameplay

### ISSUE THREAD

**Issue by Abriel14** [Quaver/Quaver#359]
**Describe the bug**
When playing I have tiny freezes that are enough to offsync a song when playing. I think that the note rendering is freezing while the music keeps playing.

**Expected behavior**
There shoudn't have freezes and if there were to have some, they should be for everything and note only with the render.

**Config:**
 - OS: W10

**Additional context**
 tried to cap the fps value because those freezes also happen with unlimited fps but nothin changes.

**Comment by EliteDreamer** [comment]
This happened to me when retryng a map via the key (and maybe scrolling up/down affects it) but just for the first note then it's all fine. Couldn't test it more

**Comment by YaLTeR** [comment]
@Swan I think this is fixed, at least the offset part? If this is still used to track the lag spikes part then it's better to rename the issue.

**Comment by Swan** [comment]
Timing issues are fixed. I've renamed it.
