### ISSUE TITLE
Display 4k in 7k-like mode.

### ISSUE THREAD

**Issue by YagaoDirac** [Quaver/Quaver#3591]
**Is your feature request related to a problem? Please describe.**
4k' display is too wide. I play 7k more and I prefer a limited 7k display to be compatible 4k maps. 

**Describe the solution you'd like**
Simply display 4k map in 7k canvas. Also, some players play 7k with spacebar but 4k without spacebar. They maybe want a blank slot in between. This should be an option entry.

**Describe alternatives you've considered**
Adjustment of the width of 4k canvas. Or also for 7k.
Or also a somewhat customized border surrounding the slots.

**Comment by chirijidev** [comment]
This can be manipulated with the use of skinning. If you need help, please come over to skinning channel in Quaver Discord. Thank you.
