### ISSUE TITLE
Loading takes too much time

### ISSUE THREAD

**Issue by foxy1459** [Quaver/Quaver#3592]
When I open the game, it always takes almost 10 minutes to load , and this is mainly due to detecting maps from other games (there are more than 20000 maps in my OSU! ). 
The game seems to detect all the maps from other games each time automatically once being open. So is it possible to improve the speed of loading maps from other games, or simply add an option to stop loading maps while launching (without turning off the detecting option)?
![Snipaste_2022-08-11_12-10-41](https://user-images.githubusercontent.com/85992790/184063553-73a05488-c096-42e1-981a-e798f114fff0.png)

**Comment by Swan** [comment]
@foxy1459 Can you attach logs, so we can see where it's hanging at?

**Comment by foxy1459** [comment]
> @foxy1459 Can you attach logs, so we can see where it's hanging at?

[runtime.log](https://github.com/Quaver/Quaver/files/9313407/runtime.log)
This is the logs when the game have completed updating maps from other games before launching, but it still takes 2 minutes to load
