### ISSUE TITLE
Playlist/BeatmapPack import

### ISSUE THREAD

**Issue by pixelguy126** [Quaver/Quaver#3594]
**Is your feature request related to a problem? Please describe.**
downloading playlist and all that is kind off annoying most of the time especially when you need to download every beatmap one by one then import them also one by one

**Describe the solution you'd like**
best solution is to have playlists accessible in the in-game beatmap downloader.

**Describe alternatives you've considered**
i think that beeing able to download a zip file containing the playlists beatmap would be fine.

**Additional context**
re work the beatmap in game downloader pls.

**Comment by Zumoo** [comment]
There already is a way to install playlists. You can download an entire uploaded playlist in one click off of the website, and then drag and drop the file in game.

**Comment by pixelguy126** [comment]
the only thing that appears in the website is the import button. which imports the playlist but skips beatmaps that arent downloaded locally.
