### ISSUE TITLE
User Rating Maps

### ISSUE THREAD

**Issue by EpiCreeper** [Quaver/Quaver#3597]
The Problem:
There are a lot of good unranked maps people cant enjoy because of the amount of bad maps out there, and with all respect to the ranking supervisors, the ranking queue is pretty slow. it takes 4 months for your map just to get checked by the rs' and there is a chance you will have to submit it again if you have to fix too much.

My Solution:
Add a "Rate" button next to maps you played and in the end screen after you beat a map. It should be pretty easy to press, because no one would actually use that feature if you have to go to the site to do it or something. After that you will be able to rate the map.
I thought of three rate systems that could work:
- Like And Dislike: Its pretty simple, but could work well. Though, I do think its too limiting.
- Five Stars: You just say how much you like the map out of 5. It allows you to rate really accurately, but some people might rate maps differently than others.
- 😠 😐 😃 : (my personal favorite) you will be able to chose between one of three options, represented by faces and descriptions underneath each face - 😠 Bad Map, 😐 The charting is a bit flawed, 😃 Good map, well charted. This method will give pretty accurate results while letting players understand what each rating means and avoiding confusion.

After enough scores are submitted, you will be able to see what people think of the unranked maps and enjoy more well charted maps. This will also help the ranking queue since mapsets with better ratings will be checked by the ranking team sooner.

Stuff I think you should add in edition to just rating to make it better:
- Being able to search by most liked and disliked maps.
- The ability to search by Unrated maps.
- Rating ranked maps as well, but for originality instead well chartedness (if thats a word).
- Showing the rating in the download maps and downloaded maps sections.

Although I didnt see anyone with a similar idea in the page, it is a pretty obvious idea, so I wont be surprised if there is a reason for this feature not being implemented yet. Despite that, it is an idea I would be happy to see in the game.

**Comment by Zumoo** [comment]
I understand the idea here, but with all due respect people will just vote randomly. There's a high chance that someone will just rate randomly instead of honestly, and the entire system will get messed up quickly.

Good concept, but the community will trash it

**Comment by EpiCreeper** [comment]
sorry I am new to git

**Comment by EpiCreeper** [comment]
> I understand the idea here, but with all due respect people will just vote randomly. There's a high chance that someone will just rate randomly instead of honestly, and the entire system will get messed up quickly.
> 
> Good concept, but the community will trash it

I think its still worth a shot. Im sure will like some bad maps because its a song they like or its a funny map or something, but I think that will at least give you a more clear indication of what are the better maps (not perfect, but more clear). And I think that for every person that votes inaccurately on a bad map, there will be another person that rates it as bad. I think that way most of the actually good maps will be at the top and the bad ones could stay at the middle or lower. its like with steam reviews when you know a game is bad if it has mixed results, even if its just 50 50.
