### ISSUE TITLE
Quaver will try to launch and fail.

### ISSUE THREAD

**Issue by megaman15** [Quaver/Quaver#3605]
**Describe the bug**
I have tried to launch quaver over the past two weeks and out of the many, many attempts have managed to open it three times. i have tried to open it at least 10 to 20 maybe even 30 time a day. i have even when looking in the local files and tried to launch the executable to have no success. I even tried launching the executable as an administrator in case something on my system was keeping it restricted. Nothing i tried has worked and it has pretty much just been a big pile of luck and frustration knowing my computer more than meets the minimum requirements and for some odd reason won't launch for a reason that can't be found.

**To Reproduce**
1. Go to steam
2. launch Quaver
3. fail
4. try again for like 50 attempts
5. succeed once
6. have it fail the very next time

**Expected behavior**
when hitting play, it should launch automatically

**Desktop (please complete the following information):**
 - OS: windows 11 home version 10.0.22000 Build 22000
 - Browser: steam launcher
 - Version : beta version as of 8/20/2022

**Additional context**
i have checked everything related to steam to no avail. i have also updated all drivers to their current release. i even made sure  that my system requirement were met to the best they can be. i really want this fixed as i really enjoy this game.

**Comment by Kizuna-dev** [comment]
Can you provide your runtime.log when your game doesn't launch ?

**Comment by megaman15** [comment]
I would but it seems to have suddenly started working properly. i did have issues with steam that made me have to uninstall then reinstall. that is about when it began. When i would try it would launch and steam would show the stop button but nothing would happen. then it flashed back to saying play. so maybe it was an error in steam seeing as they followed each other.
