### ISSUE TITLE
Mouse Bug move to up right corner when i launch the game 

### ISSUE THREAD

**Issue by Chimer51** [Quaver/Quaver#3621]
All is in the tittle

**Comment by Chimer51** [comment]
It move non stop, so i can't modify the song for exemple, or i have to alttab to another windows then doubble click on modifier(or other thing) then alt tab  modify the speed etc... i hope you understand what i mean.

**Comment by IceDynamix** [comment]
Do you have a controller or a tablet connected to your PC? Maybe any other peripherals?

**Comment by Chimer51** [comment]
Omg i'm dumb thx ^^
