### ISSUE TITLE
Unable to filter in download songs for songs with at least one difficulty between x and y

### ISSUE THREAD

**Issue by YuJin44** [Quaver/Quaver#3623]
**Describe the bug**
So basically I want to find new songs for me and let's say I am playing on difficulty 3.
Songs have multiple difficulties, let's say there is a song with multiple modes (like, beginner, easy and hard and so on). One song has let's say difficulty of 1, 2, 3, 6 and 7. Now I want to find that song. I actually don't care what other difficulty it has as long as there is a difficulty around 3, so this example song would be just perfect for me (difficulty wise). But the thing is I can't adjust the filter so that it shows me that song among other similar songs. There is "min difficulty" and "max difficulty". If I set min difficulty to 2, this song will be excluded, because it's "min" difficulty is 1 (although it has a difficulty higher than 1) and if I set max difficulty to 5, this song will also be excluded again because it's "max" difficulty is 7 (although it again has a difficulty lower than 5).

**To Reproduce**
1. Go to Download Songs
2. set max difficulty to 5
3. There are no songs shown which have at least one difficulty above 5 although they do have other difficulties below 5

**Expected behavior**
songs with at least 1 difficulty below 5 should be found

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by YuJin44** [comment]
Why is this closed? The issue/request is still present from what I can tell, or did I miss something?

**Comment by WarpABoi** [comment]
Swan explains it in #dev-updates in the discord:
https://discord.com/channels/354206121386573824/630734138923810827/1138476874360705114

**Comment by Swan** [comment]
We're tracking this issue in the appropriate repo.
