### ISSUE TITLE
One or more of youir maps contains a non-uploaded map ID

### ISSUE THREAD

**Issue by Enarmonika** [Quaver/Quaver#3624]
**Describe the bug**
When this error notification appears, it's misspelled ("youir")

**To Reproduce**
1. Uplodad a mapset with a certain number of maps
2. Map another diff
3. Try to re-upload the map

**Expected behavior**
The error notification not to be misspelled 💀

**Screenshots**
![image](https://user-images.githubusercontent.com/112730536/188234088-1f2f79a6-c1e5-49eb-b126-1326c258898a.png)

**Desktop (please complete the following information):**
 - OS: [Win10 Home x64]
 - Browser [Chrome]
 - Version [104.0.5112.102 x64]

**Additional context**
Not really.

**Comment by AiAe** [comment]
Check qua file mapid make sure its set to -1 for that difficulty.

**Comment by Enarmonika** [comment]
Yeah I was talking about the misspelling. I already got around the issue.

Thanks anyway for the response, keep it up chief 👍✨
