### ISSUE TITLE
Store settings in Steam Cloud

### ISSUE THREAD

**Issue by REALalphas** [Quaver/Quaver#3625]
### **Problem.**
Basically, I often switch computers and OS. And saving settings would be a very nice feature.

### **Solution**
Sync to cloud newest settings.

### **Alternatives**
Store on your own server. (Idk why, but maybe)

### **Additional context**
Nope. = /

**Comment by AiAe** [comment]
I personally see no real reason to sync settings. 
Visual and audio offsets depend on your PC.
Skin is already coming from workshop so you just need to select it. 
The rest if the settings u rarely would change. 

And for us to split those settings to allow steam cloud would require more work than its worth i think.

**Comment by IceDynamix** [comment]
yes, there are options that are machine dependent but there are plenty of options that are not, such as keybinds or whether hitsounds are used or not. splitting them up and putting them into separate files, where only one of them is uploaded to the cloud, makes sense and is something i could see happening

**Comment by makaiiart** [comment]
> yes, there are options that are machine dependent but there are plenty of options that are not, such as keybinds or whether hitsounds are used or not. splitting them up and putting them into separate files, where only one of them is uploaded to the cloud, makes sense and is something i could see happening

Communicating this clearly to the user through a prompt on whether to overwrite settings or use steam cloud is something I could see as a problem. 

Are offsets overwritten or not? Skins? Various visual settings? New/different system on different localization for keyboard? Different display resolution breaking the skin? Different refresh rate on display? etc.

As most settings are local system dependent, it should just stay as it is, and encourage tuning it to the PC you're playing on.

**Comment by AiAe** [comment]
If we are going to do such thing, I think having another database that stores such things + move some of the current ones from quaver.db like local scores and few more would be good for cloud save.

I think this is the best solution for this, because it also resolved people losing everything once uninstalling or playing on another PC.

**Comment by REALalphas** [comment]
I think the settings that need to be saved are:

- Video => Linux => Prefer Wayland
- Gameplay => *All* (Almost)
- Input => *All*
- Misc => Login, Notifications, Effects, Song Select, Beta

**Comment by REALalphas** [comment]
Saving your settings is useful when you're at a friend's house and want to play a game with your settings without messing with others.
