### ISSUE TITLE
my offset randomly got screwed up and i cant return it back to normal

### ISSUE THREAD

**Issue by KurumiiTokisakii** [Quaver/Quaver#3636]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by KurumiiTokisakii** [comment]
update the game is completly unplayable now for me

**Comment by AiAe** [comment]
We cannot help you if you cannot explain the issue properly, maybe try to make video and send your logs (which can be found in the game directory > logs)
