### ISSUE TITLE
Constant disconnects.

### ISSUE THREAD

**Issue by JustJakeee** [Quaver/Quaver#3637]
**Describe the bug**
Every minute or so, I disconnect from the servers for seemingly no reason, and a few seconds later I'm back.

**To Reproduce**
It happens no matter what for me.

**Expected behavior**
I expect to  stay connected to the servers, since I do not have this problem with any other game.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Brave]
 - Version [0.32.0]

**Additional context**

**Comment by chirijidev** [comment]
If you still have your game open and experiencing this, please send your *network.logs* file here. It is located in your **Logs** folder in your Quaver folder so we can check what your problem is.

**Comment by SFrez** [comment]
having the same issue.
[network.log](https://github.com/Quaver/Quaver/files/9590599/network.log)

**Comment by Stateofreflex** [comment]
Also having the same problem
