### ISSUE TITLE
Add "SVs are ranked" tag for mapset creators

### ISSUE THREAD

**Issue by EpiCreeper** [Quaver/Quaver#3641]
Some maps use a very little amount of SVs just to make it cooler, even though it isn't an SV map. The skill of beating such maps isn't based on reading SVs well, so they are pretty much normal maps. but, some creators that could add SVs to make the map cooler don't do it because some people don't like SVs at all, and disabling SVs makes scores unranked, which sucks for this kind of maps.

I suggest adding a new tag for level creators called "SVs are ranked" tag. Mapset creators (not players) could turn it of if they want to add a bit of purely cosmetic SVs, and it will allow players to just turn them off, without risk of their scores becoming unranked. It will let more creators use SVs in their levels without it being annoying, and will let SV levels keep their value.

**Comment by AiAe** [comment]
So in tl;dr you want NoSV mod that does not make the scores to not submit?

**Comment by PianoLuigi** [comment]
They want editor option to choose whether the map can be played with NSV and get ranked scores or not. This would be ideal for maps where svs are not main focus and can be disabled without affecting map integrity.

**Comment by EpiCreeper** [comment]
> They want editor option to choose whether the map can be played with NSV and get ranked scores or not. This would be ideal for maps where svs are not main focus and can be disabled without affecting map integrity.

exactly

**Comment by AiAe** [comment]
For this to work as fairly as possible, would have to be new type of leaderboard in my opinion.
Because it wont be fair to have no sv and sv players in the same leaderboard. 
Then again NSV is submitting to the server and visible for Donators for looking mod leaderboard.

**Comment by EpiCreeper** [comment]
> For this to work as fairly as possible, would have to be new type of leaderboard in my opinion. Because it wont be fair to have no sv and sv players in the same leaderboard. Then again NSV is submitting to the server and visible for Donators for looking mod leaderboard.

Not all SVs were meant to add difficulty. I played maps with a slow section in the song with a slower SV, maps that just mess with timing lines or maps that use SVs to just make one or two notes feel more special. I think mappers should be able to use SVs in those cases without fear of being annoying, and I dont think you need an entirely new type of leaderboard for that to work well. Besides, if its toggleable, the mappers should have no issue with such change.
