### ISSUE TITLE
LeaderboardScoreColorEven and Odd cannot be transparent

### ISSUE THREAD

**Issue by AkiriMusic** [Quaver/Quaver#3643]
**Is your feature request related to a problem? Please describe.**

When I am in the Skin.ini and I set "LeaderboardScoreColorEven" or "LeaderboardScoreColorOdd" to NAN, it simply goes black.

**Describe the solution you'd like**

I'd like to be able to make it transparent in order to display the custom "leaderboard-panel.png" I have created for my skin.

**Additional context**

![image](https://user-images.githubusercontent.com/110740676/190952255-da3147f6-6042-43ae-ad8a-a62ef4537f21.png)
![image](https://user-images.githubusercontent.com/110740676/190952308-2051a7f4-eac5-4ad2-aa3d-cc6b2b48f984.png)

**Comment by chirijidev** [comment]
Well, the thing is, Quaver doesn't use **RGBA(Red, Green, Blue, Alpha)** function when it comes to setting a color in the skin.ini.  RGBA is not only used for setting colors, but also can specify an opacity for the color used in the values. So yeah, if you set an empty value of **LeaderboardScoreColorOdd** or **LeaderboardScoreColorEven**, the game will set it to default color instead, which is black.

**Comment by IceDynamix** [comment]
poorly worded issue, this is a feature request that *asks* for transparent colors

**Comment by Swan** [comment]
Duplicate #2993
