### ISSUE TITLE
map fps trouble

### ISSUE THREAD

**Issue by nngv** [Quaver/Quaver#3644]
when i play or watch this map in the menu, my fps downed to 10-20

1. Go to game
2. Click on single player
3. Scroll down to the bug map

https://youtu.be/rjtSfeYrjLA

 - OS: win 10
 - Browser firefox

**Comment by Reihynn** [comment]
the background causes it to lag like that
I suggest replacing the background on the song folder or just deleting it

**Comment by nonameorous** [comment]
it's because of background's resolution being high. (like 4000 pixels+) you can always just downscale it.
