### ISSUE TITLE
Lag spikes and sudden game crash.

### ISSUE THREAD

**Issue by Supbads** [Quaver/Quaver#365]
Pretty self explanatory.

I am having minor lag spikes every 5-10 seconds while in a file.
Game ver: Quaver v0.11.0
OS: Windows 10 64x
Attached logs for analyzing the crash:
[network.log](https://github.com/Quaver/Quaver/files/2707388/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/2707389/runtime.log)

**Comment by Swan** [comment]
@Supbads Can you post your PC specs?

**Comment by Supbads** [comment]
Ofcourse.
https://i.imgur.com/1WJXUr7.png

**Comment by Swan** [comment]
Duplicate of #359
