### ISSUE TITLE
Can't Launch The Game

### ISSUE THREAD

**Issue by Peremious** [Quaver/Quaver#3652]
**Describe the bug**
The game doesn't launch when pressing play on Steam. I actually had to time my screenshot shortcut key press so precisely because the game says running for such a short amount of time. I have tried the native linux version and using proton on the windows version. Same result on both.

**To Reproduce**
1. Go to 'Steam Library'
2. Click on 'Play within the Quaver game page'
3. See error

**Expected behavior**
The game should launch

**Screenshots**
![Screenshot_20220926_001654](https://user-images.githubusercontent.com/43022063/192199071-e76af929-97c4-4a5b-b7aa-b6dd0763c4df.png)
![Screenshot_20220926_001724](https://user-images.githubusercontent.com/43022063/192199082-6720309b-f70a-4cb0-89c9-6ae063425411.png)

**Desktop (please complete the following information):**
 - OS: Manjaro 5.24.6
 - Browser: Firefox
 - Version: 103.0.1 (64-bit)

**Additional context**

**Comment by AiAe** [comment]
Go to properties then Betas tab and try Canary . We deployed new build yesterday which should resolve those problems

**Comment by Peremious** [comment]
> Go to properties then Betas tab and try Canary . We deployed new build yesterday which should resolve those problems

I can confirm that upon downloading the Canary beta test version, I can now launch and play the game.
