### ISSUE TITLE
Crash in Steam version

### ISSUE THREAD

**Issue by REALalphas** [Quaver/Quaver#3654]
**Describe the bug**
When trying to run game it crashes.

**To Reproduce**
1. Start game

**Expected behavior**
Crash

**Log from terminal**
```
[alphas@pixel-2xl Quaver]$ ./Quaver
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentCulture()
   at System.String.ToLower()
   at Wobble.Logging.Logger.GetLogPath(Wobble.Logging.LogType)
   at Wobble.Logging.Logger.Initialize()
   at Quaver.Program.Run()
   at Quaver.Program.Main(System.String[])
Aborted (core dumped)
```

**Desktop (please complete the following information):**
 - OS: ArchLinux (Linux pixel-2xl 5.19.12-zen1-1-zen ZEN SMP PREEMPT_DYNAMIC)
 - Browser: Vivaldi
 - Version: Steam Build

**Additional context**
Just installed game. icu package is installed.

**Comment by REALalphas** [comment]
I fixed this problem, all because the game uses icu 68, which requires a build, and not icu 71 (latest).

**Comment by REALalphas** [comment]
Please add icu68 in linux buid because for installation you need to compile it. : /
![image](https://user-images.githubusercontent.com/26285012/201527840-dc5b094e-8050-41e5-bd07-17ea482aace0.png)

**Comment by YaLTeR** [comment]
Use the Steam Linux Runtime compatibility tool, it provides the old icu. When we finish update to dotnet 6 this will no longer be a problem.

**Comment by REALalphas** [comment]
@YaLTeR It is not native linux build. Performance will be lower.

**Comment by YaLTeR** [comment]
what?

**Comment by YaLTeR** [comment]
You're playing the same Linux-native Quaver with the same Linux-native libraries, just older version in the Steam Linux Runtime. It was made specifically for this purpose, to run games which need older libraries.

**Comment by REALalphas** [comment]
> You're playing the same Linux-native Quaver with the same Linux-native libraries, just older version in the Steam Linux Runtime. It was made specifically for this purpose, to run games which need older libraries.

Sorry I was thinking about proton :eyes:
