### ISSUE TITLE
Being able to have by default different skins chosen for each gamemode.

### ISSUE THREAD

**Issue by Nabuhra** [Quaver/Quaver#3662]
I have been playing multiple rhythm games for over 15 years and some of the ones that stuck with me had very different skins from one to another. For example O2Jam had bars by default, while Stepmania had arrows.

I wonder if it would be possible to use 2 different skins for the 2 gamemodes available, to have arrows for 4k and bars for 7k (or any other mix of choices) (or entire different skins for each other, which would be loaded when song is started)

**Comment by IceDynamix** [comment]
The skinning system was designed with using different skins for different gamemodes in mind, so the 4k and 7k sections of a skin are separated. You can take either of your skins as your base and copy over the 4k/7k folder of the other skin over to the base skin. Finally, all you need to do is to edit the skin.ini file so the 4k/7k sections contain the content from the skins you took them from.
