### ISSUE TITLE
Allow users choose their own difficulty in multiplayer

### ISSUE THREAD

**Issue by Nabuhra** [Quaver/Quaver#3665]
This feature is borrowed from other rhythm games like Smash Drums (VR) and the rhythm flash game OMGPOP had a decade ago.

Allow users to set their own difficulty on the same song:
From chart difficulty (from whatever the song has included) to filters which each adds a multiplier to score. Leave the entire option set activatable by the host, some sort of 'friendly' lobby.

Example: Host: Score 25 Difficulty Chart, Speed 28x
Client 1: Score 5 Difficulty Chart, Speed 10x
etc. (I know speed is already adjustable for each user)

Example:
![image_2022-10-13_160715917](https://user-images.githubusercontent.com/115430772/195634856-1db7669c-e3e3-4801-8a61-7e36fb3928e4.png)

**Comment by EpiCreeper** [comment]
This. Please, it would be great.
