### ISSUE TITLE
[canary] User-uploaded maps stuck at 0% download in multiplayer

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#3667]
**Describe the bug**

When trying to download user-uploaded maps in multiplayer on the canary client, they get stuck at 0%. Maps from the Quaver server (ranked, unranked) download fine. Stable client also works without issues.

**To Reproduce**
1. Go to a multiplayer lobby
2. Ask your friend to pick and upload some map you don't have
3. Try to download it

**Expected behavior**
The map downloads fine.

**Desktop (please complete the following information):**
 - OS: Fedora 37 Silverblue running Quaver on latest Flathub Steam. No compatibility runtime vs. Steam Linux runtime does not make a difference.

**Additional context**

Logs from the canary client where in the very end I try to download a map and it gets stuck at 0%: [runtime (copy).log](https://github.com/Quaver/Quaver/files/9791037/runtime.copy.log), [network (copy).log](https://github.com/Quaver/Quaver/files/9791038/network.copy.log)

Logs from the stable client downloading the same map from the same lobby successfully (I quit the game before it finished): 
[runtime (another copy).log](https://github.com/Quaver/Quaver/files/9791039/runtime.another.copy.log) [network (another copy).log](https://github.com/Quaver/Quaver/files/9791040/network.another.copy.log)

**Comment by YaLTeR** [comment]
ginge said they also have the same 0% issue on canary.

**Comment by Swan** [comment]
Figured it out. Somehow the actual downloading got commented out when I was porting parts of the code over.

https://github.com/Quaver/Quaver/blob/36082c54582091b8cdd699fbff2fbda4db42905b/Quaver.Shared/Screens/Download/MultiplayerSharedMapsetDownload.cs#L40-L48
