### ISSUE TITLE
Game not rendering in entire window on Mac

### ISSUE THREAD

**Issue by cckatoo** [Quaver/Quaver#3673]
**Describe the bug**
This appears to be the same problem as #3461 and #3365 however I am running v1.0.0

**To Reproduce**
1. Open game in window

**Expected behavior**
Game screen should fill entire window.

**Screenshots**
<img width="1284" alt="Screen Shot 2022-10-18 at 5 40 17 pm" src="https://user-images.githubusercontent.com/116060867/196358396-f7203ad2-ca1e-4697-a0fc-b4ab014d6b7c.png">

**Desktop:**
 - OS: MacOS 10.15.7 Catalina
 - Version: Quaver v1.0.0 (Steam)

**Comment by bredcat999** [comment]
I'm also having this problem on the canary build and stable.

**Comment by bredcat999** [comment]
my macOS version is 10.15.7 and I'm using the steam canary build.

**Comment by AiAe** [comment]
Sadly there is probably nothing we can do about this, until we start having proper dedicated OS builds. 
That will enable us to have proper OS specific parameters for how it should work (if u heard of plist)
But then again I don't have such issue on my MacOS and I've been using Monterey and now Ventura without such issues.

**Comment by AiAe** [comment]
Can you also provide more info about which Macbook/iMac you have?
Also do you use external displays and display scaling (i can suggest you try using the default one if that resolves it)

![image](https://user-images.githubusercontent.com/3695158/197993060-0821911d-f841-42d8-9016-92b89a5b32d4.png)

**Comment by cckatoo** [comment]
thanks for getting back to me!

> Can you try switching to Canary from Betas and see if thats still the case?

seems to happen exactly the same in Canary i'm afraid


> Can you also provide more info about which Macbook/iMac you have? Also do you use external displays and display scaling (i can suggest you try using the default one if that resolves it)

my specs are:
macOS Catalina 10.15.7 
MacBook Pro (Retina, 15-inch, Mid 2014)
2.2 GHz Quad-Core Intel Core i7 processor
16 GB 1600 MHz DDR3 memory
Intel Iris Pro 1536 MB graphics

i only use the built-in display set to the default resolution/scaling.

one thing i forgot to mention is that when i open the game in fullscreen it gives me a black space at the bottom, but it disappears and the screen realigns itself properly when i click "single player"

![Screen Shot 2022-10-26 at 10 48 57 pm](https://user-images.githubusercontent.com/116060867/198018587-e3ea93f7-c72c-4445-802d-925664d67963.png)
