### ISSUE TITLE
"Click lag"

### ISSUE THREAD

**Issue by S4ndst0ne** [Quaver/Quaver#3678]
Everything is fine until I try to click an option, it lags so much... Sometimes I need to click something multiple times to get it to register. Playing songs works perfectly, typing and search works fine. Even loading TPs works fine, so what is happening?

**Comment by Swan** [comment]
Can you attach a video of what you're seeing?

**Comment by bredcat999** [comment]
I'm having the same issue on my Mac. I have a late 2013 Macbook Pro with MacOS 10.15.7. My mouse cursor lags consistently when I open the skins menu in options or when I open the chat.

**Comment by Swan** [comment]
Closing because no response

**Comment by S4ndst0ne** [comment]
https://www.youtube.com/watch?v=yQ9J4ofLGug

**Comment by S4ndst0ne** [comment]
Sorry for late response.
