### ISSUE TITLE
auto play mod bug

### ISSUE THREAD

**Issue by zhangyuanmin55** [Quaver/Quaver#3681]
**Describe the bug**
when using the auto play mod,click the pause button.The map will be jammed.		

**To Reproduce**
1.Turn on the auto play mod
2. Click the pause button quickly 
3. See error
4. Click the pause button again
5. See error

**Expected behavior**
Clear faults or retain

**Screenshots**
This is the video
https://drive.google.com/file/d/1-5vmpuJUeBABgcicwDN0bQxh_VtRLPqi/view?usp=drivesdk							

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]
 - Version [107]

**Additional context**

**Comment by Swan** [comment]
Duplicate #2285.
