### ISSUE TITLE
Charting Issue

### ISSUE THREAD

**Issue by NeonShikaro** [Quaver/Quaver#3684]
Hi, so I'm having a charting issue where when I try to click on the map where I want the note to go, but it's not showing up, when I try to exit it says that "You have unsaved changes, would you like to save?" when I don't see the notes that I tried to place down, and it didn't effect that one song, nope, it effected other songs that I try to chart.. please help! (I really don't wanna start from scratch..)

**To Reproduce**

**Expected behavior**
I expected it to be a one time thing to happen to only one chart and not the other songs i try to chart

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Gaming PC
 - Chrome
 - Windows 11(??)

**Additional context**
Nope, I have nothing else to report, have a good day/night!

**Comment by AiAe** [comment]
Have you set BPM? Usually you wont be able to map until thats entered.

**Comment by NeonShikaro** [comment]
> Have you set BPM? Usually you wont be able to map until thats entered.

Thing being is that it worked normally when I had no bmp set but I'll try out using the bpm.

**Comment by AiAe** [comment]
> > Have you set BPM? Usually you wont be able to map until thats entered.
> 
> Thing being is that it worked normally when I had no bmp set but I'll try out using the bpm.

Did it resolve the issue?

**Comment by Swan** [comment]
Closing because no response
