### ISSUE TITLE
Notes are "duplicated" (Linux)

### ISSUE THREAD

**Issue by Im-NyaA** [Quaver/Quaver#3689]
Basically, the notes are shifted, or doubled, a bit higher than their actual position, which causes problems when playing.

I don't have a specific way to do the bug.

Characteristics of my pc:
Celeron N4020 1.10gz
4GB RAM
Linux (Debian 10)

Here is a video of the bug:

https://user-images.githubusercontent.com/117041710/201448876-0ac68509-2473-4c58-9f22-320cba1e5bce.mp4

**Comment by YaLTeR** [comment]
Please try opening `quaver.cfg` in the Quaver folder (Browse Local Files on Steam) and rising `DevicePeriod` and `DeviceBufferLengthMultiplier` a little.

**Comment by Swan** [comment]
Closing because no response
