### ISSUE TITLE
changing multipliers back to 1x causes the chart to glitch

### ISSUE THREAD

**Issue by AVY6** [Quaver/Quaver#3690]
So I was playing with 1.1x on a ton of my songs for a bit and when I went back to 1x, the charting on all my songs were glitching like as if I had a low frame rate. I turned on my fps counter and it looked perfectly fine, so I know this isn't something on my end. All I had to do was restart my game in order to get my game to revert back to normal. It's obviously not that annoying to just restart your game, but I don't want to have to restart my game a lot.

I don't know if I'm doing something wrong or being a complete idiot when I'm saying this, so let me know if you have ran into this problem before or if I'm just dumb. :)

**Comment by AiAe** [comment]
Can you replicate it and record an video of the problem?
