### ISSUE TITLE
offline

### ISSUE THREAD

**Issue by Abizzzi** [Quaver/Quaver#3694]
Please add offline mode , sometimes i have not internet connection
When I go to the game in offline mode, it comes, but when I want to go in a level, the screen is black

**Comment by AiAe** [comment]
Click on your profile and click "logout"

**Comment by Abizzzi** [comment]
> Click on your profile and click "logout"

 When I start Steam in offline mode, it doesn't work
It still shows a black screen

**Comment by AiAe** [comment]
Go to Options > Misc and turn off "Automatically log into the server" 

Tested it and everything seems fine.

**Comment by Abizzzi** [comment]
> Go to Options > Misc and turn off "Automatically log into the server"
> 
> Tested it and everything seems fine.

This way did not work.

What I did :

(1) no internet connection
(2) launch steam
(3) connection error ( start in offline mode )
(4) launch quaver
(5) play a map ( Already logged out )
(6) see error ( black screen )

Maybe this problem is due to my system , idk

OS : Windows 10

**Comment by Swan** [comment]
@Abizzzi  Can't reproduce either. Will need your runtime.log and network.log files located in the Logs folder.
