### ISSUE TITLE
Double Text multiplayer chat

### ISSUE THREAD

**Issue by Sl4nixGD** [Quaver/Quaver#3697]
**Describe the bug**
This is not a harmful bug but when i try to say something in the multiplayer chat (i haven't tested it on others) sometimes it enters what you said twice. for example it looks something like this :
- User : Hi i'm new to this game.
- User : Hi i'm new to this game.
- User2 : Lol why you said it twice.
- User : i didn't. i said it one time but the game outputted it twice..

**To Reproduce**
1. Go to a multiplayer room,
2. Click the three lines at the top-right,
3. Go to Multiplayer-chat,
4. Say something,
5. See error

**Expected behavior**
I... expected it to say it once?? of course i said it once it should output once.

**Screenshots**
(sorry i left the room so i can't show it.. i rejoined it but it's all deleted)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : OperaGX/Opera
 - Version : 22H2

**Additional context**
About screenshots. i tried doing the bug again but it did not work, sorry.. it could be just a self-fix bug..

**Comment by Swan** [comment]
Duplicate #1522
