### ISSUE TITLE
Custom Judge Weighting

### ISSUE THREAD

**Issue by 10ai** [Quaver/Quaver#3699]
Next to the custom judge ms value, it would be nice if you could specify a weighting for the judge as well. This would allow players to think about the score in more familiar terms, such as if they are from a different game engine. This would also allow proper support for osu!mania dans.

Pardon the low quality mock-up.

![mockup](https://user-images.githubusercontent.com/70670873/203004365-e2dbdf71-b588-4daa-bebb-c9032e7851bd.png)

**Comment by Swan** [comment]
@Janko5 I can do this quickly but will need a design.
