### ISSUE TITLE
Crash after deleting file and opening it

### ISSUE THREAD

**Issue by Reihynn** [Quaver/Quaver#3701]
**Describe the bug**
Deleting .qua and then trying to open the map in editor crashes the game

**To Reproduce**
Create new mapset
Open song folder
Delete .qua
Exit editor
Open map in editor
crash

**Expected behavior**
Kicks the player out instead of attempting to open the file

**Additional context**
Crash can be consistently triggered

**Comment by Swan** [comment]
Closing because no response
