### ISSUE TITLE
unsubmitted map cuz refresh maps

### ISSUE THREAD

**Issue by Abizzzi** [Quaver/Quaver#3702]
I clicked f5 because I was curious, now all of my maps looks like this

https://user-images.githubusercontent.com/118627883/204108481-a540aad9-c11e-4797-b531-cf308c8cd47d.mp4

https://user-images.githubusercontent.com/118627883/204108514-5995db45-18e3-4600-8322-8c4f1e0a9bfa.mp4
f5 again is not work

Is there no way to fix it?

**Comment by AiAe** [comment]
Please upload runtime and network files found in the game directory > logs folder
Only after you get those errors.

You can also run the status update manually from Options > Misc

**Comment by Abizzzi** [comment]
thanks <3 , it's works
[network.log](https://github.com/Quaver/Quaver/files/10099402/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/10099403/runtime.log)

I don't think these files will be useful anymore
