### ISSUE TITLE
Leaderboard Opacity (not the background)

### ISSUE THREAD

**Issue by its54ig** [Quaver/Quaver#3704]
Maybe you should make it Easier to change the opacity of scores in the leaderboard (e.g to see the background better etc)
![image (2)](https://user-images.githubusercontent.com/117812960/204452244-9d02e725-6db7-4200-87da-3e8349cf0c1d.png)
I tried using paint to change how some of the sprites look, but I couldn't find one of the leaderboard, I searched through ever single file in the skin folder, then I looked at the code of the skin folder, still no luck... Maybe you should make it easier to change the leaderboard opacity

**Comment by Swan** [comment]
Duplicate #2993
