### ISSUE TITLE
Game Crashes when right clicking Quaverbot in F9 menu

### ISSUE THREAD

**Issue by Xylezia** [Quaver/Quaver#3706]
**Describe the bug**
When in the F9 menu on the main menu, if you right click the QuaverBot, your game crashes.

**To Reproduce**
1. Press F9 in main menu
2. Find QuaverBot
3. Right click QuaverBot
4. Game crash

**Expected behavior**
For the game not to crash, ideally.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.0.0

**Logs**
[runtime.log](https://github.com/Quaver/Quaver/files/10147399/runtime.log)

**Comment by AiAe** [comment]
This can be reproduced on both Stable and Canary.
To add to this the game is constantly spamming errors for updating the online count, and the only crash part is when you try to open the drop down menu for QuaverBot in which case it also throws memory error

![Quaver_jeejYNV07M](https://user-images.githubusercontent.com/3695158/205462627-dad27a31-b64f-4a4b-9624-43d7db114e2b.png)
