### ISSUE TITLE
[Canary] United States flag instead Unknown in Local scores

### ISSUE THREAD

**Issue by nonameorous** [Quaver/Quaver#3710]
**Describe the bug**
US flag displays in local scores instead usual question mark flag.
![image](https://user-images.githubusercontent.com/89769379/205664380-5fce5691-35c1-4881-bfb9-4c4747003f27.png)

**To Reproduce**
1. Launch Quaver with Canary Steam Beta enabled. 
2. Search for a map you've played. 
3. See error

**Comment by AiAe** [comment]
This is quite weird, looked at the code and it should default to "XX" in DrawableLeaderboardScoreContainer

**Comment by nonameorous** [comment]
Closed since it got fixed in v1.1.2
