### ISSUE TITLE
Map objects having negative StartTime causes weirdness 

### ISSUE THREAD

**Issue by AiAe** [Quaver/Quaver#3711]
Somehow map notes go to the negative max which is -2147483648
Tried to reproduce but I cannot get it to happen from the editor itself, 
but its quite common error that causes black screens/fps issues.

Edit qua file and add new HitObject at the start
```
- StartTime: -2147483648
  Lane: 1
  KeySounds: []
```

Solution:
We should ignore negative StartTime/EndTime when parsing qua.

**Desktop:**
 - OS: Any
 - Version Any

**Comment by Illuminati-CRAZ** [comment]
There are a few maps that intentionally assign a negative time to a hitobject, perhaps to compensate for an mp3's offset. I also have a map that relies on negative time for timing points for line art.
