### ISSUE TITLE
Dot rendered in wrong color in Deviance chart

### ISSUE THREAD

**Issue by mcwindy** [Quaver/Quaver#3713]
**Describe the bug**
There is a dot with wrong color in the Deviance chart between the OKAY line and the MISS line.

**Screenshots**
![image](https://user-images.githubusercontent.com/40684304/206842438-425eb934-2a78-40bb-98a8-76be256484c6.png)

**Desktop (please complete the following information):**
 - OS: Windows 11, 22H2
 - Version steam Quaver

**Comment by Illuminati-CRAZ** [comment]
I don't actually know if it's meant to do that but that sounds about right so sure
