### ISSUE TITLE
Wrong "You cannot beat this score with your currently activated modifiers!" display

### ISSUE THREAD

**Issue by mcwindy** [Quaver/Quaver#3714]
**Describe the bug**
Activated the same modifiers(2.0x) with the top score on song  "Petit Rabbit's - Daydream cafe (TV size)" (difficulty:Normal). There is an exclamation symbol on the top record played by "ERA Zenith".

**Expected behavior**
There should not be an exclamation symbol.

**Screenshots**
![image](https://user-images.githubusercontent.com/40684304/206842881-4f07cf69-b242-45e2-92e8-e398b3c358d9.png)

**Desktop (please complete the following information):**
 - OS: Windows 11, 22H2
 - Version steam Quaver

**Comment by AiAe** [comment]
Technically it is correct, that you would not be able to get #1 since he already has X grade.

**Comment by mcwindy** [comment]
However, there are warnings in some X scores and not in others.
![image](https://user-images.githubusercontent.com/40684304/208586129-e1e5f74b-f5a7-4643-8603-b774b5c31a9b.png)

**Comment by AiAe** [comment]
If i have to guess, thats because the OR rounding error (i could be wrong), which we know its a bug and not something easy to resolve.
This could've happen due to difficulty rating recalculations.
