### ISSUE TITLE
Screen blacks out when clicking through menus

### ISSUE THREAD

**Issue by Bl3ckThun4r** [Quaver/Quaver#3720]
Screen blacks out when clicking through menus as if changing resolution

**To Reproduce**
1. Go to options
2. Click on screen resolution
3. Scroll down to any resolution over 2800x1600 (within limited testing)
4. Click on any other menu in options, such as skins
**Needs to be ~144hrts as when at 60 stopped occurring**
*Expected behavior*
screen goes black for ~4 seconds

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Monitor: Dell G3223q
 - Version 0.32.0

**Comment by Swan** [comment]
Open the issue back up with logs if this is still happening on the latest update
