### ISSUE TITLE
Cannot Login on Linux

### ISSUE THREAD

**Issue by PappasBrent** [Quaver/Quaver#3726]
**Describe the bug**
I cannot log in.
When I start Quaver and select the "Login" button in the top right corner of the screen, the text "Connecting to the server" appears.
The game never finishes logging in.

**To Reproduce**
1. Star Quaver.
2. Click on the "Login" button in the top right corner of the screen.

**Expected behavior**
I expect to be able to log in.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS x86_64
 - Browser: Brave
 - Version v1.1 (tried both the Canary beta and normal version of the game)

**Comment by IceDynamix** [comment]
Please update to version v1.1.2 and try again.

**Comment by PappasBrent** [comment]
My apologies for taking so long to reply - the fix appears to have worked!
I can login now, thanks.
