### ISSUE TITLE
Mapset background changes

### ISSUE THREAD

**Issue by ValklireSyS** [Quaver/Quaver#3732]
When entering a mapset and playing it, sometimes the background chages to another one, normally to the mapset above or under the selected. It seems to happen randomly. Game version: v1.1, Windows 11. Just visual bug, nothing else changes.

**Comment by Reihynn** [comment]
from my knowledge it happens when you switch maps too fast
probably has to do with how backgrounds are loaded?

**Comment by Swan** [comment]
Duplicate #3655
