### ISSUE TITLE
Scroll Velocity Issue: Shorter long notes appearing properly in preview but not in gameplay.

### ISSUE THREAD

**Issue by Hey-S1r1** [Quaver/Quaver#3733]
**Describe the bug**
At certain configurations of scroll velocities, when shorter long notes are in close proximity to each other, they appear fine in the map preview, but not in actual gameplay. This applies both in the editor (Display Gameplay Preview vs Test Play) and out of the editor (View Map vs Play).
In the attached video, I display what happens to shorter long notes in close proximity at scroll velocities ranging from 1.00 to 1.60 at intervals of 0.05. None of the long notes show when the scroll velocity is 1.10 or below. The most problematic velocity is 1.15. Velocities from 1.20 to 1.40 (inclusive) all have an identical result that is not expected. Velocity 1.45 has an unexpected result slightly different from 1.20 to 1.40. Velocities 1.50 and above do not have issues as far as I can tell.

**To Reproduce**
1. Go to the editor.
2. Turn on Display Gameplay Preview. Place shorter long notes in close proximity to each other. Experiment with scroll velocities.
3. Test play the section with said shorter long notes.
4. See error.
5. Save map and press View Map outside of editor (there should be no error here).
6. Play map outside of editor.
7. See error.

**Expected behavior**
Preview of shorter long notes should match the gameplay regardless of scroll velocity.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome (?)
 - Version 1.1 Full Release

**Additional context**
In this video, I display what happens to shorter long notes in close proximity at scroll velocities ranging from 1.00 to 1.60 at intervals of 0.05. The BPM of the song is 143.
**Describe the bug**
At certain configurations of scroll velocities, when shorter long notes are in close proximity to each other, they appear fine in the map preview, but not in actual gameplay. This applies both in the editor (Display Gameplay Preview vs Test Play) and out of the editor (View Map vs Play).

**To Reproduce**
1. Go to the editor.
2. Turn on Display Gameplay Preview. Place shorter long notes in close proximity to each other. Be sure to adjust the scroll velocity just enough that the shorter long notes start appearing in test play.
3. Test play the section with said shorter long notes.
4. See error.
5. Save map and see view map outside of editor (there should be no error here).
6. Play map outside of editor.
7. See error.

**Expected behavior**
Preview of shorter long notes should match the gameplay.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome (?)
 - Version 1.1 Full Release

**Additional context**
In this video, I display what happens to shorter long notes in close proximity at scroll velocities ranging from 1.00 to 1.60 at intervals of 0.05. The BPM of the song is 143.

**Describe the bug**
At certain configurations of scroll velocities, when shorter long notes are in close proximity to each other, they appear fine in the map preview, but not in actual gameplay. This applies both in the editor (Display Gameplay Preview vs Test Play) and out of the editor (View Map vs Play).

**To Reproduce**
1. Go to the editor.
2. Turn on Display Gameplay Preview. Place shorter long notes in close proximity to each other. Be sure to adjust the scroll velocity just enough that the shorter long notes start appearing in test play.
3. Test play the section with said shorter long notes.
4. See error.
5. Save map and see view map outside of editor (there should be no error here).
6. Play map outside of editor.
7. See error.

**Expected behavior**
Preview of shorter long notes should match the gameplay.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser(?): Steam
 - Version 1.1.2 Full Release

**Additional context**
This issue occurs twice in my unranked map Desire Blue Sky. The BPM of the song is 143 if it matters.

Link to bug video: https://drive.google.com/file/d/1awtUmCdg9-t-h-qQzfGN_Try6TyvUYX4/view?usp=sharing

**Comment by YaLTeR** [comment]
When playtesting anything with LNs, restart by holding `~` first thing. There's a bug currently that LN lengths don't get computed properly the first time.

**Comment by Hey-S1r1** [comment]
Does it need to be restarted specifically with ~? Because I remapped the restart button to R a while back and restarted with that, and the error was still there.

**Comment by YaLTeR** [comment]
Shouldn't make a difference, no. Weird

**Comment by Swan** [comment]
Duplicate #1872
