### ISSUE TITLE
maps from other games display difficulty of 00.00

### ISSUE THREAD

**Issue by elijad1** [Quaver/Quaver#3735]
**I installed a load of osu maps that are compatible with quaver, but all the maps difficulty is labeled as 00.00 when browsing them. when you play the map it will give the correct difficulty at the beginning of the map**

**To Reproduce**
1. have osu installed on D drive
2. have quaver installed on C drive
3. import songs from osu
4. difficulties labeled 00.00

**Expected behavior**
the difficulties should have been labeled correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/74698865/211212183-7edb3f62-8f6c-474b-b921-c2599b57220c.png)
![image](https://user-images.githubusercontent.com/74698865/211212237-6dbf6b2c-f461-4ed7-a3de-171bbed6f852.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [1.1]

**Additional context**
I installed the maps through a map pack into osu by dropping the folders into the song folder. I didn't install them with osk files. some of my osu songs display correctly but the songs installed from the pack seem to not work

**Comment by IceDynamix** [comment]
Loading in songs from other games will show 0 difficulty at the beginning, since the difficulties are being calculated in the background. Leave your game open and it should fill over time.
