### ISSUE TITLE
Add "InvertYOnUpscroll" tag to the skin.ini

### ISSUE THREAD

**Issue by EpiCreeper** [Quaver/Quaver#3739]
It is no secret that the skin system was made for downscroll, but upscroll players have to invert the Y values for the combo and judgements manually to have a decent experience.

My solution is to add "InvertYOnUpscroll" tag to the skin.ini. It should be on by default and be separate for 4k and 7k.
What it does is invert the values (+ to -, - to +) of these tags:
HitErrorPosY
JudgementBurstPosY
ComboPosY

(I don't wanna start thinking about how to make it better for split scroll...)

**Comment by Swan** [comment]
Just makes everything more complicated.

**Comment by EpiCreeper** [comment]
:(
