### ISSUE TITLE
I can't select songs/change the playback rate on songs

### ISSUE THREAD

**Issue by Chadpool3954** [Quaver/Quaver#3740]
**Description**
-So i played galaxy collapse (cut ver.) on 1.15x, and i wanted to go higher,
but it just reseted to normal and didn't let me change it after.
This already happened to me at my friends house.
I restarted the game and now i can't even select songs with my mouse.

-For me just clicking it repeteatedly worked.

**Expected behavior**
-After the bug activated, there is no way i can change the rate or click on songs.

**Desktop (please complete the following information):**
 - OS: Windows 10 Education edition
 - Browser: Firefox
 - Version 109.0

**Additional context**
-When i restart the game, it behaves like it's non-interactive.
And it dosen't go away. I can restart again, reset, delete and install back, 
shut down the pc and it still stays.

**Comment by Swan** [comment]
You're not clicking on the button. The cursor on your skin probably doesn't have `CenterCursor = True` if you're using a circle cursor instead of an arrow.
