### ISSUE TITLE
Left Mouse Click in menu barely functions as intended

### ISSUE THREAD

**Issue by S4ndst0ne** [Quaver/Quaver#3741]
It works fine playing maps.
I have to spam the left mouse click button to make it work.
My mouse is not the issue.
The ESC button works.

**Comment by AiAe** [comment]
Could be your skin cursor, if the image is not exactly at 0,0 and has spacing

**Comment by Swan** [comment]
And/or set `CenterCursor = True`

**Comment by S4ndst0ne** [comment]
It's not that. It happens on all skins.

**Comment by AiAe** [comment]
Can you record an video to show whats wrong exactly?

**Comment by S4ndst0ne** [comment]
[https://www.youtube.com/watch?v=yQ9J4ofLGug](url)

**Comment by S4ndst0ne** [comment]
It's also scroll wheel and right click.

**Comment by AiAe** [comment]
I have feeling its because your window is kinda weird, does it happen if u don't use borderless and change to fullscreen?

**Comment by S4ndst0ne** [comment]
Doesn't matter, I've tried.
