### ISSUE TITLE
Auto-generate Playlist When Importing Stepmania Simfiles.

### ISSUE THREAD

**Issue by valyrie97** [Quaver/Quaver#3747]
**Is your feature request related to a problem? Please describe.**
Not a problem, but rather a use case. When importing beatmaps from stepmania / etterna, there seems to be no way to look at a given collection. Id like to, similar to stepmania / etterna, be able to see maps grouped by the pack they came from (as often, packs may have a similar mapping style which is desirable if you're training one thing in isolation)

**Describe the solution you'd like**
I think a really simple first pass solution to this use case, would be the automatic generation of a playlist when you import multiple stepmania files at once.

**Describe alternatives you've considered**
I think there are many more in depth alternatives around having more metadata about sourcing information, but as I havent delved into the code I cant speak to what is present / could be done.

**Additional context**
I would assume this would only work if you drag a folder with many folders inside it, similar to how stepmania scans the folder for certain files to give the pack its style.

It may be slow, but I would be happy to look into an actual implementation for this feature if it seems reasonable / in scope

Edit: additional info

**Comment by Reihynn** [comment]
It already exists lol just open Playlists tab (if you use the detect maps from other games option)

**Comment by Reihynn** [comment]
Yeah that seems nice 

Maybe add a multi select maps into playlist as well so making playlists would be easier

**Comment by valyrie97** [comment]
@Swan could you reference the commit this is in? love to look at the changes :)

**Comment by Swan** [comment]
@valyrie97 If you import the charts directly from Etterna, a playlist with the pack name is automatically created. I don't have any plans to support this for converted files. You can always create the playlist upon import.

**Comment by valyrie97** [comment]
Ah i see, i mistaken thought closed as completed meant it was implemented.
