### ISSUE TITLE
[Canary] Long LN rendering issues

### ISSUE THREAD

**Issue by nonameorous** [Quaver/Quaver#3759]
**Describe the bug**
If you miss/drop a long LN it straight up disappears instead of game coloring it with the "dead note color". It also affects how preview displays the map if you enable FLN mod on lowest difficulty maps. (<2 diff)

**Expected behavior**
Revert to how they were rendered in Stable.

**Screenshots**
![image](https://user-images.githubusercontent.com/89769379/220762750-7b03e3de-4f06-4eba-879f-448c39f37b43.png)
![image](https://user-images.githubusercontent.com/89769379/220763195-816a2d0c-84ff-4d06-bdd7-0a8ea71e930d.png)
This bug makes it seem like there weren't any notes in other columns prior to the moment I selected in the preview window.
https://user-images.githubusercontent.com/89769379/220763565-35fd8e68-c1d9-4f01-b8c1-c0067028d4b2.mp4
Gameplay example.

**Comment by Illuminati-CRAZ** [comment]
Need to handle LNs differently here: https://github.com/Illuminati-CRAZ/Quaver/blob/61b64d8d7ba9d705701d0c9738941f2bd300d7e9/Quaver.Shared/Screens/Gameplay/Rulesets/Keys/HitObjects/HitObjectManagerKeys.cs#L641
