### ISSUE TITLE
Long Note Tail has unwanted gap in default Arrow Skin for upscroll

### ISSUE THREAD

**Issue by staravia** [Quaver/Quaver#376]
I know the skin is temporary, but it's driving me crazy.

Evidence:
https://cdn.discordapp.com/attachments/525409883877539860/526981998544158730/Ca23aaaapture.PNG

**Comment by Abriel14** [comment]
I have changed the pictures in the Quaver.ressource branch but I don't know how to make a pull request with my changes...

**Comment by Abriel14** [comment]
Nice, texture fixes and improvements branch upcoming!
