### ISSUE TITLE
Suggestion: re-add autohost lobbies automatically starting when everyone's ready

### ISSUE THREAD

**Issue by TempyseemoPOG** [Quaver/Quaver#3768]
Auto host lobbies just feel super sluggish having to wait 90 seconds...
I want you to revert the autohost to automatically start whenever everyone in the lobby is ready.

**Comment by Reihynn** [comment]
yes yes pleaasseeee i agree please

**Comment by TempyseemoPOG** [comment]
it's been like this for 9 months lol

**Comment by Reihynn** [comment]
well that's 9 months of me barely touching autohost

**Comment by EpiCreeper** [comment]
THIS PLSSS
