### ISSUE TITLE
Add ability to change color and opacity of each individual column instead of just the entire stage

### ISSUE THREAD

**Issue by cindsa** [Quaver/Quaver#377]
Some skins use different colors and opacity for individual columns
[Example 1](https://media.discordapp.net/attachments/396997881309167617/527007006297554955/screenshot1481.png?width=833&height=469)
[Example 2](https://media.discordapp.net/attachments/526940434715377664/527003268396875787/unknown.png)
Right now those skins are impossible to replicate in Quaver because such option doesn't exist. I'd be nice to have something like
ColumnColor1: 0,0,0,150
ColumnColor2: 5,10,13,150
and so on in skin.ini if possible to allow for creation of such skins

**Comment by Swan** [comment]
You can use `ColumnColor1/2/3/...` the same way. You just need a `column-lighting` element

https://github.com/Quaver/Quaver.Wiki/blob/master/Skins/Keys/en.md#column-lighting
