### ISSUE TITLE
quaver doesnt launch on linux with steam (even after fresh reinstall)

### ISSUE THREAD

**Issue by ana-rchy** [Quaver/Quaver#3772]
**Describe the bug**
on steam, the game shows as running for a few secs, and then closes and stops showing as playing, no window opens or anything

**To Reproduce**
1. use linux
2. try to launch quaver through steam
3. nothing happens

**Expected behavior**
game should launch

**Desktop (please complete the following information):**
 - OS: arch linux
 - Browser: firefox
 - Version: 6.2.1-arch1-1-vfio (linux-vfio kernel)

**Additional context**
i use bspwm as my window manager, running the game with proton seems to work but not for certain versions like proton-tkg that have the same issue

**Comment by YaLTeR** [comment]
Thanks; I pinged you in discord with a checklist for diagnosing audio issues.

**Comment by YaLTeR** [comment]
They said in Discord that they fixed it.
