### ISSUE TITLE
Option to choose between hold to pause and tap to pause

### ISSUE THREAD

**Issue by cindsa** [Quaver/Quaver#378]
Since pausing already invalidates your score if you're playing on a ranked map, I don't see why just simply tapping to pause shouldn't be an option.
I know Quaver decided to made it hold to pause so that players don't accidentally hit the pause button, but why not keep hold to pause by default and add an option where you can choose to simply tap to pause if you're not worried about accidentally hitting the pause button?
Quite often I get situations where I want to just quickly pause the game, do something and then go back to the game from where I stopped but hold to pause makes it impossible because holding to pause pretty much guarantees that you're going to fail if you try to do it in the middle of the map. So in my opinion having an option to choose between hold to pause and a simple tap to pause would be nice to have.

**Comment by Sublimity** [comment]
I feel like this feature request is pretty redundant, but nevertheless I'll submit a pr later with the proposed changes, and we'll see what Swan thinks.
