### ISSUE TITLE
osz file does not import properly

### ISSUE THREAD

**Issue by ghostlyentity** [Quaver/Quaver#3782]
**Describe the bug**
Dragging and dropping in osz files should import the map and it doesnt show up (qua files are missing, only mp3 files are present)

**To Reproduce**
import an osz map

**Expected behavior**
a  working imported osu map

**Screenshots**
https://user-images.githubusercontent.com/86599520/231934655-c57c5af4-67fc-499b-866e-c47d65cf2a0b.mp4

**Desktop (please complete the following information):**
 - OS: endeavourOS Linux x86_64 
 - Browser not applicable

**Additional context**
when importing different osu maps, it creates a folder and puts in the cover and mp3 files but is missing the qua files that would otherwise make the map playable and or visible

Since github doesnt wanna display the mp4 properly:
![Snapshot_2023-04-14_05-38-40](https://user-images.githubusercontent.com/86599520/231935612-349047f6-468c-4c26-b94e-b92effa0ef8f.png)
![Snapshot_2023-04-14_05-38-55](https://user-images.githubusercontent.com/86599520/231935616-00d54856-2521-4230-9ad0-8f0c84587fd4.png)
![Snapshot_2023-04-14_05-39-08](https://user-images.githubusercontent.com/86599520/231935619-9a4362af-398b-43a6-8c3f-94613b155703.png)

**Comment by IceDynamix** [comment]
Please send the relevant .osz file for reproduction. Send logs as well. If this happens on every .osz file, chances are it's a OS related drag&drop issue.

**Comment by ghostlyentity** [comment]
im not certain how i would post the logs but here is one of the links
https://osu.ppy.sh/beatmapsets/147962#osu/366139

is there another more straightforward method to import maps?

**Comment by IceDynamix** [comment]
I just checked and it seems you're trying to import non-mania mapsets. Quaver does not support converts from other gamemodes and support will likely not be added because of lack of demand and quality. If you're looking for songs on osu! to import, make sure to enable to osu!mania filter when searching.

**Comment by ghostlyentity** [comment]
well, i tried to do so, came up with
https://osu.ppy.sh/beatmapsets/152786#osu/375834
same result

**Comment by ghostlyentity** [comment]
apologies, osu website design is just absolute dogpoo and it wasnt a usable song, i found one that has mania and worked
