### ISSUE TITLE
NSV mod stops applying to preview when autoplay is disabled

### ISSUE THREAD

**Issue by Illuminati-CRAZ** [Quaver/Quaver#3785]
**Describe the bug**
When previewing a map with the NSV mod enabled, disabling autoplay results in SVs being applied to the preview. Seeking backwards results in incorrect scrolling behavior as well.

**To Reproduce**
1. Pick an SV map in song select.
2. Turn on NSV
3. Open map preview
4. Disable autoplay
5. Seek backwards

**Expected behavior**
A playable map preview with no SVs applied.

Video of bug:
https://cdn.discordapp.com/attachments/492960211271680030/1096930951088570480/2023-04-15_15-49-55.mp4

**Comment by masakk1** [comment]
I can second this, bit annoying since I'm trying to train a few bits on a map with a lot of SVs and it's literally impossible.
