### ISSUE TITLE
Better Credit For Collaborative Mapsets

### ISSUE THREAD

**Issue by EpiCreeper** [Quaver/Quaver#3796]
Collab mapsets are always a bit weird because most of the time the one who uploaded the mapset gets most of the credit, even if in some cases they did less work then the other collaborators.

I suggest a way to credit mappers directly, here is how I think it should be done:
- Select an option in the editor to credit more mappers.
- Select the mapsets you contributed to.
- Select the maps the mapper contributed to and write their Quaver username.
- A message would show up in the players game, they can ether accept or deny it (a way to block this kind of messages should probably also be added)
- If they accept, the mapset would show multiple mappers instead of just one.

This feature would make it clearer and easier to know which mapper worked on which map. It would also allow you to visit any mappers page from the website, even if it has many mappers. Mappers who changed their name would also stay credited. This change would also help mappers by pinging them in the discord when the map changes its ranked status. Added mappers could also upload changes to their map directly instead of going through a middle man.

**Comment by Swan** [comment]
Similar to #875
