### ISSUE TITLE
Handful of a user's mapsets are freezing the game and forcing you to close Quaver.

### ISSUE THREAD

**Issue by cybonics** [Quaver/Quaver#3798]
**Describe the bug**
5/13/2023
A user by the name of "ZockerPlay" uploaded multiple maps/mapsets spamming a symbol causing the game to freeze and eventually force you to close the game.

**To Reproduce**
1. Go to "Maps" (the Map Downloader)
2. Click on the Ranked Bar and change it to Unranked; 
   2a. Sort by Newest
   2b. Set mode to All  
   2c. Set status to All
3. Scroll down a bit (on 5/13/2023),

**Expected behavior**
I expected Quaver to freeze & not respond for over 15 minutes, eventually forcing me to close out of the program.

Also, I got the same trying different skins & the default setting.

**Screenshots**
[Imgur Album of the bug](https://imgur.com/a/o7W8gdg)

*Each individual screenshot (3)*
[Bug Screenshot 1](https://i.imgur.com/iycsacK.png)
[Bug Screenshot 2](https://i.imgur.com/M3XiJsC.png)
[Bug Screenshot 3](https://i.imgur.com/eWcMQDU.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Brave
 - Latest Steam Version (V 1.1?)

**Additional context**
Everything works fine until the maps are loading in. As you try to scroll down, the game will freeze before the maps become visible. After sitting through multiple minutes of white loading screens waiting for Quaver to respond, the maps become visible. I've relaunched Quaver 10 times and ran into the bug every time. In one of my attempts I waited over 15 minutes for the maps to load and grabbed the screenshots. Then, I went back to the home page and re-opened the map downloader where it happened again. 

Also, I tried swapping to different skins and I got the same result for all of them, including the default.

**Comment by Illuminati-CRAZ** [comment]
The offending mapsets have been removed, but it looks like this can generally happen with any long enough string of text that gets cached (probably related to #2916).
