### ISSUE TITLE
ranking queue giving me error 

### ISSUE THREAD

**Issue by Tqycv** [Quaver/Quaver#3822]
recently i have gotten this error whenever i try to submit map for rank 

![7212023 1-8-54-741](https://github.com/Quaver/Quaver/assets/140139595/65f1ad58-978b-48bb-a179-e35a557c0fa4)

**Comment by AiAe** [comment]
@Tqycv and did you try to read what the alert said?

**Comment by Tqycv** [comment]
may i ask where to check to see if the ranking queue is open is

**Comment by AiAe** [comment]
> may i ask where to check to see if the ranking queue is open is

Your best bet is to be in our Discord server, since it will be for sure announced there when it opens.
