### ISSUE TITLE
Note doesnt appearing when editing a new map song

### ISSUE THREAD

**Issue by GumballHeroItMe** [Quaver/Quaver#3823]
Hello im am sure this is only me get this bug but here is it :

I had another song that have one new map and feel wanna to make a new map song..But when i done editing it show none of note are appear in my map song..the previusly work but new one wont..the note just stucking at click note! Sorrry my grammar are so bad but i hope someone ever understand what i just say 

Quaver ACC : GumballheroItMe

**Comment by AiAe** [comment]
Have u set BPM before you started mapping?
Would be good if u can export/zip the mapset u made and upload it for us to check it.
