### ISSUE TITLE
Random quick restart trigger (4K mode)

### ISSUE THREAD

**Issue by SFNutria** [Quaver/Quaver#3824]
Sometimes the game has absolutely zero issues but at random intervals after/during very dense/high nps maps triggers the quick reset as if it was auto binded to the first note. 
This happens in random times even with different keyboards/layouts. 

Even after resetting keybinds to default, preseting my defaults ("QWOP" with quick restart usually on "M"). Re binding my inputs does nothing to fix this. Tried different languages, three different keyboard models and it keeps happening, as soon as this triggers the only solution i found was fully restarting my pc. It's like it rebinds itself as soon as the map begins to my first setted note input (Always the first left one and only that one.)
Please note that this has happened to me across different configs including a laptop so i don't think its a hardware issue at all.

**To Reproduce**
I wish i knew how to reproduce, maybe play fast?

**Expected behavior**
Normal gameplay instead of quick restart on first key press using first leftmost note on 4k mode.

**Desktop:**
 - OS: Windows 10
 - Browser Chrome
 - Version: Latest

**Additional context**
Reinstalled and tested across different configs/hardware and this issue persists. Mostly after few warmup rounds everything is okay until i start playing on 32+ nps maps.

**Comment by Storn42** [comment]
Its possible you have the No Miss modifier on. This will automatically restart the chart upon combo break, based on your judgement settings. You are likely missing the first note by hitting it early and the chart is restarting because of that.

**Comment by SFNutria** [comment]
> Its possible you have the No Miss modifier on. This will automatically restart the chart upon combo break, based on your judgement settings. You are likely missing the first note by hitting it early and the chart is restarting because of that.

It's unrelated to that, already checked. The quick restart triggers even on the "intro" of a map. Also happens while using No Fail modifier as well.

**Comment by Swan** [comment]
It's possible that you are pressing the quick restart key and not realizing. The only time the game restarts in this fashion is if you press the button to do it or if you miss while having the No Miss modifier on.

**Comment by SFNutria** [comment]
> It's possible that you are pressing the quick restart key and not realizing. The only time the game restarts in this fashion is if you press the button to do it or if you miss while having the No Miss modifier on.

Having enough experience in rhythm games this was the first thing i thought but discarded immediately due to the distance between my keybinds, also i use a proprietary handmade "rhythmgame keyboard" with only the keys used for the game. With it, it is impossible for me to reach said keybind as it is not set on it. As well as with a normal kb since my keybinds location prevents this kind of mistakes. Using QWOP with function keys such as Pause / Insert as quick exit/restart. 
Even after rebinding all of em' with further away keys this issue persists, testing such keyboards with a tester on to test any possible keyboard shorts that might trigger any other keys. As said on the main post, usually triggers only on very dense maps after a few attempts on random intervals, since theres sessions that i can play normally for a few hours after warmup and in some other sessions it only takes a few short maps to trigger this.

**Comment by Swan** [comment]
Unfortunately there is no way for us to solve your issue. There is no randomness or map density factor to gameplay screen restarts, it only occurs in the aforementioned scenarios. If more users were having this issue, then I would be happy do dig deeper into your issue, but that isn't the case. Please triple check your hardware and selected modifiers. Closing this issue.
