### ISSUE TITLE
Unable to import songs

### ISSUE THREAD

**Issue by Rojoow** [Quaver/Quaver#384]
I'm not able to import any type of song file (qp, osz, sm) to the game respectively

This is what happens:
1. I download the file 
2. I try to drag it 
3. This happens:
![image](https://user-images.githubusercontent.com/46137649/50426037-37526d00-0852-11e9-8e27-27f17c8232fc.png)
4. And then nothing happens, no messages pop up, no notifications and nothing is imported

(Running windows 10)

(Yes i have been told that some convert files dont work but none of the quaver ones work either, downloaded everything from the newest ranked and none of them import)

**Comment by AiAe** [comment]
Could you send runtime logs?

**Comment by Rojoow** [comment]
[runtime.log](https://github.com/Quaver/Quaver/files/2710756/runtime.log)
tried to import around 10 maps and then i sent this log, however some people already told me that my logs seem to be completely empty anyways?

**Comment by robby250** [comment]
discord had this issue where drag&drop wasnt working when i was running it as administrator, it might be the same for quaver?

**Comment by KeepSOBP** [comment]
> discord had this issue where drag&drop wasnt working when i was running it as administrator, it might be the same for quaver?
@robby250 

Thanks! It works.

**Comment by RackYican** [comment]
> discord had this issue where drag&drop wasnt working when i was running it as administrator, it might be the same for quaver?

I have the same problem in LInux Mint, idk why is not, im using Dolphin btw
