### ISSUE TITLE
Player converted from referee to normal player will get score 0 when playing maps

### ISSUE THREAD

**Issue by QiuFeng54321** [Quaver/Quaver#3840]
**Describe the bug**
After turning into a referee and turning back to normal player, the player's scores will be zero, as shown in the screenshots.

The player turning back from referee will see other players' scores being 0, while others will see the player's score being 0, which is what the online history shows. You can see the behavior from the screenshots below.

After rejoining the game, the bug will fly afar.

P.S. In one of the screenshots you can see that the other players didn't see me quitting the game and rejoining, and instead saw me in the lobby the whole time.

P.S. The multiplayer online history shows the result as being in team mode.

**To Reproduce**
+ Make an mp room
+ `!mp referee <your name>`
+ play some map?
+ `!mp clearreferee`
+ Play a map
+ F

**Expected behavior**
;w;

**Screenshots**
![20230806210707_1](https://github.com/Quaver/Quaver/assets/32996262/668ca488-d7c6-40f7-8182-88a9e48c4108)
![20230806210755_1](https://github.com/Quaver/Quaver/assets/32996262/fddf59b6-df15-4e47-8f7a-86db3ea9a34c)
![20230806210911_1](https://github.com/Quaver/Quaver/assets/32996262/2d66907b-1cce-4a0c-95e0-a2f0e372609c)

**Desktop (please complete the following information):**
 - Quaver 1.2
 - macOS ventura

**Additional context**
\> <

**Comment by Swan** [comment]
Should be resolved on the next server deploy
