### ISSUE TITLE
Multiplayer Maps always error when uploaded from another game

### ISSUE THREAD

**Issue by YashikiWarashi1** [Quaver/Quaver#3841]
**Describe the bug**
Whenever a player attempts to upload a map in multiplayer, it will always result in an error message and fail to upload. 

**To Reproduce**
1. Go to multiplayer
2. Click on any lobby or make a new lobby
3. have host
4. Aave a map from another game
5. Attempt to upload map

**Expected behavior**
The map should upload if it is within the allowed file size

**Screenshots**
N/A

**Desktop (please complete the following information):**
 N/A

**Additional context**
This bug has been present since the recent multiplayer update.

**Comment by AiAe** [comment]
Please share your log files once the error happens.
Can be found in Game directory > Logs and upload both files to here.

**Comment by Swan** [comment]
@YashikiWarashi1 Logs along with the map(s) you are trying to upload would be very helpful.
