### ISSUE TITLE
Multiplayer Wins, Losses and Ties not being tracked

### ISSUE THREAD

**Issue by YashikiWarashi1** [Quaver/Quaver#3842]
**Describe the bug**
Multiplayer wins, losses and ties are not being submitted to players profiles and the global leaderboards.

**To Reproduce**
1. take note of your wins and losses in multiplayer
2. play a multiplayer match
3. note if you have won or lost the match
4. check your multiplayer stats

**Expected behavior**
after a multiplayer match, you should be given a win, loss, or tie

**Screenshots**
N/A

**Desktop (please complete the following information):**
 N/A

**Additional context**
This bug has only been happening since the recent multiplayer update

**Comment by Swan** [comment]
This is intentional
