### ISSUE TITLE
Multiplayer: Allow !mp randmap for non-autohost

### ISSUE THREAD

**Issue by QiuFeng54321** [Quaver/Quaver#3855]
**Is your feature request related to a problem? Please describe.**  
It's not rare that as host we don't know what to pick, and in this case `!mp randmap` can solve this issue. 

**Describe the solution you'd like**
`!mp randmap` is currently only allowed to be used in autohost mode, but it is also useful when autohost is off. By making the server pick a map, we can not only drop our frustration for lack of map to choose, but also get new maps the host doesn't have, which can give unexpected picks, like maps with weird patterns that were implicitly ignored by the host.

**Describe alternatives you've considered**
Turning on autohost, run the command and turn autohost off.

Currently, the host can pick a random map by pressing `F2` in map selection screen and filtering out maps using queries like`d>25 d<30`, but this only picks maps that are present in the host's game, and the filter needs to be manually typed to keep up with the constraints in the lobby. For players with fewer maps at hand, this might not be very useful.

**Additional context**
None.

**Comment by Swan** [comment]
This should be live now
