### ISSUE TITLE
spectator timestamp

### ISSUE THREAD

**Issue by minimum1674** [Quaver/Quaver#3856]
I am always frustrated when I don't see who spectated me, because I am currently trying really hard to get to a good spot on the Iran leaderboards, I really want to see who was spectating me so I can implement different strategies to stay on the place I am and/or improve.
streamers or quaver's famous people can also use this to see how many people spectated them through the whole song and streamers might use this for statistics and other reasons like "people who spectate the song I am playing get placed in a tournament".
a spectator timestamp would be amazing because people can see who spectated them and see what they should expect.
I do not have any alternatives in mind, any differences are okay.

**Comment by Swan** [comment]
Also added a message in chat that shows who started spectating. The spectator list during gameplay will be in the next update
