### ISSUE TITLE
Cant download any maps.

### ISSUE THREAD

**Issue by Muriahh** [Quaver/Quaver#3863]
### Describe the bug

I tried to download some maps, but I can't seem to download any maps. I tried to double-click them, press the download button, and even try to download them through the website. I've already uninstalled and reinstalled them, but nothing seems to be working.

my discord : muriahhh 

my steam account : https://steamcommunity.com/id/wantothavesexrightnow/

### To Reproduce

.

### Log Files

.

**Comment by AiAe** [comment]
@Muriahh give us some more info like what OS do you run + your log files

**Comment by Muriahh** [comment]
> @Muriahh give us some more info like what OS do you run + your log files

im kinda new to this where can i see my log files and os.

**Comment by AiAe** [comment]
OS as in operating system (Windows, MacOS or Linux (+distro)
For logs u can find them by doing:
![CleanShot 2023-08-15 at 18 49 07](https://github.com/Quaver/Quaver/assets/3695158/51302e1d-7e7c-4dfb-b8fb-cdc3f97e8b16)

Then go to Logs folder and drag both files into the text editor here

**Comment by AiAe** [comment]
Yes this is what i needed, and it looks like your Windows has locked some folders, which is quite annoying to fix... 
I will give u this source if you want to try to fix it yourself 
https://support.microsoft.com/en-gb/topic/-access-denied-or-other-errors-when-you-access-or-work-with-files-and-folders-in-windows-219af563-1953-ab4a-f17e-b0182755214e

Good luck

**Comment by Muriahh** [comment]
> Yes this is what i needed, and it looks like your Windows has locked some folders, which is quite annoying to fix... I will give u this source if you want to try to fix it yourself https://support.microsoft.com/en-gb/topic/-access-denied-or-other-errors-when-you-access-or-work-with-files-and-folders-in-windows-219af563-1953-ab4a-f17e-b0182755214e
> 
> Good luck

thank you

**Comment by AiAe** [comment]
Forgot to mention to be more specific:
Access to the path 'D:\Steam\steamapps\common\Quaver\Data\Downloads' is denied.
