### ISSUE TITLE
Window bug?

### ISSUE THREAD

**Issue by AnInanimateObject** [Quaver/Quaver#3867]
### Describe the bug

When booting up the game (I play in Windowed mode), 90% of the screen is gray except for a tiny left corner square

### To Reproduce

All I did was open the game.

### Expected behavior

I expected the game to play normally in the window instead of being 90% gray.

### Log Files

No logs? Game didn't crash, just a bug

### Screenshots

<img width="1152" alt="Screen Shot 2023-08-17 at 7 58 55 PM" src="https://github.com/Quaver/Quaver/assets/106692188/e8eeb64a-2f87-4d03-bfad-9fb595eeb256">

**Comment by WarpABoi** [comment]
Log files are still appreciated even if the game does not crash

**Comment by Swan** [comment]
@AnInanimateObject 

- Which MacOS version are you using?
- What do your video settings look like (resolution, fullscreen, borderless, etc)? 
- Does this happen every time or just that one time?

**Comment by AiAe** [comment]
To add to the questions above, also tell us your MacOS Display resolution and if u use any of the scaling options (pretty sure this was due to this)

**Comment by AnInanimateObject** [comment]
> 

Sorry for the late reply. I am using a MacOS Catalina 10.15.7. My resolution is 1160x648, although I attempted changing it to see if thats the issue to no avail. It has happened every time for the past handful of months. The resolution I believe is 4096 x 2304

**Comment by Swan** [comment]
@AnInanimateObject Are you using any of the scaling options in the Mac settings?
