### ISSUE TITLE
"Failed to submit score! Retrying shortly."

### ISSUE THREAD

**Issue by SpamLRBLX** [Quaver/Quaver#3871]
### Describe the bug

Every time I submit a score, it keeps spamming the message: "Failed to submit score! Retrying shortly." And not only did it happen to me, but it also happened to someone else. 

### To Reproduce

1. Submit a score
2. It will spam the error message

### Log Files

[network.log](https://github.com/Quaver/Quaver/files/12386631/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/12386632/runtime.log)

### Screenshots

https://cdn.discordapp.com/attachments/531647732612464640/1142548252789592115/image.png

Someone else's screenshot
https://cdn.discordapp.com/attachments/531647732612464640/1142534877619695739/image.png

**Comment by Swan** [comment]
It's fixed
