### ISSUE TITLE
the quaver icon went missing in the taskbar?

### ISSUE THREAD

**Issue by AgmonBlynkos** [Quaver/Quaver#3874]
### Describe the bug

I got no idea why this happened but yeah, it pretty much happened 

I restarted the game and now it's there, I don't know if it is a client issue or my laptop being dumb, but this never happened before so I got no idea

### To Reproduce

best I can tell is try to keep opening the game, or maybe it got something to do with lower spec hardware which might be possible

### Log Files

I don't know how helpful these are but might as well
[runtime.log](https://github.com/Quaver/Quaver/files/12411148/runtime.log)
[network.log](https://github.com/Quaver/Quaver/files/12411150/network.log)

### Screenshots

![Screenshot 2023-08-22 201221](https://github.com/Quaver/Quaver/assets/108335762/0eda6bb8-7e21-44fb-88eb-dbc27bbc887c)

**Comment by Swan** [comment]
100% your issue and not the game. The best help I can give you is to google around for some solutions.
