### ISSUE TITLE
Does not show correct full screen resolution

### ISSUE THREAD

**Issue by e00E** [Quaver/Quaver#3876]
### Describe the bug

Windows 10, AMD Radeon RX 6800 XT

My monitor is 2560x1440 but the highest resolution Quaver shows in the settings is 1152x648. This prevents me from fullscreening the game.

I have a second monitor which is 1080x1920. Maybe this confuses Quaver. The first monitor is marked as the main display in the Windows settings.

### To Reproduce

Start Quaver.

### Log Files

[runtime.log](https://github.com/Quaver/Quaver/files/12422233/runtime.log)

**Comment by AiAe** [comment]
You can set custom resolution by editing quaver.cfg, but it might look quite bad.

**Comment by AiAe** [comment]
Stale issue, what I've gave you for solution should be enough.

**Comment by e00E** [comment]
Please reopen the issue. The bug is still present.

Thank you for mentioning the workaround. The workaround is just that though and not a fix for the underlying problem. I didn't post this to get support. I posted it to get the bug fixed.

**Comment by AiAe** [comment]
@e00E I'm not quite sure how this is a Quaver bug when for me I clearly see the option and I am able to pick it here.
This has to be some AMD Driver or Windows issue.
Without us be able to reproduce the bug, we cannot fix it.

![CleanShot 2023-08-25 at 19 55 26](https://github.com/Quaver/Quaver/assets/3695158/d0176a1b-1b32-413a-af89-a143c6de1fad)

**Comment by AiAe** [comment]
Have you checked if u by chance have turned on "AMD Super Resolution", if you have that on try to check if having it off resolves anything.

**Comment by e00E** [comment]
It could be a driver bug. In that case it is true that Quaver can't easily do anything about it. It could also be a Quaver bug. I have never seen missing resolutions in any other application. This makes it more likely a Quaver bug. I suspect Quaver is confused by my second monitor and there is something wrong with Quaver's method of deciding what resolutions are available. We could find out more by debugging that part of the code. I feel you're rushing to close the issue too quickly. Maybe someone familiar with the monitor related Quaver code to check if this is enough information to find a problem in the code.

Super resolution isn't enabled.

**Comment by AiAe** [comment]
We use something thats get provided by the framework we use, which gives us a list with the possible resolutions one could have. 
I also have 2 monitors, and I have no issues with that either, have u tried to change which monitor is your main one? Maybe that could give us lead to what the issue could be.

**Comment by e00E** [comment]
Windows has the right (bigger) as the main monitor. Anyway, I just tested this again and after a reboot Quaver is now showing the correct resolutions, which makes me unable to reproduce the bug too.

**Comment by AiAe** [comment]
That should be enough to test if we are able to resolve it, thanks.

**Comment by Swan** [comment]
This is not a Quaver issue. It is an issue with either [MonoGame](https://github.com/MonoGame/MonoGame) or your hardware. The issue should be redirected there instead.
