### ISSUE TITLE
Game doesn't start anymore after setting "custom fps" to unreasonably high values

### ISSUE THREAD

**Issue by XeZey** [Quaver/Quaver#3885]
### Describe the bug

I set the custom fps to 6000000 because I thought it would be interesting. I guess its really not that interesting after all. The game doesn't start anymore through steam or through the files once closed, and verifying the steam files doesnt do anything either.

### To Reproduce

1. Go to settings
2. Change the custom fps to something unreasonably high.
3. Attempt to play a map or close the game. In either case the game will crash/not restart afterwards.

### Expected behavior

Not being able to put a fps value that high (as its useless anyway), or not have it try to actually use that limit and instead just resort to "unlimited" (im guessing it somehow tries to enforce the cap of 6000000 idk?) (also yea I know you can change these settings outside of quaver back but idk if that means that this shouldnt be adressed)

### Log Files

[network.log](https://github.com/Quaver/Quaver/files/12448194/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/12448195/runtime.log)

**Comment by WarpABoi** [comment]
you can change the CustomFpsLimit back to something reasonable in the quaver.cfg file

**Comment by AiAe** [comment]
Will be fixed in next update
