### ISSUE TITLE
Set custom fps max value

### ISSUE THREAD

**Issue by AgmonBlynkos** [Quaver/Quaver#3886]
### Is your feature request related to a problem? Please describe.

Seeing how curiosity overtakes most people, the new function of setting custom fps should have a limit to lets say 2000 or somewhere there. So that people will not start creating issues over and over again about how they broke the game and won't start after setting custom fps to like 80 million.

### Describe the solution you'd like

Simply modify the function to add a max value it can take. If somebody does try to set an fps value over the limit make it throw an error like "invalid fps value" or something like that

**Comment by AiAe** [comment]
Will be fixed in next update
