### ISSUE TITLE
"Approaching the Blue Zenith" bug still exists in 1.2.0

### ISSUE THREAD

**Issue by VRcontrib** [Quaver/Quaver#3888]
### Describe the bug

The "Approaching the Blue Zenith" bug (last reported for version 0.24.0-0.25.0 on issue #2621) seems to be back. Since I couldn't reopen that bug report, I'll copy the original description and my comment here.

Original report from [Bentacool](https://github.com/Bentacool):
> I got the Blue Zenith achievement even though I am rank 600 global in 7k
> I should not have the Blue Zenith achievement
> ![image](https://user-images.githubusercontent.com/70726419/92177639-3aee2200-ee84-11ea-98d4-f3dc848e8d3c.jpg)
> ![image](https://github.com/Quaver/Quaver/assets/129344938/0e2db31d-423f-416a-b46a-fa372d0b5216)
> version 0.24.0

My comment:
>This issue still exists in 1.2.0! Not on my account, but I noticed it on a steam friend's account. User ID is [507704](https://quavergame.com/user/507704) if that helps. They're nowhere near 100 rank, but they somehow got the achievement on August 19, 2023.

### To Reproduce

To be honest, I'm not sure how to reproduce it. I don't think this person has the logs from that date, maybe you could figure something out by investigating their account on the website, or someone with access to the server(s) could access game or network request logs there.

### Expected behavior

The "Approaching the Blue Zenith" achievement is not earned if the user has never reached 100 global rank.

### Log Files

I don't think this person has the logs from that date.

### Screenshots

![image](https://github.com/Quaver/Quaver/assets/129344938/5be2a736-ebdc-4eab-858b-4161e215dbcf)
![image](https://github.com/Quaver/Quaver/assets/129344938/7114a810-e9d3-4d65-ad7f-e2171f14c1fe)
![image](https://github.com/Quaver/Quaver/assets/129344938/b6468784-93c0-492f-b1bd-58d3442c13cb)
![image](https://github.com/Quaver/Quaver/assets/129344938/d05b7c90-8143-427f-ad0e-9c54407d46ab)
![image](https://github.com/Quaver/Quaver/assets/129344938/d7798b78-1679-41fa-9d2d-4416a1715fdd)
![image](https://github.com/Quaver/Quaver/assets/129344938/29d274d4-cb1d-45d0-be2e-1ff8834cbc1b)

**Comment by MatrixFurry** [comment]
Thank you for your response!

Will you also remove the achievement from anyone else that submitted a score during that time frame? Also, are you just removing it from Quaver profiles, or is there a way to also remove it from the Steam accounts connected to them?

Thank you,
A VRContrib contributor.

**Comment by VRcontrib** [comment]
As well as what @MatrixFurry commented, will there be fixes so this doesn't happen again in the future @Swan?

**Comment by Swan** [comment]
Just report it as it comes up. It was a rare case.

**Comment by MatrixFurry** [comment]
Hey, @Swan

The achievement still isn't removed, as a reminder the user id is [507704](https://quavergame.com/user/507704).

Thank you!
