### ISSUE TITLE
Exporting skins

### ISSUE THREAD

**Issue by seezuire** [Quaver/Quaver#3892]
### Describe the bug

When trying to export a skin to save for when Quaver updates again (because if you edit a uploaded skin, whenever Quaver updates it resets the skin back to how it was uploaded on the workshop), it doesn't necessarily open the folder for exports but instead my folder on "This PC".
This issue has been happening for a while as though I haven't experienced it, a friend of mine has when trying to send his skin and had to upload it in a dropbox.

### To Reproduce

1. Go to Settings, Skin
2. Click on Export Skin
3. Your folder may either open exported skins or just your folder

### Expected behavior

The exported folder is meant to open. 

### Log Files

[network.log](https://github.com/Quaver/Quaver/files/12489651/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/12489652/runtime.log)

8:37pm  ^

### Screenshots

https://cdn.discordapp.com/attachments/708421152674021497/1146891741941743616/Quaver_2023.08.31_-_20.37.15.01_Trim.mp4
hopefully this works to download

**Comment by AiAe** [comment]
Tested on Windows 11 with Canary (same version as you) cannot replicate.
The video linked also does not work, please download it and just upload directly to here.

**Comment by seezuire** [comment]
I'm on a Windows 10
https://www.youtube.com/watch?v=ORjucS40Vws&ab_channel=seez Uploaded to YT

**Comment by Swan** [comment]
- What is the name of the skin that you're trying to export?
- Is it on the workshop? If so, could you link the skin?

**Comment by Swan** [comment]
Closing due to no response and unable to replicate. 

Please respond with answers to the above questions, so we can open the issue again.
