### ISSUE TITLE
Cannot delete words in search bar

### ISSUE THREAD

**Issue by Nexility0** [Quaver/Quaver#3898]
### Describe the bug

this is within the map downloading screen. where if you search for any song specifically; once exiting and going back to download page the position of the curser is wrong. it is at the start of the search bar causing the ability to not be able to delete anything in the search bar. arrow keys do not work either as they just change the selected song

### To Reproduce

1. go to map download screen
2. in search bar put any word, phrase or letters to search for songs
3. exit the menu
4. go back into the menu
5. it saves the previous search and places curser at the start of search bar
6. cannot use backspace to delete the previous search

### Expected behavior

either the map download screen shouldn't save the previous search or the curser saves it's last position and re-loads it so you can delete words, phrases etc.

(the only way to have a clear search bar is by closing & reopening Quaver)

### Log Files

[network.log](https://github.com/Quaver/Quaver/files/12510146/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/12510147/runtime.log)

### Screenshots

https://github.com/Quaver/Quaver/assets/143315101/48e76b32-71b2-4e38-9203-baf9d4e1d9a3

https://github.com/Quaver/Quaver/assets/143315101/cc4ff4ab-7af3-404d-a740-d8fe8976247f

**Comment by Nexility0** [comment]
i forgot to mention but when i was switching songs i was trying to use arrow keys to move the curser

**Comment by WarpABoi** [comment]
already fixed in https://github.com/Quaver/Wobble/pull/134

**Comment by Nexility0** [comment]
ah ok!

**Comment by WarpABoi** [comment]
until next release, you can press delete to delete characters forward
