### ISSUE TITLE
[Qua] Serializer misconverts "null" string to null value

### ISSUE THREAD

**Issue by AiAe** [Quaver/Quaver#3900]
### Describe the bug

If we set `DifficultyName: NULL` as our difficulty name, Quaver will fail to parse it and will result in black window.

Looks like that has been fixed in newer versions of YamlDotNet https://github.com/aaubry/YamlDotNet/pull/699

### To Reproduce

1. Change name from .qp.zip to .qp
[Frums_-_HALL_-_21928 - Copy.qp.zip](https://github.com/Quaver/Quaver/files/12528483/Frums_-_HALL_-_21928.-.Copy.qp.zip)
2. Import the file
3. Open editor

### Log Files

[runtime.log](https://github.com/Quaver/Quaver/files/12528487/runtime.log)

**Comment by Swan** [comment]
Fixed in [this commit](https://github.com/Quaver/Wobble/commit/bba6e46af3b8c25c47e06e9cbae5fa95bcb23df3). It's not that it fails to parse. It's that `SpriteTextPlus` couldn't handle when the text is null, so now it defaults to an empty string.
