### ISSUE TITLE
Add block user list

### ISSUE THREAD

**Issue by AiAe** [Quaver/Quaver#3903]
When muted players should not be able to:
1. Play multiplayer (and invite)
2. Spectate players

**Comment by WarpABoi** [comment]
so this should be a client side block list?

**Comment by AiAe** [comment]
> so this should be a client side block list?

From the sound of it yes, I assume we can store block list in either quaver.cfg divided by commas or new table in quaver.db. 
Where you can block anyone from right-clicking their username.
