### ISSUE TITLE
Note hit changing position

### ISSUE THREAD

**Issue by Nexility0** [Quaver/Quaver#3906]
### Describe the bug

I found this in a muti game with my friend where i chose a simple map and it had LN in it. for some reason i the LN note receptor AFTER getting hit moves up to above it. i do not have a way to reproduce as i do not know how/why it happened. i do have a video of it though during and after game restart.

### To Reproduce

Unknown

### Expected behavior

after getting hit the first note should dissapear and continue the long note as usual

### Log Files

[network.log](https://github.com/Quaver/Quaver/files/12585675/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/12585676/runtime.log)

### Screenshots

https://github.com/Quaver/Quaver/assets/143315101/774568ab-9f24-437d-90a6-e6c2b76aa71f

https://github.com/Quaver/Quaver/assets/143315101/c5d9d3c5-a310-4be1-99a0-a5acf1545558

**Comment by Swan** [comment]
You have a visual offset in the first video one. The behavior is correct.

**Comment by Nexility0** [comment]
i've been playing with that visual offset & skin for months and never experienced this. could it be like a one off time? or if i can find a way to reproduce just keep it closed

**Comment by Swan** [comment]
You changed the visual offset in the video which changed the behavior. This is normal. When you change the visual offset, the hitposition changes.

**Comment by Swan** [comment]
It updates when you reload the map.
