### ISSUE TITLE
Calibration screen crash

### ISSUE THREAD

**Issue by Nexility0** [Quaver/Quaver#3912]
### Describe the bug

When going into calibration screen (for audio offset) it crashes if you are averaging around 3 notes per second before the actual calibration starts

### To Reproduce

1. go to settings
2. Audio
3. 'calibrate' 
4. before actual calibration starts, average around 3 notes per second. 
5. crash

### Expected behavior

i'd assume that it would just calibrate depending on when the notes actually get hit on the receptors

### Log Files
[network.log](https://github.com/Quaver/Quaver/files/12706191/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/12706192/runtime.log)

### Screenshots

https://github.com/Quaver/Quaver/assets/143315101/56e5dcc2-5920-45e1-b1e1-0df964d128f1

**Comment by AiAe** [comment]
This looks like issue to your machine only, it has no access to the Songs folder.
[7:40:30] - RUNTIME - ERROR: System.UnauthorizedAccessException: Access to the path '/Users/elliott/Library/Application Support/Steam/steamapps/common/Quaver/Songs/' is denied.
 ---> System.IO.IOException: Permission denied

**Comment by AiAe** [comment]
Will close since its not Quaver related bug and can be resolved with google.
