### ISSUE TITLE
can't use clicks on the central UI

### ISSUE THREAD

**Issue by DominoKorean** [Quaver/Quaver#3915]
### Describe the bug

You cannot use features, including song selection and editor usage, through clicks.

I'm not sure what triggers it.
This bug has been present since a year ago,
and there have been instances where this issue persisted for several days.
There were also times when the bug was resolved after briefly hiding and reopening the game window.

### To Reproduce

I'm not sure what triggers it.

### Log Files

[network.log](https://github.com/Quaver/Quaver/files/12804306/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/12804307/runtime.log)

### Screenshots

https://youtu.be/ModXblUxnB8?si=e1bOgitEXQBSVNX0

**Comment by AiAe** [comment]
This is an old bug that i've tried to find out why it happens many times. 
Usually what triggers it is chat overlay + dropdowns and the only fix most of the times is to restart the game.
