### ISSUE TITLE
When I try to log in, it keeps loading forever and I can't connect.

### ISSUE THREAD

**Issue by Vipera-0** [Quaver/Quaver#3921]
### Describe the bug

![スクリーンショット (81)](https://github.com/Quaver/Quaver/assets/147840186/ec4dabe3-97e1-4a6f-90c7-33bd79dd0d9e)

### To Reproduce

1. Go to 'Login'
2. Click on 'LOG IN'
3. Can't log in

### Log Files

[network.log](https://github.com/Quaver/Quaver/files/12895094/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/12895095/runtime.log)

**Comment by AiAe** [comment]
There is on-going server maintenance.
You can join our Discord server if you want to get notified when its back https://quavergame.com/discord
