### ISSUE TITLE
visual bug

### ISSUE THREAD

**Issue by rhythm-flow** [Quaver/Quaver#393]
**Description**
on the very top of the screen and shifted to the right, textures appear when hitting notes which I assume should constitute hitting animations, in which case they are obviously out of place.
**To Reproduce**
1. select a track
2. wait for first note to fall
3. hit corresponding button
4. notice glitch in top of screen, to the right

**Expected behavior**
either for hit animations to not display, or appear where they should

**Screenshots**
https://youtu.be/aChPA6-tBxk

**Desktop:**
 - OS: win10
 - Version v0.12.0

**Additional context**
noticed today for first time, might be caused by recent changes

**Comment by JaanJah** [comment]
this is already known and issued here: https://github.com/Quaver/Quaver/issues/383
