### ISSUE TITLE
separate arrow/bar option for 7k and 4k

### ISSUE THREAD

**Issue by rhythm-flow** [Quaver/Quaver#394]
**Is your feature request related to a problem? Please describe.**
to play 4k, I have to go back to options menu and switch to arrow mode, and revert the change when done, or I get arrows in 7k. since no one uses arrows for 7k, there is obviously an issue here. 

**Describe the solution you'd like**
to be able to select 
4k -> arrows
7k -> bars
**Describe alternatives you've considered**
removing arrows for 7k entirely. nobody uses them that I know.

**Additional context**

**Comment by Sublimity** [comment]
If you're talking about the "Default Skin" selector in the options, it doesn't work like that. 

The Custom Skin & Default Skin options work in the way that, if no custom skin is chosen, then it will default to one of the Default Skin's, of which contains the default Bar and Arrow skin's. For custom skin's, the skin folder can contain a 4k and 7k folder, which then can be used to load sprites for either keymode.

Take a gander at #275

**Comment by rhythm-flow** [comment]
that's weird behavior for a default setting. I understand the point of it working like that, but it basically forces people to use a custom skin to have 4k arrows and 7k bars at the same time. which is ok. just not necessary.

**Comment by Sublimity** [comment]
Well not necessarily, you can just make a 4k skin that are arrows, and then have the default setting set to bar, so that when it attempts to load you're 7k skin (which doesn't exist), it'll just default to bars.

**Comment by rhythm-flow** [comment]
to rephrase, then, requesting for 4k to default to arrows and 7k to default to bars out of the box.

**Comment by Sublimity** [comment]
Tbh, doing that is pretty redundant, the reason the default skin feature is there, is so whenever certain skin elements are missing, then it'll default to those. So requesting a feature so it defaults to arrows for 4k and bars for 7k is pretty silly, other people might want the opposite, and having it defaulting to those defaults isn't worth doing.

**Comment by rhythm-flow** [comment]
so it's assumed people will use custom skins from the start, I see. well then, in that case this really is redundant. I'm sure you see why it would make sense otherwise.

**Comment by Sublimity** [comment]
No, the option for default skin's is so players have a choice, having to switch between bar/arrow for 4k/7k isn't that big of a deal as you think, and using custom skins is what most players will probably end up using in the end.

**Comment by rhythm-flow** [comment]
if its purpose is to give a choice in the sense that it lets players pick between the two styles, then it should include combinations, not just one or the other, but if it's just there to smooth things out when some skin elements are missing, then I'll assume it functions perfectly as is.

**Comment by Sublimity** [comment]
As i did say above, and as you just mentioned, it is indeed to smoothen things out when skin elements are missing from custom skins :P
