### ISSUE TITLE
Keyboard keys issues

### ISSUE THREAD

**Issue by Hinnaas** [Quaver/Quaver#3945]
### Describe the bug

Quaver is skipping some keys while I'm playing, resulting in losses. It's as if I press the keys, but it's not being registered, as if I'm not hitting the note.

It's not my keyboard! I tried with the laptop keyboard, and everything worked fine without any losses. I also attempted to play another rhythm game, and it worked normally. Quaver seems to have an issue with the keyboard for me.

**Comment by AiAe** [comment]
What are your laptop specs? CPU, RAM, GPU.

**Comment by Hinnaas** [comment]
> What are your laptop specs? CPU, RAM, GPU.

CPU: Intel(R) Celeron(R) N4020C CPU 1.10ghz

RAM: 4GB Ram

GPU: Intel(R) UHD Graphics 600

**Comment by AiAe** [comment]
So, the engine we use on Quaver is known to not run very well (or at all) on such old hardware. 
There is nothing we can do, thus I will be closing this issue.
