### ISSUE TITLE
cant open settings

### ISSUE THREAD

**Issue by acoolusername12** [Quaver/Quaver#3950]
### Describe the bug

i can get into the game just fine i cant get into the settings it wont let me change anything ive tried fixing the files ive tried deleting the game and reinstalling it it just crashes the moment i try to open my settings does anyone know how to fix this

### To Reproduce

s

### Expected behavior

s

### Log Files

s

### Screenshots

s

**Comment by AiAe** [comment]
Please send your logs, without them we cannot help you.
