### ISSUE TITLE
Game Crash if use of 1-4 in map editor

### ISSUE THREAD

**Issue by Hifty** [Quaver/Quaver#3953]
### Describe the bug

The game crashes if you use the place object many times with 1, 2, 3, 4 add a note at where the scroll is. did not work in 7k only 4k

### To Reproduce

1. Go to editor level (4k)
2. spam 1-4 while playing song (still in editor)
3. game crashes

### Expected behavior

game will crash, after using the 1-4 function of placing notes only in 4k (from what ive tested.)

### Log Files

[runtime.log](https://github.com/Quaver/Quaver/files/14071338/runtime.log)

**Comment by Warp9000** [comment]
By the logs it looks like an issue with the skin you're using. Does it crash using the default skin?

**Comment by Hifty** [comment]
> By the logs it looks like an issue with the skin you're using. Does it crash using the default skin?

It does appear to be the case, thank you for the clarification! It does not crash using the default skin.

I will notify the skin creator if possible.
