### ISSUE TITLE
Custom maps wont download windows 11

### ISSUE THREAD

**Issue by gorillaglue44** [Quaver/Quaver#3954]
### Describe the bug

when i download a song, it says its all downloaded, but it just doesnt appear on any menu i go on and i cant play it

### To Reproduce

idk just when i download a song it doesnt

### Expected behavior

the song will download and i can play it

### Log Files

[network.log](https://github.com/Quaver/Quaver/files/14073734/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/14073735/runtime.log)

**Comment by AiAe** [comment]
From the logs it appears that the mapset your trying to download is broken, it says it has no hit objects or time points. 
Does this happen on all maps or just specific one/s?

**Comment by gorillaglue44** [comment]
all maps, it will just refuse to appear in multiplayer or singleplayer

**Comment by Warp9000** [comment]
Are you able to download maps from the website?
