### ISSUE TITLE
Download An Entire Playlist At Once

### ISSUE THREAD

**Issue by EpiCreeper** [Quaver/Quaver#3956]
### Is your feature request related to a problem? Please describe.

When I want an entire playlist downloaded i have to download the maps one at a time. This is tedious and I often accidentally skip a few maps with long playlists.

### Describe the solution you'd like

Add a "Download Playlist" button that would download all the maps at once. There could also be a "Download Playlist In Game" button that would download all the maps in game and would group them automatically.

### Describe alternatives you've considered

Just remove playlists from the game! (JK please don't)

### Additional context

Just so you know, this is especially annoying during Quaver tournaments.

**Comment by AiAe** [comment]
Probably wont happen, as alternative for now I can suggest u to use https://chromewebstore.google.com/detail/linkclump/lfpjkncokllnfokkgpkobnkbkmelfefj

**Comment by EpiCreeper** [comment]
bruh
