### ISSUE TITLE
Skin elements break on Arch Linux (local and workshop)

### ISSUE THREAD

**Issue by Dragon3328** [Quaver/Quaver#3961]
### Describe the bug

Almost all skin elements that are in play can break on arch Linux. Exported skins also break even if the non exported version works properly. Some skins work perfectly, some skins are half and half and some skins completely break and just become the default skin. You also cant view the skin in the folder when clicking "view skins" it just shows up with nothing. 

### To Reproduce

Simply go on any skin and test it. Main examples of skins that dont work are Scattered (Bojiis year end skin), Plox circles (jkzu edit) and sanik circle skin 2022

### Expected behavior

The skin elements should work properly on all skins

### Log Files
[runtime.log](https://github.com/Quaver/Quaver/files/14289393/runtime.log)

### Screenshots

![image](https://github.com/Quaver/Quaver/assets/160070302/52562a99-5614-4c89-8fdf-580a8fc2926c)
![image](https://github.com/Quaver/Quaver/assets/160070302/f5114242-3092-49e9-97ca-4ea62c5db2a8)

**Comment by Warp9000** [comment]
Could you edit your issue to include the log files instead of pasting it in.

**Comment by Dragon3328** [comment]
> Could you edit your issue to include the log files instead of pasting it in.

done that sorry

**Comment by AiAe** [comment]
@Dragon3328 if i remember correctly this is most likely caused because the skin files are not named properly upper/lower case wise. Which means the game fails to find those files and load them.
