### ISSUE TITLE
Completed a song before ending it.

### ISSUE THREAD

**Issue by elproticus22** [Quaver/Quaver#3962]
### Describe the bug

So, basically what happened was that, i was playing galaxy collapse, the ranked one, and suddendly at the begin of the song the screen became black and i ended the song with 98% acurracy before it ended, when my best record was 89%. I dont know what happened but i dont want to geta ban or something like that for hacking.

### To Reproduce

I dont know how or why it happened, i was just playing normally when it ocurred.

### Expected behavior

I was expecting to play normally.

### Log Files

[runtime.log](https://github.com/Quaver/Quaver/files/14315721/runtime.log)

### Screenshots

![WhatsApp Image 2024-02-16 at 3 29 45 PM](https://github.com/Quaver/Quaver/assets/160279798/1121d114-555f-4f6b-9ebe-cf581ce568bc)
![WhatsApp Image 2024-02-16 at 3 30 01 PM](https://github.com/Quaver/Quaver/assets/160279798/345ea00c-c64a-49c1-bfb0-2b4780eba75d)

**Comment by AiAe** [comment]
@elproticus22 thanks for reporting this, your score will be soon deleted.
