### ISSUE TITLE
Editor cannot make new mapsets when dragging mp3 files into the editor.

### ISSUE THREAD

**Issue by WIngs4505** [Quaver/Quaver#3967]
### Describe the bug

When I try to drag an mp3 file in to make a new mapset, the mp3 file doesn't get dragged into Quaver and the new mapset isn't created. The mp3 file doesn't disappear from the place it was dragged from, and the editor is still requesting for an mp3 file to be dragged in to make a new mapset for. Even when I copy-paste it, the mapset still isn't created. The mp3 file's size was around 10 megabytes at around 4 minutes and 20 seconds in length, with a bitrate of 192kbps and a sample rate of 48000.

### To Reproduce

1. Go to the singleplayer song select menu
2. Right-click any difficulty of any mapset and select "Edit" from the drop-down menu.
3. Click "File" from the top-left corner of the editor menu and select "New Song" from the drop-down menu.
4. Select any mp3 file you have on your computer and attempt to drag it or copy-paste it into the game window.

### Expected behavior

The mp3 file should be accepted and a new mapset should be created. The editor menu should show the new empty chart made for the new mapset.

### Log Files

[runtime.log](https://github.com/Quaver/Quaver/files/14427252/runtime.log)
[network.log](https://github.com/Quaver/Quaver/files/14427253/network.log)

### Screenshots

![Screenshot 2024-02-27 194257](https://github.com/Quaver/Quaver/assets/108817663/5c2a7990-d405-4f6e-adac-eafa0ab4c51b)
A screen shot of my system build

**Comment by Warp9000** [comment]
If you haven't already, try dragging it onto the game in windowed mode.

**Comment by AiAe** [comment]
@WIngs4505 make sure Quaver and Steam are not running as admin.

**Comment by WIngs4505** [comment]
> If you haven't already, try dragging it onto the game in windowed mode.

That is how I drag my songs in as I only use one monitor.

**Comment by WIngs4505** [comment]
> @WIngs4505 make sure Quaver and Steam are not running as admin.

I don't run any of my steam games with admin privileges as they're unnecessary.

**Comment by AiAe** [comment]
> > @WIngs4505 make sure Quaver and Steam are not running as admin.
> 
> I don't run any of my steam games with admin privileges as they're unnecessary.

And you are 100% sure? Since the logs contain nothing about that your trying to drop something into the game, which leads me to think that the game has higher privilege than your user.

**Comment by WIngs4505** [comment]
> > > @WIngs4505 make sure Quaver and Steam are not running as admin.
> > 
> > 
> > I don't run any of my steam games with admin privileges as they're unnecessary.
> 
> And you are 100% sure? Since the logs contain nothing about that your trying to drop something into the game, which leads me to think that the game has higher privilege than your user.

That is interesting, I'll look at the permissions that my computer allows for Quaver.

**Comment by Warp9000** [comment]
@WIngs4505 Did you manage to solve your issue?
