### ISSUE TITLE
Sound and maps not working on bazzite linux

### ISSUE THREAD

**Issue by EeveeZipYT** [Quaver/Quaver#3981]
### Describe the bug

When i start the game, i can't hear any sound, and when i try to play a map, i starts scrolling, but stops.

### To Reproduce

Open up Quaver on the latest version of Bazzite Linux.

### Expected behavior

Hear sound and play the game normally.

### Log Files

[network.log](https://github.com/Quaver/Quaver/files/14621858/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/14621859/runtime.log)

**Comment by Warp9000** [comment]
You should take a look at the pins in the #help channel on the discord server.
