### ISSUE TITLE
Option to disable rendering timing lines in editor

### ISSUE THREAD

**Issue by ESV-Sweetplum** [Quaver/Quaver#3999]
### Is your feature request related to a problem? Please describe.

I made a timing line animation called [AFFINE](https://github.com/ESV-Sweetplum/AFFINE), which can often place hundreds or thousands of timing lines at a time. When it comes to SVs, this isn't much of an issue, but large numbers of timing lines seem to drop performance significantly.

### Describe the solution you'd like

A new option in the settings panel, allowing you to skip rendering of timing lines. This should greatly boost performance.

### Describe alternatives you've considered

Kusa made the timing lines underneath the map in [cherry blossoms explode across the dying horizon](https://quavergame.com/mapset/map/35926), but this has a few flaws:

1. These timing lines are not accessible within the editor (obviously excluding Timing Line Viewer), making them hard to delete using plugins.
2. Changing the SVs between the start and the animation will completely break the animation, due to the fact that timing lines are displaced by a constant MSX distance.

AFFINE adjusts for this by placing the timing lines during the animation itself, instead of outside of it. This fixes the two issues listed above, but can slow or even crash the game on low-end devices. This setting would make timing line plugins more accessible to the general public.

**Comment by Warp9000** [comment]
added in https://github.com/Quaver/Quaver/pull/4021
