### ISSUE TITLE
Add bookmark support to plugins

### ISSUE THREAD

**Issue by ESV-Sweetplum** [Quaver/Quaver#4000]
### Is your feature request related to a problem? Please describe.

Looking in the `map`, `utils`, and `actions` enums (located [here](https://github.com/Quaver/Quaver/tree/ui-redesign/Quaver.Shared/Screens/Edit/Plugins)), there seems to not be any support for bookmark creation, editing and deletion. 

### Describe the solution you'd like

Add the following type: `BookmarkInfo`

Implement the following method to `utils` (located at [EditorPluginUtils.cs](https://github.com/Quaver/Quaver/blob/ui-redesign/Quaver.Shared/Screens/Edit/Plugins/EditorPluginUtils.cs)):
```cs 
// Return a bookmark object given a time and string
BookmarkInfo CreateBookmark(double time, string note);
```

Implement the following methods to `actions` (located at [EditorActionManager.cs](https://github.com/Quaver/Quaver/blob/ui-redesign/Quaver.Shared/Screens/Edit/Actions/EditorActionManager.cs)):
 ```cs
// Add a bookmark to the map
void PlaceBookmark(BookmarkInfo bookmark);

// Add a table of bookmarks to the map
void PlaceBookmarkBatch(List<BookmarkInfo> bookmarks);

// Remove a bookmark from the map
void RemoveBookmark(BookmarkInfo bookmark);

// Remove a table of bookmarks from the map
void RemoveBookmarkBatch(List<BookmarkInfo> bookmarks);
```

Implement the following values to `action_type` (located at [EditorActionType.cs](https://github.com/Quaver/Quaver/blob/ui-redesign/Quaver.Shared/Screens/Edit/Actions/EditorActionType.cs)):
```cs
AddBookmark,
AddBookmarkBatch,
RemoveBookmark,
RemoveBookmarkBatch
```

Implement the following method to `map` (located at [EditorPluginMap.cs](https://github.com/Quaver/Quaver/blob/ui-redesign/Quaver.Shared/Screens/Edit/Plugins/EditorPluginMap.cs)):
```cs
// Returns a table with all bookmarks in the map
List<BookmarkInfo> Bookmarks { get; [MoonSharpVisible(false)] set; }

// Gets the most recent bookmark at a given time
BookmarkInfo GetBookmarkAt(double time);
```

This would make bookmarks catch up to scroll velocities, in terms of plugin support.

### Describe alternatives you've considered

I have not considered anything else, as I do not know or work with C#.

**Comment by ESV-Sweetplum** [comment]
Thanks for your help so far.

I looked through the code and noticed that you used `AddBookmarkBatch` instead of `PlaceBookmarkBatch` in [EditorActionManager.cs](https://github.com/Quaver/Quaver/pull/4001/files#diff-4396ba853bab10af14301e3788b8d54ce83c06352dde5d06ac6ddf97ddc03214). Was this intentional? Note that the names in `EditorActionManager.cs` are different from `EditorActionType.cs`: creation of something is usually always prefaced with "Place". Besides that, fantastic work and thanks for the quick commits.

**Comment by QiuFeng54321** [comment]
Though I hardly believe that anyone has utilised this in anything big (possibly as storing data?), so it might not actually be a big issue. It's up to the developers to decide.

**Comment by ESV-Sweetplum** [comment]
Interesting, I suppose that's why `PlaceBookmark` didn't work when I was doing testing for this issue. I also have not seen any plugin developer utilize bookmarks at all yet; I asked Ice about bookmark support a few months back and it didn't seem to be supported at all.

**Comment by ESV-Sweetplum** [comment]
It's alright, I mostly use `actions.PerformBatch()` anyways (one undo is a necessity when dealing with thousands of timing lines and svs), so having that naming be consistent is good enough for me.
