### ISSUE TITLE
song name didn't show up

### ISSUE THREAD

**Issue by aaronjdb15** [Quaver/Quaver#4002]
### Describe the bug

i was scrolling through my songs and one of the song names didn't show up

### To Reproduce

idk

### Log Files

idk

### Screenshots

![Untitled](https://github.com/Quaver/Quaver/assets/127987870/cd4822fd-f4c5-4c2e-a414-9a6348f7f605)

**Comment by QiuFeng54321** [comment]
This map is probably [Cupid](https://quavergame.com/mapset/map/118376). Can you check if the bug still exists? 
+ If you scroll to this map do you still see this glitch?
+ If you go to global leaderboards of this map, does it show a orange button titled `UPDATE`? If so, after updating, doe it still show up? It seems like the author is different (changed name)
+ Can you send a `runtime.log` when the glitch happens again?
