### ISSUE TITLE
Universal keyboard support

### ISSUE THREAD

**Issue by Adrriii** [Quaver/Quaver#401]
You could use FNA (looks very related to XNA) for converting keycodes and supporting all keyboards with minimal effort.

If you tell me where you handle all the keyscans i'll try to implement it but i'm not sure i will be able to, since it might be an extension to XNA and i don't really want to meddle with structure.

https://github.com/FNA-XNA/FNA/wiki/5:-FNA-Extensions#getkeyfromscancodeext

**Comment by Swan** [comment]
Duplicate of #297
