### ISSUE TITLE
its showing leaderboard and i din't buy the donatation

### ISSUE THREAD

**Issue by moa8th** [Quaver/Quaver#4019]
### Describe the bug

when i opened quaver and select song i saw leaderboard working without donatation!

### To Reproduce

1.Start quaver  2.select any song 3.look at leaderboard

### Log Files

IDK the logs

### Screenshots

![Base Profile Screenshot 2024 04 09 - 13 27 34 83](https://github.com/Quaver/Quaver/assets/106300728/0fa53ee1-329d-4299-94f1-6603a13d7054)

**Comment by Warp9000** [comment]
Ranked global leaderboards are visible to anyone.
