### ISSUE TITLE
Preserve editor window layout

### ISSUE THREAD

**Issue by WilliamQiufeng** [Quaver/Quaver#4039]
### Is your feature request related to a problem? Please describe.

Mappers have to reopen a bunch of windows every time they edit a map.

### Describe the solution you'd like

Store the editor layout so it can be restored

**Comment by ESV-Sweetplum** [comment]
Ideally, state for the plugin should not be conserved between editor sessions.

**Comment by QiuFeng54321** [comment]
> Ideally, state for the plugin should not be conserved between editor sessions.

Do you mean the plugin shouldn't save anything in e.g. input fields?

**Comment by AiAe** [comment]
Would love this to be also extended to save the boxes x/y for details, composition tools, layers and hitsounds.
