### ISSUE TITLE
Linux text rendering issues

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#404]
**Describe the bug**
All text is blurry and gets cut off or split into two lines (and cut off):

**Screenshots**
![image](https://user-images.githubusercontent.com/1794388/50516576-93b8c500-0abc-11e9-9610-6a6f0ca36dda.png)
![image](https://user-images.githubusercontent.com/1794388/50516588-a632fe80-0abc-11e9-8265-806f8559bb7e.png)

**Desktop (please complete the following information):**
- Arch Linux x64
- Quaver from #403

**Comment by Swan** [comment]
We'll most likely have to re-do how text is handled. Currently it seems to only work on certain operating systems. This should preferably be done before I can merge #403

**Comment by YaLTeR** [comment]
Well, this issue is more annoying than anything and merging #403 makes the game actually perfectly playable on Linux, which I'd argue is rather important. But you've a better judgement here so ¯\\\_(ツ)_/¯

**Comment by Swan** [comment]
Agreed. If it's playable, then we can merge. However, it's of course not going to be deployed on Steam for linux until the text issue is fixed.

**Comment by YaLTeR** [comment]
Fixed by https://github.com/Quaver/Wobble/pull/25
