### ISSUE TITLE
A "no LN" mod

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#406]
One of my friends hates LNs so I suggested implementing a no LN mod. The idea is to replace all LNs with regular notes at the start.

I started looking into the code to implement this, and I've some questions regarding the implementation. Since we want to change LNs to regular notes, which affects several parts of the game, it makes sense to do the change in the map object somewhere around here, before any computations are done:
https://github.com/Quaver/Quaver/blob/1b7f70943e32bb5d2fd83dbafd0d58f04ce44144/Quaver.Shared/Screens/Gameplay/Rulesets/GameplayRuleset.cs#L58-L66

However I'm not sure if map objects are reused, because if they are then obviously changing something will do that permanently. How should I go about implementing this?

**Comment by Swan** [comment]
This is relatively easy to do. You can create a new [Qua](https://github.com/Swan/Quaver.API/blob/master/Quaver.API/Maps/Qua.cs) object - which is essentially the .qua map file that gets parsed and used for gameplay. After doing so, you can use the newly created object and set it [here](https://github.com/Quaver/Quaver/blob/develop/Quaver.Shared/Screens/Loading/MapLoadingScreen.cs#L83) if the mod is activated.

**Comment by YaLTeR** [comment]
So I was in the middle of implementing the mod when I realized it affects the difficulty rating, and the relevant code doesn't seem very extensible:
https://github.com/Quaver/Quaver/blob/7e1392f9a071de9a55a992fbccce4922292503ed/Quaver.Shared/Database/Maps/Map.cs#L298-L318

How should I handle this?
