### ISSUE TITLE
Unable to Load Map Files

### ISSUE THREAD

**Issue by RoxLoxB** [Quaver/Quaver#4065]
### Describe the bug

I unable to load maps after i reset my PC, I dont know the cause of this, once i reset this PC. 
System Disk (C) is clear without steamapp game data in there, so before I going in there. I already tried reinstalling the game, even deleting the current folder of Quaver map, and reinstall again still cannot do Edit Mode. Installed files, Verify Integrity of Game files also didnt work, though it says "All 363 files successfuly validated". 

If you mind to tell me/us how Edit mode works in Quaver, it would be really helpful.
Side note : It works perfectly before i reset this pc which i downloaded it from.. 2022.

If the cause needed Quaver in steamapps from System Disk, give me a reason why i should do that before proceeding.
Like, does Quaver needed something in System Disk? beside making the game smoother (?), or really that's the crucial part?
If else, likewise to tell~

After the reset :
While playing the map, it works perfectly fine, but when I entered Edit Mode, instant kick out (cannot enter Edit Mode).
I'm saying all this to save abit of time

![image_2024-04-16_100305485](https://github.com/Quaver/Quaver/assets/167156015/8864ed82-5879-48ab-98d4-e3b3145c813a)
![image_2024-04-16_100445654](https://github.com/Quaver/Quaver/assets/167156015/a611b72e-db4b-4d3d-8139-fbce007ef61f)

### To Reproduce

What error?

### Expected behavior

To play able use Edit mode normally

### Log Files

[runtime.log](https://github.com/Quaver/Quaver/files/14986572/runtime.log)
[network.log](https://github.com/Quaver/Quaver/files/14986573/network.log)

### Screenshots

![image_2024-04-16_100305485](https://github.com/Quaver/Quaver/assets/167156015/8864ed82-5879-48ab-98d4-e3b3145c813a)
![image_2024-04-16_100445654](https://github.com/Quaver/Quaver/assets/167156015/a611b72e-db4b-4d3d-8139-fbce007ef61f)

**Comment by AiAe** [comment]
It appears that your missing some library we require, try verifying the files from Steam.
![image](https://github.com/Quaver/Quaver/assets/3695158/887f39dd-e270-4ea6-af5d-39d74f53f264)

**Comment by RoxLoxB** [comment]
Yooo, thanks. I needed to restart my computer and then it works again, idk which one but all of method mention works
