### ISSUE TITLE
Change Ranked Map Metadata

### ISSUE THREAD

**Issue by EpiCreeper** [Quaver/Quaver#4070]
### Is your feature request related to a problem? Please describe.

Some ranked maps just have errors in their metadata, such as incorrect sources or missing credit. As it is right now, ranked maps can't be changed in any way. This is understandable for the charts themselves - trolls could turn their ranked maps to unholy unrankable abominations. Not to mention, RS would potentially have to check a flawless map multiple times. However, I think this could be relatively harmless if done right with metadatas.

### Describe the solution you'd like

I think a good way to handle this would be through the website. The levels creator could request to edit a specific section of the metadata, like the tags or the source. If the map is ranked, the edit request would be sent to supervision, and an RS would need to verify it before it's applied.
![temp](https://github.com/Quaver/Quaver/assets/77532703/9059a974-ce83-4f3a-852e-66004e44996c)
The changes would be marked as metadata only changes - a new type of update that doesn't affect scores. These will update in game the same way you update outdated mapsets.

### Describe alternatives you've considered

A different approach is to enable metadata altering only to the RS. Mappers could simply ask them to make changes to any map submitted to the ranking queue.
While I like the other method better, This one seems easier to implement and sustain, sense it doesn't require a separate queue to keep track of all the requests. It would also require less moderation and would generally take less work.

### Additional context

I know this idea would probably never get added, but I do think it can solve a few problems with Quavers maps. I've seen quite a few maps with incorrect capitalization, wrong sources and not to mention outdated RC standards. This change could also be really useful for modding.

**Comment by Reihynn** [comment]
the problem with this approach is that it doesn't change the ingame metadata, and it's quite impossible to change up metadata to already downloaded songs

**Comment by Warp9000** [comment]
We cant change the metadata of the maps without the hash being modified.
