### ISSUE TITLE
Osu mania sv convert not working properly

### ISSUE THREAD

**Issue by RGZN-Vanquish** [Quaver/Quaver#4081]
### Describe the bug

A couple sections of the sv chart does not work as intended.

### To Reproduce

Play the map on quaver. does not change at all

### Expected behavior

The sv to be the exact same as it is on osu mania.

### Log Files

[runtime.log](https://github.com/Quaver/Quaver/files/15090987/runtime.log)

### Screenshots

https://www.youtube.com/watch?v=KWKUZfarm4A (this is the osu! version working as intended)
https://www.youtube.com/watch?v=rLwBob42ITc (this us the quaver version NOT working as intended)
i have the export aswell for quaver. Can't put it here though lol but https://osu.ppy.sh/beatmapsets/2073593#mania/4340334
this is the mania link here. discord is RGZN or ATP RGZN and if you need anything else hmu :D

**Comment by Warp9000** [comment]
you put the same video 2 times
