### ISSUE TITLE
Make a lane cover possible

### ISSUE THREAD

**Issue by EliteDreamer** [Quaver/Quaver#409]
As the title says I would love you to make possible lane covers.
Osu style lane covers should be more than doable with the current code, you need to separate hitposition and receptor position:
-In "GameplayPlayfieldKeys.cs" line 77:
-- from "return WindowManager.Height - (skin.ReceptorPosOffsetY + LaneSize * skin.NoteReceptorsUp[0].Height / skin.NoteReceptorsUp[0].Width)" to "return WindowManager.Height - LaneSize - skin.HitPosOffsetY";
-In "GameplayPlayfieldKeysStage,cs" line 268:
-- from " Position = new ScalableVector2(posX, ReceptorPositionY)" to " Position = new ScalableVector2(posX, Skin.ReceptorPosOffsetY)";
I've to add another line of code but I don't remember where it is but substantially makes the hitpos actually move otherwise it stays fixed on the bottom;
The only thing I dunno is what's the use for "skin.NoteReceptorsUp[0].Height / skin.NoteReceptorsUp[0].Width" in "GameplayPlayfieldKeys.cs" line 77 otherwise it's a pretty decent modification (still not 100% sure) 
Another possibility is to allign the hitposition with the bottom of the receptor I mage instead of the top but I'm not sure about that since I've not tested it.
I would like you to test it since I'm not a coder and I'm not sure it's a good modification also I want my  keyyyyy :angry:

**Comment by staravia** [comment]
I don't quite understand this post, but it's already possible to create your own lane cover by configuring the Stage-Distant-Overlay image.

**Comment by EliteDreamer** [comment]
Oh didn't knew about that, may have missed it while looking arround with the skin wiki mb, closing it.
Tomorrow I'll try it
