### ISSUE TITLE
Using 1/48 snap in the editor turns all lines invisible

### ISSUE THREAD

**Issue by Storn42** [Quaver/Quaver#4093]
### Describe the bug

Switching to 1/48 snap in the editor turns all lines invisible. You have to zoom REALLY far into the chart for the lines to start appearing again. The line culling added in a recent update just feels to aggressive to the point where its more often a detriment than actually helpful.

### To Reproduce

1) open editor
2) switch to 1/48 snap

### Expected behavior

 I expect lines to not disappear so aggressively. 

### Log Files

[network.log](https://github.com/Quaver/Quaver/files/15152329/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/15152330/runtime.log)

### Screenshots

![4292024 12-52-37-417](https://github.com/Quaver/Quaver/assets/68167130/263b5cd0-5a2a-456f-be19-9e7b1c57e296)

**Comment by Emik03** [comment]
I'll make a fix in 2 days. I'm mostly leaving this comment as a reminder for myself to keep the current distance, but change it so that this only applies to the distance between 1/1 beat snaps, and not just any snap.
