### ISSUE TITLE
Chart not moving

### ISSUE THREAD

**Issue by will-zhang221** [Quaver/Quaver#4094]
### Describe the bug

when playing specific songs the chart doesnt move but you get misses, resulting in you eventually dying in singleplayer

### To Reproduce

play "dion timmer - shiawase"

### Expected behavior

the chart doesnt move 

### Log Files

not sure where to find in macos

### Screenshots

https://github.com/Quaver/Quaver/assets/114208579/24428f27-a27f-4548-a409-ab4e66027996

**Comment by Warp9000** [comment]
This is an SV map, its supposed to look like this.

**Comment by derwFi** [comment]
😭😭😭😭😭

**Comment by Warp9000** [comment]
You can turn on the NSV mod if you want to play it without SVs.
