### ISSUE TITLE
crash when click option

### ISSUE THREAD

**Issue by RifkyAdha** [Quaver/Quaver#4096]
### Describe the bug

when i try to go to the option the game always crash

### To Reproduce

1. click option

### Expected behavior

open option menu

### Log Files

[network.log](https://github.com/Quaver/Quaver/files/15168795/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/15168796/runtime.log)

**Comment by AiAe** [comment]
Those logs contain no crashes

**Comment by RifkyAdha** [comment]
https://drive.google.com/file/d/1N-bHFwALNmJg_Wu2AqpN44YeK_lpqnTJ/view?usp=sharing 
the screen record

**Comment by AiAe** [comment]
@RifkyAdha is there any reason why your on fallback 1.2 version still? Does this issue happen if you use stable 1.3?

**Comment by AiAe** [comment]
@RifkyAdha are you in our Discord server, I want to see Event Viewer logs to why the game might've crashed. 
And maybe send custom build just to test your crash, because I'm kinda going blindly on this.

**Comment by Circunia** [comment]
I encounter the samer problem, clicking on option make Quaver crash

**Comment by AiAe** [comment]
@RifkyAdha @Circunia does this issue still happen on latest Canary version?

**Comment by Circunia** [comment]
I uninstall/reinstall and this time it worked !

Le sam. 1 juin 2024 à 17:08, Daniel Dimitrov ***@***.***> a
écrit :

**Comment by RifkyAdha** [comment]
i just reinstall it in my ssd not my hdd, and suddenly the option its worked. i dunno why, but before i start reinstalled it in my ssd, i reinstalled it in my hdd and it still crashing when open the option

**Comment by AiAe** [comment]
I did push an update that probably fixed the issue, and since you both don't have it anymore, I will be closing the issue
