### ISSUE TITLE
Cmd-Tab doesn't work on macOS

### ISSUE THREAD

**Issue by sayofthelor** [Quaver/Quaver#4106]
### Describe the bug

Whenever I attempt to press Cmd-Tab on a Quaver window, it doesn't open any other window or the app switcher. My guess for this would be because Quaver doesn't seem to use the macOS fullscreen window API, instead drawing a window over the display. I tried to look through both Quaver and Wobble, but I'm not entirely sure where the code that handles this is. (If I find it, I'll make an update here)

### To Reproduce

1. Open game on a Mac
2. Press Cmd-Tab
3. See error

### Expected behavior

I expected either the macOS dock or app switcher to pop up and allow me to switch into another window.

### Log Files

N/A

**Comment by AiAe** [comment]
Can you test Canary version of the game, you can switch to it by going Properties > Betas and pick Canary from the dropdown, we have added support for Mac key binds which will probably resolve your issue.
Reopen the issue if you have this issue with Canary please.
