### ISSUE TITLE
The editor is really slow

### ISSUE THREAD

**Issue by Reycko** [Quaver/Quaver#4116]
### Describe the bug

I'm trying to map a song, but the editor is really slow and it takes up to 3 seconds to do an action like placing a note of flipping them etc...

### To Reproduce

1. Go to Editor
2. It's slow and laggy

### Expected behavior

A non-laggy and responsive editor

### Log Files

[network.log](https://github.com/Quaver/Quaver/files/15280875/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/15280876/runtime.log)

### Screenshots

https://github.com/Quaver/Quaver/assets/78082869/b7ad9ffa-05dd-452a-8666-66c71527a65b

**Comment by Emik03** [comment]
The next canary build has been shown to reduce lag spikes. Once the new build is out, consider opting in through the Steam Beta section and see if it helps at all.

**Comment by Storn42** [comment]
This is likely an issue with your .qua file. If you open the .qua file in notepad you'll probably find one or more notes at -2147483648. if you delete those you should find the editor running smoothly again.

**Comment by Reycko** [comment]
> This is likely an issue with your .qua file. If you open the .qua file in notepad you'll probably find one or more notes at -2147483648. if you delete those you should find the editor running smoothly again.

I saw a warning on the editor about that through AutoMod but I thought it was just an automod bug, thanks.

**Comment by Emik03** [comment]
We might be planning to add a pop-up warning the moment you accidentally place notes that far into the past or future to prevent repeat confusion.
