### ISSUE TITLE
Songs in None grouping already in playlists do not appear so in the context menu

### ISSUE THREAD

**Issue by dylan-park** [Quaver/Quaver#4117]
### Describe the bug

When right clicking a song in None sorting mode, and clicking Add to Playlist, songs will appear to not be in any playlists, even if they are in one

### To Reproduce

1. Right click a song, and click add to playlist
2. Once added to a playlist, you can confirm the song is in the playlist by opening Group By: Playlist, and opening the playlist you added the song into
3. When returning to None grouping with the song selected, you will not see the song in None grouping
4. You can re-search the song and see it in None grouping again, but when right clicking and selecting add to playlist again, the song will appear to not be in any playlists again

### Expected behavior

I would expect the checklist in the context menu to properly display playlists a song is already added to in all views.

### Log Files

[network.log](https://github.com/Quaver/Quaver/files/15281949/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/15281950/runtime.log)

### Screenshots

None Grouping:
![image](https://github.com/Quaver/Quaver/assets/5841057/97190830-15d9-4103-bcf4-79584fd2cd34)
Playlist Grouping:
![image](https://github.com/Quaver/Quaver/assets/5841057/d416eb7f-7b33-40fa-af94-18633410ba3e)
Same song

**Comment by dylan-park** [comment]
This appears to have been fixed in today's patch, issue no longer occurs

**Comment by AiAe** [comment]
There has not been any new patch?

**Comment by dylan-park** [comment]
> There has not been any new patch?

I had a 6.9kb update on canary, didn't say it was workshop content or anything, I just assumed. Either way issue is no longer occurring, I cannot reproduce it.
