### ISSUE TITLE
Cant download maps

### ISSUE THREAD

**Issue by epiccatt** [Quaver/Quaver#4131]
### Describe the bug

When I try to download maps it just keeps loading 

### To Reproduce

1. Click on "Download Songs"

### Expected behavior

I expected that it would finish loading

### Log Files

[network.log](https://github.com/Quaver/Quaver/files/15335408/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/15335409/runtime.log)

### Screenshots

![5162024 14-57-26-10](https://github.com/Quaver/Quaver/assets/95578349/dee5ef56-0388-402e-bd0c-0c3f086ca979)

**Comment by AiAe** [comment]
Run Steam & Game via flatpak

**Comment by epiccatt** [comment]
> Run Steam & Game via flatpak

didnt fix anything

**Comment by AiAe** [comment]
> > Run Steam & Game via flatpak
> 
> didnt fix anything

Can you send the logs again when your using flatpak?
