### ISSUE TITLE
Notes twitch erratically on Linux build (Ultramarine (Fedora) Linux 39 w/ Pipewire)

### ISSUE THREAD

**Issue by MeowcaTheoRange** [Quaver/Quaver#4139]
### Describe the bug

On Linux, notes will jitter at random times. Sometimes they will stay completely smooth, as normal gameplay should, but eventually will start to jitter as if the game is going back a few frames. For me, this causes confusion, as I can't specifically tell where in time the notes are. For others, this could be compared to certain SV effects.

This has also happened to me when I used to use Ubuntu Linux. I think for that, I was using PulseAudio.

Possibly like #3689, #3291, and #3287, but on PipeWire.
It's important to note that when I changed these settings as described:
```cfg
DevicePeriod = 5
DeviceBufferLengthMultiplier = 6
```
They went to this as soon as I restarted Quaver, and the issue still persists.
```cfg
DevicePeriod = 2
DeviceBufferLengthMultiplier = 4
```

### To Reproduce

Quaver settings:
- Screen Resolution / 1920x1080
- Enable Fullscreen / OFF
- Enable Borderless Window / OFF
- Frame Limiter / Limited (240 FPS)
- Audio Output Device / Default
- Enable High Process Priority / ON
- Prefer Wayland / OFF
- Use Smooth Audio/Frame Timing During Gameplay / ON

Quaver [canary] build 14415302 (Steam)
Ultramarine Linux 39
Linux 6.8.7-200.fc39.x86_64
KDE Plasma 5.27.11 on X11
Pipewire Compiled/Linked with libpipewire 1.0.5

Quaver in /mnt/steam/SteamLibrary/steamapps/common/Quaver/ (ext4)

NVIDIA GeForce GTX 1660 Ti (using proprietary drivers 550.76)
Lenovo Legion 5 15IMH05H

### Log Files

[runtime.log](https://github.com/Quaver/Quaver/files/15370223/runtime.log)
[network.log](https://github.com/Quaver/Quaver/files/15370224/network.log)

### Screenshots

Here is a video with PipeWire stopped, showing the jitter up-close.
[Video with PipeWire stopped](https://github.com/Quaver/Quaver/assets/58280776/33cf9b95-ce42-422f-bb2f-d7e77b14348b)
Here are some videos of what usually happens during normal gameplay. 
[Video with PipeWire enabled](https://github.com/Quaver/Quaver/assets/58280776/a1d1809b-df17-4f15-a638-e62a7cb13448)
[120 FPS video with PipeWire enabled](https://github.com/Quaver/Quaver/assets/58280776/cff84e2e-55db-4297-9001-6ad7035be44f)

### Notes
- Changing `Use Smooth Audio/Frame Timing During Gameplay` to `OFF` does not seem to affect the issue.
- I have experienced brief stutters in audio with PipeWire overall. I've "fixed" this by changing these settings: 
```conf
default.clock.quantum       = 2048
default.clock.min-quantum   = 1024
default.clock.max-quantum   = 8192
```
And adding `50-alsa-config.conf`.
```conf
monitor.alsa.rules = [
  {
    matches = [
      # This matches the value of the 'node.name' property of the node.
      {
        node.name = "~alsa_output.*"
      }
    ]
    actions = {
      # Apply all the desired node specific settings here.
      update-props = {
        api.alsa.period-size   = 1024
        api.alsa.headroom      = 8192
      }
    }
  }
]
```
The audio stutter is no longer present with these settings, but I suspect this could be assisting in the jitter on Quaver.

**Comment by AiAe** [comment]
> They went to this as soon as I restarted Quaver, and the issue still persists.
If you edit quaver.cfg, you must close the game first, so the changes you did wont be overwriten.

**Comment by MeowcaTheoRange** [comment]
Oh, thanks! This helped the issue, but it's still a little jittery at times.

[120 FPS video with new quaver.cfg settings](https://github.com/Quaver/Quaver/assets/58280776/a37d7378-9901-4fe6-928f-6c49c56fc145)

**Comment by MeowcaTheoRange** [comment]
Update: added some notes

**Comment by MeowcaTheoRange** [comment]
Any update on this? I tried playing Quaver again today on the latest Canary build and it was quite hard to play. The jitter it still present, and it looks like some offset has developed, even though I seriously do not remember changing any offset settings in Quaver. Maybe it's just because I have multiple monitors this time, or something.

BEFORE SETTINGS MENU:
Global Audio Offset / +4ms
AFTER SETTINGS MENU:
Global Audio Offset / +68ms

Anyway, my issue isn't with me having to fix my audio offset - it's more about how/why it changed like that. It could be the update, I dunno. I haven't played Quaver in a long time ever since I made this issue.

https://github.com/Quaver/Quaver/assets/58280776/55b61234-dd76-41d9-90ed-e44bbeedcbca

Same computer specs, just Quaver build 14571725 this time.

**Comment by Emik03** [comment]
Have you tried increasing `DevicePeriod` and `DeviceBufferLengthMultiplier` by a ton if it helped? Specifically 100 and 10 respectively.

**Comment by MeowcaTheoRange** [comment]
> Have you tried increasing `DevicePeriod` and `DeviceBufferLengthMultiplier` by a ton if it helped? Specifically 100 and 10 respectively.

y'know I don't know why I never thought "let's make the values obscenely large" This works perfectly Thank You

**Comment by MeowcaTheoRange** [comment]
Ok so turns out this delays audio by a TON and now Quaver recommends me a 159 ms offset... and the hitsounds are delayed :/
