### ISSUE TITLE
Bad image format exception

### ISSUE THREAD

**Issue by SunnyLii** [Quaver/Quaver#414]
**Describe the bug**

When I build Quaver in my Visual Studio, the dotnet.exe window would stop responding instantly, so I tried running it with debugging mode, which gave me this exception: Unhandled Exception: System.BadImageFormatException: Could not load file or asse
mbly 'C:\Users\Peeter\Desktop\quaver\Quaver\Quaver\bin\Debug\netcoreapp2.1\Quave
r.dll'. An attempt was made to load a program with an incorrect format.

**To Reproduce**

Error occurs right after building Quaver.

**Expected behavior**

**Screenshots**
https://i.imgur.com/QVP84mx.png

**Desktop (please complete the following information):**
 - OS: wind 8.1

**Additional context**

**Comment by Sublimity** [comment]
Try "Clean Solutionist o
