### ISSUE TITLE
Dont let anyone view steam profile.

### ISSUE THREAD

**Issue by FritzTom** [Quaver/Quaver#4145]
### Is your feature request related to a problem? Please describe.

You can view someones steam profile even when you're only able to view their profile.

### Describe the solution you'd like

It shouldn't be possible to view the steam profile from someone.

### Describe alternatives you've considered

You can only view the steam profile of someone when you are friends with them in game.

Adding a setting to disable the ability for others to see your steam profile.

### Additional context

Someone brought this issue to my attention when I noticed that the steam id is in the runtime log.

**Comment by Emik03** [comment]
Can't you just use Steam's "Profile Privacy" feature to determine what can be shown to people? https://help.steampowered.com/en/faqs/view/588C-C67D-0251-C276

**Comment by FritzTom** [comment]
Having a setting in the game would give users more control because I believe that the steam setting only allows you to change it globally and not per game.

**Comment by Emik03** [comment]
I don't see what's stopping people from doing a little bit more research, considering that Quaver's profile system couples it to a Steam profile by design.

**Comment by Reihynn** [comment]
every steam profile is public, if you don't want people to stalk you then you can make your account private using steam settings 👍
