### ISSUE TITLE
Plugins: Passing `nil` into ImGui causes game crash

### ISSUE THREAD

**Issue by Emik03** [Quaver/Quaver#4149]
### Describe the bug

\-

### To Reproduce

1. Download this plugin [crash.zip](https://github.com/Quaver/Quaver/files/15443964/crash.zip).
    - Alternatively, create a plugin with the following snippet:
    ```lua
    function draw()
        imgui.Button(nil)
    end
    ```

2. Install the plugin as you would with any other editor plugin.
3. Open the editor and load the plugin. Game crashes.

### Expected behavior

A script error shows up in-game instead. This isn't even niche, or something you do on purpose to crash the game, because this was discovered by accident on the fact that `nil` is a very easy value to accidentally slip in if you parameterize.

### Log Files

[network.log](https://github.com/Quaver/Quaver/files/15443967/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/15443968/runtime.log)

**Comment by AidanHsiao** [comment]
Passing a table into `imgui.Text(tbl)` also crashes the game

**Comment by Emik03** [comment]
Types don't have to be incorrect to cause a game crash either:
```cs
imgui.BeginTabItem("foo")
imgui.EndTabItem()
```

**Comment by Emik03** [comment]
I forgot to close this issue now that the ImGui version has been updated.
