### ISSUE TITLE
Quaver audio issues in nixos in a proxmox VE environment

### ISSUE THREAD

**Issue by rubiigen** [Quaver/Quaver#4150]
### Describe the bug

When running quaver on a proxmox nixos instance i get crackling and low pitched audio if my sound device is set to 'default'. changing this to my HDA device directly works but quaver cannnot change to this device consistently.

screenshots are as follows: 

1: game failing to launch with hda device set
2: audio device set as default, audio going to hda device "fine" but with audio crackling (obviously cant show in a picture
3: failure to manual change to hda device if hda device is default
4: failure to change is hda device is NOT default

### To Reproduce

1: launch the game in a nixos (or any linux, probably) install running under PVE with the onboard intel PCH audio passed through

2: observe crackling sound when audio device is set to default

3: observe issue go away if the default audio device in the sound server is not set to the analogue pch audio AND changing quaver to the analog pch audio device directly

4: observe game fail to change to analogue pch device if it is the default in the sound server

5: observe game fail to launch if analogue pch device is set in quaver and set as the default device in the sound server

### Expected behavior

game should work fine with no crackling and pitch issues regardless of audio device selected

### Log Files

[network.log](https://github.com/Quaver/Quaver/files/15453063/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/15453069/runtime.log)

### Screenshots

![image](https://github.com/Quaver/Quaver/assets/139723175/91992380-5a3f-49bf-b323-3d346af6083b)
![image](https://github.com/Quaver/Quaver/assets/139723175/8d3fd11c-2a20-447f-84ac-129294ec929d)
![image](https://github.com/Quaver/Quaver/assets/139723175/14cfe00a-cc54-4be0-9b3c-5dd56aa9e1bd)
![image](https://github.com/Quaver/Quaver/assets/139723175/397c6983-4541-4d16-827a-2ad16fde58d0)

**Comment by rubiigen** [comment]
to add more: these issues are not present if i boot this nixos install natively.

**Comment by rubiigen** [comment]
seemingly fixed now. just un-blacklisted snd_hda_intel on the proxmox install

**Comment by Emik03** [comment]
Thanks for leaving an issue anyway, as it'll be useful to link back on in the event of a duplicate or otherwise similar issue.
