### ISSUE TITLE
fullscreen

### ISSUE THREAD

**Issue by strawbzwafer** [Quaver/Quaver#4157]
### Describe the bug

screen goes completely black on macos when enabling fullscreen and can only command q to exit the game

### To Reproduce

(on macos) go to settings, video then enable fullscreen

### Expected behavior

???

### Log Files

???

### Screenshots

literally how does this help

**Comment by Warp9000** [comment]
Right click the game in your steam library
Go to Manage => Browse local files
![image](https://user-images.githubusercontent.com/59202433/260766613-c6f12d6c-8984-48ad-84d2-e562f250c8ab.png)
In the Logs folder you can find 2 files named runtime.log and network.log
