### ISSUE TITLE
cannot log in

### ISSUE THREAD

**Issue by the-biggest-birfd** [Quaver/Quaver#4166]
### Describe the bug

stuck in connecting to server

### To Reproduce

1. click log in
2. wait

### Expected behavior

a log in prompt

### Log Files

[network.log](https://github.com/user-attachments/files/15575622/network.log)
[runtime.log](https://github.com/user-attachments/files/15575627/runtime.log)

### Screenshots

![CleanShot 2024-06-05 at 15 11 06@2x](https://github.com/Quaver/Quaver/assets/132025093/036ccfde-ac0e-4cd9-b09d-5f3249d05e09)

**Comment by WilliamQiufeng** [comment]
Please try relogging into or restarting steam, and make sure you are online.
