### ISSUE TITLE
Skin Jukebox-overlay dimesions issue

### ISSUE THREAD

**Issue by A6sT** [Quaver/Quaver#4170]
### Describe the bug

After messing a bit with few skin component for the main menu, i found out that the jukebox-overlay dimensions that are written on the forum might be wrong.

### To Reproduce

Here's the process to follow to reproduce this issue. Note that this has been tested with the 1920x1080 and 2560x1440 screen resolutions.

Let's say i want to set this picture as my background image
![menu-background_1](https://github.com/Quaver/Quaver/assets/58571281/028bcf56-f23d-4c54-9cfc-dbce9499d3b1)

First of all, let's rename it to menu-background, and place it into the [skin]/MainMenu folder. Main menu should then look like this:
![menu-background_2](https://github.com/Quaver/Quaver/assets/58571281/4f4e7b13-9863-46df-a91c-5af79869f13f)

Now, imagine that i wanted to make the background take the whole screen; I'd have to remove the MenuBorder components, or at least make them transparents. Once this is done, my main menu looks like this:
![menu-background_3](https://github.com/Quaver/Quaver/assets/58571281/78c2e439-5204-415b-aac7-e309b03ab05b)

Last thing (and the trickiest part) is now to make the jukebox-overlay fit in with my background. To do this, I'll simply edit the background image to see the borders of the jukebox on the image:
![menu-background_bordered](https://github.com/Quaver/Quaver/assets/58571281/1b3f2185-d618-49dc-b6e0-8bcb22f7db8b)

I can now finally take what's inside of the box i made to end up with the "content" of my jukebox-overlay component, which should look something like this (as you can see, it also has the same dimensions as what is written on the wiki; 500x54)
![jukebox-overlay](https://github.com/Quaver/Quaver/assets/58571281/2e6ef662-89d3-49c2-a987-fb8da1f4b3ab)

Here's the final result, and where we can see that something went wrong during the process, because our jukebox-overlay seems to be off by a few pixels
![menu-background_incorrect](https://github.com/Quaver/Quaver/assets/58571281/9150210d-72d8-4ed6-a72f-ff6d892b2a6e)

### Expected behavior

The solution to this is, in my opinion, a simple question of knowing the right dimensions. 
From my testings i haven't been able to find the correct dimensions yet (the process to test each dimensions is very slow and painfull).
I also have no idea if this is hardcoded somewhere (sounds like a good lead for anyone out there who want to actually put a bit of effort into this very specific and gamebreaking issue), but wiki should at least be corrected once the good dimensions are found.

### Log Files

No log files needed for this issue

### Screenshots

See the "How to Reproduce" section

**Comment by AiAe** [comment]
[Fixed ](https://github.com/Quaver/Quaver.Wiki/pull/198)
