### ISSUE TITLE
Legacy LN Rendering shuts itself off when uploading a map.

### ISSUE THREAD

**Issue by rileyalphanumerics** [Quaver/Quaver#4175]
### Describe the bug

when you upload a map with Legacy LN Rendering enabled, it will upload the map, and the svs, but the Legacy LN Rendering option will be disabled when it is uploaded to the server.

### To Reproduce

1. place any amount of notes in a map file and fill the metadata with anything, as long as the map can be uploaded online, it should be fine.
2. enable Legacy LN Rendering in the metadata for the map.
3. upload the map to the server.
4. when the map is done uploading, reenter the map in the editor, and check the metadata again for Legacy LN Rendering, if the bug happens, it should be disabled once again.

### Expected behavior

I would expect that after uploading a map with Legacy LN Rendering enabled in the metadata, it would upload to the online server with Legacy LN Rendering enabled, so the SV effects will affect the LNs like how the mapper intends for them to.

### Log Files

-

### Screenshots

-

**Comment by Emik03** [comment]
Swan just rolled out an update to the Quaver servers (no need to update your game), and I have confirmed it now works. This issue will be considered resolved and therefore closed (by someone else).

**Comment by Emik03** [comment]
To be more specific, I made a [test map](https://quavergame.com/mapset/map/144162) demonstrating both `BPMDoesNotAffectScrollVelocity` and `LegacyLNRendering` staying persistent across upload.
