### ISSUE TITLE
"there was a issue creating a new mapset"

### ISSUE THREAD

**Issue by matrixmilanila** [Quaver/Quaver#4195]
### Describe the bug

when i drag the .mp3 file to quaver on windowed, it says there was a issue creating a new mapset, im on linux mint 21.3 virginia cinnamon.

### To Reproduce

1 - have linux mint virginia 21.3
2 - drag the mp3 file to quaver
3 - ERROR

### Expected behavior

it should display "There was a issue creating a new mapset"

### Log Files

[runtime.log](https://github.com/user-attachments/files/15944355/runtime.log)
[network.log](https://github.com/user-attachments/files/15944356/network.log)

### Screenshots

![image](https://github.com/Quaver/Quaver/assets/173608517/259499c4-23b3-40a8-8b74-faaa142110c5)

**Comment by Atavixion** [comment]
I found that quaver cannot handle 320kbps mp3 files, so when converting to a lover bitrate (160kbps) it worked fine.

**Comment by Warp9000** [comment]
not the issue, quaver cant access your home directory.
