### ISSUE TITLE
[linux] buttons that open a file manager prompt do nothing/silently fail

### ISSUE THREAD

**Issue by platonictf** [Quaver/Quaver#4208]
### Describe the bug

distro: artix linux (openrc)
desktop environment: kde plasma 6.1

when a file manager prompt is supposed to open, instead nothing happens and no explanation is given as to why

### To Reproduce

1. click on any button that should open a file manager prompt (open game folder for example)
2. nothing

### Log Files

[network.log](https://github.com/user-attachments/files/16091924/network.log)
[runtime.log](https://github.com/user-attachments/files/16091925/runtime.log)

### Screenshots

https://github.com/Quaver/Quaver/assets/156929034/a43401b0-6675-446f-bc6b-51d869de0ad8

**Comment by AiAe** [comment]
Our linux implementation of this requires xdg-open to be installed, otherwise it wont work.
