### ISSUE TITLE
A multiplayer command to skip current host

### ISSUE THREAD

**Issue by BlossomsPlace** [Quaver/Quaver#4230]
### Is your feature request related to a problem? Please describe.

The host can be afk for several minutes while everyone has to wait a long time (If they even come back) I think it would be good to have a vote skip current host command (transfer host to another player) also using !mp host doesn't work if you are not host if you try to use this as a way to transfer it won't work (not sure if that command was made for this issue)

**Comment by AiAe** [comment]
Creator of the lobby, already can use !mp host username to swap host. That should be enough.
