### ISSUE TITLE
Moving Notemaps

### ISSUE THREAD

**Issue by JulenV2010** [Quaver/Quaver#4234]
### Is your feature request related to a problem? Please describe.

There is a feature that I found that exists on certain engines on _Friday Night Funkin'_, and it's the fact that lanes can move around the screen, or come from anywhere. Similar to SVs, but with MUCH more movement.

### Describe the solution you'd like

In the _Editor_, on the _Tools_ section, you could find a section called Note Keyframes, this is basically a separate editor adjacent to the song currently being edited.

![632291ed0d884](https://github.com/user-attachments/assets/9f504acb-7b3e-4507-9c65-b6f65f4ce84c)
(Image is not mine) Whenever this _Tool_ opens, the user should see a menu like the one above.

- The bottom is the **keyframe sheet** for each lane.
- On the right are some **settings for the keyframes**.
- On the main screen, where the user can see the notes, this is the **preview area**.

On the settings, the user can also change easing types, from where the notes are coming from (a.k.a. Angle), and positions of the notes.

A solution that I've thought for Upscroll/Downscroll is that if the editor used Downscroll, but the player uses Upscroll, then _Y_ values on lanes should be inverted, to prevent issues where the lanes can leave the screen.

Additionally, there can be a modifier to **_remove_ this feature** before playing a song via the **modifier menu**

### Additional context

I know this sounds too ambitious, but in the website and Steam page, it reads "The **ultimate** community-driven, and open-source competitive rhythm game". **Ultimate** is the word that I focus on, and by adding this feature, there could be way more gameplay to make Quaver **feel** like the ultimate rhythm game.

**Comment by WilliamQiufeng** [comment]
Achievable through ongoing PR #4045 through lua scripting. Keyframe editor is not included in that PR but will be worked on in the future.

**Comment by JulenV2010** [comment]
@WilliamQiufeng thanks for letting me know that this feature is already on-going! Love to see this release this to the public!
(P.S. seriously though, how come I've never heard of this? No-one on the discord nor anywhere said anything regarding this feature.)
