### ISSUE TITLE
Linux version of quaver checks wrong folder for workshop skins

### ISSUE THREAD

**Issue by unmellow** [Quaver/Quaver#4235]
### Describe the bug

on my linux machine the quaver game checks /steam/SteamLibrary/steamapps/workshop/content/980610 for the skins

the correct path is /steam/SteamLibrary/steamapps/Workshop/Content/980610 so it sees nothing. i can manually fix this by symlinking the path it checks to the correct folder but that isn't very clean.

### To Reproduce

1. download the game through steam.
2. get some skins from the workshop
3. launch the game
4. try to change to the skin you downloaded and see that nothing exist.
5. try to click the open skins folder button which tells you the skins folder doesn't exist.
6. check you steamapps directory and see that two workshop folders exist

### Expected behavior

it should be checking the correct path which is /steam/SteamLibrary/steamapps/Workshop/Content/980610

### Log Files

[network.log](https://github.com/user-attachments/files/16366963/network.log)
[runtime.log](https://github.com/user-attachments/files/16366964/runtime.log)

### Screenshots

![image](https://github.com/user-attachments/assets/a1d60b22-135c-46e6-95d5-74f01e40e6d3)
![image](https://github.com/user-attachments/assets/867d08b4-ac5a-4644-a7c4-c2371ce728ab)

**Comment by Warp9000** [comment]
The workshop folder isn't capitalized on mine and another devs installation. Are you sure your steam installation is correct?

**Comment by Emik03** [comment]
What disk format do you use for `/`? (btrfs, exFAT, ext4, etc.)

**Comment by unmellow** [comment]
I use btrfs.
I use a third party driver to mount it on windows too though.
It is entirely possible that windows capitalizes steam folders and Linux just copies that.

It occured to me too that I tested rivals of aether. A Windows game running in proton and therefore using Windows naming convention.

But then again quaver should be running in proton too because I play it on windows and it doesn't reinstall or anything before I can start it.

**Comment by unmellow** [comment]
Just checked to make sure it is in fact on the btrfs drive.

**Comment by unmellow** [comment]
Ok yomi hustle a game on my NTFS drive uses a lower case folder.  It runs natively.

The steam app for some reason with your game exclusively, and this has only been tested on the btrfs drive, installed the game into a capitalized folder.

I transferred yomi hustle to my btrfs drive and the files were put in the lower case workshop folder as expected. I will try moving quaver to the NTFS filesystem and see what happens.

**Comment by unmellow** [comment]
I couldn't move the install so I just deleted everything workshop related and checked file integrity. Now everything is being downloaded to the correct folder. IDK how I created this situation but it wasn't your fault. Thanks for the help though.
