### ISSUE TITLE
mapset load show up

### ISSUE THREAD

**Issue by dumby137** [Quaver/Quaver#4238]
### Describe the bug

I have a map set I created and it is in the files, but it won't show up in the game.
I had deleted it on accident and then went to my recycle bin to redownload it, and when I did so, it never appeared.

### To Reproduce

1. Create a map set (or use a preexisting map but I'm not sure if it would work the same)
2. Delete it
3. Redownload it through your recycling bin

### Expected behavior

If you try to insert the files into the game it flags it as "Catastrophic Failure", And upon inserting the whole file into the game, the song just loads as a new map set.

### Log Files

I can't seem to find anything about this in logs.

### Screenshots

![issue](https://github.com/user-attachments/assets/31c335e2-e830-4424-8bed-ee69a6ff9f86)

(I had tried to open the map through osu, so that's why it looks like that)

![issue2](https://github.com/user-attachments/assets/977fee4d-1170-49c3-a3e0-ea38e160f4f5)

**Comment by Warp9000** [comment]
you can press F5 while in song select to reload all maps

**Comment by Emik03** [comment]
Alternatively to import a map, it needs to be packaged as a .qp file, which is just a .zip (archive) file containing all of the relevant files, and drag it into the game. I do not recommend importing from the recycle bin since it's considered a special folder.

**Comment by dumby137** [comment]
> you can press F5 while in song select to reload all maps

So, I went back and did this, and it worked!
But now there's a new issue, it's not really a problem, it's just bothering me. And that's when I reloaded my maps, all the unranked ones turned to unsubmitted, is there a way to fix this or do I have to deal with it?

![issueagain](https://github.com/user-attachments/assets/56253769-4439-4f48-ab5e-d65f9cfa355d)

**Comment by Warp9000** [comment]
Im pretty sure this option will fix that
![24-07-30, 21 35 58](https://github.com/user-attachments/assets/b6dd3410-74a5-43f6-97d9-a57b3bfe0fbb)

**Comment by dumby137** [comment]
> Im pretty sure this option will fix that ![24-07-30, 21 35 58](https://private-user-images.githubusercontent.com/59202433/353592615-b6dd3410-74a5-43f6-97d9-a57b3bfe0fbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NjQ2OTAsIm5iZiI6MTcyMjQ2NDM5MCwicGF0aCI6Ii81OTIwMjQzMy8zNTM1OTI2MTUtYjZkZDM0MTAtNzRhNS00M2Y2LTk3ZDktYTU3YjNiZmUwZmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDIyMTk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YjFhODJiZDI2YzNjMGMwNWU2NTNhZTQwYzA4MWVhZGNkM2QyMTgzYzcyYmQ0YzNiZjI5YmE0ZTdjYTdhOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yWk1s1jqnQRj-0nQw55nTPvGQyDGsMP40d4WSBaL3iw)

I have tried that multiple times upon reloading my maps, but it always says that 0 maps ranks have been updated.

![image](https://github.com/user-attachments/assets/8e01e857-f017-41f4-974a-b3b184f393a7)

**Comment by Emik03** [comment]
In that case I guess you can manually go to each map and select the global leaderboards. Assuming you're logged in, this will definitely correct the mistake for that specific map.
