### ISSUE TITLE
Selecting search issue

### ISSUE THREAD

**Issue by AiAe** [Quaver/Quaver#425]
Searching for something that it has two or more of the same letter both will get deleted.

1. Search for Lone Digg
2. Press backspace

**Comment by JaanJah** [comment]
That is how it is meant to be atm, this is also Wobble's "issue". Repost this issue under Wobble repository.

**Comment by JaanJah** [comment]
The whole textbox writing should be rewritten imo, because right now it's bit broken and not highresolution.

**Comment by Swan** [comment]
It's not an issue in Wobble. It's just that the displayed text isn't the same as the "raw text" the textbox actually sees as having entered. It's a very simple fix. I just forgot to add it.

https://github.com/Quaver/Quaver/blob/develop/Quaver.Shared/Screens/Select/UI/Search/MapsetSearchContainer.cs#L163

Adding `RawText = SelectScreen.PreviousSearchTerm,` in the object initialization will fix it.
