### ISSUE TITLE
Judgements bounce WAY too much when viewing Gameplay preview. 

### ISSUE THREAD

**Issue by Storn42** [Quaver/Quaver#4253]
### Describe the bug

When viewing gameplay preview in either song select or editor, the bounce animation on judgements is extremely exaggerated. While I understand preview isn't 100% accurate to gameplay, this is simply too exaggerated and extremely annoying to look at, especially at higher frame rates. Even setting bounce to 0 in skin.ini doesn't work in gameplay preview. 

### To Reproduce

1) go to song select or editor
2) anable gameplay preview

### Expected behavior

It would be nice if the bounce matched gameplay or was at least a lot closer to it.

### Log Files

[network.log](https://github.com/user-attachments/files/16639216/network.log)
[runtime.log](https://github.com/user-attachments/files/16639217/runtime.log)

### Screenshots

https://github.com/user-attachments/assets/1ca286cf-e10e-45a2-83c8-13f6a5754021

[Storn Skin.zip](https://github.com/user-attachments/files/16639219/Storn.Skin.zip)

**Comment by Warp9000** [comment]
Seems to just affect up scroll.

**Comment by ESVEBE** [comment]
Affects downscroll too, although not as egregious as with storn's skin [(I couldn't get it small enough to upload to github)](https://cdn.discordapp.com/attachments/470728060354822154/1274070206028840982/2024-08-16_13-16-08.mp4?ex=66c0e9d8&is=66bf9858&hm=67f7ebb1a68e5c76b9651a16f9975b1b198a84c9e8c5f700b165e734f7503192&)
