### ISSUE TITLE
maps over 50mb still dont show up in the recently uploaded maps queue

### ISSUE THREAD

**Issue by Skrubbble** [Quaver/Quaver#4262]
### Describe the bug

seems you can find them by manually searching unlike before but they dont show up the same way any other map would in the recent maps section still

### To Reproduce

upload a map over 50mb and check the maps tab. the uploaded map will not show up anywhere in the list

### Log Files

.

**Comment by AiAe** [comment]
We already discussed this in ticket, it has nothing to do with the limit. 
For now the old site/ingame search is getting updated every few hours, until proper solution is put in place.
