### ISSUE TITLE
'Maps' tab fails to load maps for Linux installations without Proton

### ISSUE THREAD

**Issue by gouldnathan** [Quaver/Quaver#4278]
### Describe the bug

Using Linux Mint 21.3, Cinnamon 6.0.4

The version of Quaver that is installed by default on Steam (no Proton) hangs for a long while when loading the custom maps screen. Interacting with and waiting for this page will eventually result in an empty maps screen. Logs look like something's upset about a JSON response from APIRequestMapsetSearch.ExecuteRequest() and APIRequestNewsFeed.ExecuteRequest()

### To Reproduce

1. Install Quaver through Steam on Linux
2. Click on the 'Maps' tab
3. Wait, and the Privacy Policy modal will appear with odd formatting
4. Accept the privacy policy
5. Wait, and the Terms and Conditions dialog will show again
6. Accept the Terms and Conditions
7. The maps screen will show with no loading spinner 

### Expected behavior

The maps screen should display Terms and Conditions and load custom maps available for download upon accepting them.

### Log Files

[network.log](https://github.com/user-attachments/files/16859085/network.log)
[runtime.log](https://github.com/user-attachments/files/16859086/runtime.log)

### Screenshots

![Quaver Maps Bug](https://github.com/user-attachments/assets/15e3c647-b13c-423f-a760-33590b917d89)

![Quaver Bug 2](https://github.com/user-attachments/assets/8d2d78a5-0307-400c-bd56-d3a5e4add197)

**Comment by WilliamQiufeng** [comment]
Hi, could you check if you have any kind of configuration that disables Quaver from accessing the Internet?

**Comment by gouldnathan** [comment]
Yeah I'll take a look around, but generally I haven't made any edits to the networking configuration on this machine.

**Comment by Emik03** [comment]
Is Steam installed via flatpak?

**Comment by gouldnathan** [comment]
> Is Steam installed via flatpak?

It is not - it was installed through the Debian package that's provided through the Steam website.

**Comment by gouldnathan** [comment]
> Hi, could you check if you have any kind of configuration that disables Quaver from accessing the Internet?

Calls to api.quavergame.com seem to resolve in the Steam web browser from within a running instance of quaver - specifically /v1/mapsets/maps/search as per the method that threw the logged exception. 

However I did notice that on my machine I am not able to ping api.quavergame.com. The resolved IP is defaulted to an IPv6 address, and pinging the public IPv4 addresses associated with api.quavergame.com responds normally. I'm not 100% sure if that is really related to the problem.

**Comment by gouldnathan** [comment]
After some more troubleshooting, and an unrelated issue that required a reinstall of steam via Mint's Software Manager, Quaver appears to be working for me in full. Thanks for everyone who gave their suggestions :) If I ever manage to get my machine to play nice with dotnet I'd love to contribute in the future.
