### ISSUE TITLE
the bug of watch replay 

### ISSUE THREAD

**Issue by soskun** [Quaver/Quaver#4279]
### Describe the bug

When watching the relplay, the note drops but there is no music when the playback is started, and the note disappears but there is music when the playback is turned off. That is, the note is gone when it starts playing

### To Reproduce

.

### Expected behavior

.

### Log Files

.

### Screenshots

.

**Comment by Warp9000** [comment]
Please provide exactly how to reproduce, logs and screenshots/video.
