### ISSUE TITLE
Bug on downloading music

### ISSUE THREAD

**Issue by andrix16** [Quaver/Quaver#4282]
### Describe the bug

When i press to download the music it stays in 0% and doesen't work, it says that an import fail has ocurred
![image](https://github.com/user-attachments/assets/2a9c4681-c6db-4163-9339-7e0936301d3a)

### To Reproduce

idc

### Log Files

[network.log](https://github.com/user-attachments/files/16925032/network.log)
[runtime.log](https://github.com/user-attachments/files/16925033/runtime.log)

### Screenshots

![image](https://github.com/user-attachments/assets/7448754d-4341-4966-9b92-86b86c30d38e)

**Comment by Swan** [comment]
This should be fixed. It was due to a server outage. Open back up if this is still happening
