### ISSUE TITLE
A semi auto way to map, but needs some extra features.

### ISSUE THREAD

**Issue by YagaoDirac** [Quaver/Quaver#4284]
### Is your feature request related to a problem? Please describe.

Not a problem. I mean, the editor works now, I appreciate. I think it's possible to achieve a semi auto work flow with very little extra features, and all the needed new features are very easy to code.

### Describe the solution you'd like

Because most maps are not very specialized for the song, it's possible to design a general purposed way to speed up the mapping job.
Extra editor features needed:
1, Scatterring notes onto map.
2, Turning short notes into begin and end of long notes. The odd ones become start, the even ones become end. The result should be a half covered map by long notes. This is the final fantasy of long notes players.
3, Randomly selecting a given porpotion of notes in a range. Or randomly selecting some of the "already selected"notes. Then, we can delete these notes.
4, Randomly move notes horizontally(different place but same timing).

Then, the new semi auto work flow should be like:
1, create a new layer.
2, scatter some short notes there.
3, convert short note pairs into long notes.
4, select some of these long notes, delete them.
5, adjust them if needed.
6, create a new layer for short notes.
7, scatter short notes.
8, select some, delete. Check out the density.
9, combine the 2 layers, control the density again.
10, finish, upload.
It should be very no brain and fast. 
For people who don't play long notes, they only need to scatter short notes.
For long notes holic, they want half filled style, and this work flow actually covers it.

### Describe alternatives you've considered

The speed actually comes from a super fast way to put notes into map. Any method speed up this process, is alternative to my idea.

### Additional context

(none)

**Comment by windows-phone67** [comment]
i feel like this is not a very good idea

**Comment by Emik03** [comment]
This is what editor plugins are for, such as [VanillaChinchilla](https://github.com/kloi34/VanillaChinchilla). I don't see a reason for that kind of editor tooling to be built-in since a plugin can rapidly develop and evolve far quicker than the game.
