### ISSUE TITLE
Brightness adjusting for long notes.

### ISSUE THREAD

**Issue by YagaoDirac** [Quaver/Quaver#4285]
### Is your feature request related to a problem? Please describe.

When the screen is full of long notes, it's too bright.

### Describe the solution you'd like

The beginning of long notes should keep as bright as short notes. The body of long notes can dim a bit.
2 options are needed. The brightness of body of long notes, and the brightness of end of long notes.

### Describe alternatives you've considered

(None) 

### Additional context

(none)

**Comment by ESVEBE** [comment]
You do realize that the body of a long note is a skinnable texture that you can edit at will, right?

https://wiki.quavergame.com/docs/skins/gameplayinterface#holdbodies

**Comment by YagaoDirac** [comment]
> You do realize that the body of a long note is a skinnable texture that you can edit at will, right?
> 
> https://wiki.quavergame.com/docs/skins/gameplayinterface#holdbodies

I didn't. Thanks.
