### ISSUE TITLE
Quaver.Server.Client.dll missing Quaver.Server.Client.Events.Download namespace

### ISSUE THREAD

**Issue by Szunti** [Quaver/Quaver#4315]
### Describe the bug

Cloned the develop branch. I get errors regarding the Quaver.Server.Client namespace for example

Quaver/Quaver.Shared/Graphics/Overlays/Hub/Downloads/Scrolling/DrawableDownload.cs(7,35): error CS0234: The type or namespace name 'Download' does not exist in the namespace 'Quaver.Server.Client.Events' (are you missing an assembly reference?) [Quaver/Quaver.Shared/Quaver.Shared.csproj]

The cause is the following line:

```c#
using Quaver.Server.Client.Events.Download
```

Decompiled Quaver.Server.Client.dll and there is no Download namespace there.

### To Reproduce

Clone the develop branch and follow build instructions

### Log Files

Build log
[Quaver.build.txt](https://github.com/user-attachments/files/17737425/Quaver.build.txt)

**Comment by Swan** [comment]
Should be good now, thanks
