### ISSUE TITLE
Editor Keybinds are missing

### ISSUE THREAD

**Issue by ARGEBE** [Quaver/Quaver#4322]
### Describe the bug

Some of the newer keybinds don't exist in the current 1.6 build, notably you cannot jump between bookmarks with Ctrl + left/right, and you cannot paste without resnapping with Ctrl + Shift + V (thanks cuckson for spotting that). 

### To Reproduce

Press either button sets of buttons, it's likely some of the other newer functions also haven't been added back

### Log Files

N/A

**Comment by ARGEBE** [comment]
Ctrl+B's implementation creates a confliction with Apply Offset to map (as pointed out by Tempy)

**Comment by WilliamQiufeng** [comment]
You will need to reset keybinds since default keybind has been changed.
Alternatively, remove key binding entry for Applyy Offset, Increase/Decrease Snap
