### ISSUE TITLE
[1.6.0+] Shadow Misses / Missing before chart starts

### ISSUE THREAD

**Issue by txbi** [Quaver/Quaver#4351]
### Describe the bug

When previewing a chart in the Song Select, you can start the map and already start tapping "ghost notes" of some sorts. These cause the player to miss / hit judgements of notes that the chart does not have, causing accuracy to drop and potentially get more combo

### To Reproduce

1. Preview Chart in Song Select
2. Start chart
3. Spam / Ghosttap keybinds 

This causes the player to miss before the regular chart starts playing

### Expected behavior

Notes from the preview should not be accounted for in the chart itself. This only happens in 1.6.0. and above.

### Log Files

[runtime.log](https://github.com/user-attachments/files/17815053/runtime.log)

### Screenshots

https://github.com/user-attachments/assets/11c8d477-13dc-4801-8239-513eaf48e0fb

**Comment by WilliamQiufeng** [comment]
Should be fixed in #4350
