### ISSUE TITLE
[1.6.x Canary] Keybind for "Pause/Play Track" doesn't work while Autoplay is disabled

### ISSUE THREAD

**Issue by SparkySpartan** [Quaver/Quaver#4353]
### Describe the bug

Attempting to use the "Editor: Pause/Play Track" keybind will fail to have any function - even though every other keybind works as expected.

This issue is new to Canary.

### To Reproduce

1. Go into the Editor of any chart.
2. Disable Autoplay with Tab.
3. Attempt to play/pause the chart with the "Pause/Play Track" button (usually Space)

### Log Files

[runtime.log](https://github.com/user-attachments/files/17816913/runtime.log)

**Comment by WilliamQiufeng** [comment]
I guess it' because 7k keybind has space and I made it to exclude those binds when playtesting... Will see if I can do anything about that.
