### ISSUE TITLE
Issues with HitBubbles elements

### ISSUE THREAD

**Issue by transdifferentiation** [Quaver/Quaver#4362]
### Describe the bug

Changing HitBubblesPosX, HitBubblesPosY values don't work; HitBubblesRecordedJudgements = All doesn't display Marvelous rating.

### To Reproduce

1. Open skin.ini 2. Add the following values: HitBubblesPosX = {number} ; HitBubblesPosY = {number} ; HitBubblesRecordedJudgements = All 3. Save and open the skin in-game.

### Log Files

[runtime.log](https://github.com/user-attachments/files/17894247/runtime.log)
[network.log](https://github.com/user-attachments/files/17894248/network.log)

**Comment by A6sT** [comment]
Can you provide you skin.ini file too ? I feel like this would help

**Comment by transdifferentiation** [comment]
nevermind i put the values at the wrong parts in the file lmao
