### ISSUE TITLE
Offset Bug

### ISSUE THREAD

**Issue by M3M3STUFF** [Quaver/Quaver#4401]
### Describe the bug

I was testing visual offset on the game and when I tried to bring it back to 0ms it wouldnt let me. -1 or 1. no 0

### To Reproduce

1: open settings
2: go to audio tab
3: scroll down to offset
4: take visual offset off of 0 to any number
5: try to take it to 0ms

### Log Files

no log

**Comment by Warp9000** [comment]
you can press left and right arrow keys when hovering a slider for precise control.

**Comment by M3M3STUFF** [comment]
> you can press left and right arrow keys when hovering a slider for precise control.

okay thanks, but a slider shouldnt just be by 1,4,7 aswell
