### ISSUE TITLE
Trembling notes when sliding on the road(linux)

### ISSUE THREAD

**Issue by NamakeKuma** [Quaver/Quaver#4404]
### Describe the bug

When you start the map, the road runs smoothly, but once the note reaches the click zone, it immediately moves as if at 14 FPS

OS: Arch linux
Game release: Native

### To Reproduce

1. open the card
2. wait for the notes

### Expected behavior

I was expecting a smooth slide of notes along the road, not a miracle, as if it were 15 fps.

### Log Files

[network.log](https://github.com/user-attachments/files/18271092/network.log)
[runtime.log](https://github.com/user-attachments/files/18271093/runtime.log)

### Screenshots

https://github.com/user-attachments/assets/ed4a3064-223e-4e8f-a34e-ca88b2d74451

**Comment by Warp9000** [comment]
https://wiki.quavergame.com/docs/faq#how-do-i-reduce-the-hitsound-audio-latency-on-linux%3F

**Comment by NamakeKuma** [comment]
> https://wiki.quavergame.com/docs/faq#how-do-i-reduce-the-hitsound-audio-latency-on-linux%3F

I'm fine with audio latency, it's just that it bothers me that the notes are playing at like 15 FPS.
by the way, this problem is not only when playing the card, but also when viewing it on F3

**Comment by Emik03** [comment]
> https://wiki.quavergame.com/docs/faq#how-do-i-reduce-the-hitsound-audio-latency-on-linux%3F

latency has absolutely nothing to do with this, notice how the audio is completely clean in the actual video and that the notes are *consistently* stuttering (and not based on how fast the audio buffer can refresh)

as for the actual issue, i haven't ever seen this before, but try going into settings (or press CTRL+O) and search for "smooth timing" and see if toggling it helps

**Comment by NamakeKuma** [comment]
> > https://wiki.quavergame.com/docs/faq#how-do-i-reduce-the-hitsound-audio-latency-on-linux%3F
> 
> latency has absolutely nothing to do with this, notice how the audio is completely clean in the actual video and that the notes are _consistently_ stuttering (and not based on how fast the audio buffer can refresh)
> 
> as for the actual issue, i haven't ever seen this before, but try going into settings (or press CTRL+O) and search for "smooth timing" and see if toggling it helps

It worked, thank you very much!
