### ISSUE TITLE
Can't remove text from search bar 

### ISSUE THREAD

**Issue by Bakuretsue** [Quaver/Quaver#458]
Whenever I search up  a map, for example I type in Kaneko and find a map called Final Letter - Kaneko Chiharu. Whenever I play the map and I either finish the map or exit the song I can't remove the "Kaneko" I typed in the search bar before playing the song unless I exit to the menu and return to single player map selection

windows 10 64x
1920x1080

**Comment by Swan** [comment]
Already fixed in #442 

Haven't deployed new build on Steam.
