### ISSUE TITLE
Using alpha layers for skinning

### ISSUE THREAD

**Issue by Abriel14** [Quaver/Quaver#463]
Ability to change the "ColorObjectsBySnapDistance" ingame and:

1) If it is activated:
The colors of the arrows could be selected by the player in a RGB selector for each snap distance and each column like this only one of two texture images (alpha layer) would be needed.
The player could also be able to choose the rotation of images in each column.

2)if not:
This would be the same but only the color per column and the rotation should be available to change.

**Possible Issues**
-If someone wants to have a different image for each column, that would be problematic.
-Same problem for ssomeone wanting to have a different picture for different snap distance. But no one would like this so this is not a problem.
-> Solution: have as many base pictures as the number of columns.

**Comment by Swan** [comment]
There's now a `note-hitobject-sheet@9x1.png` element you can add to your skin that will handle each snap and rotation automatically.
