### ISSUE TITLE
Audio Delay if Intro Skipped

### ISSUE THREAD

**Issue by fakebrin** [Quaver/Quaver#464]
**Describe the bug**
If you skip a song intro the moment you enter the song, the audio gets delayed.

**To Reproduce**
1. Choose a song (only tried 4K, not sure about 7K)
2. Enter any difficulty
3. Press Alt (or any button you binded your skip to)
4. Notice the delay

**Screenshots**
https://youtu.be/VOuHoVzP1pc  (first play is a normal play, no skipping, the second one has a skip when entering the song)

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional
 - Version 0.12.0

**Comment by Swan** [comment]
Fixed in
https://github.com/Quaver/Quaver/pull/514
https://github.com/Quaver/Wobble/pull/23
