### ISSUE TITLE
Forced miss on a long note

### ISSUE THREAD

**Issue by soler98012** [Quaver/Quaver#471]
**Describe the bug**
When skipping the beginning of the map you're forced to miss

**To Reproduce**
1. open the map that you can download from https://cdn.discordapp.com/attachments/525409883877539860/531123266610397184/Captain_Jack_-_Captain_Jack_-_57397.qp

2. Skip the beginning
3. Miss the LN
**Expected behavior**
The game should start before the slider making you able to hit the notes

**Screenshots**

![20190105155954_1](https://user-images.githubusercontent.com/18517329/50725770-005a4200-1103-11e9-897c-d0d9b1bc1cbc.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Performance-improvements & Default branch

**Additional context**
i couldn't get to create another map with this glitch on it in order to replicate it out of that map

**Comment by EliteDreamer** [comment]
I noticed that is tied with the "speed up" converts maybe that's the cause.

**Comment by YaLTeR** [comment]
Seems related to SVs. doesn't occur with NSV.
