### ISSUE TITLE
Scroll speed settings from other games

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#473]
**Is your feature request related to a problem? Please describe.**
When you're coming from osu!mania/Stepmania/insert other VSRG you probably want your scroll speed to match the value you're used to. Quaver uses its own scroll speed with no obvious conversion from other games.

**Describe the solution you'd like**
In the scroll speed settings, allow setting up the scroll speed in multiple different formats, so as osu!mania scroll speed, as Etterna scroll speed and possibly others (idk how other games work). Maybe even display all values changing at once (so you can see what quaver scroll speed your osu!mania scroll speed would equal to).

**Describe alternatives you've considered**
Make some tool for converting the scroll speeds. Maybe a web page or a discord bot or something. If this doesn't exist someone will probably make it anyway.

This wouldn't be very convenient to use and also isn't very discoverable.

**Comment by Swan** [comment]
Don't see the purpose of this. It doesn't take very long to figure out a comfortable scroll speed. Quaver works differently than other games.

**Comment by YaLTeR** [comment]
Why would I want to take time figuring out a comfortable speed when I already have a comfortable speed from another game?

**Comment by Swan** [comment]
Realistically you'd only have to configure your scroll speed one time when you first begin playing - after of which is just minor adjustments to suit whatever your needs are at that time. Each game is different, and as far as I can see, there's no way to provide an absolutely accurate conversion, so it ends up not providing any real use.
