### ISSUE TITLE
"full long note/noodle" modifier

### ISSUE THREAD

**Issue by cindsa** [Quaver/Quaver#482]
Since now we have a "No Long Notes" modifier it'd be nice to have the opposite of that, a full long note/noodle modifier which would convert any map to a full long note one.

Such mod would be great for practice.

![example](https://user-images.githubusercontent.com/46068230/50748312-de1f0c00-1249-11e9-92b6-400a51ad721d.png)

**Comment by YaLTeR** [comment]
Yep, already planned!

**Comment by Swan** [comment]
What would be the determining factor for where the LNs should end?

**Comment by YaLTeR** [comment]
Initially I thought using some sort of a "BPM / 4" computation but then I realized it's not very robust (think 2× BPM maps or whatever). I haven't come up with an alternative yet.
