### ISSUE TITLE
Ability to customize judgement counter boxes

### ISSUE THREAD

**Issue by cindsa** [Quaver/Quaver#483]
I'm not sure if this is how they're called but I'm talking about these judgement counter boxes that are displayed on the very right side of the screen
![boxes](https://user-images.githubusercontent.com/46068230/50748416-67364300-124a-11e9-9a7b-59c7d7494b91.PNG)

In my opinion those are quite ugly looking and it'd be nice to be able to change things like:
Color
Opacity
Font Color
Size

And also have an option to disable them all together for people who might find them distracting.

**Comment by Swan** [comment]
There is already some customization possible for this to a certain degree.

1. You can change the color of the boxes by setting `JudgeColorPerf/Marv/Great` etc in [skin.ini](https://github.com/Quaver/Quaver/blob/develop/Quaver.Shared/Skinning/SkinKeys.cs#L502). This will also set the color of the hit error lines as well.

2. You can change the background image for the boxes by placing a file at `Judgements/judgement-overlay.png` in your skin.
