### ISSUE TITLE
Stuttering

### ISSUE THREAD

**Issue by Sorprice** [Quaver/Quaver#489]
I have Stutter every 10-15 seconds on any map, I try to reduce the resolution, disabling some functions, but it seems that it does not work.

I still have stuttering after the update.
W10 PRO 64BITS
GT730 GGDR5
FX8320e
7GB of RAM

**Comment by FatLongPizza** [comment]
Exact same problem I have, but a little bit more intensive.

Win10 64bits
MSI GTX 1060 6GB
Intel Core I5 4460
8GB RAM

**Comment by kAlekki** [comment]
Getting stutters which last less than half a second every 5 seconds or so.
Win10 w/ GTX 1060, i5-3570k & 8 gigs of ram

**Comment by Swan** [comment]
Duplicate of #359
