### ISSUE TITLE
Effect Volume changing when it should not change

### ISSUE THREAD

**Issue by Luftii** [Quaver/Quaver#511]
**Description**
When changing Effect Volume or Master Volume, Effect Volume will change its value to whichever of these two was changed last (As seen in the videos below).

**Expected Behaviour**
Effect Volume should scale with Master Volume and itself (for example: Master Volume = 50%, Effect Volume = 0%, 50% * 0% = 0% = Actual Effect Volume) instead of just overwriting itself whenever either of those is changed.

**Additional Information**
https://streamable.com/ylhgk
https://streamable.com/htfl3

**Comment by IceDynamix** [comment]
Unfixed in UI Redesign

**Comment by YaLTeR** [comment]
wut, how would it unfix
