### ISSUE TITLE
Search Issues

### ISSUE THREAD

**Issue by staravia** [Quaver/Quaver#516]
Search does not work properly when adding a space at the beginning or end of search input

Examples:
![img](https://media.discordapp.net/attachments/525409883877539860/540276164648894501/unknown.png)

![img](https://media.discordapp.net/attachments/525409883877539860/540276297046163499/unknown.png)

**Comment by YaLTeR** [comment]
The in-game part should have been fixed by #607. The website part seems to be working properly too.
