### ISSUE TITLE
A magnifying glass feature for the hit difference graph

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#524]
By BrokenGale on Discord:
> Is it possible to get a magnifying glass to  look more closely at single parts of the error charts? I think it might be interesting, espiecially if there can be a GUI  of the map  right next to it

That minimap idea especially is very interesting tbh, although I'm really not sure how that could work or look.

**Comment by Kangaroux** [comment]
You could just have it show a zoomed in window when you hover over the graph. If there are plans to add some interactions into the hit graph later on you could make the zoom only appear when you are holding down the mouse button.

Mockup with 3x zoom:

![graphzoom](https://user-images.githubusercontent.com/2302541/52996943-08d5b600-33ed-11e9-99f3-b4b45d56a434.png)
