### ISSUE TITLE
Audio doesn't fade in from zero volume after a song ends

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#527]
When finishing a chart and going back to the select screen the audio starts off really loud. Either it really starts off louder than it should or maybe not, either way it should have some sort of a fade from lower volume like it does on other screen transitions.

**Comment by Swan** [comment]
All fades have been removed and most likely won't be added back. The fade causes issues with setting the preview time in the editor where creator usually has to place it at a much earlier time.
