### ISSUE TITLE
Handle new ranked mods in some way

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#542]
When a new ranked mod is added and a score with it is submitted, older clients catch fire. There needs to be some fallback logic, like an error popup saying that you can't watch the replay and a string for unknown mods.

This will also help in an offline case when sharing a replay with another player with an older build.

**Comment by Swan** [comment]
Gonna close this for now since in the future everyone will be on the same client with the same mods (and should be in an offline/dev environment)
