### ISSUE TITLE
Handle Audio Device Changes

### ISSUE THREAD

**Issue by Kangaroux** [Quaver/Quaver#569]
**Describe the bug**
On Windows, when you change the system output audio device, Quaver does not recognize that it changed and will continue to use the previous audio device.

For example, if my audio device is set to headphones and I switch to speakers, Quaver will still play through my headphones until I restart the game.

**To Reproduce**
1. Run Quaver
2. Change the system audio device by clicking the speaker icon in the task bar
3. Click back into Quaver. The game audio is still coming out the original audio device

**Expected behavior**
Quaver recognizes audio device changes while the game is running instead of checking once when it starts.

An option dropdown to select the audio playback device, with a Default option that automatically detects when the default audio device changes in Windows. (#1850)

**Desktop (please complete the following information):**
 - OS: Windows 10 build 17134

**Comment by robby250** [comment]
When selecting an option other than Default, it should remember it even if the device becomes unavailable, use the windows default audio device as a fallback while the selected device is unavailable, and then switch back to the selected audio device when it's detected/plugged in again (if possible).

**Comment by AiAe** [comment]
Should be fixed with https://github.com/Quaver/Wobble/pull/124
Still would be good to have proper ingame dropdown to select audio source, will create new issue if there is not about it.
