### ISSUE TITLE
Waveform/automatic bpm detection for editor

### ISSUE THREAD

**Issue by percyqaz** [Quaver/Quaver#587]
In ArrowVortex you can have it automatically detect BPM of a song and place a timing point
You can also see a rendered waveform of the audio so you can visually confirm that your note placements are aligned with the music
These sort of come under the same thing because you have to figure out how to get BASS to do both

**Describe the solution you'd like**
In the stage of the editor where you set up timing, there should be an option to try and detect the BPM of the music
In the stage of the editor where you place notes, there should be a waveform aligned next to the playfield - It is probably best for the (vertical) middle of the notes to be aligned with the waveform peaks however this could be a user setting

**Describe alternatives you've considered**
Just use your ears lol

**Additional context**
See ArrowVortex for more ideas/example of how it works

**Comment by YaLTeR** [comment]
As a comment, I've seen BPM detection in bass_fx

**Comment by Swan** [comment]
I played around with it a little bit. Should be able to get it to work with [this method](https://managedbass.github.io/api/ManagedBass.Fx.BassFx.html#ManagedBass_Fx_BassFx_BPMDecodeGet_System_Int32_System_Double_System_Double_System_Int32_ManagedBass_BassFlags_ManagedBass_Fx_BPMProgressProcedure_IntPtr_). Not sure about the offset though.
