### ISSUE TITLE
"Filters" in editor

### ISSUE THREAD

**Issue by percyqaz** [Quaver/Quaver#588]
So basically like a brush in an image editor, you can select an group of notes and run a filter on them

**Describe the solution you'd like**
In the editor you should be able to select notes and have a dropdown menu that filters can be selected from
Some sensible ideas for filters would be
- Inverse (extends all notes as LNs that stop just before the next note in the column)
- Stutter SV (places SVs of an adjustable amount on the times of notes and midpoints of notes to create a stuttering effect)

It would be very nice if filters could pop up a little prompt where you can set values an other things i.e in inverse the snap distance to use
I particularly would really like to see SV filters where you can design a curve you want SV values to follow and it will place several down over a section to create this effect (as this would make many SV mappers' life much much easier)

**Additional context**
Mods like inverse or NoLN could be implemented as an editor filter applied to the whole chart

**Comment by Swan** [comment]
This along with much more can be done via plugins.
