### ISSUE TITLE
Pattern generator in editor

### ISSUE THREAD

**Issue by percyqaz** [Quaver/Quaver#589]
For lazy mappers who want to place a lot of jumpstream/chordstream/certain type of very easy to machine-produce pattern

**Describe the solution you'd like**
In the editor there should be an option to generate patterns for a certain section/number of beats
A custom syntax could be created to express what kind of patterns you want i.e
12|34 would express jumptrills
My suggested implementation of rules (unrevised but I planned this a little bit a while ago) would be
- Each new "row" of notes is separated by |
- A number on its own represents a note in a specific column
- An S represents a "stream" note which will randomly select a column to form streams (previous row does not contain this note and potentially S is adjacent to a note from the previous row to form rolls)
- A J represents a "jack" note which will randomly select a column to form jacks (by playing a note in a column that also has a note there in the previous row)
- some other stuff, maybe R would be rolls and S could just randomly pick a column

Then you just give it the snap distance between each generated row and press "generate"

**Describe alternatives you've considered**
Sitting there and spending ages making a stream and then getting bored and copy pasting it to get the chart done faster

**Additional context**
This could be implemented as a filter (from my other issue)

**Comment by Swan** [comment]
This along with much more can be done via plugins.
