### ISSUE TITLE
Hitsound for layer

### ISSUE THREAD

**Issue by V3rald** [Quaver/Quaver#594]
Remapping something takes huge time if you want to fully hitsound it, so maybe a way to just click on layer and the wanted hitsound would set the hitsound for all the notes in that layer

**Comment by YaLTeR** [comment]
Would disabling all other layers and then using Ctrl+A to select everything and applying the hitsound work?

**Comment by Swan** [comment]
You can already select an entire layer with CTRL+ALT+A or via the toolbar.
