### ISSUE TITLE
Scroll Speed 0

### ISSUE THREAD

**Issue by Cajowo** [Quaver/Quaver#596]
**Describe the bug**
Scroll Speed 0 causes hitobjects to freeze 

**To Reproduce**
Set Scrollspeed of 4 or 7 to 0

**Expected behavior**
 Notes will freeze ontop of hitbar 

**Screenshots**
![unknown](https://user-images.githubusercontent.com/47928157/53291176-0685aa00-37a7-11e9-865f-17d3552edcc5.png)

Was told to report this so idk

**Comment by YaLTeR** [comment]
This needs to be fixed along with the generalization of option sliders (currently they can only be from 0 to 100 which is why 0 is an option here in first place).
