### ISSUE TITLE
Dans: Concept

### ISSUE THREAD

**Issue by IceDynamix** [Quaver/Quaver#603]
Currently, Dans are made up of 4 songs/maps/charts, with one mp3 that has all 4 songs together. Making something similar to what LR2 has (just without indefinite breaks) is something that can be appreciated by a lot of players. Dans have always played a big part in the o!m community, and having them transferred here to Quaver in a smarter way would be something a lot of players would appreciate.

**Describe the solution you'd like**
A dan course, in form of a special beatmap, combined from 4 chosen songs. Betweens songs during the dan course, show accuracy and other stats. At the end, save those stats so you always know what % you had inbetween the dans. 

Dans have a certain % threshold for a clear. Implementing this into the dan course (file) itself means no need for grade letters. Having a big CLEAR (with some applause) and a big NOT CLEAR makes it easier to distinguish.

Since the dan couse has the beatmaps information, a list of the songs in the dan visible from the song select menu with their respective stats, clickable to get sent to the beatmap itself (in the song select) or to a download prompt would be a nice way of making it easier to practice the dans maps itself. The beatmaps themselves have to be uploaded to Quaver for that to happen, of couse.

**Comment by BrokenGale** [comment]
A Dan is a patchwork solution to a functional difficulty/ranked system. Having 4 charts in a dan only means that you are good at those 4 specific maps with those specific skills. While more general skills i.e. speed, jacking, reading etc. are more universal and thus can be tested with a Dan based system, it is no substitute to a difficulty system that takes into account all possible patterns.

**Comment by YaLTeR** [comment]
Dans aren't exclusively for assessing your current skill though. They serve very nicely for the feel of "skill progression": you pass a dan and begin working towards the next dan.
