### ISSUE TITLE
Long note tails cover up beat snap lines in the editor

### ISSUE THREAD

**Issue by loafusofbread** [Quaver/Quaver#604]
As you can clearly see in this here wonderful screenshot, while in the editor, the long note tails cover up the succeeding beat snap line. 

![temp](https://user-images.githubusercontent.com/41889550/53294731-b4925380-37a9-11e9-91aa-5b998062c8f0.png)

One would expect that this wouldn't happen, and we would always be able to see the beat snap lines. Thank you for your time.

**Comment by YaLTeR** [comment]
These LN tails in particular should not be drawn at all because the default skin has `DrawLongNoteEnd = False` to fix this exact issue.

**Comment by Swan** [comment]
Intentional. To get around this, you can either use a different skin that doesn't cover the line, or the "Long Note Opacity" option in the new editor
