### ISSUE TITLE
Universal Sort by Difficulty

### ISSUE THREAD

**Issue by BrokenGale** [Quaver/Quaver#605]
**Is your feature request related to a problem? Please describe.**
Currently there is no system for sorting by individual charts between songs (like osu!) Nor is there a universal sort by difficulty.

**Describe the solution you'd like**
I would like to see an option to universally sort all charts by difficulty separate from the songs that they are charting.

**Describe alternatives you've considered**
A system akin to etterna's sorting system still leaves a lot of players struggling to find the maps that match their skill level. 
A filer system where you can choose a range of difficulties to show would also be interesting but still somewhat inferior to a universal sort.

**Additional context**
I understand that the difficulty scale is a work in progress, but having an option to sort by difficulty is always better than not having it.

**Comment by YaLTeR** [comment]
This request has been in the air for a while especially since I'd like sorting by difficulty myself. Before it's done, though,

> A filer system where you can choose a range of difficulties to show would also be interesting but still somewhat inferior to a universal sort.

You can do that via `diff>10 diff<22` type search query.

**Comment by BrokenGale** [comment]
Thanks for telling me the filter command, does it work for all charts, even ones under the umbrella of other songs?

**Comment by YaLTeR** [comment]
Should work for everything.
