### ISSUE TITLE
Autoplay crash

### ISSUE THREAD

**Issue by semyon422** [Quaver/Quaver#608]
**Describe the bug**
I tried to play my map with Autoplay mod to see how it works in Quaver but it crashed when got to inverse long notes which I used in this map.
Map link: https://osu.ppy.sh/beatmapsets/783721#mania/1645683

**To Reproduce**
1. Turn on Autoplay mod
2. Start playing Outro difficulty
3. Get Quaver crashed at 0:40.840

**Expected behavior**
Quaver should not crash, it should play this map with misses (like osu Auto) or without them

**Screenshots**
https://puu.sh/CQWA9/9bb5e1b409.png

**Desktop (please complete the following information):**
 - OS: Windows 7 Ultimate
 - Browser Firefox
 - Version 65.0.1 (64-bit)

**Additional context**
Also this beatmap should look like this on arrow skin:
https://puu.sh/CQXew/9055a4079d.jpg
[runtime1.log](https://github.com/Quaver/Quaver/files/2897762/runtime1.log)

**Comment by YaLTeR** [comment]
Not sure we want to support LNs with end time before start time, cc @Swan. For now I'll just make Qua fail the validity check if there are any degenerate LNs I guess.
