### ISSUE TITLE
When "DrawLongNoteEnd" is set to false, the LN body is still drawn as it passes through the receptor

### ISSUE THREAD

**Issue by IceDynamix** [Quaver/Quaver#612]
LN Bodies are still drawn (pass through the receptor) even though they were hit correctly. This is especially noticable with receptors that don't extend to the window border.

**Comment by YaLTeR** [comment]
This is intended and documented on the wiki. If you'd keep the same LN start sliding behavior when not drawing LN ends, the LN start would slide off the LN in the end and look bad.

**Comment by IceDynamix** [comment]
Alright then.

**Comment by YaLTeR** [comment]
I don't consider it the perfect solution though but I couldn't come up with anything that made more sense, so if you have ideas please post them.

**Comment by YaLTeR** [comment]
To clarify, this is the issue I'm talking about, note how LN starts slide off LNs in the end: https://streamable.com/1ednj

**Comment by IceDynamix** [comment]
We're on the same track. I don't feel like it shouldn't slide off, ever. 
Example with Receptors that don't cover everything to the window border:
https://puu.sh/CR0aV/0625c5b1d9.gif

**Comment by YaLTeR** [comment]
On skins such as the default that behavior looks bad and makes releases of really slow LNs (think SV maps) _really_ hard to time.

**Comment by YaLTeR** [comment]
One solution I can think of is, when `DrawLongNoteEnd = False`, sliding the LN start up to the point where its top aligns with the LN body top, and then just clipping it against the hit receptors for the remaining height of the LN start sprite, but that could look a little weird.

**Comment by YaLTeR** [comment]
Other options:
- Clip the LN start right away in the beginning as if it was part of the LN body. This is strictly better than the current solution (LNs don't slide down).
- Hide the LN start as soon as the LN is held. I think it's worse than the above point.
- Hide the LN start altogether (`DrawLongNoteEndAndStart = False`?).

**Comment by YaLTeR** [comment]
I still think one of these solutions with clipping would be a better behavior for `DrawLongNodeEnd=False`, just haven't got around to trying to implement it yet.
