### ISSUE TITLE
Switching from beatsnap "A" to beatsnap "B" should be faster in the interface

### ISSUE THREAD

**Issue by staravia** [Quaver/Quaver#613]
It's a pain to switch from (for example) 1/6th to 1/8th snap. It should feel more fluid in the interface

**Comment by jakads** [comment]
you can shift+mouse scroll

**Comment by staravia** [comment]
specifically talking about the interface. You have to click a button 9 times to go back 1 snap

**Comment by IceDynamix** [comment]
maybe left/right click the button in the playback bar, left click = increase snap, right click = decrease snap
