### ISSUE TITLE
Editor: Make merging layers more UX friendly

### ISSUE THREAD

**Issue by staravia** [Quaver/Quaver#620]
Preferable keybind would be Ctrl+E like in photoshop.
It should be possible to merge the current layer to the layer below without having to select a layer.
It should also be possible to merge 3 or more layers together.

**Comment by staravia** [comment]
Reopened. It should be possible to move all the hit objects from the current layer into another layer, and the current layer should be deleted after merging.

**Comment by Swan** [comment]
Edit -> Move selected objects to layer. Delete the layer you no longer need.

**Comment by staravia** [comment]
This should be a user interface thing for better UX since it is a repeated action that is frequently used.

In photoshop, while you can copy+paste from one layer to another and delete the previous layer, you do not do this because it is inconvenient. You simply just right-click on the layer and click on merge down or you can press Ctrl+E.

This is a repeated action that is frequently used.
