### ISSUE TITLE
Support decimal places for hit objects

### ISSUE THREAD

**Issue by jakads** [Quaver/Quaver#633]
Current osu! editor doesn't support them, making some of the creative SV ideas not possible.
I could explain the details if you want, but trust me, we need them.

**Solution**
Let the in-game editor place objects on integer times (and make objects with times on decimal places unrankable), but make the client be able to read notes with decimal places times.
e.g. StartTime: 1234.56

**Comment by Swan** [comment]
Judgement windows and timing in general don't use decimal values,, so I don't think it would make much sense for objects to.
