### ISSUE TITLE
Inverse/Full Long Notes Map Not Working

### ISSUE THREAD

**Issue by Swan** [Quaver/Quaver#641]
[Map](https://cdn.discordapp.com/attachments/412000948752351252/549579784733196298/Camellia_ft._Hatsune_Miku_-_Extraterrestrial_-_11140.qp)

**Comment by YaLTeR** [comment]
Works for me. Are you using the latest Quaver.API? Since the one currently checked out is missing a few fixes.

**Comment by Swan** [comment]
^
