### ISSUE TITLE
Something like AiMod for Quaver's editor

### ISSUE THREAD

**Issue by cindsa** [Quaver/Quaver#656]
I'm not sure if somebody has already made this request but I couldn't find one so I'm making this, apologies if this is a duplicate.

It'd be very handy to have something like AiMod that's automatically detect things that are wrong with the map like:

Stacked Notes.
Notes inside long notes.
Overlapping notes.
Lack of tags in metadata and other things that would make the map unrankable.

**Comment by staravia** [comment]
Similar: https://github.com/Quaver/Quaver/issues/618
