### ISSUE TITLE
Stop scrolling when changing volume by alt+scroll wheel

### ISSUE THREAD

**Issue by cindsa** [Quaver/Quaver#657]
Right now if you try changing the volume by using alt + scroll wheel, if you're in song select or the editor you'll end up scrolling which is pretty annoying because then you have to scroll back to where you were after adjusting the volume.

So it's gonna be better if when changing the volume by using alt + scroll wheel, initial scrollwheel function would be disabled.

**Comment by Piparkuucinsh** [comment]
This is fixed for only song scrolling and would be nice to fix for every scrollable list in the game.
