### ISSUE TITLE
Autoplay keybind + Pausing

### ISSUE THREAD

**Issue by percyqaz** [Quaver/Quaver#660]
Haven't looked at the code on how you're reusing the gameplay screen so unsure how much the difficulty of adding this could vary
But basically on osu! you can press tab to toggle autoplay, and the game just 1 mills notes while it's on
Ctrl-P also pauses and unpauses the music but unsure if trivial to implement

**Comment by Swan** [comment]
Currently the keybind is F2, but this is being changed in https://github.com/Quaver/Quaver/pull/648 to tab. Pausing is doable as well. Would you prefer if it brings up the pause menu like in gameplay or just pauses the music?

**Comment by percyqaz** [comment]
would prefer if it just pauses the music, freezing the notes in place (like in osu editor)
