### ISSUE TITLE
Steam says Quaver is still running after closing

### ISSUE THREAD

**Issue by spagtet** [Quaver/Quaver#663]
**Describe the bug**
When you close the game via the Quit button on the bottom right in the main menu, the game closes completely (no process in Task Manager), but Steam says it's still running. I have to exit Steam and reopen in each time.

**To Reproduce**
1. Click the Power icon in the bottom right on the main menu
2. Click 'Exit game'
3. Check Steam status under your name

**Expected behavior**
I expected to see that no game was running on Steam so I could either reopen Quaver or another game.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 
**Additional context**

**Comment by YaLTeR** [comment]
Possibly related to #625?
