### ISSUE TITLE
[RFC] Power of ¹⁰√2 rates

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#666]
### Idea
Use powers of ¹⁰√2 for rates, that is
```
(¹⁰√2) ^ -10 = 0.50
(¹⁰√2) ^ -9  ≈ 0.54
(¹⁰√2) ^ -8  ≈ 0.57
(¹⁰√2) ^ -7  ≈ 0.62
(¹⁰√2) ^ -6  ≈ 0.66
(¹⁰√2) ^ -5  ≈ 0.71
(¹⁰√2) ^ -4  ≈ 0.76
(¹⁰√2) ^ -3  ≈ 0.81
(¹⁰√2) ^ -2  ≈ 0.87
(¹⁰√2) ^ -1  ≈ 0.93
(¹⁰√2) ^ 0   = 1.00
(¹⁰√2) ^ 1   ≈ 1.07
(¹⁰√2) ^ 2   ≈ 1.15
(¹⁰√2) ^ 3   ≈ 1.23
(¹⁰√2) ^ 4   ≈ 1.32
(¹⁰√2) ^ 5   ≈ 1.41
(¹⁰√2) ^ 6   ≈ 1.52
(¹⁰√2) ^ 7   ≈ 1.62
(¹⁰√2) ^ 8   ≈ 1.74
(¹⁰√2) ^ 9   ≈ 1.87
(¹⁰√2) ^ 10  = 2.00
```
This way every rate is equal to the previous rate multiplied by the exact same factor (¹⁰√2), unlike the current system where, say, the jump from 1.9 to 2.0 (~1.05×) is smaller than the jump from 1.0 to 1.1 (1.1×).

EDIT: here's a plot of relative speed-up to illustrate the issue better:

![image](https://user-images.githubusercontent.com/1794388/53525441-d4e84800-3af2-11e9-8d8f-07294853fad2.png)

### Drawbacks
- Rates as currently implemented (0.5, 0.55, 0.6, ..., 0.95, 1.0, 1.1, 1.2, ..., 2.0) look nicer and are easier to remember, say, etc. ("I got this score on <chart name> one point five" vs. "I got this score on <chart name>... what was that rate again?")
  - Most of rates above 1.0 can be rounded to the first decimal digit when talking for better or worse.
- Rates as currently implemented exist in other games (SM/Etterna) which allows to compare scores, difficulties, etc.
  - Unclear how practical this actually is considering the games have different accuracy and HP systems.
  - Even if comparing scores is impractical, it allows to compare _accuracy systems themselves_ between the games: I got 97% on this chart + DT on osu! and 92% on Quaver 1.5×, so Quaver's accuracy system is this stricter.
    - For this purpose you can still compare 1.0× scores.
- There's already a lot of ranked scores with current rates and it's unclear what to do with them.

**Comment by semyon422** [comment]
What about using not fixed rates. Or make fixed values unlimited and customizable.

**Comment by YaLTeR** [comment]
I think non-fixed rates have some disadvantages.

First and foremost, it'll be impossible to store a difficulty database since you can't pre-compute difficulties for an unlimited number of rates. This is essential for searching and sorting by difficulty and for keeping any sort of a sensible online ranking system.

Then, each player would likely establish their own discrete rate steps anyway, which, while maybe good for an individual player, prevents easy score comparison between different players ("- I have a 95% on 1.5, what about you? - Oh, I have a 94% on 1.52").

**Comment by semyon422** [comment]
For storing difficulty you can make difficulty algorithms linear to get diffuculty for 1.5x rate just by multiplying difficulty for 1.0x rate by 1.5 and store only base value in database.
Comparation between different plays with different rates can be made by comparation between scores (or acc) multiplyed by rate values, or something like this

**Comment by YaLTeR** [comment]
I really doubt that a linear difficulty algorithm would produce any decent difficulty results.

**Comment by N1ckn1ght** [comment]
based
