### ISSUE TITLE
Issue downloading a replay

### ISSUE THREAD

**Issue by Fretzi** [Quaver/Quaver#670]
I tried downloading the top 2 replays on this map https://quavergame.com/mapsets/76 and got this error 
https://i.imgur.com/7Ku2TVH.png
I then posted this on the Discord and was told
> looks like the server is failing to build the replay for some reason
you able to report on github?

(log here: https://i.imgur.com/X0CvkOq.png)
Here is a quick GIF of how it looks https://i.imgur.com/Z4azfKg.gif

Done on Windows 10 Pro using Version 0.14.0

**Comment by Swan** [comment]
Should be fixed. Please re-open if you find any other replays that can't be downloaded.
