### ISSUE TITLE
Changing the value ColumnAlignment in the skin.ini does nothing 

### ISSUE THREAD

**Issue by MyAngelHana** [Quaver/Quaver#680]
**Describe the bug**
Even when changing the value of the ColumnAlignment in the skin.ini file, the playfield is still at the center of the screen 

**To Reproduce**
1. Go to 'skin.ini'
2. Change the value of the ColumnAlignment
3. nothing happens

**Expected behavior**
The playfield should move towards either side depending on the value.

**Comment by YaLTeR** [comment]
Fixed by #677
