### ISSUE TITLE
Paused Mod/Flag showing when it shouldnt

### ISSUE THREAD

**Issue by Sublimity** [Quaver/Quaver#740]
**Describe the bug**
The Paused Mod, which is used as a flag for pausing/exiting to results shows up as an active mod in the select screen

**To Reproduce**
just exit a map and it'll show

**Expected behavior**
dont show it in the mods listing

**Screenshots**
![image](https://user-images.githubusercontent.com/6015313/56666307-376a5880-66de-11e9-830e-517aba5b233c.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux (gang gang)
 - Build 4.19.2019

**Comment by Swan** [comment]
Fixed in #844
