### ISSUE TITLE
Difficulty scroll container locking up

### ISSUE THREAD

**Issue by Sublimity** [Quaver/Quaver#745]
**Describe the bug**
After searching and entering a mapset, at an entry in the list it forcefully scrolled all the way to the bottom of the difficulty container and selecting using the left and right keys stopped working, the only way to continue using the arrow keys is to click onto another map.

**To Reproduce**
1. Use the search
2. Enter moderately sized mapset from the search results
3. Use arrow keys until one of the maps produces the bug

side note: I'm not entirely sure if it's just this one mapset or if it can happen at any point to any moderately sized mapset, see video below.

**Expected behavior**
not do what it shows in the video below

**Screenshots**
https://streamable.com/t5hc9

**Desktop (please complete the following information):**
 - OS: Arch Linux (gang gang)
 - Version: 4.19.2019

**Comment by Swan** [comment]
Resolved in the new UI
