### ISSUE TITLE
Restart Game Dialog Always Shows

### ISSUE THREAD

**Issue by Swan** [Quaver/Quaver#796]
**Describe the bug**
When opening the options menu and hitting apply, the dialog will always appear even if you haven't made any changes.

**Expected behavior**
It should only appear if you've modified those settings.

**Comment by YaLTeR** [comment]
Huh, not for me. Some windows bass properties thing?

**Comment by Swan** [comment]
[Here is a video](https://streamable.com/gkeg1)

**Comment by YaLTeR** [comment]
Hmm, could it be because BASS doesn't apply the properties on Windows since they aren't supported? Then the options menu will continue showing the properties you have in your config, but compare them to the actual audio properties which won't change.

**Comment by YaLTeR** [comment]
On Linux if you don't restart the game after applying and try opening/closing the options again it will prompt to restart again because it checks against the actual properties which are only changed on game start.

**Comment by YaLTeR** [comment]
@Swan could you test if either of the properties apply? The game prints the values into the log on start, could you check if at least one of the values changes according to the config option.

**Comment by Swan** [comment]
Fixed in #844
