### ISSUE TITLE
Odd behavior when reloading a custom skin and switching windows at the same time

### ISSUE THREAD

**Issue by voidxn** [Quaver/Quaver#803]
**Bug description**
When reloading a custom skin it takes a relatively long amount of time. However, alt-tabbing / switching from the Quaver window, to another arbitrary window and back makes it load almost instantaneously.

Demonstration: [Video](https://youtu.be/UYeSAt0OR90)

**Steps to reproduce:**
For normal skin loading time:
1. Apply a custom skin
2. Press CTRL+Shift+S to reload it

'Abnormal' time:
1. Apply a custom skin
2. Press CTRL+Shift+S to reload it
3. Select or tab into a different window, go back to Quaver
Skin ends up loading much faster than the aforementioned method.

**Expected behavior**
It's odd that the skin loads fully when alt-tabbing even though normal loading seems to take much longer. One would expect it to load as fast normally as it does when alt+tabbing.

**Environmental info**
 - OS: Win10 Pro x64 build 17134
 - Quaver v.0.14.1
 - Running on an EVGA GTX 1070 with driver ver. 417.71
 - Fullscreen mode is not used, game resolution doesn't seem to matter for this to happen (Both 1366x768 and 1600x900 has been tried)

**Additional context**
Skin used can be downloaded from: [Link to Google Drive](https://drive.google.com/open?id=1sTo7OqdJQZcQGcihAws1jrHlhdZLrfsP)
Runtime log is attached below.
[runtime.log](https://github.com/Quaver/Quaver/files/3229792/runtime.log)

**Comment by voidxn** [comment]
Updating graphics drivers to 430.86 and disabling Nvidia's in-game overlay hasn't helped either.

**Comment by Swan** [comment]
This is due to the game limiting its FPS when the window is inactive by default. Can be avoid by disabling the setting in the options menu.
