### ISSUE TITLE
Cursor is not hidden if the pause menu is exited via "Continue"

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#806]
**Describe the bug**
It _is_ hidden if the pause menu is exited via the escape button, but not when using Continue.

**To Reproduce**
1. Play a map.
2. Press escape to pause.
3. Press Continue.
4. Cursor isn't hidden.

**Comment by JaanJah** [comment]
I thought I fixed it with this PR: https://github.com/Quaver/Quaver/issues/295, but I guess not then
