### ISSUE TITLE
Non 16:9 support when (especially 21:9)

### ISSUE THREAD

**Issue by Cheburelka** [Quaver/Quaver#816]
If i set resolution like 2560x1080 (not 1440) which are 21:9 it just obscales from 1920x1080

**Comment by Cheburelka** [comment]
what is wobble?

**Comment by Sublimity** [comment]
As seen in #208, the scaling issues need to be resolved before other aspect ratios can be introduced.

p.s. For the second question, Wobble (Quaver/Wobble) is the framework on which Quaver is built upon.
