### ISSUE TITLE
Maps aren't marked as ranked automatically

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#827]
**Describe the bug**
When a mapset is downloaded and imported its ranked status isn't updated automatically. This means that searches such as `status=ranked` don't show newly downloaded ranked maps, for example.

**Expected behavior**
The maps' ranked status should be checked and cached on import.

**Comment by robby250** [comment]
Also check the ranked status of unchecked maps in the background in case you reset your database or something.
