### ISSUE TITLE
name disappears from the multiplayer list

### ISSUE THREAD

**Issue by Cansta** [Quaver/Quaver#856]
**Describe the bug**
after finishing a multiplayer game I see that my name simply disappeared from the list of players

**To Reproduce**
I dont know how exactly because was accidentaly but..
1. maybe with free rate selector
2. I put 1.2x
3. the song was adamas (TV size) insane (23.87)
4. and happen after finish, i ask the others players if they see my nickname but the say me no.

**Screenshots**
https://cdn.discordapp.com/attachments/531723335109836819/594589336087822356/20190629124759_1.jpg

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version the last?

**Additional context**
I roll the mouse to see if my name was down or smth but nothing happen

**Comment by robby250** [comment]
I've had this bug as well, I was in a multiplayer lobby then the game disconnected with the message "Unable to connect to server". It reconnected in a few seconds and I joined the lobby but the others inside couldn't see me until I restarted the game. I was able to play a few matches while invisible and talk in the chat.
