### ISSUE TITLE
Overlapping in "Download Maps" screen

### ISSUE THREAD

**Issue by CrayZigg** [Quaver/Quaver#857]
**Describe the bug**
Scrolling down in the download maps screen sometimes makes the new maps overlap with the higher maps instead of appearing below them.

**To Reproduce**
1. Go to 'Download Maps'
3. Scroll down

**Screenshots**
![20190629223520_1](https://user-images.githubusercontent.com/52359291/60388850-fd437b80-9abf-11e9-9db1-881abb615a0b.jpg)

**Additional Notes**

The maps realign back in order when scrolling up and back down.

**Comment by Sublimity** [comment]
Potential Duplicate #661

**Comment by CrayZigg** [comment]
> 
> 
> Potential Duplicate #661

Incorrect, #661 happens when using the search bar.

**Comment by Sublimity** [comment]
I should've described what I meant by that.

The bug is similar in that both instances in where it occurs, it causes overlapping of ScrollContainer entries, because of this, a fix to fix one of these bugs, might indirectly fix the other.
