### ISSUE TITLE
Support Different Keyboard Layouts

### ISSUE THREAD

**Issue by TruthIsNear** [Quaver/Quaver#858]
**Describe the bug**
The ', (<)' and '. (>)' buttons are not recognised when switching to Russian keyboard layout. The equivalents to those buttons in russian layout are 'Б' and 'Ю' respectively.

They are also displayed as 'None' when set in input options.

**To Reproduce**
1. Set ', (<)' and '. (>)' in gameplay layout.
2. Set alternative keyboard layout to Russian.
3. Alt + Shift.
4. Buttons don't work in game.

**Expected behavior**
', (<' and '. (>)' work in game no matter what your keyboard layout is

**Screenshots**
![kbd_russian](https://user-images.githubusercontent.com/22364098/60388888-b904ab00-9ac0-11e9-8c76-3121df4c7295.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by Cheburelka** [comment]
it doesn't work with ; ' [ and ] buttons tho
