### ISSUE TITLE
Judgement Bar

### ISSUE THREAD

**Issue by Fanykins** [Quaver/Quaver#859]
It'd be great to have the judgement bar / hit position (the blue bar in the screenshot below) have a UI display associated with it, possibly a toggle in the skin.ini or something since arrow skins won't need it, but bar skins usually do.

![screenshot040](https://user-images.githubusercontent.com/22548866/60389152-c8103c80-9a71-11e9-8014-1b5dad5711dc.jpg)

**Comment by Swan** [comment]
`/Stage/stage-hitposition-overlay.png`
