### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by Cheburelka** [Quaver/Quaver#860]
Back button in multiplayer map select backing you to lobby, not map select. 
**To reproduce:**
1. Press button **Map select**
2. Go to difficulty choose menu
3. **Press button **Back**
4. ?????
5. **PROFIT!!!**

**Comment by Sublimity** [comment]
This is intentional. Use mouse right click or ESC to navigate back to mapset selection.

Just to note, this does the same in singleplayer song select.
