### ISSUE TITLE
Local Score saving proposal

### ISSUE THREAD

**Issue by Sceptimis** [Quaver/Quaver#861]
**Describe the solution you'd like**
This is just a thought, but it'd be a cool idea if it was possible to allow for local score saves to be stored in [Steam Cloud](https://support.steampowered.com/kb_article.php?ref=6736-QEIG-8941) using the save games aspect of it. It would allow users to easily transfer and manage their scores on multiple computers/installs if need be.

**Comment by Swan** [comment]
This would require saving replays in the cloud and each Steam user is limited to a certain amount of storage space. Steam cloud is only meant for small files like game saves.
