### ISSUE TITLE
Local/Unranked Profile

### ISSUE THREAD

**Issue by itzinferr** [Quaver/Quaver#866]
**Is your feature request related to a problem? Please describe.**
Well, imagine you do a pretty good record on a "X" song and well, let's suppose it could have been your top play "if ranked", but then you know the map isn't popular enough for that or for whatever reasons. Also, for those vibro players (if that's even possible on Quaver lol) that want to improve at doing vibro it would be a nice way to keep track of their progress at that skill (I myself can't even vibro properly but I think that kind of people could benefit from that)

**Describe the solution you'd like**
I think it could be a nice idea to have local calculations to keep track of any score you might have done that doesn't meet the ranking criteria or that isn't popular enough to get into a hypothetical future "loved category". Something like the Local Profile system Etterna has; where basically any map that you might have (be it ranked/blacklisted or not) counts toward your local rating and then only those maps that are ranked counts toward their Etterna Online rankings.

**Describe alternatives you've considered**
As I don't know how could it affect performance (I don't really think it will affect a lot though) it could be an option for users to decide whether they want to have calculations running in the background to have a local profile or not, depends completely on whether they want to use the feature or not and those that don't wanna won't get affected. But at the end it solely depends if it's something that can be implemented into the game or not.

Well whatever this was pretty long but still, I think it'd be a nice feature.

**Comment by YaLTeR** [comment]
Well, if you want to track progress at certain skills then you should probably use local map scores (which do exist and do work). If you had a local profile then a single dominant skill would contribute the majority of your local performance rating and you wouldn't be able to use it for any other skills (which means that you, once again, will have to use local scores, so why not use them in first place).

**Comment by itzinferr** [comment]
Yeah but having them placed in a "top local scores" sort of thing would be useful to no have to sort through many local scores, supposing you have a lot of them and don't remember which was your "local top play" or something lol
