### ISSUE TITLE
Option to remove F2 animation

### ISSUE THREAD

**Issue by robby250** [Quaver/Quaver#868]
I'd like the F2 (Random map) to be snappier so I can read the map quickly and F2 again if I don't want to pick it. Currently it has a long bouncing animation that I have to wait for to settle in order to read the map. Either remove it altogether, make it much faster, or provide an option to remove it.

**Comment by YaLTeR** [comment]
It currently looks like this mainly due to the limitations of the song select container. It'll be fixed when those are resolved.
