### ISSUE TITLE
Don't play fail animation / fail sound when quitting map

### ISSUE THREAD

**Issue by robby250** [Quaver/Quaver#869]
Retry doesn't have the red screen, fail sound and delay when pressing it, back to menu shouldn't have it either if "Skip Results Screen After Quitting" is toggled on. Every bit of navigation speed optimization helps so that you spend less time in menus and more time playing the game.

**Comment by robby250** [comment]
With the new fail screen animation, this issue still applies. I don't think it should display the fail animation when double tapping F1, or pausing and pressing "Back".

**Comment by staravia** [comment]
Reopened issue because PR does not solve issue.
