### ISSUE TITLE
Map Deletion Crash

### ISSUE THREAD

**Issue by Necriotic** [Quaver/Quaver#870]
**Describe the bug**
Game crashes when deleting maps and Alt+Tab out of the application.

**To Reproduce**
1. Go to Singleplayer
2. While deleting maps, Alt+Tab

**Expected behavior**
The game crashing as it had been reproducing.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 ver. 1809 (17763.557)
 - Browser: Chrome
 - Version: 0.15.0

**Additional context**
Speed of deletion of maps may affect the reproduction of the bug.

[bugged.log](https://github.com/Quaver/Quaver/files/3343162/bugged.log)

**Comment by Sublimity** [comment]
You left this empty, can you please edit your message and attach the appropriate information.

**Comment by Necriotic** [comment]
> You posted this with the default template, can you please edit your message and attach the appropriate information.

Strange, I had it all filled out. Possibly had it reset when editing. Should be good now.
