### ISSUE TITLE
Windows Scaling issue

### ISSUE THREAD

**Issue by Miaourt** [Quaver/Quaver#871]
**Describe the bug**
Quaver seem to follow the Windows scaling for the whole game, so when you have a 125% scaling for example, and you want to max out the game resolution, the game overflow the screen.

**To Reproduce**
1. Set Windows scaling to another value than 100%
2. Launch Quaver

**Expected behavior**
Do not follow the Windows scaling for the whole game, maybe just the UI instead

**Screenshots**
The game on my 2560x1440 screen with the 1920x1080 resolution :
![image](https://user-images.githubusercontent.com/1571367/60399962-7c42bd80-9b6d-11e9-8aad-6cd5d8ac2ff2.png)
Same, but with 2560x1440 resolution : 
![image](https://user-images.githubusercontent.com/1571367/60399976-d2176580-9b6d-11e9-8088-2e67c69a944e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1904

**Comment by YaLTeR** [comment]
There's some WinAPI call to tell Windows that the program shouldn't be scaled. I would guess MonoGame exposes it somewhere. Should probably be called in Wobble?

**Comment by Miaourt** [comment]
Is it fixed ?
