### ISSUE TITLE
Game closing itself after few seconds

### ISSUE THREAD

**Issue by BokuNoNico2012** [Quaver/Quaver#878]
**Describe the bug**
When I opened the Game through Steam, the Game just closed itself after showing the main menu for a second

**To Reproduce**
Open the Game

**Expected behavior**
The Game not crashing

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Additional context**

**Comment by Sublimity** [comment]
Can you reproduce this bug and provide your __**runtime.log**__ file from the Logs folder in the game's local files.

**Comment by BokuNoNico2012** [comment]
[runtime.log](https://github.com/Quaver/Quaver/files/3346100/runtime.log)

**Comment by Swan** [comment]
The cause is due to the # character in the Steam profile name. It'll have to be escaped upon logging in
