### ISSUE TITLE
Separate Mapping Skin

### ISSUE THREAD

**Issue by Reyder95** [Quaver/Quaver#881]
There are people who enjoy mapping with a specific skin, and I thought it'd be nice to have a native feature where you can choose a "mapping" skin and everytime you go into the editor it uses that skin. 

This might be useful for those who like having a specific skin for mapping, and if they have a LOT of skins, constantly changing skin to map might be tedious. Just a thought.

**Comment by Swan** [comment]
[Already possible to some degree in the editor](https://wiki.quavergame.com/docs/skins/keys#editor).
