### ISSUE TITLE
Game enlarges past the screen when using high resolution monitor

### ISSUE THREAD

**Issue by Fvern** [Quaver/Quaver#883]
When toggling the resolution settings down and up on a 2560×1440 monoitor, and switching from fullscreen to windowed and vice versa, the game somehow... does this.
![20190702000620_1](https://user-images.githubusercontent.com/25032854/60451214-2ac62b80-9c5e-11e9-92a1-b2a2b7570f23.jpg)
Moves past the clickable screen, and cursor movement is limited.

I originally wanted to have the game run at 2560×1440, but switching to this caused the game to be blurry, and the game became sharp at 1920x1080. Switching back to 2560×1440 caused this problem, and it worsed as I clicked about the settings.

OS: Windows 10 Pro

**Comment by YaLTeR** [comment]
Could you please fill in the issue with information?

**Comment by Vernonlim** [comment]
I suppose I should add that the game is now unplayable because reinstalling doesn't reset the settings. I suppose I should find the config file or something.

**Comment by Sublimity** [comment]
Look for `WindowWidth` and `WindowHeight` in quaver.cfg, set those to your desired window size.

**Comment by Vernonlim** [comment]
The game apparently bugs out at native resolution, but works when scaled from a smaller one.

**Comment by nobbele** [comment]
@Swan how is this related to "Song Select"
