### ISSUE TITLE
Problem with skin

### ISSUE THREAD

**Issue by Andrey08083** [Quaver/Quaver#884]
**Describe the bug**
When I changing hitposition, receptor doesn't changing his position. This bug is on the arrow
skin, but i think this bug on circle skin too.
**To Reproduce**
1. Open skin configuration file
2. Change "HitPosOffsetY" from 110 to 50 (In my case)
3. Reload skin

**Expected behavior**
The receptor should change its position the same way like hitposition.

**Video**
https://www.youtube.com/watch?v=YKfDWA-IMfo

**Comment by Janko5** [comment]
this isn't a bug. You changed the hitposition and it shows. HitPosOffsetY is not used to change the position of receptor. Change HitPosOffset to previous value (the same value as ColumnSize) and set ReceptorPosOffsetY. Then the position of the receptor will change with the hitposition
