### ISSUE TITLE
Wrong country?

### ISSUE THREAD

**Issue by Axieee** [Quaver/Quaver#887]
**Describe the bug**
I created an account for Quaver and obtained a beta key via the bot, but as soon as I signed in, I was automatically set to India, and the website also confirms that I am from India despite me living in the UK. 

**To Reproduce**
1. https://quavergame.com/profile/885?mode=1
Site claims I'm from India, however I am from the UK and even osu shows that. 
https://osu.ppy.sh/users/2377299 

**Expected behavior**
I expected to get put in the United Kingdom ladder with the other UK players, as I know most of them and I compete against their scores in osu!mania.

**Screenshots**
[20190701201755_1](https://user-images.githubusercontent.com/52428720/60467154-b4b9c880-9c4d-11e9-87cf-3c629b068234.jpg)

**Comment by Sublimity** [comment]
This was not mean't to be submitted in here as it is not related to anything wrong with the source code.

Email support@quavergame.com

**Comment by Axieee** [comment]
Oh, right! Thanks for the fast response, I assumed it was just a bug so I made a post here. Sorry.
