### ISSUE TITLE
Quaver - Crashes when opening on steam

### ISSUE THREAD

**Issue by xdeagan** [Quaver/Quaver#889]
**Describe the bug**
The game crashes when i start Quaver using Steam. it auto crashes before even showing the splash screen or main menu.

**To Reproduce**
1. Start Quaver on steam

**Expected behavior**
I expected it to run the game

**Screenshots**
![oof](https://user-images.githubusercontent.com/50999729/60476950-5c290200-9c32-11e9-8058-4225042bbabc.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 64 bit  
 - Browser Chrome

**Additional context**
I really want to play this game

**Comment by Swan** [comment]
Windows 7 requires extra dependencies in order to run the game. 

Follow the instructions in the purple box.
https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x#net-core-dependencies
