### ISSUE TITLE
Add a splash screen to make it clear quaver is launching

### ISSUE THREAD

**Issue by micajoeh** [Quaver/Quaver#891]
**Is your feature request related to a problem? Please describe.**
When launching the quaver client, it tends to start as a background process, and even not launch at all.

**Describe the solution you'd like**
 Adding a splash screen that could be as simple as a loading wheel with the quaver logo would make it easy to determine if quaver crashed on launch, if it never launched, or if it's currently launching. 

**Describe alternatives you've considered**
The only alternative is better reporting to the steam client that the game is launching (which is a limitation of the client), or telling users to check task manager for the QuaverGame.exe process.

**Comment by YaLTeR** [comment]
The issue is that there's stuff being done before Quaver opens a window which takes a while and doesn't need to be done before Quaver opens a window, and the correct solution would be to do it after Quaver opens a window. There shouldn't be any delays once that's done.
