### ISSUE TITLE
I have low fps and can't raise it

### ISSUE THREAD

**Issue by StepoS96** [Quaver/Quaver#896]
Hello. In the game I have about 300 fps. I have about 700-800 stable in osu!mania.
My PC:
Laptop;
Intel (R) Core (TM) i5-4200M 2.50GHz;
12 GB RAM;
Two video card:
1) Intel (R) HD Graphics 4600 - about 150-200 fps;
2) NVIDIA GeForce GT 745M - about 250-300 fps, sometimes 150 fps;
Windows 10;

![A2XVk_7ot5Q](https://user-images.githubusercontent.com/52458971/60521205-024b3980-9d11-11e9-8496-3b06e35b697d.jpg)
![Q7zuIVhwrXw](https://user-images.githubusercontent.com/52458971/60521211-0a0ade00-9d11-11e9-9a61-08e1a1c573f9.jpg)

I put the NVIDIA GeForce GT 745M graphics card for high performance, FPS 250-300. 

I do not know what to do or how to increase the FPS in the Quaver :(

The only thing I noticed is that if you put the resolution of 800x600 in windowed mode, the FPS became about 400. But it’s also very difficult to play (
My monitor has resolution 1366x768

Please help me!

**Comment by StepoS96** [comment]
Ignore :(

**Comment by Janko5** [comment]
this is rather a matter of optimization. Take into consideration that the game is in closed alpha phase and much needs improvement so you have to wait for improvement I think
