### ISSUE TITLE
Fps dropping so much

### ISSUE THREAD

**Issue by FelipeLink14** [Quaver/Quaver#898]
**Describe the bug**
The fps is dropping randomly in the middle of the maps, tried with limited fps(250) still getting lag

**Expected behavior**
idk? i guess something to fix that?

**Screenshots**
i have a video about it
https://www.dropbox.com/s/kenc8x0acfbm877/HPO7sjXsCh.webm?dl=0

**Desktop (please complete the following information):**
 - OS: Windows 10
I7-7700K
AMD Radeon RX 580 8gb
8 gb ram 2400mhz

**Comment by StepoS96** [comment]
Oh, i have 300 fps, I just can't raise it :(  Wrote about this just now, created a topic. In osu!mania i have 700-800 stable
