### ISSUE TITLE
[EDITOR] Stackable Notes

### ISSUE THREAD

**Issue by TCHalogen** [Quaver/Quaver#913]
While using the editor, it is possible to place two notes in the same point on the timeline.

This can be reproduced by placing a note using the left mouse click, and then using the key-binding corresponding to the note just inserted. These notes both exist at that given point and as a result, one out of every two notes will be missed assuming the user is playing on a single setup/not using extraneous means to add another setup.

Note type is not limited here: you can stack long notes with long notes, regular notes with regular notes, long notes with regular notes, or regular notes with long notes.

On occasion, this would produce a crash; however, I don't get any sort of error/stack trace to grab any information.

If any assistance, some specifications:

**OS:** Windows 10
**GPU:** AMD Radeon R9 360
**Processor:** AMD FX-770K @ 3.5 GHz
**RAM:** 8GB

**Comment by Reyder95** [comment]
It's also worth noting this can also occur if you left click to place the first note, then left click off the side of the note (almost like in between the columns) which can place the 2nd note. Happens to me quite a bit.
