### ISSUE TITLE
Notes dissapearing with Audio Cut off

### ISSUE THREAD

**Issue by Eve-ning** [Quaver/Quaver#924]
**Describe the bug**
Audio cuts off abruptly, then the current notes on the screen disappear. Note that the **combo persists** despite not being able to hit the disappeared notes.

*Audio sync is perfectly fine despite the cutting.*

Happened quite a few times during my plays on [1.2x Cyber Inductance](https://quavergame.com/mapsets/86). Presumably only happens during rates

It has only happened on dense sections (jumptrills0, not sure if that's related.

**To Reproduce**
1. Play 1.2x Cyber Inductance
2. It may happen, it may not, I have no idea

Sorry I don't have a runtime.log atm, i accidentally overwritten it, I'll comment if I manage to get this issue again

**Expected behavior**
Notes not disappearing and accounted in the combo and score.

**Screenshots**
Sorry no screenshots, have an illustration
![Untitled](https://user-images.githubusercontent.com/26498608/60758988-760e7e80-a050-11e9-9e45-48ccee30af8a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 0.15.2

**Additional context**
I use a very slow scroll speed, 24, probably related. Default Circle Skin.

**Comment by Swan** [comment]
Providing a video showing this would also help tremendously if you're able to.
