### ISSUE TITLE
Quaver doesn't launch

### ISSUE THREAD

**Issue by AndreiAlisson** [Quaver/Quaver#927]
**Describe the bug**
The game doesn't launch anymore **(Started today)**.

**To Reproduce**
1 - Open the game

**Expected behavior**
The game should open.

**Behavior**
I get the "running" status for quaver on my steam, but after a few seconds the status disappear and nothing happen.

**Desktop (please complete the following information):**
 OS: Windows 10.

**Additional context**
Also I noticed that the quaver process doesn't even appear on taskmanager.
[runtime.log](https://github.com/Quaver/Quaver/files/3365033/runtime.log)

**Comment by Eve-ning** [comment]
Posting on behalf of KingTB, seems to be the same issue, on a different OS

Notably:
`OS: Microsoft Windows 6.1.7601 S`

[runtime.log](https://github.com/Quaver/Quaver/files/3368304/runtime.log)

**Comment by Swan** [comment]
It's due to the skip texture in the default skin being too large for some PCs to load. I will replace this and deploy another build.

**Comment by jccatilo** [comment]
hi. same issue right now and has already been like a week. any luck?

**Comment by Faact** [comment]
This thing is happening to me as well, but it opens. It takes about half an hour to open it, and when it opens. QUAVER IS NOT RESPONDING. Can you help me with this? 
PC Specs.
Alienware Laptop
14 years old
GT 555

**Comment by kinantara** [comment]
same thing happened
