### ISSUE TITLE
[Web] The comment that just typed still "leaving trace" after submitting comment

### ISSUE THREAD

**Issue by aphelionosu** [Quaver/Quaver#931]
Hello, i just found this issue when opening [this game website](https://quavergame.com)

I just submiting comment to reply PianoLuigi but apparently the comment i just type still there even after submitting comment
![Screenshot (1506)](https://user-images.githubusercontent.com/41836319/60818873-14c1e900-a1d1-11e9-8812-ab23b8156203.png)

**Comment by Sublimity** [comment]
@AiAe

**Comment by Swan** [comment]
Moved to website repo
