### ISSUE TITLE
Option to play hitsounds on LN releases

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#934]
I believe this could help with practicing release acc. Hitsounds definitely help me practice LN press acc currently.

**Comment by WetWayne** [comment]
I am interested in this feature.

I recently played a vsrg that does have this feature (vivid/stasis) and I thought it helped me time releasing long notes immensely.

If this is introduced as a togglable option then it shouldn't impact anybody that doesn't want to use it.
