### ISSUE TITLE
Windows-Key working while playing

### ISSUE THREAD

**Issue by BokuNoNico2012** [Quaver/Quaver#935]
**Describe the bug**
when the windows-key is pressed during gameplay, the game tabs-out.

**To Reproduce**
1.) Start a Map
2.) Press the Windows-Key

**Expected behavior**
Windows key not working during gameplay

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by nobbele** [comment]
Isn't this a feature request, not a bug

**Comment by YaLTeR** [comment]
This comes to mind on programmatically disabling the Windows key and some stuff like sticky keys: https://docs.microsoft.com/en-us/windows/win32/dxtecharts/disabling-shortcut-keys-in-games
