### ISSUE TITLE
Top Cover and Bottom Cover Options in Modifiers

### ISSUE THREAD

**Issue by KaidenFrizu** [Quaver/Quaver#938]
**Is your feature request related to a problem? Please describe.**
I think it's more accessible to adjust (and toggle) Top and Bottoms Covers in Modifiers rather than in Options. In some cases, I need to remove the covers in some maps but I'm struggling to find and change it in Options.

**Comment by Sublimity** [comment]
This feature belongs in options, its more for user preference like scroll speed rather than a modifier that alters gameplay (ie. ln conversion)
