### ISSUE TITLE
File format is wrong on linux

### ISSUE THREAD

**Issue by nobbele** [Quaver/Quaver#941]
**Describe the bug**
All the lines of the quaver.sh file end with a ^M thing, can be fixed by going into vim and typing `:set fileformat=unix`

**To Reproduce**
1. Download Quaver
2. Run quaver.sh

**Expected behavior**
quaver.sh runs

**Desktop (please complete the following information):**
 - OS: Manjaro

**Comment by Sublimity** [comment]
It does work, check #932
