### ISSUE TITLE
Ability to have a visual note offset that only effects LN ends

### ISSUE THREAD

**Issue by SparkySpartan** [Quaver/Quaver#945]
Many players, new and old, deal with the issue of hitting every tap note in a map with perfect accuracy, but always hitting early or late when releasing LN ends. If you know a good amount about skinning, you can fix this yourself by editing the body/end image, but this means that every skin has its own fine-tuned position where

My proposed solution? Add a slider that changes when it looks like a player should release any given long note. Whether it's measured in pixels, a scroll rate-like number, or some other value, it should just make it look like every LN is X pixels or milliseconds shorter/longer then it actually is. This would greatly help many new players, and a good handful of old players that just can't release long notes that tenth of a second earlier or later without losing their accuracy on regular notes. It might also be helpful to have a static setting of where LN ends are placed in any given skin.cfg, so if you want to do something interesting with LN ends, you have the freedom to do so.

In cases of stacking, (LN end in the same place as a new note) I'd probably recommend hiding the LN behind the new note, and prevent the end from extending past it.
Sorry if this is a bit vague in some places, hope that I got the right message across. 

Keep up the good work devs, y'all are doing great!

**Comment by YaLTeR** [comment]
This sounds like a nice replacement for `DrawLongNoteEnds = False`. I just want to add that there should be a preset to align the LN end top with the LN end to emulate its behavior, as this type of bar skin is quite common.

> but this means that every skin has its own fine-tuned position where

You accidentally a sentence
