### ISSUE TITLE
Different Scoring Systems

### ISSUE THREAD

**Issue by BokuNoNico2012** [Quaver/Quaver#955]
It would be really convenient to have the decision between different scoring systems.
I currently am only playing Quaver and I would love to play the osu!mania DAN phases in Quaver, but in order to really evaluate the skill from them you'd need the osu!mania scoring system.
You could maybe give the choice between the different scoring systems but only rank the current one

**Comment by Swan** [comment]
We don't have any intentions on doing this. If you're curious to see what your score is on that system, you can convert it using their formula.
