### ISSUE TITLE
Got "Baby Steps"(pass a map) achievement when failing a song

### ISSUE THREAD

**Issue by nobbele** [Quaver/Quaver#961]
**Describe the bug**
 I got "Baby Steps"(pass a map) achievement when I failed a song

**To Reproduce**
1. Play a song
2. Fail
3. Get achievement

**Expected behavior**
I expect to not get pass a map achievement from failing a map

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Fretzi** [comment]
You most likely already passed a map before the new update, and achievements only unlock after you submitted a new play, no matter if you passed or failed.

**Comment by nobbele** [comment]
hmm, yeah probably that
