### ISSUE TITLE
Show notes per column count in editor

### ISSUE THREAD

**Issue by IceDynamix** [Quaver/Quaver#966]
Basically have a place where you can view the amount of notes in each column, so you're able to check for hand balance during mapping/modding.

**Comment by Janko5** [comment]
This number won't give you anything. It will only give you awareness that there is a balance or not. Lack of balance of hands can be seen without any counter. The counter wont help you to point out every part of map that isn't balanced

**Comment by IceDynamix** [comment]
This can be accomplished quite easily with plugins now

**Comment by IceDynamix** [comment]
Relevant plugin I just wrote: https://gist.github.com/IceDynamix/fa57522bd332f45f4b902a9c45cc7a06
