### ISSUE TITLE
Game doesn't start up

### ISSUE THREAD

**Issue by IceDynamix** [Quaver/Quaver#969]
**Describe the bug**
Game doesn't start up. Clicking on the "Play" button. Only shows "Quaver - Running..." in the library for 6 seconds, then changes into "Quaver - Syncing..." for a second. Already restarted my PC, updated Steam and checked for updates for Quaver. The "Preparing to launch Quaver..." window does appear, nothing else though.

**To Reproduce**
1. Go to 'Quaver' in the Steam library
2. Click on 'Play'
3. ...

**Expected behavior**
Game to start up as usual

**Additional context**
[runtime.log](https://github.com/Quaver/Quaver/files/3438633/runtime.log)

**Comment by Swan** [comment]
Try deleting some of the most recent maps you have installed and load the game again.

**Comment by IceDynamix** [comment]
Worked. Thanks.
