### ISSUE TITLE
Ghost Notes

### ISSUE THREAD

**Issue by V3rald** [Quaver/Quaver#973]
Pretty simple, some notes coming down into your field but u dont actually need to press them and even if you do press them it does nothing
obviously it needs to be differentiated so players know if its ghost note or real note

A funny bug in osu appeared in sillyfangirl's stream and it basically shows exactly how i would imagine it
https://clips.twitch.tv/WanderingSparklyToadDxCat

**Comment by YaLTeR** [comment]
But why?

**Comment by V3rald** [comment]
Why not
