### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by V3rald** [Quaver/Quaver#979]
**Is your feature request related to a problem? Please describe.**
Printscreen takes picture of the game from 5 seconds ago or so

**Describe alternatives you've considered**
built-in screenshot system like in osu or something

**Additional context**
I know steam has screenshot system but for that i need to pin a location of those pictures, sort by date and then drag the picture to discord which takes some time.

So im suggesting either fixing the printscreen issue or making a built-in screenshot system

**Comment by IceDynamix** [comment]
If we're already at it, an option to copy the screenshot to clipboard automatically would be nice. It would make sharing images easier, since, in Discord for example, CTRL+V works just fine to paste an image.
