### ISSUE TITLE
Option to filter out scores that is impossible to beat with your current rate on the scoreboard

### ISSUE THREAD

**Issue by KitsuneDeity** [Quaver/Quaver#994]
**Is your feature request related to a problem? Please describe.**
The global leaderboard features the top 4 scores of a map, but assuming that you are playing a significantly lower rate, it can be generally impossible to take on any of them if they have really high scores. The rate-specific leaderboards fixes this problem, but it leaves out all of the various scores that are possible to beat but have different rates.

**Describe the solution you'd like**
An option to:
- Highlight the scores on the global leaderboards that are possible to beat with your current rate (if no scores are possible, then don't highlight any). 
- Show scores that are possible to beat with your current rate in the scoreboard during play, hide scores that aren't possible. This includes scores that aren't in the top 50 plays.

**Example Image**:
![unknown-10](https://user-images.githubusercontent.com/53100510/63265614-0c42e080-c25c-11e9-96d5-d00c6ef98b1e.jpg)

In the scoreboard while playing, Polaris would be #1, AirSpan would be #2, Bread would be #3, Neo would be #4, etc.
This suggestion would enhance the incentive to place your score on the leaderboards, with more realistic goals to aim for.

**Comment by Swan** [comment]
Added in #1003
